- CONTRIBUTING.md
* add PR Welcome badge
* add link to How to Contribute to Open Source on Github
* move Documentation up the table of contents
> Add contributor-friendly badge and resources

- webapp/src/css/variables.less
Otherwise the head of the add contact button is salmon.
medic/medic#5877
> Fill circles as well as paths

- webapp/src/css/dropdown.less
> Only set top for dropdown menus not dropups

- ddocs/medic-client/views/contacts_by_type/map.js
- ddocs/medic-client/views/contacts_by_type_freetext/map.js
- webapp/tests/mocha/unit/views/contacts_by_type_freetext.spec.js
> Patch view to support configurable hierarchy

- webapp/src/js/controllers/edit-user.js
- webapp/src/js/services/user.js
- webapp/tests/karma/unit/services/user-settings.js
Forces loading of user profile from remote instead on relying on cache which is not in sync with remote.
medic/medic#5616
> Forces loading of user profile from remote

- webapp/src/css/dropdown.less
- webapp/src/js/bootstrap-multidropdown.js
Before it was returning the parent and all the children which
made our search much slower than it needed to be.
Also updates the UI so it's harder to select all children but one.
medic/medic#5724
> Modify the multidropdown to return selected parent

- webapp/src/js/services/check-date.js
- webapp/src/js/services/telemetry.js
- webapp/tests/karma/unit/services/check-date.js
This means we can more accurately calculate the actual reported
date. We can also help find and fix users with phones with
incorrect dates.
medic/medic#5590
> Record client date offset

- webapp/src/js/services/enketo.js
medic/medic#1926
medic/medic#5652
> Fix a bad merge leading to 404s loading attachments

- webapp/src/css/inbox.less
- webapp/src/templates/partials/theme.html
> Fix scrolling and tidy styles of theme page

- .github/ISSUE_TEMPLATE/improvement.md
- .github/ISSUE_TEMPLATE/performance.md
- .github/ISSUE_TEMPLATE/technical_issue.md
By only providing two templates we were only ever getting two
types of issues. This adds templates for the other three types
that we have defined in our labels.
> Add issue templates for all types

- webapp/src/js/bootstrapper/index.js
- webapp/tests/mocha/unit/bootstrapper.spec.js
> Fixes fetch not auto-forwarding cookies in some browsers

- webapp/src/js/controllers/inbox.js
- webapp/src/js/services/db-sync.js
- webapp/tests/karma/unit/controllers/inbox.js
Check if DBSync is enabled immediately
medic/medic#5930
> Check if DBSync is enabled immediately

- webapp/src/css/inbox.less
> Fixes review dropup style

- scripts/get_users_meta_docs.js
> Fix a potential race condition with async/await

- README.md
> Include serveo execution instructions

- Gruntfile.js
- scripts/e2e-servers.js
- tests/constants.js
- tests/e2e/africas-talking.js
Fixing issues with NODE_NAME not being set correctly
> Fixing e2e docker

- tests/e2e/release/standard.js
- tests/page-objects/contacts/contacts.po.js
Automating this manual release test. 
https://github.com/medic/medic-release-testing/issues/31
> Automating a release test for creating districts, health centers, and clinics. 

- demo-forms/multimedia.xml
Adds audio to the multimedia demo xml form. 
[description]
medic/medic#[number]
> adds an element to play an mp3 file if configured

- webapp/src/js/services/tour.js
> Quick fix to show tour buttons again

- scripts/conflicts/README.md
The provided couch URL was not accurate.
> Update Documentation  For Conflict Resolution

- webapp/src/templates/modals/user_language.html
> Enable submit button when language is chosen

- api/.eslintrc
- scripts/.eslintrc
- sentinel/.eslintrc
> Update eslint to use ES2017 for api and sentinel

- tests/page-objects/common/common.po.js
Fixes flakey test by waiting for modal element
medic/medic#5890
> Fixes flakey test

- CONTRIBUTING.md
Update forum link for public launch
> Update Forum Link

- README.md
Update forum link for public launch, remove Slack link
> Add new Forum link, remove Slack link

- README.md
> Update required software list in readme

- .travis.yml
- admin/src/js/main.js
> Add targets-edit state default param value.

- webapp/src/js/services/telemetry.js
- webapp/tests/karma/unit/services/telemetry.js
Fixes month index (months are zero indexed)
medic/medic#5949
> Fixes month index

- webapp/src/css/inbox.less
Fixes text wrap
medic/medic#5967
> Fixes text wrap

- ddocs/medic/_attachments/translations/messages-en.properties
- webapp/src/js/controllers/edit-user.js
- webapp/tests/karma/unit/controllers/edit-user.js
Corrects error message being displayed
medic/medic#6020
> Corrects error message being displayed

- package-lock.json
- package.json
Correct version in `package.json` and `package-lock.json`
medic/medic#6048
> Correct version

- admin/src/css/configuration.less
- admin/src/css/theme.less
- webapp/src/css/analytics-widgets.less
- webapp/src/css/badge.less
- webapp/src/css/content-list.less
- webapp/src/css/dropdown.less
- webapp/src/css/enketo/medic.less
- webapp/src/css/font.less
- webapp/src/css/inbox.less
- webapp/src/css/material.less
- webapp/src/css/panel.less
- webapp/src/css/targets.less
- webapp/src/css/theme.less
- webapp/src/css/variables.less
Uses a more restrictive set of colours to slightly improve the look
Renames less variables to be more readable
medic/medic#5716
> Implement a colour palette

- sentinel/src/schedule/outbound.js
There have been instances where the outbound request handler has hung
completely in production. It's not clear from logging why this occured
and it's not consistent or repeatable, but a good potential option is
that requests to external servers are hanging.
This change adds an explicit timeout to the two outbound IO requests.
Depending on various factors there may already be an implicit timeout,
but this makes it explicit and much shorter (10 seconds).
medic/cht-core#6025
> Add a timeout to outbound requests

- webapp/src/css/enketo/medic.less
Datetimepicker will show in a wrong place if the container of the input is not positioned relative
medic/cht-core#2272
> Fixes positioning of Datetimepicker

- package-lock.json
- package.json
> Bump version for 3.8.0

- shared-libs/message-utils/src/index.js
- shared-libs/message-utils/test/index.js
- tests/e2e/sentinel/schedules/due_tasks.spec.js
- tests/utils.js
Also adds `due_tasks` e2e test. 
medic/cht-core#6071
> Fixes SMS recipient mapping for flexible contact types

- config/default/GUIDE.md
* Changes Reference Config and similar to Reference Application
* Capitalized Tasks, Targets, etc uniformly
* Removed use of "simply" per style guide 
* Edited instructions for brevity
> Language and grammar changes

- webapp/tests/karma/unit/services/lineage-model-generator.js
> Removes debug code left in a test

- webapp/src/js/controllers/inbox.js
This isn't guaranteed to work but if it does means the data will
never be deleted unless explicitely requested by the user.
medic/cht-core#6134
> Request persistent storage

- Gruntfile.js
> Alias just the right libraries for minimal bundle size

- scripts/travis/cleanup.js
- scripts/travis/package-lock.json
- scripts/travis/package.json
After each build, delete:
- up to 50 branch artefacts that are older than 100 days
- up to 50 beta artefacts leaving the most recent 5 betas sorted by semver
medic/cht-core#5129
> Clean up branch and beta releases

- webapp/src/js/services/enketo.js
- webapp/tests/karma/unit/services/enketo.js
> Only store MRDT photos as attachments

- sentinel/src/lib/feed.js
- sentinel/src/lib/metadata.js
- sentinel/src/transitions.js
- sentinel/tests/unit/lib/feed.js
- sentinel/tests/unit/lib/metadata.js
- sentinel/tests/unit/transitions.js
Otherwise sentinel hangs until restarted.
medic/cht-core#6169
> Restart changes feed if an error is thrown

- webapp/src/js/controllers/inbox.js
- webapp/tests/karma/unit/controllers/inbox.js
> Show unread count and refresh unread count for online users.

- shared-libs/rules-engine/src/target-state.js
- shared-libs/rules-engine/test/provider-wireup.spec.js
- shared-libs/rules-engine/test/target-state.spec.js
medic/cht-core#5493
Pull Requests in Three Branches:
* Muso: medic/medic-projects#7097
* Medic-Conf: https://github.com/medic/medic-conf/issues/277 https://github.com/medic/medic-conf/issues/283
* WebApp: https://github.com/medic/cht-core/pull/6178
Base branch is https://github.com/medic/cht-core/pull/6041. Rebase to master and merge only after that PR merges.
- Backwards compatible: Works with existing data and configuration or includes a …
> 5493 - Support for "GroupBy" property on target emissions

- scripts/poe/.env.example
This ID isn't private information and folk shouldn't have to look it up
> It's OK to hardcode this ID

- shared-libs/server-checks/src/checks.js
For https://github.com/medic/cht-core/issues/6192
> Fix link in Sentinel error message

- ddocs/medic/_attachments/translations/messages-en.properties
> Missing translation added

- tests/patches/webdriver-manager-config.patch
> Bumps chromedriver patch to 79

- package-lock.json
- package.json
> Update package version to 3.9.0

- admin/src/templates/sms_forms.html
> Fix alignment on sms forms admin page

- admin/src/js/controllers/upgrade.js
> Handle invalid version numbers gracefully

- INSTALL.md
Adding how to bypass Chrome's unsafe warning.
Adding instructions on how to restart the process and get a fresh
installation.
> Updating instructions

- api/src/services/users.js
- api/tests/mocha/services/users.spec.js
- tests/e2e/api/controllers/users.js
> Adds conflict handling when adding new contacts and creating places

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
> Convert the release process into issue templates

- scripts/package-lock.json
- scripts/package.json
- scripts/replication.js
Small script to allow people to replicate between servers without
worrying about Fauxton's UI being bad and our docker image not having a
legitimate certificate.
> Replication script

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
- scripts/changelog-generator/index.js
Specifically ignore internal process issues, and won't fix issues.
> Update changelog generator to ignore issues

- webapp/src/js/actions/global.js
- webapp/src/js/controllers/reports-content.js
Implemented suggestion in issue description:
```javascript
if (change.deleted) {
if (ctrl.selectMode) {
ctrl.removeSelectedReport(change.id);
} else {
ctrl.unsetSelected();
}
}
```
medic/cht-core#6161
> Fixes race condition by checking the selectMode

- admin/src/templates/upgrade.html
> Fix typo that caused upgrade pages to display incorrectly

- tests/patches/webdriver-manager-config.patch
> Bump chromedriver to 81

- DEVELOPMENT.md
CouchDB recommends against using homebrew and if you try then the deployment fails with a cryptic message. This change makes that more explicit.
> Update dev setup instructions regarding homebrew

- webapp/src/js/controllers/inbox.js
When moving to another tab be sure to dismiss the tour so it
doesn't overstay its welcome.
medic/cht-core#6111
> Dismiss Tour on transition

- api/src/routing.js
- demo-forms/geopoint.xml
Add CSP exceptions to allow requests from the geopoint enketo
widget to complete.
medic/cht-core#6183
medic/cht-core#6184
> Allow geopoint requests

- shared-libs/rules-engine/src/target-state.js
- shared-libs/rules-engine/test/target-state.spec.js
- webapp/src/js/controllers/analytics-targets.js
- webapp/tests/karma/unit/controllers/analytics-targets.spec.js
> Hides non-visible targets from the user

- webapp/src/css/variables.less
> Changes UHC colors to use the Medic palette

- webapp/src/css/dropdown.less
- webapp/src/css/enketo/medic.less
> Make label colors consistently dark grey

- api/src/controllers/login.js
- api/src/public/login/script.js
- api/src/templates/login/index.html
- api/tests/mocha/controllers/login.spec.js
Actually pay attention to the redirection parameter.
Also stops it being cached by the service worker.
#5955
> Fix login page redirection

- DEVELOPMENT.md
> Add CouchDB docker instructions

- webapp/src/js/controllers/inbox.js
- webapp/tests/karma/unit/controllers/inbox.js
> Sync immediately when docs have changed locally

- sentinel/src/schedule/index.js
https://medic.slack.com/archives/C024KTGRW/p1589296690196500
> Update sentinel heartbeat to 1 minute on moh-covid-ke branch

- .github/ISSUE_TEMPLATE/z_release_major.md
> Improvements to major release process issue template

- webapp/src/js/controllers/tasks-content.js
- webapp/tests/karma/unit/controllers/tasks-content.js
> Catch hydration errors and provide stub contact in tasks-content

- tests/e2e/api/controllers/all-docs.spec.js
- tests/e2e/api/controllers/bulk-docs.spec.js
- tests/e2e/api/controllers/bulk-get.spec.js
- tests/e2e/api/controllers/db-doc.spec.js
> Convert api e2e tests to chai

- admin/src/js/controllers/export-dhis.js
- admin/src/templates/export_dhis.html
- admin/tests/unit/controllers/export-dhis.spec.js
- api/README.md
- api/src/services/export/dhis.js
- api/tests/mocha/services/export/dhis.spec.js
- config/default/app_settings.json
- config/default/translations/messages-en.properties
- ddocs/medic/_attachments/translations/messages-en.properties
> Rework the DHIS2 config schema for readability

- package-lock.json
- package.json
> Bump cht-core version to 3.10.0

- webapp/tests/karma/unit/directives/auth.js
> Add 10ms timeout for karma auth directive tests.

- package-lock.json
- package.json
- sentinel/tests/unit/lib/feed.js
And fix unit test that failed in node 8
> Revert eslint upgrade

- Gruntfile.js
- package-lock.json
- package.json
- scripts/e2e/e2e-servers.js
- shared-libs/outbound/src/outbound.js
- tests/.eslintrc
- tests/conf.js
- tests/constants.js
- tests/e2e/sentinel/schedules/purging.spec.js
- tests/e2e/sentinel/transitions/mark_for_outbound.js
- tests/utils.js
Attempts to detect the error type and provide useful and non spammy logs
medic/cht-core#6024
> Cleaner outbound error logs

- webapp/src/css/inbox.less
- webapp/src/templates/directives/header.html
Also cleans up some of the CSS and HTML used for the menu.
medic/cht-core#6492
> Increase clickable area of hamburger items

- release-notes/docs/3.8.0.md
@binokaryg Does this capture the problem you experienced in covid-moh-mali?
> Added breaking change to 3.8.1 release notes

- admin/src/js/controllers/authorization-roles.js
- admin/src/js/controllers/edit-language.js
- admin/src/js/controllers/edit-translation.js
Translations to be available after clicking the submit button after creating the translation.
medic/cht-core#6121
> New role translated without refresh

- .gitignore
- webapp/src/js/controllers/contacts.js
- webapp/src/js/controllers/messages.js
- webapp/src/js/directives/messages-list.js
- webapp/src/templates/partials/messages.html
- Fix infinity spinner issue described here: medic/cht-core#6433
- Also add IntelliJ-based IDEs settings rule to .gitignore
> 6433 fix infinite spinners

- sentinel/src/schedule/reminders.js
- sentinel/tests/unit/schedule/reminders.js
> Add ability to configure reminders to anyone

- webapp/src/js/controllers/delete-doc-confirm.js
- webapp/tests/karma/unit/controllers/delete-doc-confirm.js
- webapp/tests/karma/unit/controllers/reports.js
Deleted records are minified correctly but the patient key is not removed which is the issue addressed by this PR.
medic/cht-core#6130
> delete patient key in record if doc type is data_record

- webapp/src/js/actions/contacts.js
- webapp/src/js/controllers/contacts.js
- webapp/tests/karma/unit/controllers/contacts.js
- webapp/tests/karma/unit/store/contacts.js
Filters contact create links in by permissions to their corresponding create forms. 
medic/cht-core#6401
> Use contact forms permissions when displaying actionbar 

- shared-libs/server-checks/src/checks.js
- shared-libs/server-checks/test/checks.js
> Improve logging in server-checks

- webapp/src/css/inbox.less
Adds a more specific CSS selector to overwrite the existing value
for top.
medic/cht-core#6575
> Remove whitespace so content has more room

- .github/PULL_REQUEST_TEMPLATE.md
Some of the links were outdated.
> Updates links in GitHub pull request template

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
> Update links in release templates.

- package-lock.json
- package.json
> Update version to 3.9.1

- admin/tests/unit/controllers/message-queue.js
- package-lock.json
- package.json
- tests/patches/webdriver-manager-config.patch
- webapp/tests/karma/unit/directives/auth.js
> Bump version to 3.8.2

- webapp/src/js/controllers/contacts-report.js
- webapp/src/js/controllers/reports-add.js
- webapp/src/js/controllers/tasks-content.js
- webapp/src/js/services/android-api.js
- webapp/src/js/services/enketo.js
- webapp/src/js/services/geolocation.js
- webapp/tests/karma/unit/services/android-api.js
- webapp/tests/karma/unit/services/enketo.js
- webapp/tests/karma/unit/services/geolocation.spec.js
Will create a watcher from when you instantiate it that progressively
gets more accurate over the lifetime of the watcher.
Actually waits until it gets a handle or timesout. If 30s is too long to
potentially wait we can reduce it.
#5917
> Geolocation rework

- tests/patches/webdriver-manager-config.patch
> Bump webdriver patch to 85

- tests/scalability/start_jmeter_ec2.sh
Title says it all.
medic/cht-core#6609
> Added tag name to the s3 bucket path for easier identification

- webapp/src/ts/services/changes.service.ts
This PR will wrap the ChangeService's watch function in Angular's zone so Angular can recognise the changes in its cycle.
medic/cht-core#4750
> Putting changes watch in the angular zone

- sentinel/src/lib/feed.js
- sentinel/tests/unit/lib/feed.js
> Only resume listening when queue is not paused.

- .travis.yml
- Gruntfile.js
- package.json
- webapp/src/ts/providers/exception-handler.provider.ts
- webapp/src/ts/services/feedback.service.ts
Also, don't log debug messages in production. 
> Enables bundlesize and runs publish before test

- DEVELOPMENT.md
Instructions on docker volume args
> Fix instructions for docker volume command

- Gruntfile.js
- package-lock.json
- package.json
- webapp/angular.json
- webapp/tests/karma/karma-unit.conf.js
Also tries to stabilize the continuous karma tests. 
See: https://github.com/karma-runner/karma/issues/3267 
> Adds code coverage to Karma

- DEVELOPMENT.md
I made a few minor suggestions that I thought would improve the doc
> various suggestions related to grammar

- webapp/src/ts/services/enketo.service.ts
- webapp/src/ts/services/geolocation.service.ts
- webapp/tests/karma/ts/services/geolocation.service.spec.ts
Also migrates the timeout fix for forms saves hanging. 
> Fixes Geolocation unhandled rejections & timeouts

- webapp/src/ts/modals/bulk-delete-confirm/bulk-delete-confirm.component.html
- webapp/src/ts/modals/bulk-delete-confirm/bulk-delete-confirm.component.ts
- webapp/src/ts/modals/check-date/check-date.component.html
- webapp/src/ts/modals/delete-doc-confirm/delete-doc-confirm.component.html
- webapp/src/ts/modals/delete-doc-confirm/delete-doc-confirm.component.ts
- webapp/src/ts/modals/edit-report/edit-report.component.ts
- webapp/src/ts/modals/edit-user/edit-user-settings.component.html
- webapp/src/ts/modals/edit-user/edit-user-settings.component.ts
- webapp/src/ts/modals/edit-user/update-password.component.html
- webapp/src/ts/modals/edit-user/update-password.component.ts
- webapp/src/ts/modals/feedback/feedback.component.html
- webapp/src/ts/modals/feedback/feedback.component.ts
- webapp/src/ts/modals/guided-setup/guided-setup.component.ts
- webapp/src/ts/modals/logout/logout-confirm.component.ts
- webapp/src/ts/modals/mm-modal/mm-modal.component.html
- webapp/src/ts/modals/mm-modal/mm-modal.ts
- webapp/src/ts/modals/navigation-confirm/navigation-confirm.component.ts
- webapp/src/ts/modals/reloading/reloading.component.html
- webapp/src/ts/modals/reloading/reloading.component.ts
- webapp/src/ts/modals/send-message/send-message.component.html
- webapp/src/ts/modals/send-message/send-message.component.ts
- webapp/src/ts/modals/session-expired/session-expired.component.html
- webapp/src/ts/modals/session-expired/session-expired.component.ts
- webapp/src/ts/modals/tour/tour-select.component.html
- webapp/src/ts/modals/verify-report/verify-report.component.ts
> Fixes modals wrapper ids.

- .github/actions/deploy-with-medic-conf/README.md
- .github/actions/deploy-with-medic-conf/action.yml
https://github.com/medic/cht-core/issues/6758
https://github.com/medic/app-services-team/issues/5
> Re-usable GitHub action for deploying configurations via medic-conf

- tests/conf.js
enabled sentinel queue [ tests](https://github.com/medic/angular10-migration/issues/70)
> 70 sentinel queue tests

- tests/conf.js
Enable content security policy tests
medic/angular10-migration#[81 ](https://github.com/medic/angular10-migration/issues/81)
> enable content-security-policy test

- tests/conf.js
[description]
medic/angular10-migratioe#[59](https://github.com/medic/angular10-migration/issues/59)
> 59 api server on angular10

- webapp/src/ts/modules/contacts/contacts.component.ts
- webapp/tests/karma/ts/modules/contacts/contacts.component.spec.ts
Fix Contacts tour not starting when other tab was active.
- medic/cht-core#4750
- https://github.com/medic/angular10-migration/issues/18
> 4750 - Angular 10 migration: Contacts tour fix

- webapp/src/css/inbox.less
- webapp/src/ts/components/filters/freetext-filter/freetext-filter.component.html
- webapp/src/ts/modules/contacts/contacts-content.component.html
- webapp/src/ts/modules/contacts/contacts-filters.component.html
Little fixes for contact's search filter in mobile view and translation parameters in contact's cards
https://github.com/medic/angular10-migration/issues/103
https://github.com/medic/angular10-migration/issues/100
The software is provided under AGPL-3.0. Contributions to this project are accepted under the …
> 4750 contact bug fixes

- tests/conf.js
- tests/e2e/create-meta-db.js
- tests/page-objects/common/common.po.js
- tests/page-objects/login/login.po.js
- tests/page-objects/users/add-user-modal.po.js
- tests/page-objects/users/users.po.js
fix/ update test on creating the meta data database. 
> E2e create meta data

- webapp/src/ts/effects/contacts.effects.ts
- webapp/tests/karma/ts/effects/contacts.effects.spec.ts
This fixes this [bug](https://github.com/medic/angular10-migration/issues/96)
> fix contact update bug and add test

- DEVELOPMENT.md
> Document Node LTS versions required

- package-lock.json
- package.json
> Bumping version to 3.10.2.

- Gruntfile.js
- scripts/e2e/start_webdriver.sh
Scripted the chrome driver install when running in CI
> Chrome driver script

- webapp/src/js/app.js
- webapp/src/js/moment-locales/ceb.js
- webapp/src/js/moment-locales/hil.js
- webapp/src/js/moment-locales/tl.js
Closes #6861 
This PR only cherry-picks the commits from https://github.com/medic/cht-core/pull/6866/commits in an effort to have the same PR running on Travis on the Medic remote, working around docker pull limits.
The original https://github.com/medic/cht-core/pull/6866/commits PR is preferred, but this is being queued up in the event that we have issues and end up at the end of the Travis build queue.
> Using moment locales

- webapp/src/ts/services/contact-summary.service.ts
- webapp/src/ts/services/rules-engine.service.ts
- webapp/tests/karma/ts/services/contact-summary.service.spec.ts
This PR migrates the webapp changes from [this other PR](https://github.com/medic/cht-core/pull/6808) only. Tested following the steps in the original ticket.
Migration ticket: https://github.com/medic/angular10-migration/issues/116
Original ticket with test steps: https://github.com/medic/cht-core/issues/6629 …
> Migration of feedback service fix.

- webapp/.eslintrc
- webapp/tests/karma/utils.js
Removing unused globals and overrides in webapp's eslint.
https://github.com/medic/angular10-migration/issues/117
> Cleaned eslint for webapp

- tests/conf-disabled.js
- tests/e2e/login/token-login.spec.js
- tests/page-objects/common/common.po.js
- tests/page-objects/login/login.po.js
- tests/utils.js
Refactor token login specs for angular 10 and async/await
https://github.com/medic/angular10-migration/issues/69
> 69 token login

- .github/PULL_REQUEST_TEMPLATE.md
[skip ci]
Adds checkboxes to code review section of PR template
> adds checkboxes to code review section of PR template

- webapp/src/ts/services/android-api.service.ts
- webapp/tests/karma/ts/services/android-api.service.spec.ts
This addresses a TODO task in the android-api service for calling the simprints service.
> call simprints service and enable tests

- tests/conf-disabled.js
- tests/e2e/contacts/add-new-health-center.js
- tests/e2e/contacts/add-new-person.js
- tests/page-objects/contacts/contacts.po.js
- tests/page-objects/forms/generic-form.po.js
Bundled 2 together since they use a lot of the same functions.
https://github.com/medic/angular10-migration/issues/62 
https://github.com/medic/angular10-migration/issues/61
> 61 add new health center and add person

- tests/conf-disabled.js
- tests/e2e/forms/submit-photo-upload-form.spec.js
- tests/page-objects/forms/generic-form.po.js
- tests/page-objects/forms/photo-upload.po.js
Refactor submit_upload_form
https://github.com/medic/angular10-migration/issues/65
> submit upload form refactor

- tests/conf-disabled.js
- tests/e2e/forms/submit-delivery-form.specs.js
- tests/helper.js
- tests/page-objects/forms/delivery-report.po.js
async/await and angular 10 for 64_submit_delivery_Form
> 64 submit delivery form

- tests/conf-disabled.js
- tests/e2e/users/add-user.specs.js
- tests/helper.js
- tests/page-objects/users/add-user-modal.po.js
Update add-user-tests to async/await and angular 10 changes
medic/cht-core#https://github.com/medic/angular10-migration/issues/77
> 77 add user tests async

- package-lock.json
- package.json
- tests/.eslintrc
- tests/e2e/login/purge.spec.js
- tests/e2e/registration-by-sms.js
- tests/e2e/sentinel/utils.js
- tests/page-objects/contacts/contacts.po.js
- tests/page-objects/forms/delivery-report.po.js
- tests/page-objects/forms/z-score.po.js
- tests/page-objects/reports/reports.po.js
- tests/utils.js
Eslint plugin to check the functions that have async are also using await. Only for the test eslint files. Includes the fixes based on the eslint findings.  
> missing async eslint updates

- DEVELOPMENT.md
There was some talk in App Services about how some folks like to install outside of using docker and found that `snap` was a viable alternative.  It seemed worth documenting given the `DEVELOPMENT.md ` doc targets technical folks.
no issue
> Update developer install instructions with bare metal couch install steps

- tests/e2e/login/purge.spec.js
Purge will randomly fail. After reviewing it looks like there are a few awaits needed. 
https://github.com/medic/angular10-migration/issues/136
> handeling more async calls with await

- .github/ISSUE_TEMPLATE/support_request.md
Adds a support request GH issue template
> Adds a support request GitHub issue template

- webapp/src/ts/modules/messages/messages.component.html
- webapp/src/ts/modules/messages/messages.component.ts
- webapp/tests/karma/ts/modules/messages/messages.component.spec.ts
Fixing change detection in messages tab.
> Fix change detection in messages

- tests/conf-disabled.js
- tests/conf.js
- tests/e2e/contact-summary.js
- tests/e2e/contacts/add-new-health-center.js
- tests/e2e/contacts/add-new-person.js
- tests/e2e/create-meta-db.js
- tests/e2e/docs-by-replication-key-view.js
- tests/e2e/forms/submit-delivery-form.specs.js
- tests/e2e/forms/submit-photo-upload-form.spec.js
- tests/e2e/forms/submit-z-score-form.spec.js
- tests/e2e/login/db-sync-filter.spec.js
- tests/e2e/login/purge.spec.js
- tests/e2e/login/token-login.spec.js
- tests/e2e/registration-by-sms.js
- tests/e2e/send-message.js
- tests/e2e/sentinel/utils.js
- tests/e2e/service-worker.js
- tests/e2e/sms-gateway.js
- tests/e2e/submit-enketo-form.js
- tests/e2e/transitions/public_form_transitions.spec.js
- tests/e2e/transitions/sms_workflows.spec.js
- tests/e2e/users/add-user.specs.js
- tests/page-objects/forms/delivery-report.po.js
- tests/page-objects/forms/photo-upload.po.js
- tests/page-objects/forms/z-score.po.js
- tests/utils.js
> Removes duplicated code from e2e tests utils.

- Gruntfile.js
Cleans up commented code. 
Cleans up eslint command. 
Runs eslint before installing dependencies (fail early). 
Runs shared libs tests after webapp and admin (like before). 
https://github.com/medic/angular10-migration/issues/115
> Clean up gruntfile

- tests/conf-disabled.js
- tests/e2e/login/db-sync-filter.spec.js
- tests/e2e/target-aggregates.spec.js
- tests/page-objects/analytics/analytics.po.js
- tests/page-objects/common/common.po.js
- webapp/src/ts/components/analytics-targets-progress/analytics-targets-progress.component.html
- webapp/src/ts/components/content-row-list-item/content-row-list-item.component.ts
- webapp/src/ts/modules/analytics/analytics-target-aggregates-detail.component.ts
- webapp/tests/karma/ts/modules/analytics/analytics-target-aggregates-detail.component.spec.ts
Fixes some target-aggregates markup.
Also fixes selected style not appearing.
https://github.com/medic/angular10-migration/issues/145
https://github.com/medic/angular10-migration/issues/146
> Enable target-aggregates e2e test.

- tests/conf-disabled.js
- tests/e2e/forms/submit-delivery-form.specs.js
- tests/page-objects/forms/generic-form.po.js
- tests/utils.js
https://github.com/medic/angular10-migration/issues/144
> Fix flaky upload form e2e test

- tests/conf-disabled.js
- tests/conf.js
- tests/e2e/content-security-policy.js
- tests/e2e/navigation/common.specs.js
- tests/e2e/navigation/hamburger-menu.js
- tests/e2e/transitions/message_duplicates.spec.js
- tests/helper.js
- tests/page-objects/common/common.po.js
https://github.com/medic/angular10-migration/issues/84
https://github.com/medic/angular10-migration/issues/72
https://github.com/medic/angular10-migration/issues/81
https://github.com/medic/angular10-migration/issues/141
> Migrates infodocs, CSP, message_duplicates and navigation e2e tests

- tests/page-objects/contacts/contacts.po.js
Fix for add new health center test
https://github.com/medic/angular10-migration/issues/132
> e2e flacky: add new health center test

- tests/conf-disabled.js
- tests/e2e/release/cht-config/contact-create.specs.js
- tests/e2e/release/cht-config/contact-edit.specs.js
- tests/e2e/submit-enketo-form.js
- tests/helper.js
- tests/page-objects/contacts/contacts.po.js
Fixes flaky Submit Enketo form submits on reports tab
https://github.com/medic/angular10-migration/issues/133
https://github.com/medic/angular10-migration/issues/142
> Migrates /release/cht-config tests

- tests/.eslintrc
- tests/conf-disabled.js
- tests/e2e/bulk-delete.js
- tests/e2e/login/db-sync-filter.spec.js
- tests/e2e/login/purge.spec.js
- tests/helper.js
- tests/page-objects/common/common.po.js
- tests/page-objects/login/login.po.js
- tests/page-objects/reports/reports.po.js
Bulk delete changes for asyn/await and angular 10
https://github.com/medic/angular10-migration/issues/79
> 79 bulk delete async

- tests/e2e/login/privacy-policy.spec.js
- tests/helper.js
- tests/page-objects/common/common.po.js
- tests/utils.js
https://github.com/medic/angular10-migration/issues/149
> Fixes flaky privacy policy test

- tests/conf-disabled.js
- tests/e2e/contact-summary.js
- tests/page-objects/contacts/contacts.po.js
- tests/page-objects/forms/generic-form.po.js
Enabling contact summary e2e
https://github.com/medic/angular10-migration/issues/153
> Enable contact summary e2e

- tests/e2e/bulk-delete.js
- tests/page-objects/common/common.po.js
- tests/page-objects/reports/reports.po.js
Fix for bulk delete e2e test.
https://github.com/medic/angular10-migration/issues/150
> Bulk delete e2e test

- api/src/db.js
- api/tests/mocha/migrations/restrict-access-to-audit-db.spec.js
- api/tests/mocha/migrations/restrict-access-to-sentinel-db.spec.js
- api/tests/mocha/services/monitoring.spec.js
- shared-libs/outbound/test/outbound.spec.js
> Fix a bunch of brittle unit tests.

- tests/e2e/contacts/add-new-health-center.js
- tests/e2e/create-meta-db.js
- tests/e2e/login/login.specs.js
- tests/e2e/login/privacy-policy.spec.js
- tests/e2e/login/purge.spec.js
- tests/e2e/login/token-login.spec.js
- tests/e2e/target-aggregates.spec.js
- tests/helper.js
- tests/page-objects/common/common.po.js
- tests/page-objects/login/login.po.js
- tests/page-objects/privacy-policy/privacy-policy.po.js
- tests/page-objects/users/users.po.js
https://github.com/medic/angular10-migration/issues/161
https://github.com/medic/angular10-migration/issues/164
https://github.com/medic/angular10-migration/issues/140
https://github.com/medic/angular10-migration/issues/165
https://github.com/medic/angular10-migration/issues/147
> Fix login e2e tests

- tests/conf.js
- tests/e2e/translations/incorrect-locale.spec.js
- tests/helper.js
- tests/page-objects/common/common.po.js
- tests/page-objects/contacts/contacts.po.js
- tests/page-objects/user-settings/user-settings.po.js
- tests/page-objects/users/add-user-modal.po.js
- tests/utils.js
https://github.com/medic/angular10-migration/issues/167
> Merges and migrates incorrect-locale e2e test

- tests/e2e/forms/submit-z-score-form.spec.js
- tests/e2e/send-message.js
- tests/e2e/sentinel/transitions/mark_for_outbound.js
- tests/e2e/sentinel/transitions/muting.spec.js
- tests/e2e/sentinel/transitions/registration.spec.js
- tests/e2e/sentinel/transitions/self_report.spec.js
- tests/e2e/sentinel/transitions/update_clinics.spec.js
- tests/page-objects/forms/z-score.po.js
- tests/page-objects/login/login.po.js
> Some e2e test tweaks and small fixes

- tests/e2e/concatenate-xpath-strings.spec.js
- tests/page-objects/forms/concatenate-strings.po.js
- tests/page-objects/forms/generic-form.po.js
https://github.com/medic/angular10-migration/issues/169
> Migrates concatenate xpath strings e2e test

- webapp/src/ts/app.component.ts
- webapp/src/ts/components/actionbar/actionbar.component.html
- webapp/src/ts/components/actionbar/actionbar.component.ts
- webapp/src/ts/modules/contacts/contacts-content.component.ts
- webapp/tests/karma/ts/app.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-content.component.spec.ts
> Track by form _id not internal id

- scripts/changelog-generator/index.js
Add new sections for breaking and UI/UX changes so issues labelled
as such aren't missed in the release notes.
> Add breaking changes to changelog generator

- .github/workflows/build.yml
> Fix typo in config test suites names

- package-lock.json
- package.json
> Bumps version to 3.10.3

- DEVELOPMENT.md
- TESTING.md
It was a bit easier to get  https://github.com/medic/cht-core/pull/6958 into master by creating a new branch vs rebasing. 
> add dev and testing md changes

- .github/workflows/build.yml
- .github/workflows/cleanup.yml
- scripts/travis/cleanup.js
Instead add it as a separate build that can be executed overnight.
medic/cht-core#7025
> Remove cleanup from build action

- webapp/src/ts/modules/contacts/contacts-content.component.ts
- webapp/src/ts/selectors/index.ts
- webapp/tests/karma/ts/modules/contacts/contacts-content.component.spec.ts
- webapp/tests/karma/ts/selectors/index.spec.ts
Also adds Selectors unit tests.
medic/cht-core#7022
> Pass contact-summary to forms context.

- package-lock.json
- package.json
> Bump the version for 3.11.0 release

- shared-libs/rules-engine/src/rules-state-store.js
- shared-libs/rules-engine/test/rules-state-store.spec.js
- webapp/src/ts/services/contact-view-model-generator.service.ts
- webapp/src/ts/services/tasks-for-contact.service.ts
- webapp/tests/karma/ts/services/contact-view-model-generator.service.spec.ts
> Fix rules engine trying to load tasks for undefined contact.

- webapp/tests/karma/ts/services/contact-view-model-generator.service.spec.ts
> Fixes unit test broken by other merge

- shared-libs/message-utils/src/index.js
- shared-libs/message-utils/test/index.js
- tests/e2e/transitions/sms_workflows.spec.js
> Fixes recipient resolution for reports that are about places.

- admin/src/js/controllers/forms-xml.js
- admin/src/js/main.js
- admin/src/js/services/validate-form.js
- admin/src/templates/forms_xml.html
- admin/tests/unit/controllers/forms-xml.js
- api/src/controllers/forms.js
- api/src/routing.js
- api/src/services/generate-xform.js
- api/tests/mocha/controllers/forms.spec.js
- api/tests/mocha/services/generate-xform.spec.js
New endpoint to validate XForms.
Used by medic-conf with the changes in the PR https://github.com/medic/medic-conf/pull/374, check _In Progress_ list.
Tcket: medic/medic-conf#331
> New endpoint to validate XForms

- .github/workflows/scalability.yml
- tests/scalability/run_suite.sh
- tests/scalability/start_ec2_medic.sh
* updated to use new way for env vars in github actions removed the quiet for logging and updated the jmeter version
backport the jmeter changes for scalability
> Update set env (#7063)

- tests/scalability/start_ec2_medic.sh
The curly brace isn't required and was setting the env var with extra characters. 
> remove curly

- tests/scalability/previous_results/3.10_gha.jtl
- tests/scalability/previous_results/3.11_gha.jtl
- tests/scalability/previous_results/3.9_gha.jtl
Previous results for 3.9,3.10, and 3.11 run through our Github actions and AWS flow. 
> added results from github action/aws runs for 3.9,10, and 11

- scripts/bulk-password-change.js
Script that gets the list of users on an instance and then sets there password to what is passed as an arg. 
> Script to bulk set passwords

- tests/e2e/login/login-logout.spec.js
- tests/page-objects/common/common.po.js
- tests/page-objects/login/login.po.js
Login tests = > checking login page elements/locales and log out modal
medic/cht-core #5772 
medic/cht-core #6280 
> Login logout tests

- tests/e2e/forms/forms-against-muted-contacts.spec.js
- tests/page-objects/contacts/contacts.po.js
- tests/page-objects/forms/generic-contact-form.po.js
- tests/page-objects/forms/home-visit.po.js
- tests/page-objects/forms/unmute-person.po.js
- webapp/src/ts/modules/contacts/contacts-content.component.ts
Also adds e2e test. 
medic/cht-core#7091
> Fix contact muted modal not redirecting correctly.

- README.md
> Updates status badge for GitHub Actions. 

- tests/e2e/release/cht-config/contact-create.specs.js
- tests/utils.js
> Fix Creating contacts with standard config e2e test

- webapp/src/ts/modules/about/about.component.ts
- webapp/tests/karma/ts/modules/about/about.component.spec.ts
> Handle missing doc when loading About page

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
> Updates release issue templates for milestones

- webapp/src/ts/app.component.ts
- webapp/src/ts/services/check-date.service.ts
- webapp/src/ts/services/db-sync.service.ts
- webapp/tests/karma/ts/services/check-date.service.spec.ts
- webapp/tests/karma/ts/services/db-sync.service.spec.ts
> Retry checking server date on every sync. 

- Gruntfile.js
- webapp/patches/pouchdb-unhandled-rejection.patch
> Add patch to fix unhandled rejection in PouchDB

- tests/conf.js
- tests/utils.js
Trying to remove all non-protractor functions from conf.js for reuse as we switch to new framework.
> Refactor conf file

- webapp/src/ts/modules/tasks/tasks-content.component.ts
- webapp/tests/karma/ts/modules/tasks/tasks-content.component.spec.ts
Expose task ID to Enketo
medic/cht-core#6690
> 6690 expose task id to enketo

- .github/workflows/build.yml
- Gruntfile.js
- api/src/auth.js
- api/src/middleware/authorization.js
- api/src/routing.js
- api/src/server-utils.js
- api/tests/mocha/auth.spec.js
- api/tests/mocha/middleware/authorization.spec.js
- api/tests/mocha/server-utils.spec.js
- package-lock.json
- package.json
- tests/e2e/api/routing.js
- webapp/src/js/controllers/inbox.js
Switch to GitHub Actions
medic/cht-core#7169
> Backport logout fix to 3.10.x

- package-lock.json
- package.json
> Bump version to 3.11.1

- api/server.js
- api/src/routing.js
> Disable Node HTTP request timeout. 

- api/server.js
- api/src/routing.js
> Revert "Disable Node HTTP request timeout. "

- api/server.js
- api/src/routing.js
Also fix user-info returning a 500 when not authenticated. 
medic/cht-core#7183
> Disable Node HTTP request timeout.

- package-lock.json
- package.json
> Bump version to 3.11.2

- package-lock.json
- package.json
> Bump version to 3.10.5

- tests/scalability/block-device-mapping.json
- tests/scalability/medic-os.sh
- tests/scalability/run_suite.sh
- tests/scalability/start_ec2_medic.sh
- tests/scalability/start_jmeter_ec2.sh
Changing scalability instance from spot to onDemand
- [x ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
> Changing scalability instance from spot to onDemand

- Gruntfile.js
- scripts/e2e/start_webdriver.sh
> Revert fixed webdriver version.

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
Updated based on our discussion in the product team leaders call. If/when this passes I'll copy the templates to the other repos.
> Streamline release issue template

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
- package-lock.json
- package.json
- tests/e2e/contacts/new-lineage-structure.wdio-spec.js
- tests/page-objects/contacts/contacts.wdio.page.js
- tests/page-objects/forms/generic-form.wdio.page.js
[description]
https://github.com/medic/medic-release-testing/issues/63
> 63-create-new-lineage-structure

- Gruntfile.js
- tests/integration/contacts/contact-edit.spec.js
[description]
medic/medic-release-testing#[92](medic/medic-release-testing)
> 24 change primary contact

- .github/workflows/build.yml
- Gruntfile.js
- scripts/e2e/start_webdriver.sh
- tests/conf.js
- tests/helper.js
- tests/mobile/common/common.specs.js
- tests/mobile/login/login.specs.js
- tests/page-objects/common/common.po.js
- tests/page-objects/login/login.po.js
- tests/utils.js
[description]
https://github.com/medic/medic-release-testing/issues/78
> 78 display tab text

- tests/e2e/cht/pregnancy.spec.js
- tests/page-objects/contacts/contacts.wdio.page.js
Fixing flaky test breaking master builds
> wait for submit button to disappear

- tests/e2e/common/run-guided-tour.wdio-spec.js
- tests/page-objects/common/common.wdio.page.js
- tests/page-objects/common/guided-tour.wdio.page.js
- tests/page-objects/reports/reports.wdio.page.js
[run-guided-tour-wdio-test]
medic/cht-core#[79]
> 79-run-guided-tour-wdio-test

- .github/workflows/build.yml
- Gruntfile.js
- package.json
- tests/conf.js
- tests/e2e/sms/create-place-sms.standard-wdio-spec.js
- tests/factories/cht/users/users.js
- tests/page-objects/common/common.wdio.page.js
- tests/page-objects/contacts/contacts.wdio.page.js
- tests/wdio-standard.conf.js
- webapp/src/ts/modules/contacts/contacts-content.component.html
81 create place via sms
medic/cht-core#81
> 81 create place via sms

- tests/utils/browser.js
- tests/wdio.conf.js
Closes #6787  and automates this release test https://github.com/medic/cht-release-testing/issues/111
medic/cht-core#[6787 ]
> Checking for feedback docs and failing if they exist

- api/src/routing.js
> Adds CSP hash for Enketo's onsubmit event handler.

- tests/e2e/contacts/new-lineage-structure.wdio-spec.js
- tests/page-objects/contacts/contacts.wdio.page.js
Person & Place Creation (admin only)
medic/cht-core#[[92](url)]
> 92-person-place-creation

- .github/workflows/cleanup.yml
It needs to use the AUTH_MARKET_URL to have the permissions to
delete builds.
> Update build cleanup script

- .github/workflows/build.yml
- scripts/ci/horti-compose.yml
Adds tests/results back to the archive and sets the read url. The bad news is this would mean we were logging into logs again when it failed. 
> Test results

- tests/e2e/common/renew-token.wdio-spec.js
- tests/utils/browser.js
[description]
medic/cht-core [87](https://github.com/medic/cht-release-testing/issues/87)
> 87-token-renew

- api/src/auth.js
- api/src/controllers/users.js
- api/src/services/users.js
- api/tests/mocha/auth.spec.js
- api/tests/mocha/controllers/users.spec.js
- tests/e2e/api/controllers/users.js
> Adds mm-online back to api auth

- webapp/src/ts/services/telemetry.service.ts
- webapp/tests/karma/ts/services/telemetry.service.spec.ts
Add settings version to telemetry
medic/medic-conf#304
> add settings version to telemetry

- tests/conf.js
- tests/e2e/sentinel/queue.spec.js
- tests/e2e/sentinel/schedules/background-cleanup.spec.js
- tests/e2e/sentinel/schedules/due_tasks.spec.js
- tests/e2e/sentinel/schedules/outbound.spec.js
- tests/e2e/sentinel/schedules/purging.spec.js
- tests/e2e/sentinel/schedules/reminders.spec.js
- tests/e2e/sentinel/transitions/accept_patient_reports.spec.js
- tests/e2e/sentinel/transitions/conditional_alerts.spec.js
- tests/e2e/sentinel/transitions/death_reporting.spec.js
- tests/e2e/sentinel/transitions/default_responses.spec.js
- tests/e2e/sentinel/transitions/generate_patient_id_on_people.spec.js
- tests/e2e/sentinel/transitions/generate_shortcode_on_contacts.spec.js
- tests/e2e/sentinel/transitions/mark_for_outbound.js
- tests/e2e/sentinel/transitions/multi_report_alerts.spec.js
- tests/e2e/sentinel/transitions/muting.spec.js
- tests/e2e/sentinel/transitions/registration.spec.js
- tests/e2e/sentinel/transitions/resolve_pending.spec.js
- tests/e2e/sentinel/transitions/self_report.spec.js
- tests/e2e/sentinel/transitions/update_clinics.spec.js
- tests/e2e/sentinel/transitions/update_notifications.spec.js
- tests/e2e/sentinel/transitions/update_scheduled_reports.spec.js
- tests/e2e/sentinel/transitions/update_sent_by.spec.js
- tests/integration/.mocharc.js
- tests/integration/hooks.js
- tests/utils.js
- tests/wdio-standard.conf.js
- tests/wdio.conf.js
[description]
medic/cht-core #7289 
> 7289 refactor e2e sentinel tests

- tests/scalability/medic-os.sh
> Fix scalability test script to set password ENVARS in proper folder

- .github/workflows/cleanup.yml
- scripts/ci/cleanup.js
> Updates script to also delete external builds

- tests/scalability/previous_results/3.13_gha.jtl
Add results from the Scalability Workflow Test [run](https://github.com/medic/cht-core/runs/3704394914?check_suite_focus=true) for `3.13.0`.
> Add scalability test results for 3.13.0

- .github/ISSUE_TEMPLATE/z_release_major.md
Add a step to the release template to track scalability results. 
> add notes about scalability results

- api/src/services/cookie.js
- api/tests/mocha/services/cookie.js
- tests/e2e/login/login-logout.wdio-spec.js
> Propagate AuthSession cookie max-age attribute.

- webapp/src/ts/modules/contacts/contacts-edit.component.ts
Reproduced by throttling the CPU and the network
medic/cht-core#7184
> Fix partial load of contact form on slow devices

- DEVELOPMENT.md
- TESTING.md
Adds documentation for configuring UFW to work with `nginx-local-ip`.
Adds documentation for debugging wdio tests via Intellij.
> Update developer doc for debugging and firewall config

- DEVELOPMENT.md
minor change to developer readme to denote Java 11
> Specify Java 11 in developer readme

- tests/e2e/login/initial-replication.wdio-spec.js
- tests/factories/cht/reports/generic-report.js
- tests/page-objects/common/common.wdio.page.js
- tests/page-objects/login/login.wdio.page.js
- webapp/src/js/bootstrapper/index.js
- webapp/tests/mocha/unit/bootstrapper.spec.js
> Create purging checkpointer before initial replication.

- admin/src/templates/upgrade.html
This PR fixes the condition that shows the admin release section.
https://github.com/medic/cht-core/issues/7320
> 7320 - Fix admin's release section 

- tests/conf.js
- tests/e2e/contacts/add-new-district.wdio-spec.js
- tests/e2e/reports/report-date-filter.wdio-spec.js
- tests/page-objects/contacts/contacts.wdio.page.js
- tests/page-objects/forms/generic-form.po.js
> Stabilize three e2e tests

- tests/e2e/forms/add-family-form.specs.js
- tests/e2e/forms/pregnancy-danger-sign-form.wdio-spec.js
- tests/forms/pregnancy-danger-sign-follow-up.xml
- tests/page-objects/forms/generic-form.wdio.page.js
- tests/page-objects/forms/pregnancy-danger-sign-form.wdio.page.js
- tests/page-objects/reports/reports.po.js
- tests/page-objects/reports/reports.wdio.page.js
- webapp/src/ts/effects/reports.effects.ts
- webapp/tests/karma/ts/effects/reports.effects.spec.ts
Pull the document data from the database record instead of the app's global store when setting the verification fields
medic/cht-core#6802
> Keep report minified when verifying one

- tests/e2e/contacts/contact-details.wdio-spec.js
> Fix contact-detail flaky e2e test

- package-lock.json
- package.json
> Bump version to 3.13.1

- webapp/src/ts/components/filters/multi-dropdown-filter/multi-dropdown-filter.component.ts
> Fix single place selection report filter header translation

- api/src/controllers/export-data.js
- api/tests/mocha/controllers/export-data.spec.js
- tests/integration/.mocharc.js
- tests/integration/api/controllers/export-data-2.js
- webapp/src/ts/modules/reports/reports.component.ts
Also fixes API export throwing errors when using the "verified" filter. 
medic/cht-core#7464
medic/cht-core#7465
> Webapp report export uses filters

- tests/utils.js
> Retry when resetting user contact doc

- tests/scalability/previous_results/3.14_gha.jtl
Add results from the Scalability Workflow Test [run](https://github.com/medic/cht-core/runs/5145691804?check_suite_focus=true) for 3.14.0.
> Add scalability test results for 3.14.0

- tests/scalability/run_suite.sh
- tests/scalability/start_ec2_medic.sh
- tests/scalability/start_jmeter_ec2.sh
> 7513 fix scalability tests

- package-lock.json
- package.json
- tests/wdio.conf.js
@dianabarsan  Draft PR for devtools for logging. The output is shown below. There are duplicates that I'm unsure exactly why those are coming in.  The `Runtime.consoleAPICalled` event has so many entries it is insane. I'll tidy up a bit before a full PR but wanted your thoughts.  
```
[error]: network Failed to load resource: the server responded with a status of 404 (Object Not Found) url: http://localhost:4988/medic-user-admin-meta/ at 1628870525281.921
[error]: network Failed to load resource: the server responded with a status of 404 (Object Not Found) url: http://localhost:4988/medic-user-admin-meta/ at 1628870525281.921
[error]: network Failed to load resource: the server responded with a status of 404 (Object Not Found) url: http://localhost:4988/medic/partners? at …
```
> using devtools to get console log

- .github/ISSUE_TEMPLATE/z_release_major.md
Add step for public beta announcement and product team call retro.
> Update release process

- TESTING.md
> Clearer instructions for viewing allure report

- admin/src/js/controllers/upgrade.js
- admin/src/js/services/version.js
- admin/tests/unit/services/version.js
Make use of `version` if `base_version` is not set in deploy_info
medic/cht-core#7072
> 7072 incompatible upgrades

- package-lock.json
- package.json
- tests/e2e/forms/repeat-form.wdio-spec.js
- tests/forms/repeat-translation-button.xml
- tests/forms/repeat-translation-count.xml
- tests/page-objects/reports/reports.wdio.page.js
- webapp/src/ts/services/enketo.service.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
> Backport repeat translation fix to 3.14.x

- tests/e2e/forms/repeat-form.wdio-spec.js
- tests/forms/repeat-translation-select.xml
- webapp/src/ts/services/enketo.service.ts
> Fix blank labels in form with repeat group with choice_filter xlsforms

- package-lock.json
- package.json
> Bump to 3.14.2

- webapp/src/ts/actions/analytics.ts
- webapp/src/ts/actions/contacts.ts
- webapp/src/ts/actions/global.ts
- webapp/src/ts/actions/messages.ts
- webapp/src/ts/actions/reports.ts
- webapp/src/ts/actions/services.ts
- webapp/src/ts/actions/target-aggregates.ts
- webapp/src/ts/actions/tasks.ts
- webapp/src/ts/app.component.ts
- webapp/src/ts/components/components.module.ts
- webapp/src/ts/directives/directives.module.ts
- webapp/src/ts/main.ts
- webapp/src/ts/modals/modals.module.ts
- webapp/src/ts/modules/about/about.routes.ts
- webapp/src/ts/modules/configuration-user/configuration-user.routes.ts
- webapp/src/ts/modules/error/error.routes.ts
- webapp/src/ts/modules/home/home.routes.ts
- webapp/src/ts/modules/modules.module.ts
- webapp/src/ts/pipes/pipes.module.ts
- webapp/src/ts/reducers/contacts.ts
- webapp/src/ts/reducers/reports.ts
- webapp/src/ts/services/enketo.service.ts
- webapp/src/ts/services/navigation.service.ts
Sending these quick fixes in a separate PR for fast merging into the main branch, because I'm working on a feature release that might take long to merge into main. 
This PR:
- Fixes data types in Enketo Service interface.
- Remove unused parameters in Enketo Service function.
- Fixes alias in imports.
Ticket: https://github.com/medic/cht-core/issues/7557
> Quick code fixes in webapp

- tests/e2e/snackbar.wdio-spec.js
- tests/page-objects/common/common.wdio.page.js
> First attempt to fix snackbar e2e tests

- .github/ISSUE_TEMPLATE/z_release_patch.md
- scripts/release-notes/index.js
> Link to known issues from release notes

- .github/ISSUE_TEMPLATE/z_release_feature.md
Add Feature Release ticket template
per #7609
> Add Feature Release ticket template

- scripts/release-notes/index.js
This means validation passes - the type is ignored later in the process so it's not included in the release notes.
> Add internal process type so validation passes

- admin/src/js/controllers/main.js
- admin/src/js/services/language.js
> Use the locale cookie to set the language

- api/src/services/config-watcher.js
- api/tests/mocha/services/config-watcher.spec.js
> Handle deleted docs gracefully

- api/src/controllers/changes.js
- api/tests/mocha/controllers/changes.js
- config/covid-19/app_settings.json
- config/covid-19/app_settings/base_settings.json
- config/default/app_settings.json
- tests/config.default.json
- tests/e2e/api/controllers/_changes.spec.js
- tests/integration/.mocharc.js
> Remove continuous replication API support

- tests/e2e/forms/pregnancy-visit.wdio-spec.js
- tests/page-objects/forms/generic-form.wdio.page.js
- tests/page-objects/forms/pregnancy-visit-form.wdio.page.js
- tests/page-objects/reports/reports.wdio.page.js
- tests/wdio.conf.js
e2e for pregnancy visit report.
> Pregnancy visit test

- .github/ISSUE_TEMPLATE/config.yml
> Add config linking to other reporting channels

- .github/ISSUE_TEMPLATE/z_release_feature.md
To match the work done [here](https://github.com/medic/cht-core/commit/726b973c4f72117f50af974e7f00a8cbc562af9a).
> Match FR template to new beta format

- tests/AUTOMATE_TEST_GUIDE.md
Document about a small guide that we can follow to create new automated test cases
> Automated test guide

- tests/e2e/forms/add-family-form.wdio-spec.js
- tests/e2e/forms/add-family-form.wdio-specs.js
- tests/page-objects/forms/add-family-form.wdio.page.js
- tests/page-objects/forms/generic-form.wdio.page.js
- tests/wdio.conf.js
> Refactor add family form tests

- haproxy/entrypoint.sh
- haproxy/haproxy.cfg
- scripts/build/cht-compose.yml.template
> Pass comma-separated couchdb servers to haproxy

- shared-libs/rules-engine/src/task-states.js
- shared-libs/rules-engine/test/mocks.js
- shared-libs/rules-engine/test/task-states.spec.js
There was some discussion about what the upper limit should be. I went for a conservative option of 6 months but open to suggestion!
medic/cht-core#6564
> Set an upper limit on future tasks

- webapp/src/ts/modules/reports/reports-content.component.html
> Fix the order of the raw content label

- admin/src/js/controllers/forms-xml.js
- admin/src/js/services/validate-form.js
- admin/tests/unit/controllers/forms-xml.js
> Add xmlVersion when uploading to admin app

- webapp/src/ts/modules/contacts/contacts-edit.component.ts
- webapp/src/ts/services/contact-save.service.ts
- webapp/tests/karma/ts/modules/contacts/contacts-edit.component.spec.ts
- webapp/tests/karma/ts/services/contact-save.service.spec.ts
> Record form version when editing contacts

- api/package-lock.json
- api/package.json
- api/src/controllers/login.js
- api/src/controllers/privacy-policy.js
- api/src/public/login/style.css
- api/src/public/privacy-policy/script.js
- api/src/routing.js
- api/src/services/privacy-policy.js
- api/src/templates/login/index.html
- api/src/templates/login/token-login.html
- api/src/templates/privacy-policy/index.html
- api/tests/mocha/controllers/privacy-policy.spec.js
- api/tests/mocha/services/privacy-policy.spec.js
> Make privacy policy available without authentication

- webapp/tests/.eslintrc
- webapp/tests/karma/ts/services/enketo.service.spec.ts
Skip tests with `xit`.
medic/cht-core#7765
> Skip Webapp blocking unit tests

- api/src/services/users-replace.js
- api/tests/mocha/services/users-replace.spec.js
> Add unit tests for offline user replace

- scripts/conflicts/diff.js
> Update diff.js with spelling correction

- scripts/.eslintrc
- scripts/build/index.js
> Archv3 - Publish clustered couchdb image

- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/wdio.conf.js
> Change base branch and change how we get the version.

- package-lock.json
- package.json
> Bump version to 4.0.0

- webapp/package-lock.json
- webapp/package.json
> Update openrosa-xpath-evaluator to fix scientific notation bug

- scripts/build/cht-core.yml.template
- scripts/build/cht-couchdb-cluster.yml.template
- scripts/build/cht-couchdb-single-node.yml.template
> Use local log driver

- .github/workflows/build.yml
- scripts/build/index.js
- scripts/build/versions.js
- scripts/ci/tag-docker-images.js
- tests/e2e/upgrade/wdio.conf.js
> Publish to public ECR

- couchdb/docker-entrypoint.sh
> Set secret when using single node CouchDb

- nginx/README.md
Update cht-nginx readme formatting
> Update README.md formatting, more succinct

- scripts/build/cht-core.yml.template
medic/cht-core#7884
* [CHT Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7884-restart-services-always/docker-compose/cht-core.yml)
* CouchDB Single: COUCH_SINGLE_COMPOSE_URL
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7884-restart-services-always/docker-compose/cht-couchdb-clustered.yml) 
> Always restart docker services

- Gruntfile.js
- admin/src/js/controllers/edit-user.js
- api/src/services/user-db.js
- api/src/services/users.js
- couchdb/README.md
- webapp/src/ts/providers/exception-handler.provider.ts
medic/cht-core#6574
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:6574-remove-sensitive-words/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:6574-remove-sensitive-words/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:6574-remove-sensitive-words/docker-compose/cht-couchdb-clustered.yml)
> Remove sensitive words

- tests/e2e/default/enketo/submit-countdown-timer-form.wdio-spec.js
- tests/page-objects/default/enketo/countdown-timer.wdio.page.js
- webapp/src/js/enketo/widgets/countdown-widget.js
Fix the countdown timer widget and refactor the audio function for readability.
Add an e2e test. Unfortunately it doesn't test much because the timer itself doesn't do anything except draw on a canvas but it'll ensure it can render.
medic/cht-core#7918
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7918-countdown-timer/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7918-countdown-timer/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7918-countdown-timer/docker-compose/cht-couchdb-clustered.yml) …
> Fix countdown timer widget

- api/src/routing.js
- tests/e2e/protractor/sms/rapidpro.spec.js
medic/cht-core#7472
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7472-fix-rapidpro-endpoint-typo/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7472-fix-rapidpro-endpoint-typo/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7472-fix-rapidpro-endpoint-typo/docker-compose/cht-couchdb-clustered.yml)
> Fix typo in rapidpro endpoint

- package-lock.json
- package.json
> Bump to 3.16.1

- package-lock.json
- package.json
> Bump to 3.17.1

- package-lock.json
- package.json
medic/cht-core#7920
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:bump_to_4.0.1/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:bump_to_4.0.1/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:bump_to_4.0.1/docker-compose/cht-couchdb-clustered.yml)
> Bump to 4.0.1

- .github/actions/update-staging-url-placeholders/compiled/index.js
medic/cht-core#7944
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7944-update-builds-url/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7944-update-builds-url/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7944-update-builds-url/docker-compose/cht-couchdb-clustered.yml)
> Compile the builds link gh action

- package-lock.json
- package.json
medic/cht-core#7903
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7903-bump-package-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7903-bump-package-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7903-bump-package-version/docker-compose/cht-couchdb-clustered.yml)
> Bump version to 4.1.0

- webapp/src/css/enketo/medic.less
- webapp/src/css/variables.less
medic/cht-core#7892
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7892-fix-enketo-hover-bug/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7892-fix-enketo-hover-bug/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7892-fix-enketo-hover-bug/docker-compose/cht-couchdb-clustered.yml)
> Change selected color and fix bug on hover

- tests/e2e/default/reports/sidebar-filter.wdio-spec.js
Fixes broken sidebar e2e. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-sidebar-e2e/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-sidebar-e2e/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-sidebar-e2e/docker-compose/cht-couchdb-clustered.yml)
> Fixes sidebar e2e

- DEVELOPMENT.md
fix link from [dev](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md) file to docs
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-fix-dev-docs-link/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-fix-dev-docs-link/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-fix-dev-docs-link/docker-compose/cht-couchdb-clustered.yml)
> fix-dev-docs-link

- webapp/src/ts/app.component.ts
- webapp/src/ts/services/contact-save.service.ts
- webapp/src/ts/services/transitions.service.ts
- webapp/src/ts/services/transitions/create-user-for-contacts.transition.ts
- webapp/src/ts/services/transitions/muting.transition.ts
- webapp/src/ts/services/transitions/test-user-for-contact.transition.ts
- webapp/src/ts/services/transitions/transition.ts
- webapp/tests/karma/ts/app.component.spec.ts
- webapp/tests/karma/ts/services/transitions.service.spec.ts
- webapp/tests/karma/ts/services/transitions/create-user-for-contacts.transition.spec.ts
- webapp/tests/karma/ts/services/transitions/muting.transition.spec.ts
Quick experiment to see if online client-side transitions could be a thing
> Update webapp logic to use client-side transitions

- .github/workflows/replace-staging-urls.yml
- .gitignore
- Gruntfile.js
- package.json
- scripts/build/index.js
- scripts/build/versions.js
Updates conditions around provided environment variables. 
Adds npm script that builds images locally and generates docker-compose files using these images. 
medic/cht-core#8014
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8014-fix-external-contrib-builds/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8014-fix-external-contrib-builds/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8014-fix-external-contrib-builds/docker-compose/cht-couchdb-clustered.yml)
> Fix external contrib builds

- .eslintrc
- admin/tests/utils.js
- shared-libs/transitions/test/unit/transitions/multi_report_alerts.js
- tests/e2e/default/users/add-user.wdio-spec.js
- tests/integration/api/controllers/db-doc.spec.js
- tests/integration/api/controllers/settings.spec.js
- webapp/src/js/enketo/widgets/countdown-widget.js
- webapp/tests/karma/ts/services/enketo-translation.service.spec.ts
medic/cht-core#7440
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7440-function-call-argument-newline/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7440-function-call-argument-newline/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7440-function-call-argument-newline/docker-compose/cht-couchdb-clustered.yml)
> Adds `function-call-argument-newline` eslint rule

- tests/e2e/upgrade/upgrade.wdio-spec.js
4.1.0 will not include 4.1.0-branch.buildtime. Reversing the two. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-upgrade-e2e/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-upgrade-e2e/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-upgrade-e2e/docker-compose/cht-couchdb-clustered.yml)
> Fix upgrade e2e test running on `master`. 

- tests/e2e/default/client-side-transitions/create-user-for-contacts.create-user.wdio-spec.js
- tests/integration/sentinel/transitions/create-user-for-contacts.spec.js
- tests/page-objects/default/contacts/contacts.wdio.page.js
Adds integration tests for adding a user while adding a contact
medic/cht-core#7753
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7753-supervisor-chw-create_integration-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7753-supervisor-chw-create_integration-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7753-supervisor-chw-create_integration-tests/docker-compose/cht-couchdb-clustered.yml)
> Add integration tests for adding a user while adding a contact

- .github/workflows/build.yml
Updates:
- docker/login-action@v1 -> docker/login-action@v2
- actions/checkout@v2 -> actions/checkout@v3
- actions/setup-node@v1 -> actions/setup-node@v3\
- aws-actions/configure-aws-credentials@v1 -> aws-actions/configure-aws-credentials@v1-node16
- actions/upload-artifact@v2 -> actions/upload-artifact@v3
Removed nelonoel/branch-name, which has not received updates in 3 years, for pulling the branch name directly from github params. 
medic/cht-core#7905
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7905-update-ci-jobs/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7905-update-ci-jobs/docker-compose/cht-couchdb.yml)
* [CouchDB …
> Bump CI actions versions

- .github/workflows/replace-staging-urls.yml
- .gitignore
- Gruntfile.js
- package.json
- scripts/build/index.js
- scripts/build/versions.js
- webapp/package-lock.json
- webapp/package.json
Fixes issue related to bikram sambat where when invalid date was inputed, cht doesn't throw an error. 
medic/cht-core#7925
Fixes for updated package is on medic/bikram-sambat#18
> Fix for #7925 by using updated bs-bootstrap

- tests/e2e/default/enketo/pregnancy.wdio-spec.js
medic/cht-core#8062
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8062-fix-e2e-test-failure/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8062-fix-e2e-test-failure/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8062-fix-e2e-test-failure/docker-compose/cht-couchdb-clustered.yml)
> Fix test failure when edd is exactly 4 weeks away

- tests/e2e/default/enketo/submit-default-delivery-form.wdio-spec.js
medic/cht-core#7966
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7966-fix-flake/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7966-fix-flake/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7966-fix-flake/docker-compose/cht-couchdb-clustered.yml)
> Attempt to fix flaky form test

- .github/workflows/build.yml
- package-lock.json
- package.json
- tests/conf.js
- tests/e2e/default/enketo/submit-default-delivery-form.wdio-spec.js
- tests/e2e/default/service-worker/service-worker.wdio-spec.js
- tests/e2e/default/wdio.conf.js
medic/cht-core#8077
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:report-test-failures/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:report-test-failures/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:report-test-failures/docker-compose/cht-couchdb-clustered.yml)
> Report test failures and add e2e test retries

- webapp/src/ts/modules/contacts/contacts-content.component.ts
medic/cht-core#7603
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7603-null-check-contact/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7603-null-check-contact/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7603-null-check-contact/docker-compose/cht-couchdb-clustered.yml)
> Check for null contact when setting action bar

- webapp/src/js/enketo/widgets/db-object-widget.js
- webapp/tests/karma/js/enketo/widgets/db-object-widget.spec.ts
medic/cht-core#7602
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7602-race-condition/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7602-race-condition/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7602-race-condition/docker-compose/cht-couchdb-clustered.yml)
> Short circuit if form is unloaded before update fires

- admin/src/js/services/version.js
- admin/tests/unit/services/version.js
medic/cht-core#7953
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7953-fix-upgrade-branches/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7953-fix-upgrade-branches/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7953-fix-upgrade-branches/docker-compose/cht-couchdb-clustered.yml)
> Fix previous releases being displayed in admin app

- tests/e2e/default/login/renew-token.wdio-spec.js
- tests/integration/api/routing.spec.js
- tests/utils.js
medic/cht-core#8110
medic/cht-core#8112
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8110-fix-date-calculation/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8110-fix-date-calculation/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8110-fix-date-calculation/docker-compose/cht-couchdb-clustered.yml)
> Fix date calculation in userCtx cookie e2e tests

- .github/ISSUE_TEMPLATE/z_release_feature.md
- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
Adds updates and clarifications to the existing [release templates](https://github.com/medic/cht-core/tree/master/.github/ISSUE_TEMPLATE).
Closes #8128 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8128-update-release-templates/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8128-update-release-templates/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8128-update-release-templates/docker-compose/cht-couchdb-clustered.yml)
> chore(#8128): Update release templates

- .github/ISSUE_TEMPLATE/z_release_feature.md
- .github/ISSUE_TEMPLATE/z_release_major.md
This PR Adds a step for  releases to add any carry over `Applies to: 4.xx.` for known issues
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-couchdb-clustered.yml)
> Update release template to carry over any known issues labels

- .github/workflows/build.yml
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8151-skip-uploading-allure-history/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8151-skip-uploading-allure-history/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8151-skip-uploading-allure-history/docker-compose/cht-couchdb-clustered.yml)
> chore(#8151): skip uploading allure history when not master

- sentinel/server.js
- tests/e2e/default/transitions/create-user-for-contacts.replace-user.wdio-spec.js
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8154-reduce-log-spam/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8154-reduce-log-spam/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8154-reduce-log-spam/docker-compose/cht-couchdb-clustered.yml)
> 8154 reduce log spam

- .github/PULL_REQUEST_TEMPLATE.md
Updating template to match [documentation](https://github.com/medic/cht-docs/pull/1022).
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_commit_message_in_pr_template/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_commit_message_in_pr_template/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_commit_message_in_pr_template/docker-compose/cht-couchdb-clustered.yml)
> chore: update commit types

- tests/e2e/default/enketo/extension-lib-form.wdio-spec.js
- tests/page-objects/default/enketo/extension-lib.wdio.page.js
- webapp/src/ts/services/cht-script-api.service.ts
- webapp/tests/karma/ts/services/cht-script-api.service.spec.ts
medic/cht-core#8210
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8210-extension-libs-exports/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8210-extension-libs-exports/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8210-extension-libs-exports/docker-compose/cht-couchdb-clustered.yml)
> feat(#8210): update extension-libs file format

- webapp/src/css/inbox.less
- webapp/src/ts/modules/contacts/contacts.component.html
- webapp/src/ts/modules/messages/messages.component.html
closes https://github.com/medic/cht-core/issues/8213
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix(8213)-contact-new-not-scroll/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix(8213)-contact-new-not-scroll/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix(8213)-contact-new-not-scroll/docker-compose/cht-couchdb-clustered.yml)
> fix(#8213): prevent contact and messages "new" button from scrolling

- tests/e2e/default/enketo/add-family.wdio-spec.js
medic/cht-core#8236
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8236-disable-add-family-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8236-disable-add-family-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8236-disable-add-family-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8236): Disable Submit Add Family form test

- webapp/src/ts/components/navigation/navigation.component.ts
- webapp/src/ts/components/search-bar/search-bar.component.html
- webapp/src/ts/components/search-bar/search-bar.component.ts
- webapp/tests/karma/ts/components/navigation/navigation.component.spec.ts
- webapp/tests/karma/ts/components/search-bar/search-bar.component.spec.ts
- Fixes exception in the contact tab (navigation component)
- Fixes exception in the reports tab (search bar component)
- Adds test coverage for the search bar component.
medic/cht-core#8022
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8022-angular-exception-contacts-reports/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8022-angular-exception-contacts-reports/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8022-angular-exception-contacts-reports/docker-compose/cht-couchdb-clustered.yml) …
> fix(8022): angular expression changed exception in contacts and reports tab

- .github/ISSUE_TEMPLATE/z_release_feature.md
- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
- tests/scalability/previous_results/4.2.0.json
- updates release steps
- uploads scalability result file
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_template_for_release/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_template_for_release/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_template_for_release/docker-compose/cht-couchdb-clustered.yml)
> chore: updating release steps and uploading scalability result for 4.2.0

- .husky/pre-commit
- package-lock.json
- package.json
medic/cht-core#8273
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8273-add-husky-pre-commit/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8273-add-husky-pre-commit/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8273-add-husky-pre-commit/docker-compose/cht-couchdb-clustered.yml)
> chore(#8273): Add husky and pre-commit hook that stops direct commits to master

- tests/e2e/upgrade/wdio.conf.js
medic/cht-core#8281
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8281-upgrade-from-latest-release/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8281-upgrade-from-latest-release/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8281-upgrade-from-latest-release/docker-compose/cht-couchdb-clustered.yml)
> chore(#8281): Update upgrade e2e test to install latest release instead of master.

- nginx/nginx.conf
medic/cht-core#8214
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8214-increase-nginx-timout/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8214-increase-nginx-timout/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8214-increase-nginx-timout/docker-compose/cht-couchdb-clustered.yml)
> chore(#8214): Increase nginx timeout to 1h to match ALB timeout

- package-lock.json
- package.json
medic/cht-core#8300
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.1-package-updates/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.1-package-updates/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.1-package-updates/docker-compose/cht-couchdb-clustered.yml)
> chore(#8300): Bump version to 4.2.1

- api/.eslintrc
- api/src/auth.js
- api/src/config.js
- api/tests/mocha/services/db-doc.spec.js
- sentinel/.eslintrc
- sentinel/tests/unit/lib/purging.js
- tests/.eslintrc
- tests/e2e/default/purge/purge.wdio-spec.js
- tests/e2e/default/wdio.conf.js
- tests/e2e/protractor/sms/rapidpro.spec.js
- tests/integration/api/controllers/all-docs.spec.js
- tests/integration/couchdb/couch_chttpd.spec.js
- tests/integration/sentinel/schedules/reminders.spec.js
- tests/integration/sentinel/transitions/mark-for-outbound.spec.js
[We _can_ have nice things](https://eslint.org/blog/2020/07/eslint-v7.5.0-released/#optional-chaining-support) in E2E tests, API and Sentinel. 
`shared-libs` are pending, because they are required by the admin app, which fails the uglify step with optional chaining. :
```
Running "uglify:admin" (uglify) task
JS_Parse_Error [SyntaxError]: Unexpected token: punc (.)
at JS_Parse_Error.get (eval at <anonymous> (/home/diana/projects/medic-second/node_modules/grunt-contrib-uglify-es/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:75:23)
```
medic/cht-core#7440
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7440-we-can-have-nice-things/docker-compose/cht-core.yml)
* [CouchDB …
> chore(#7440): Bumps ecmaversion to 2020 to get optional chaining support.

- tests/e2e/standard/contacts/contact-summary.wdio-spec.js
medic/cht-core#8342
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8342-disable-flaky-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8342-disable-flaky-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8342-disable-flaky-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8342): disable flaky test

- tests/e2e/default/contacts/infinite-scrolling.wdio-spec.js
- tests/e2e/default/reports/infinite-scrolling.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/contacts/contacts.wdio.page.js
- webapp/src/ts/modules/reports/reports.component.ts
- webapp/src/ts/providers/scroll-loader.provider.ts
medic/cht-core#8359
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8359-infinite-contact-scroll/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8359-infinite-contact-scroll/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8359-infinite-contact-scroll/docker-compose/cht-couchdb-clustered.yml)
> fix(#8359): fix scrolling selector for contacts

- package-lock.json
- package.json
medic/cht-core#8360
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8360-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8360-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8360-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#8360): bump version to 4.2.2

- tests/e2e/default/contacts/edit.wdio-spec.js
- tests/e2e/default/contacts/infinite-scrolling.wdio-spec.js
- tests/e2e/default/enketo/add-family.wdio-spec.js
- tests/e2e/default/reports/infinite-scrolling.wdio-spec.js
- tests/e2e/default/translations/enabled-languages.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/contacts/contacts.wdio.page.js
- webapp/src/ts/modules/reports/reports.component.ts
- webapp/src/ts/providers/scroll-loader.provider.ts
#8359
(cherry picked from commit 444186ecbc107c0a667e15700a471a77a8448319)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8359-for-4.2.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8359-for-4.2.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8359-for-4.2.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#8359): fix scrolling selector for contacts (#8361)

- api/src/services/setup/upgrade-log.js
- api/tests/mocha/services/setup/upgrade-log.spec.js
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/wdio.conf.js
- tests/utils/index.js
Assuming an `upgrade_log` will always exist is wrong. 
medic/cht-core#8317
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8371-fix-upgrade-log-query/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8371-fix-upgrade-log-query/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8371-fix-upgrade-log-query/docker-compose/cht-couchdb-clustered.yml)
> fix(8317): fix update_log query.

- tests/e2e/default/telemetry/telemetry.wdio-spec.js
medic/cht-core#8378
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8378-fix-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8378-fix-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8378-fix-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8378): use correct momentjs function

- tests/e2e/default/telemetry/telemetry.wdio-spec.js
#8378
(cherry picked from commit 1d19531b2404595d17f63b631c659a717a786ee5)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8378-for-4.2.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8378-for-4.2.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8378-for-4.2.x/docker-compose/cht-couchdb-clustered.yml)
> chore(#8378): telemetry e2e fix for 4.2.x

- tests/e2e/default/telemetry/telemetry.wdio-spec.js
medic/cht-core#8424
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-telemetry-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-telemetry-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-telemetry-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8424): fix telemetry test

- package-lock.json
- package.json
medic/cht-core#8418
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8418-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8418-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8418-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#8418): bump version to 4.3.0

- config/standard/test/contact-summary/nutrition/contact.json
- config/standard/test/contact-summary/nutrition/expected-output.json
The child was too old for growth monitoring. 
medic/cht-core#8435
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8435-fix-standard-nutrition/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8435-fix-standard-nutrition/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8435-fix-standard-nutrition/docker-compose/cht-couchdb-clustered.yml)
> chore(#8435): fix contact age in standard contact summary test

- .github/workflows/build.yml
#8443
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8443-mask-creds/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8443-mask-creds/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8443-mask-creds/docker-compose/cht-couchdb-clustered.yml)
> fix(#8443): mask credentials

- webapp/src/ts/app.component.ts
medic/cht-core#8463
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8463-no-wait-for-load/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8463-no-wait-for-load/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8463-no-wait-for-load/docker-compose/cht-couchdb-clustered.yml)
> fix(#8463): don't wait for all initialization tasks to load the page.

- tests/scalability/previous_results/4.3.0.json
- tests/scalability/previous_results/4.3.0.jtl
medic/cht-core#8418
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8418-jmeter-results/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8418-jmeter-results/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8418-jmeter-results/docker-compose/cht-couchdb-clustered.yml)
> chore(#8418): adds scalability tests previous results for 4.3.0

- package.json
[description]
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-build-regressions/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-build-regressions/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-build-regressions/docker-compose/cht-couchdb-clustered.yml)
> fix: wdio-local and build commands

- tests/e2e/default/sms/gateway.wdio-spec.js
- tests/factories/cht/reports/sms-pregnancy.js
Attempt to fix flaky tests by improving the message factory.
medic/cht-core#8414
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8414-fix-sms-gateway-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8414-fix-sms-gateway-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8414-fix-sms-gateway-test/docker-compose/cht-couchdb-clustered.yml)
> fix(#8414): sms gateway test flakiness

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/performance.md
- .github/ISSUE_TEMPLATE/technical_issue.md
Wrap comments in HTML comment templates so they don't get included in the issue description.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:improve-issue-template-with-comments/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:improve-issue-template-with-comments/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:improve-issue-template-with-comments/docker-compose/cht-couchdb-clustered.yml)
> chore: improve issue templates

- scripts/docker-helper-4.x/cht-docker-compose.sh
This ticket allows the docker helper to either default to most recent CHT version (current behavior) or allow the user to select from all known versions.
This PR should accompany a TBD docs PR so users will know about the feature
1. check out this branch `docker-helper-specify-version`
2. run through happy path of creating a new project - ensure it's on `4.3.0` (latest as of now
3. ensure existing project will start with BOTH `./cht-docker-compose.sh ENV_FILE_HERE` and following prompts to specify an existing project
4. run through new path and ensure new project of older version (branch of 4.x.x) works
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:docker-helper-specify-version/docker-compose/cht-core.yml)
* [CouchDB …
> chore(helper): let user specify version in docker helper

- .github/ISSUE_TEMPLATE/improvement.md
I missed one!
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-patch-2/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-patch-2/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-patch-2/docker-compose/cht-couchdb-clustered.yml)
> chore: improve improvement issue template

- api/src/auth.js
- api/src/routing.js
- api/tests/mocha/auth.spec.js
[description]
medic/cht-core#8516
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8516-remove-unused-endpoint/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8516-remove-unused-endpoint/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8516-remove-unused-endpoint/docker-compose/cht-couchdb-clustered.yml)
> fix(#8516): remove unused endpoint

- .github/actions/deploy-conf/README.md
- .github/actions/deploy-conf/action.yml
- .github/actions/deploy-with-medic-conf/README.md
[description]
medic/cht-core#8511
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8511-cht-conf-action/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8511-cht-conf-action/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8511-cht-conf-action/docker-compose/cht-couchdb-clustered.yml)
>  feat(#8511): add gh action to run cht-conf 

- .github/workflows/build.yml
[description]
medic/cht-core#8533
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8533-ignore-stats-push-fails/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8533-ignore-stats-push-fails/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8533-ignore-stats-push-fails/docker-compose/cht-couchdb-clustered.yml)
> chore(#8533): ignore unimportant step failures

- tests/e2e/default/more-options-menu/offline-user/all-permissions.wdio-spec.js
medic/cht-core#8522
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8522-handle-sync/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8522-handle-sync/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8522-handle-sync/docker-compose/cht-couchdb-clustered.yml)
> chore(#8522): handle sync after settings change

- package-lock.json
- package.json
medic/cht-core#8508
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8508-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8508-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8508-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#8508): bump version to 4.4.0

- haproxy/scripts/replace_password.lua
- tests/e2e/default/logging/logging.wdio-spec.js
- tests/e2e/default/suites.js
- tests/utils/index.js
[description]
medic/cht-core#8564
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8564-mask-more-credentials/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8564-mask-more-credentials/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8564-mask-more-credentials/docker-compose/cht-couchdb-clustered.yml)
> fix(#8564): mask more credentials

- package-lock.json
- package.json
medic/cht-core#8543
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8543-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8543-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8543-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#8543): bump version to 4.2.3

- .github/ISSUE_TEMPLATE/z_release_patch.md
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:template-issue-update/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:template-issue-update/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:template-issue-update/docker-compose/cht-couchdb-clustered.yml)
> chore: update patch release issue template to add labels.

- couchdb/README.md
Fixes in documentation (typos fixes in ines 14, 55)
> Documentation Typos 

- nginx/README.md
* Duplicate word and typo (line 12)
* Typo (line 15)
* Typo (line 17)
* typo (line 19)
medic/cht-core#[No previous related issue]
> Documentation fixes (duplicate word et alia)

- config/demo/translations/messages-en.properties
Typo fixed in line #428 in `config/demo/translations/messages-en.properties`
There is no break on code
medic/cht-core#[no related with previous issue]
> Typo fixed (line 428)

- config/default/translations/messages-en.properties
Typo fixed in line https://github.com/medic/cht-core/issues/428 in `config/demo/translations/messages-en.properties`
There is no break on code
medic/cht-core#[no related with previous issue]
> Updated messages-en.properties (line 428: fixed)

- shared-libs/transitions/src/lib/ids.js
This is the minimal fix... I resisted refactoring more to keep the backport easy and safe.
The DB call is quick against a warm view, so I think this is safe to do. If we find it's a limitation we can cache it in a way that's safe in a distributed environment.
An alternative approach would be to keep the ID cache but still check against the DB every time, which would save regenerating IDs every call, but that's the fast bit so I didn't think that optimisation was necessary.
Because we're going to request to the DB every request instead of every 100 requests the chance of finding 0 unused IDs has increased. This means the length of the ID would be increased more frequently which is bad for the user. To compensate I raised the generation size to 200. It's theoretically possible the length …
> fix(#7670): do not cache generated patient ids

- tests/integration/sentinel/transitions/sentinel-transition-error-log.spec.js
- tests/utils/index.js
medic/cht-core#8592
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8592-fix-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8592-fix-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8592-fix-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8592): stabilize unknown transition test

- tests/utils/index.js
medic/cht-core#8583
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8583-fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8583-fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8583-fix/docker-compose/cht-couchdb-clustered.yml)
> chore(#8583): wait for 12 seconds for logs, instead of 10.

- tests/e2e/default/service-worker/service-worker.wdio-spec.js
medic/cht-core#8538
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8538-fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8538-fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8538-fix/docker-compose/cht-couchdb-clustered.yml)
> chore(#8538): stabilize service worker e2e test

- haproxy/README.md
Typo fixed (minor): line 32
There is no break on code
> Syntax issue: line 32

- config/standard/forms/app/nutrition_exit.xml
Issues on spanish translation. 
There is no break on code
> Issues on spanish translation

- config/standard/forms/app/nutrition_exit.xml
> Issue on spanish translation

- scripts/ci/publish.js
Fixes in console logs messages (lines 39 & 45)
> Fixes in console logs messages

- config/standard/forms/app/off.xml
Issue on spanish string (line 109)
> Issue on spanish string

- config/standard/forms/app/on.xml
Fixed typo in spanish string in line 109
medic/cht-core#[no related with previous issue]
No break on code
> Issue on spanish string translated

- config/standard/forms/app/nutrition_screening.xml
Issue on spanish translation (line 335)
medic/cht-core#[No previous issue related]
> Spanish translation issue (line 335)

- tests/e2e/default/enketo/unauthorized-form.wdio-spec.js
- tests/e2e/default/sms/gateway.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/users/user.wdio.page.js
adds utils.url function that refreshes the page when the passed url is the same as the loaded page. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-e2e-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-e2e-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-e2e-tests/docker-compose/cht-couchdb-clustered.yml)
> chore: fix e2e tests post chrome update

- webapp/src/ts/modules/modules.module.ts
- webapp/tests/karma/test.ts
- webapp/tests/karma/ts/components/fast-action-button/fast-action-button.component.spec.ts
- webapp/tests/karma/ts/components/search-bar/search-bar.component.spec.ts
- webapp/tests/karma/ts/modals/bulk-delete-confirm.component.spec.ts
- webapp/tests/karma/ts/modals/delete-doc-confirm/delete-doc-confirm.component.spec.ts
- webapp/tests/karma/ts/modals/edit-message-group.component.spec.ts
- webapp/tests/karma/ts/modals/edit-report.component.spec.ts
- webapp/tests/karma/ts/modals/edit-user/edit-user-settings.component.spec.ts
- webapp/tests/karma/ts/modals/navigation-confirm.component.spec.ts
- webapp/tests/karma/ts/modals/send-message/send-message.component.spec.ts
- webapp/tests/karma/ts/modals/training-cards/training-cards.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-content.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-more-menu.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts.component.spec.ts
- webapp/tests/karma/ts/modules/messages/messages-content.component.spec.ts
- webapp/tests/karma/ts/modules/messages/messages-more-menu.component.spec.ts
- webapp/tests/karma/ts/modules/messages/messages.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports-content.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports-more-menu.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports-sidebar-filter.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports.component.spec.ts
- webapp/tests/karma/ts/modules/testing/testing.component.spec.ts
[description]
medic/cht-core#8554
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8554-fix-angular-test-logging/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8554-fix-angular-test-logging/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8554-fix-angular-test-logging/docker-compose/cht-couchdb-clustered.yml)
> chore(#8554): reduce spurious angular test logging

- tests/e2e/default/enketo/edit-report-with-attachment.wdio-spec.js
- tests/e2e/default/enketo/training-cards.wdio-spec.js
- tests/e2e/default/reports/reports-subject.wdio-spec.js
- tests/e2e/default/users/add-user.wdio-spec.js
- tests/page-objects/default/reports/reports.wdio.page.js
- tests/page-objects/default/users/user.wdio.page.js
Fix some flaky tests
- add-user test.wdio-spec.js
- training-cards.wdio-spec.js
- edit-report-with-attachment.wdio-spec.js
- reports-subject.wdio-spec.js
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-flaky-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-flaky-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-flaky-tests/docker-compose/cht-couchdb-clustered.yml)
> chore: Fix flaky tests

- api/package-lock.json
- tests/e2e/default/analytics/analytics.wdio-spec.js
- tests/e2e/default/enketo/death-report.wdio-spec.js
- tests/e2e/default/enketo/pregnancy-complete-a-delivery.wdio-spec.js
- tests/e2e/default/enketo/pregnancy.wdio-spec.js
- tests/e2e/default/enketo/undo-death-report.wdio-spec.js
- tests/e2e/standard/enketo/delivery.wdio-spec.js
- tests/e2e/standard/enketo/immunization-visit.wdio-spec.js
- tests/e2e/standard/enketo/pregnancy.wdio-spec.js
- tests/page-objects/default/analytics/analytics.wdio.page.js
- webapp/src/css/targets.less
- webapp/src/css/variables.less
- webapp/src/ts/modules/analytics/analytics-targets.component.html
- Update CHT "[Targets](https://docs.communityhealthtoolkit.org/apps/features/targets/)" to align with Material guidelines according to [Figma link with all the instances](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/UX-Stages?type=design&node-id=2701%3A3724&mode=design&t=emFrsbkEjCbZdWTn-1)
- A [Loom Video](https://www.loom.com/share/44efc6ed3f964d45b71d9f0ceca64b50?sid=79915612-6545-460d-bfcf-72d30d9055e6) demo-ing the change 
- Each "card" is separated into two content areas
- The content areas is shaded differently to delineate them
- The labels and images which used to be on the top, are now at the lower content area
- Instead of using red for unmet targets, the cards now use black
#8513 
- …
> feat(#8513): update target component

- tests/e2e/default/db/feedback-docs.wdio-spec.js
medic/cht-core#8671
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8671-fix-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8671-fix-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8671-fix-test/docker-compose/cht-couchdb-clustered.yml)
> chore(8671): Stabilize feedback docs e2e test.

- package-lock.json
- package.json
medic/cht-core#8679
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8679_bump_version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8679_bump_version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8679_bump_version/docker-compose/cht-couchdb-clustered.yml)
> chore(#8679): bump version to 4.5.0

- .github/PULL_REQUEST_TEMPLATE.md
By wrapping these fields in HTML comments they won't be shown in the final PR.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-patch-2/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-patch-2/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-patch-2/docker-compose/cht-couchdb-clustered.yml)
> chore: comment out description and issue number sections

- .github/workflows/build.yml
- api/tests/mocha/services/branding.spec.js
- tests/e2e/default-mobile/reports/search.wdio-spec.js
- tests/e2e/default-mobile/wdio.conf.js
- tests/e2e/default/about/about.wdio-spec.js
- tests/e2e/default/contacts/person-under-area.wdio-spec.js
- tests/e2e/default/contacts/search-contacts.wdio-spec.js
- tests/e2e/default/login/renew-token.wdio-spec.js
- tests/e2e/default/more-options-menu/offline-user/all-permissions.wdio-spec.js
- tests/e2e/default/more-options-menu/offline-user/delete-permission-disabled.wdio-spec.js
- tests/e2e/default/more-options-menu/offline-user/edit-permission-disabled.wdio-spec.js
- tests/e2e/default/more-options-menu/online-user/permissions-disabled.wdio-spec.js
- tests/e2e/default/more-options-menu/online-user/permissions-enabled.wdio-spec.js
- tests/e2e/default/navigation/bfcache.wdio-spec.js
- tests/e2e/default/navigation/hamburger-menu.wdio-spec.js
- tests/e2e/default/navigation/navigation.wdio-spec.js
- tests/e2e/default/reports/search-reports.wdio-spec.js
- tests/e2e/standard/sms/registration-by-sms.wdio-spec.js
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/wdio.conf.js
- tests/integration/sentinel/transitions/sentinel-transition-error-log.spec.js
- tests/page-objects/default/about/about.wdio.page.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/utils/index.js
- webapp/src/ts/modules/about/about.component.html
- webapp/tests/karma/ts/services/add-read-status.service.spec.ts
- webapp/tests/karma/ts/services/fast-action-button.service.spec.ts
medic/cht-core #8692 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8692-flaky-navigation-hamburguer-menu-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8692-flaky-navigation-hamburguer-menu-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8692-flaky-navigation-hamburguer-menu-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8692) flaky navigation hamburguer menu test

- tests/page-objects/default/about/about.wdio.page.js
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.5.x-fix-failing-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.5.x-fix-failing-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.5.x-fix-failing-tests/docker-compose/cht-couchdb-clustered.yml)
> fix: revert backport change which doesn't apply to this branch

- package-lock.json
- package.json
https://github.com/medic/cht-core/issues/8714
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fr-version-bump/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fr-version-bump/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fr-version-bump/docker-compose/cht-couchdb-clustered.yml)
> chore(#8714) - bump up version for FR barcode

- api/package-lock.json
- api/package.json
- api/src/auth.js
- api/src/controllers/login.js
- api/src/middleware/rate-limiter.js
- api/src/public/login/script.js
- api/src/routing.js
- api/src/server-utils.js
- api/src/services/rate-limit.js
- api/tests/mocha/controllers/login.spec.js
- api/tests/mocha/middleware/rate-limiter.spec.js
- api/tests/mocha/services/rate-limit.spec.js
- package-lock.json
- shared-libs/validation/package.json
- tests/e2e/default/login/login-logout.wdio-spec.js
- tests/e2e/default/navigation/bfcache.wdio-spec.js
- tests/e2e/default/suites.js
- tests/e2e/default/translations/enabled-languages.wdio-spec.js
- tests/integration/api/rate-limit.spec.js
- tests/integration/api/routing.spec.js
[description]
medic/cht-core#6530
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:6530-rate-limiting/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:6530-rate-limiting/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:6530-rate-limiting/docker-compose/cht-couchdb-clustered.yml)
> feat(#6530): add rate limiting for authentication requests

- scripts/build/push-ddoc-to-staging.js
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-double-publish/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-double-publish/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-double-publish/docker-compose/cht-couchdb-clustered.yml)
> chore: retry publish on conflict

- package-lock.json
- package.json
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-to-4.5.1/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-to-4.5.1/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-to-4.5.1/docker-compose/cht-couchdb-clustered.yml)
> chore(#8751): bump version to 4.5.2

- couchdb/Dockerfile
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8743-couch-bump/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8743-couch-bump/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8743-couch-bump/docker-compose/cht-couchdb-clustered.yml)
> chore(#8743): bump couchdb to 3.3.3

- webapp/src/css/enketo/medic.less
The dash and asterisk characters were replaced with an `ul li` elements. 
The best I can do is style the `ul li` to look like bullet points:
https://github.com/medic/cht-core/issues/8002
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8002-bullets-enketo/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8002-bullets-enketo/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8002-bullets-enketo/docker-compose/cht-couchdb-clustered.yml)
> fix(#8002): fixing bullet points in Enketo forms

- webapp/src/ts/modules/reports/reports-add.component.ts
- webapp/src/ts/services/telemetry.service.ts
- webapp/tests/karma/ts/modules/reports/reports-add.component.spec.ts
- webapp/tests/karma/ts/services/telemetry.service.spec.ts
#8778 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8778-skip-over-invalid-telemetry-values/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8778-skip-over-invalid-telemetry-values/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8778-skip-over-invalid-telemetry-values/docker-compose/cht-couchdb-clustered.yml)
> fix(#8778): skip over invalid telemetry values

- webapp/src/ts/actions/services.ts
- webapp/src/ts/directives/auth.directive.ts
- webapp/src/ts/effects/reports.effects.ts
- webapp/src/ts/modules/analytics/analytics.component.ts
- webapp/src/ts/modules/contacts/contact-route.guard.provider.ts
- webapp/src/ts/modules/contacts/contacts.component.ts
- webapp/src/ts/modules/home/home.component.ts
- webapp/src/ts/modules/messages/messages.component.ts
- webapp/src/ts/modules/reports/report-route.guard.provider.ts
- webapp/src/ts/modules/reports/reports.component.ts
- webapp/src/ts/modules/tasks/tasks.component.ts
- webapp/src/ts/services/indexed-db.service.ts
Removes unused variables and imports
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:unused-code/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:unused-code/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:unused-code/docker-compose/cht-couchdb-clustered.yml)
> chore: removes unused imports and variables

- shared-libs/bulk-docs-utils/package.json
- shared-libs/calendar-interval/package.json
- shared-libs/cht-script-api/package.json
- shared-libs/contact-types-utils/package.json
- shared-libs/contacts/package.json
- shared-libs/infodoc/package.json
- shared-libs/lineage/package.json
- shared-libs/message-utils/package.json
- shared-libs/nyc.config.js
- shared-libs/outbound/package.json
- shared-libs/phone-number/package.json
- shared-libs/purging-utils/package.json
- shared-libs/registration-utils/package.json
- shared-libs/rules-engine/package.json
- shared-libs/search/package.json
- shared-libs/server-checks/package.json
- shared-libs/settings/package.json
- shared-libs/task-utils/package.json
- shared-libs/tombstone-utils/package.json
- shared-libs/transitions/package.json
- shared-libs/translation-utils/package.json
- shared-libs/user-management/package.json
- shared-libs/validation/package.json
- shared-libs/view-map-utils/package.json
#5936 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:5936-shared-lib-coverage/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:5936-shared-lib-coverage/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:5936-shared-lib-coverage/docker-compose/cht-couchdb-clustered.yml)
> chore(#5936): adds coverage to all shared libs tests

- tests/e2e/default/db/ongoing-replication.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/common/modal.wdio.page.js
- tests/utils/index.js
#8819 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8819-fix-cookie-parsing/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8819-fix-cookie-parsing/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8819-fix-cookie-parsing/docker-compose/cht-couchdb-clustered.yml)
> fix(#8819): fix cookie decoding in e2e tests

- shared-libs/search/src/generate-search-requests.js
- shared-libs/search/test/generate-search-requests.js
#7288 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7288-short-keywords-miss-results/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7288-short-keywords-miss-results/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7288-short-keywords-miss-results/docker-compose/cht-couchdb-clustered.yml)
> fix(#7288): ignore short search words

- tests/e2e/default/contacts/add-new-district.wdio-spec.js
- tests/e2e/default/contacts/edit-person-home-place.wdio-spec.js
- tests/page-objects/default/contacts/contacts.wdio.page.js
- webapp/src/ts/modules/contacts/contacts.component.ts
- webapp/tests/karma/ts/modules/contacts/contacts.component.spec.ts
Fix bug to allow `userHomePlace` to update on sync. 
Closes #7110 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7110-update-user-home-place/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7110-update-user-home-place/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7110-update-user-home-place/docker-compose/cht-couchdb-clustered.yml)
> fix(#7110): update homeplace in LHS contacts list

- .gitignore
- scripts/bulk-password-update-export.js
This PR adds a script which allows CHT admins to populate a file with users in it `user-password-change.txt` and then call that script to change each users password to a random value.  Good for when you need to force reset users passwords after a breach or a failure in bulk upload.
This assumes they exist in the DB already, test steps:
1. check out this branch: `git checkout mrjones-reset-list-users-pass`
1. create a file `./cht-core/scripts/user-password-change.txt` - one user per line
1. `cd` into `scripts` dir and run the script `node bulk-password-update-export.js --url https://URL --user USR --password PASS`:  
```
➜  scripts git:(mrjones-reset-list-users-pass) cat user-password-change.txt 
123456
test
test2
➜  scripts git:(mrjones-reset-list-users-pass) node …
```
> feat(na): script to bulk change list of users passwords

- webapp/src/ts/services/telemetry.service.ts
- webapp/tests/karma/ts/services/telemetry.service.spec.ts
> fix(#8837): cherry pick - fix NaN in telemetry doc id (#8839)

- package-lock.json
- package.json
> chore(#8848): patch version

- tests/integration/api/routing.spec.js
#8855
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8790-fix-version-for-betas/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8790-fix-version-for-betas/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8790-fix-version-for-betas/docker-compose/cht-couchdb-clustered.yml)
> fix(#8855): fix deploy-info integration test for TAGs

- tests/integration/api/routing.spec.js
#8855
(cherry picked from commit 41d28031e0e2e77b51997964b7109a2544a19fb7)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8855-for-4.6.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8855-for-4.6.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8855-for-4.6.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#8855): fix deploy-info integration test for TAGs (#8856)

- scripts/deploy/helm/cht-chart/values.yaml
- adds a comment about special chars in password and subdomain valid chars.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:comments-to-values-yml/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:comments-to-values-yml/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:comments-to-values-yml/docker-compose/cht-couchdb-clustered.yml)
> chore: more documentation in values.yml

- .github/actions/update-staging-url-placeholders/action.yml
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-staging-url-action-node-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-staging-url-action-node-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-staging-url-action-node-version/docker-compose/cht-couchdb-clustered.yml)
> chore: update staging url action to node 20

- .github/workflows/build.yml
#8902
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8902-fix-external-contributions/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8902-fix-external-contributions/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8902-fix-external-contributions/docker-compose/cht-couchdb-clustered.yml)
> fix(#8902): external contributors can't access docker images

- .github/workflows/build.yml
#8902
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8902-do-not-delete-artifacts/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8902-do-not-delete-artifacts/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8902-do-not-delete-artifacts/docker-compose/cht-couchdb-clustered.yml)
> chore(#8902): do not delete docker image artifact

- scripts/ci/tag-docker-images.js
> #8841 commit as external contributor

- .github/workflows/build.yml
- scripts/ci/tag-docker-images.js
> #8841 external builder

- webapp/src/css/targets.less
- webapp/src/css/variables.less
Updates the Targets page to align the `target` card to the columns
<details>
<summary>Layout with one card in last row</summary>
</details>
<details>
<summary>Layout with two cards in last row</summary>
</details>
<details>
<summary>Layout with three cards in last row</summary>
</details>
<details>
<summary>Mobile view</summary>
</details>
<details>
<summary>Tablet view</summary>
</details>
<details>
<summary>Firefox</summary>
</details>
Closes #5807 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:5807-align-target-cards/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:5807-align-target-cards/docker-compose/cht-couchdb.yml)
* [CouchDB …
> fix(#5807): align target cards to column

- .gitattributes
Addresses issue: https://github.com/medic/cht-core/issues/8990
> chore(#8990): adds .gitattributes file

- .github/dependabot.yml
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dependabot-for-subdirs/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dependabot-for-subdirs/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dependabot-for-subdirs/docker-compose/cht-couchdb-clustered.yml)
> chore: configure dependabot for more dependencies

- .github/workflows/build.yml
- tests/utils/index.js
#9035
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9035-fix-artifact-names/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9035-fix-artifact-names/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9035-fix-artifact-names/docker-compose/cht-couchdb-clustered.yml)
> fix(#9035): Use correct job names when uploading artifacts and allure history   

- tests/e2e/default/db/initial-replication.wdio-spec.js
- tests/e2e/default/db/ongoing-replication.wdio-spec.js
- tests/utils/index.js
#8802
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8802-stabiize-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8802-stabiize-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8802-stabiize-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8802): stabilize ongoing replication test

- package-lock.json
- package.json
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9066-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9066-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9066-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9066): bump version to 4.7.0

- shared-libs/server-checks/package.json
- shared-libs/server-checks/src/checks.js
- shared-libs/server-checks/src/index.js
- shared-libs/server-checks/test/checks.js
- shared-libs/server-checks/test/index.js
#9069
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9069-mute-server-checks-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9069-mute-server-checks-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9069-mute-server-checks-tests/docker-compose/cht-couchdb-clustered.yml)
> chore(#9069): mute server checks tests

- tests/performance/apdex-score/README.md
- tests/performance/apdex-score/settings-provider.js
- tests/performance/apdex-score/test/pageobjects/login.page.js
- tests/performance/apdex-score/test/specs/num-1/test.apdex.js
- tests/performance/apdex-score/wdio.conf.js
Adds settings provider to run tests based on a settings file. 
1. Create a settings file: 
```
{
"instanceURL": "https://<add-the-rest>",
"appium": {
"platformVersion": "<add-android-version>",
"deviceName": "<add-device-name>"
},
"users": [
{
"type": "offline",
"role": "chw",
"username": "<add-username>",
"password": "<add-password>"
}
]
}
```
2. Set the environment variable  `APDEX_TEST_SETTINGS` with the path of your settings file. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:apdex-script-fill-forms/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:apdex-script-fill-forms/docker-compose/cht-couchdb.yml)
* [CouchDB …
> chore: adds settings file to apdex tests

- .gitignore
Ignore test values.yml from k3d e2e per 
#9805
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9085-ignore-test-values-yaml/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9085-ignore-test-values-yaml/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9085-ignore-test-values-yaml/docker-compose/cht-couchdb-clustered.yml)
> fix(#9805): Ignore test values.yml from k3d e2e per 

- tests/utils/index.js
#9079 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9079-random-ip/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9079-random-ip/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9079-random-ip/docker-compose/cht-couchdb-clustered.yml)
> chore(#9079): use random IP for non-auth requests.

- .github/workflows/conventional-commits.yml
- commitlint.config.js
- package-lock.json
- package.json
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:lint-pr-titles/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:lint-pr-titles/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:lint-pr-titles/docker-compose/cht-couchdb-clustered.yml)
> chore: validate pr titles using commitlint format

- api/src/services/setup/databases.js
- api/tests/mocha/services/setup/databases.spec.js
- package-lock.json
- package.json
#9124 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9124-bump-and-cherry-pick/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9124-bump-and-cherry-pick/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9124-bump-and-cherry-pick/docker-compose/cht-couchdb-clustered.yml)
> chore(#9124): bump version and cherry pick upgrade fix

- package-lock.json
- package.json
patch version to `4.8.0` as part of release process.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore: patch release version

- tests/e2e/upgrade/upgrade.wdio-spec.js
#9134 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9134-fix-beta-upgrade/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9134-fix-beta-upgrade/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9134-fix-beta-upgrade/docker-compose/cht-couchdb-clustered.yml)
> fix(#9134): fix upgrade e2e for tags

- .github/ISSUE_TEMPLATE/z_release_major.md
Updated the forum post template when releasing.
> fix(na): update z_release_major.md forum post template

- .github/workflows/build.yml
limit each build CI job to 60 min
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-couchdb-clustered.yml)
> chore(na): limit each build CI job to 60 min

- tests/factories/cht/reports/pregnancy.js
Update lmp calculation for pregnancy card to always get the same value for "Weeks pregnant"
Closes #9155 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9155-stabilise-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9155-stabilise-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9155-stabilise-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#9155): update lmp calculation

- scripts/release-notes/index.js
#9153
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9153-thank-contributors/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9153-thank-contributors/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9153-thank-contributors/docker-compose/cht-couchdb-clustered.yml)
> chore(#9153): acknowledge contributors in release notes

- .github/workflows/conventional-commits.yml
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dont-trust-input/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dont-trust-input/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:dont-trust-input/docker-compose/cht-couchdb-clustered.yml)
As per: https://securitylab.github.com/research/github-actions-untrusted-input/
> chore: protect against command injection

- package-lock.json
- package.json
#9216
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version-4-10/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version-4-10/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version-4-10/docker-compose/cht-couchdb-clustered.yml)
> chore(#9216): updates cht version

- tests/e2e/default/contacts/contact-details.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/contacts/contacts.wdio.page.js
- webapp/src/ts/modules/contacts/contacts-content.component.ts
- Fixes the filter condition 
- Adds e2e coverage
#9212
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-view-all-in-contact-details/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-view-all-in-contact-details/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-view-all-in-contact-details/docker-compose/cht-couchdb-clustered.yml)
> fix(#9212): fix view all filter in contact details

- webapp/src/ts/components/filters/analytics-filter/analytics-filter.component.ts
- webapp/src/ts/modules/analytics/analytics-target-aggregates-detail.component.ts
- webapp/src/ts/modules/analytics/analytics-target-aggregates-sidebar-filter.component.html
- webapp/src/ts/modules/analytics/analytics-target-aggregates-sidebar-filter.component.ts
- webapp/src/ts/modules/analytics/analytics-target-aggregates.component.html
- webapp/src/ts/modules/analytics/analytics-target-aggregates.component.ts
- webapp/src/ts/services/target-aggregates.service.ts
- webapp/src/ts/services/user-settings.service.ts
- webapp/tests/karma/ts/components/filters/analytics-filter.component.spec.ts
- webapp/tests/karma/ts/modules/analytics/analytics-target-aggregates-detail.component.spec.ts
- webapp/tests/karma/ts/modules/analytics/analytics-target-aggregates-sidebar-filter-component.spec.ts
- webapp/tests/karma/ts/modules/analytics/analytics-target-aggregates.component.spec.ts
- webapp/tests/karma/ts/services/target-aggregates.service.spec.ts
After the completion of https://github.com/medic/cht-core/pull/9232 which adds a sidebar filter for users with multiple facilities, this PR accomplishes the actual filtering of the Aggregate Targets through the selection of the facilities in the radio buttons. 
<details>
<summary>Video showing the filtering</summary>
https://github.com/user-attachments/assets/30e06dc4-d52d-4a58-9ff5-2baf3e241359
</details>
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:filter-aggregate-data/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:filter-aggregate-data/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fil …
> chore(#9231): filter target aggregate data using sidebar filter

- tests/page-objects/default/targets/target-aggregates.wdio.page.js
- webapp/src/css/inbox.less
- webapp/src/css/sidebar-filter.less
- webapp/src/css/targets.less
- webapp/src/css/variables.less
- webapp/src/ts/components/filters/analytics-filter/analytics-filter.component.ts
- webapp/src/ts/modules/analytics/analytics-target-aggregates-detail.component.html
- webapp/src/ts/modules/analytics/analytics-target-aggregates-sidebar-filter.component.html
- webapp/src/ts/modules/analytics/analytics-target-aggregates-sidebar-filter.component.ts
- webapp/src/ts/modules/analytics/analytics-target-aggregates.component.html
- webapp/src/ts/modules/analytics/analytics-target-aggregates.component.ts
- webapp/src/ts/services/rules-engine.service.ts
- webapp/src/ts/services/target-aggregates.service.ts
- webapp/src/ts/services/user-settings.service.ts
- webapp/tests/karma/ts/components/filters/analytics-filter.component.spec.ts
- webapp/tests/karma/ts/modules/analytics/analytics-target-aggregates-sidebar-filter-component.spec.ts
- webapp/tests/karma/ts/modules/analytics/analytics-target-aggregates.component.spec.ts
- webapp/tests/karma/ts/services/user-settings.service.spec.ts
Fixes colors in report's sidebar filter - it should look like in 4.9 branch 
Adds indicator of selected facility in aggregate targets list and details.
<details><summary>Screenshots Aggregate Target</summary>
</details>
<details><summary>Screenshot - Report filter with colors</summary>
</details>
#9231
https://github.com/medic/care-teams/issues/144
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:add-facility-name-in-aggregates-targes/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:add-facility-name-in-aggregates-targes/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:add-facility-name-in-aggrega …
> feat(#9231): add facility indicator in aggregates targets

- tests/e2e/upgrade/wdio.conf.js
- tests/integration/couchdb/couch_chttpd.spec.js
- tests/integration/haproxy/keep-alive.spec.js
- tests/scalability/README.md
- tests/scalability/prepare-ec2.sh
- tests/utils/index.js
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8781-update-docker-space-compose/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8781-update-docker-space-compose/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8781-update-docker-space-compose/docker-compose/cht-couchdb-clustered.yml)
> fix(#8781): upgrade to docker compose v2

- package-lock.json
- package.json
- webapp/angular.json
- webapp/package-lock.json
- webapp/package.json
This PR moves all angular dependencies to webapp - it's the only directory that uses angular currently so it makes sense to put everything in there.
Closes #9302 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9302-update-dependencies/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9302-update-dependencies/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9302-update-dependencies/docker-compose/cht-couchdb-clustered.yml)
> chore(#9302): consolidate angular dependencies in webapp

- api/Dockerfile
- sentinel/Dockerfile
Fix path in API and sentinel's Dockerfile i.e. `cht-core/api/Dockerfile` and `cht-core/sentinel/Dockerfile` when copying `cht-core/shared-libs` for integration and e2e tests.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:sugat__check_ci/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:sugat__check_ci/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:sugat__check_ci/docker-compose/cht-couchdb-clustered.yml)
> fix: fix shared-lib path in API and sentinel's Dockerfile

- .github/workflows/build.yml
#9328
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9328-skip-publish-docs-on-dev-branch/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9328-skip-publish-docs-on-dev-branch/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9328-skip-publish-docs-on-dev-branch/docker-compose/cht-couchdb-clustered.yml)
> chore(#9328): only publish docs from main branch

- .github/ISSUE_TEMPLATE/z_release_major.md
Updated the major/minor release issue template.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_major_release_issue_template/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_major_release_issue_template/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update_major_release_issue_template/docker-compose/cht-couchdb-clustered.yml)
> chore: update major/minor release issue template

- tests/e2e/default-mobile/reports/send-message.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
Refactor send message for reports test due to @tatilepizs 's [recommendation](https://github.com/medic/cht-core/pull/9353)
https://github.com/medic/cht-core/issues/8181
https://github.com/medic/care-teams/issues/148
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:e2e-send-message-refactor/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:e2e-send-message-refactor/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:e2e-send-message-refactor/docker-compose/cht-couchdb-clustered.yml)
> chore(#8181): refactor send message test for reports

- webapp/src/css/dropdown.less
- webapp/src/css/inbox.less
- webapp/src/css/sidebar-filter.less
- webapp/src/css/variables.less
- webapp/src/ts/components/filters/analytics-filter/analytics-filter.component.html
To simplify the support of the old navigation while having the new navigation, we need to extend the content to full-screen width.
Testing:
https://github.com/user-attachments/assets/6e633757-a5cb-43bf-b77b-90430971cba2
#9327
https://github.com/medic/care-teams/issues/156
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:extend-content-full-width/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:extend-content-full-width/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:extend-content-full-width/docker-compose/cht-couchdb-clustered.yml) …
> feat(#9327): extend content to full width

- package-lock.json
- package.json
#9333 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version-4-11/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version-4-11/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-version-4-11/docker-compose/cht-couchdb-clustered.yml)
> chore(#9333): update CHT version to 4.11.0

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
Update release templates [per Slack conversation](https://medic.slack.com/archives/C024KTGRW/p1724251528644929?thread_ts=1724149673.338049&cid=C024KTGRW), stating that `@core_devs` group should be dropped and `#development `Slack channel is preferred for release-related discussions. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-release-templates/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-release-templates/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-release-templates/docker-compose/cht-couchdb-clustered.yml)
The software is provided under AGPL-3.0. Contributions …
> chore: update targeted Slack channels in the release templates

- .github/workflows/codeql.yml
The ddocs directory is causing codeql scanning to throw warnings because it can't parse the views. Replace the default config with custom config which ignores the ddocs directory.
```
2024-09-02T12:11:01.3439150Z CodeQL scanned 1161 out of 1161 JavaScript files and 489 out of 489 TypeScript files in this invocation. Check the status page for overall coverage information: https://github.com/medic/cht-core/security/code-scanning/tools/CodeQL/status/
2024-09-02T12:11:01.3441503Z Analysis produced the following diagnostic information:
2024-09-02T12:11:01.3442948Z ##[group]Could not process some files due to syntax errors (49 results)
2024-09-02T12:11:01.3446744Z   * ddocs/logs-db/logs/views/connected_users/map.js#L1C9:9: A parse error occurred: `Missing function name`. Check the syntax of the …
```
> chore: add codeql config to ignore ddocs

- config/default/app_settings.json
- config/demo/app_settings.json
- tests/e2e/default/login/login-logout.wdio-spec.js
- tests/integration/sentinel/schedules/outbound.spec.js
#9406
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9406-disable-unsupported-language/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9406-disable-unsupported-language/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9406-disable-unsupported-language/docker-compose/cht-couchdb-clustered.yml)
> fix(#9406): disable unsupported languages

- tests/e2e/default/enketo/config/contact-summary-reports.js
- tests/e2e/default/enketo/contact-summary-reports.wdio-spec.js
- tests/e2e/default/enketo/forms/contact-summary-reports.xml
- tests/page-objects/default/enketo/common-enketo.wdio.page.js
- webapp/src/ts/services/contact-view-model-generator.service.ts
- webapp/src/ts/services/form.service.ts
- webapp/tests/karma/ts/services/form.service.spec.ts
#9429
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9429-all-reports-in-contact-summary/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9429-all-reports-in-contact-summary/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9429-all-reports-in-contact-summary/docker-compose/cht-couchdb-clustered.yml)
> fix(#9429): pass 500 reports to forms contact summary

- tests/e2e/default/enketo/config/contact-summary-reports.js
- tests/e2e/default/enketo/contact-summary-reports.wdio-spec.js
- tests/e2e/default/enketo/forms/contact-summary-reports.xml
- tests/page-objects/default/enketo/common-enketo.wdio.page.js
- webapp/src/ts/services/contact-view-model-generator.service.ts
- webapp/src/ts/services/form.service.ts
- webapp/tests/karma/ts/services/form.service.spec.ts
#9429
(cherry picked from commit a2fe0b43d4161d80c93d7fd8980d56afcaea01b6)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.11.x-500-reports-to-contact-summary/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.11.x-500-reports-to-contact-summary/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.11.x-500-reports-to-contact-summary/docker-compose/cht-couchdb-clustered.yml)
> fix(#9429): pass 500 reports to forms contact summary (#9434)

- .mocharc.js
- api/src/services/monitoring.js
- api/tests/mocha/services/monitoring.spec.js
- tests/integration/api/controllers/monitoring.spec.js
Closes https://github.com/medic/cht-core/issues/9428
Docs PR: https://github.com/medic/cht-docs/pull/1545
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9428_db_monitoring_data/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9428_db_monitoring_data/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9428_db_monitoring_data/docker-compose/cht-couchdb-clustered.yml)
> feat(#9428): add size and view_index metrics to monitoring api

- webapp/src/css/inbox.less
- webapp/src/css/material.less
- webapp/src/css/targets.less
- webapp/src/css/variables.less
- webapp/src/ts/components/snackbar/snackbar.component.html
- webapp/src/ts/components/snackbar/snackbar.component.ts
Testing: 
<details><summary> FAB + snackbar </summary> 
</details>
<details><summary> Snackbar only </summary>
</details>
<details><summary> Tabs + snackbar </summary>
</details>
<details><summary> Tabs + FAB + snackbar </summary>
</details>
<details><summary> Desktop </summary>
</details>
#9327
https://github.com/medic/care-teams/issues/181
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9327-snackbar-positioning/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9327-snackbar-positioning/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9327-snackbar-positioning/docker-compose/cht-couchdb-clustere …
> fix(#9327): snackbar positioning based on FAB display

- webapp/src/css/inbox.less
Resolves Nicole feedback about tab nav alignment: Even space between 
#9327
> fix(#9327): tab nav alignment

- scripts/build/cht-core.yml.template
- scripts/build/cht-couchdb-cluster.yml.template
- scripts/build/cht-couchdb-single-node.yml.template
remove version strings from compose files per #9476
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:remove-compose-version-string-9476/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:remove-compose-version-string-9476/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:remove-compose-version-string-9476/docker-compose/cht-couchdb-clustered.yml)
> chore(#9476): remove version strings from compose files

- package-lock.json
- package.json
Bump CHT version to 4.12 
#9475 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9475-update-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9475-update-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9475-update-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9475): update CHT version to 4.12.0

- funding.json
> chore: adds a funding.json doc to make our funding machine readable

- webapp/src/ts/services/rules-engine.service.ts
- webapp/tests/karma/ts/services/rules-engine.service.spec.ts
- changes background refresh telemetry entry name to be more intuitive
- changes changes refresh telemetry entry name to be more intuitive
- adds dirty-contacts entry when refreshing due to changes monitoring
#9551
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9551-update-rules-engine-telemetry/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9551-update-rules-engine-telemetry/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9551-update-rules-engine-telemetry/docker-compose/cht-couchdb-clustered.yml)
The software is provided under AGPL-3.0. Contributions to this project are accepted under the …
> chore(#9551): updates to rules-engine telemetry

- scripts/docker-helper/cht-docker-compose.sh
This PR:
* updates all `docker-compose` calls to be `docker compose` so the older  helper 3.x now uses compose v2
* light refactoring of installed apps checking to add new `docker_not_installed()` function which [we already use](https://github.com/medic/cht-core/blob/46a01b954f0ff6b5c17dcbb053f8c41c25938887/scripts/docker-helper-4.x/cht-docker-compose.sh#L158) in helper 4.x
closes #8781
Given how old CHT Core 3.x, I think it's reasonable to ensure just happy path works with this PR: Can you create a CHT 3.x instance using 3.x helper by following [the docs](https://docs.communityhealthtoolkit.org/hosting/3.x/app-developer/).
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8781-helper3x-new-compose/docker-compose/cht-core.yml …
> fix(#8781):  docker helper 3.x to use compose v2

- tests/e2e/default/telemetry/telemetry.wdio-spec.js
- webapp/src/ts/services/telemetry.service.ts
#9622
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9622-fix-flaky-telemetry-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9622-fix-flaky-telemetry-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9622-fix-flaky-telemetry-test/docker-compose/cht-couchdb-clustered.yml)
> test(#9622): fix flaky search telemetry test

- .github/workflows/build.yml
- api/Dockerfile
- api/package.json
- api/tests/mocha/services/async-storage.spec.js
- package.json
- scripts/deploy/package-lock.json
- scripts/deploy/package.json
- sentinel/Dockerfile
- sentinel/package-lock.json
- sentinel/package.json
- tests/integration/haproxy/keep-alive-script/Dockerfile
#9636 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9636-node-22/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9636-node-22/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9636-node-22/docker-compose/cht-couchdb-clustered.yml)
> chore(#9636): update to node 22

- package-lock.json
- package.json
https://github.com/medic/cht-core/issues/9648
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-up-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-up-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:bump-up-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9648): update version to 4.15

- README.md
#nottoosoon
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-copyright/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-copyright/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-copyright/docker-compose/cht-couchdb-clustered.yml)
> chore: bump copyright year

- tests/integration/api/controllers/bulk-docs.spec.js
- tests/integration/api/controllers/replication.spec.js
- tests/integration/api/controllers/users.spec.js
#9695
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:integration-wdio-reference/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:integration-wdio-reference/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:integration-wdio-reference/docker-compose/cht-couchdb-clustered.yml)
> fix(#9695): fix integration tests interacting with browser elements

- tests/page-objects/default/login/login.wdio.page.js
WIP
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:test-fix-repeat-e2e-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:test-fix-repeat-e2e-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:test-fix-repeat-e2e-test/docker-compose/cht-couchdb-clustered.yml)
> chore: test, trying to fix repeat e2e test

- package-lock.json
- package.json
#9730
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9730-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9730-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9730-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9730): bump version

- package-lock.json
- package.json
#9730
(cherry picked from commit 651f54abeef23fbde02525c3d33b295132b1cdfb)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.16.x-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.16.x-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.16.x-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9730): bump version (#9744)

- .github/ISSUE_TEMPLATE/z_release_feature.md
- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
Update release templates. Remove `Product` mentions. Remove mentions of teams and roles that don't exist anymore. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-release-template/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-release-template/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-release-template/docker-compose/cht-couchdb-clustered.yml)
> chore: update release templates

- package-lock.json
- package.json
#9774
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.17.x-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.17.x-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.17.x-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9774): bump version

- tests/utils/index.js
#9787 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9787-fix-k3d-comd/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9787-fix-k3d-comd/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9787-fix-k3d-comd/docker-compose/cht-couchdb-clustered.yml)
> fix(#9787): correct docker get ip command

- funding.json
I realized I should not have merged https://github.com/medic/cht-core/pull/9864 until [FLOSS](https://dir.floss.fund/browse/projects) updated the link to our `funding.json` (I sent an email this afternoon), sorry, as that might break their manifest parsing. 
Let's:
1. Put the file back, merge it
2. Get confirmation that FLOSS people have updated the `funding.json` location
3. Then delete this file
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:put-funding-back/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:put-funding-back/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:put-funding-back/docke …
> chore: put funding back

- funding.json
It looks like my [recent change](https://github.com/medic/cht-core/pull/9866) in the `funding.json` broke the [FLOSS](https://floss.fund/) parser. Changing the project's fields to the initial ones. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-funding/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-funding/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-funding/docker-compose/cht-couchdb-clustered.yml)
> chore: fix funding.json

- funding.json
- tests/e2e/default/translations/new-language.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/common/modal.wdio.page.js
- tests/page-objects/default/users/user-settings.wdio.page.js
#9859 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9859-fix-lang-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9859-fix-lang-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9859-fix-lang-test/docker-compose/cht-couchdb-clustered.yml)
> fix(#9859): stabilize add language test

- api/src/controllers/login.js
- api/tests/mocha/controllers/login.spec.js
- shared-libs/user-management/src/token-login.js
- shared-libs/user-management/test/unit/token-login.spec.js
- tests/integration/api/controllers/login.spec.js
Updated token_login flow to not allow login if oidc_provider value is set for user. Made consistent async/await changes in loginByToken function.
Closes #9764
> feat(#9764): update token_login flow to not allow oidc user

- shared-libs/cht-datasource/src/qualifier.ts
- shared-libs/cht-datasource/test/qualifier.spec.ts
This is a WIP version for adding the `ContactQualifer`.
> feat(#9835): add `ContactQualifier` functions

- shared-libs/cht-datasource/src/local/person.ts
- shared-libs/cht-datasource/src/qualifier.ts
- shared-libs/cht-datasource/test/local/person.spec.ts
- shared-libs/cht-datasource/test/qualifier.spec.ts
WIP Pull request to add support for creating Person Doc in Pouch.
Related: #10036.
> feat(#10036): implement `createPerson` for local

- api/tests/mocha/controllers/person.spec.js
- shared-libs/cht-datasource/src/local/person.ts
- shared-libs/cht-datasource/src/qualifier.ts
- shared-libs/cht-datasource/test/local/person.spec.ts
- shared-libs/cht-datasource/test/person.spec.ts
- shared-libs/cht-datasource/test/qualifier.spec.ts
- shared-libs/cht-datasource/test/remote/person.spec.ts
- tests/integration/api/controllers/person.spec.js
- tests/integration/shared-libs/cht-datasource/person.spec.js
Changes introduced as per discussion here:
https://github.com/medic/cht-core/pull/10043#discussion_r2140370176
> feat(#9835): remove lineage checks

- shared-libs/cht-datasource/src/local/place.ts
- shared-libs/cht-datasource/test/local/place.spec.ts
Adds checks for `parent` field in a place.
Related: #10038
> feat(#10038): check parent in input qualifier

- api/src/services/bulk-docs.js
- api/tests/mocha/services/bulk-docs.spec.js
- shared-libs/bulk-docs-utils/src/bulk-docs-utils.js
- shared-libs/bulk-docs-utils/test/bulk-docs-utils.js
- webapp/src/ts/services/delete-docs.service.ts
- webapp/tests/karma/ts/services/delete-docs.service.spec.ts
This pull request updates the `bulk-docs-utils.js` file to modernize the codebase by replacing the database access logic with a new data context approach. It introduces the use of the `@medic/cht-datasource` library for fetching related data and improves error handling.
fixes #10076 
> feat(#10076): update shared-libs/bulk-docs-utils to read contact from cht-datasource

- api/tests/mocha/controllers/person.spec.js
- api/tests/mocha/services/settings.spec.js
- shared-libs/cht-datasource/src/input.ts
- shared-libs/cht-datasource/src/local/libs/core.ts
- shared-libs/cht-datasource/src/local/person.ts
- shared-libs/cht-datasource/src/local/place.ts
- shared-libs/cht-datasource/src/local/report.ts
- shared-libs/cht-datasource/src/person.ts
- shared-libs/cht-datasource/src/place.ts
- shared-libs/cht-datasource/src/report.ts
- shared-libs/cht-datasource/test/index.spec.ts
- shared-libs/cht-datasource/test/input.spec.ts
- shared-libs/cht-datasource/test/libs/parameter-validators.spec.ts
- shared-libs/cht-datasource/test/local/person.spec.ts
- shared-libs/cht-datasource/test/local/place.spec.ts
- shared-libs/cht-datasource/test/report.spec.ts
- shared-libs/nyc.config.js
- tests/integration/shared-libs/cht-datasource/report.spec.js
Implementation of update person in local module
Related: #10037
> feat(#10037): implement update person local

- shared-libs/cht-datasource/src/local/libs/core.ts
- shared-libs/cht-datasource/src/local/person.ts
- shared-libs/cht-datasource/src/local/place.ts
- shared-libs/cht-datasource/test/local/person.spec.ts
- shared-libs/cht-datasource/test/local/place.spec.ts
Work in progress PR that adds local implementation for updating a place.
Related: #10039
> feat(#10039): add local support for update place

- api/src/controllers/place.js
- api/src/routing.js
- api/tests/mocha/controllers/place.spec.js
- shared-libs/cht-datasource/src/index.ts
- shared-libs/cht-datasource/src/local/libs/core.ts
- shared-libs/cht-datasource/src/local/place.ts
- shared-libs/cht-datasource/src/place.ts
- shared-libs/cht-datasource/src/remote/place.ts
- shared-libs/cht-datasource/test/index.spec.ts
- shared-libs/cht-datasource/test/local/place.spec.ts
- shared-libs/cht-datasource/test/place.spec.ts
- shared-libs/cht-datasource/test/remote/place.spec.ts
- tests/integration/api/controllers/place.spec.js
- tests/integration/shared-libs/cht-datasource/place.spec.js
> feat(#10039): add remote implementation for update place

- SECURITY.md
Update [SECURITY.md](https://github.com/medic/cht-core/blob/master/SECURITY.md) to have correct link to docs.  The link in there went to [a docs page](https://docs.communityhealthtoolkit.org/community/contributing/code/), but not the [correct page](https://docs.communityhealthtoolkit.org/community/contributing/disclosing-vulnerabilities/).
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-couchdb-clustered.yml)
The …
> chore(na): update security file with correct link to docs

- scripts/release-notes/index.js
Change the graphql query from `getCommitsForRelease` function to get the list of co-authors by commit instead of just the actual author of the commit, and update the `formatCommits` function to support the list of authors. Part of this change was using a Set instead of an array because the Set is more efficient when we need to check for duplicates.
Closes #10023 
> chore(#10023): update release-notes script to include co-authors

- sentinel/server.js
Improves sentinel logging by including detailed error information when API connections fail, replacing generic "Waiting for API to be ready..." messages with specific error details including connection information, IP addresses, and error codes.
- Modified `sentinel/server.js:25` to change from `logger.info()` to `logger.warn()` with error object
- Updated log message to include error details using winston %o formatting as requested by maintainers
**Before**: Generic unhelpful message
`Waiting for API to be ready...`
**After**: Detailed error information
`Waiting for API to be ready...: { code: 'ECONNREFUSED', address: '127.0.0.1', port: 5988, ... }`
Fixes [#8348 - Adding error object to logger in sentinel/server.js](https://github.com/medic/cht-core/issues/8348)
The software is provided …
> fix(#8348): include error details in sentinel API connection logging
