medic/cht-core

- ddocs/medic-client/views/tasks_by_contact/map.js
- shared-libs/rules-engine/test/pouchdb-provider.spec.js
Tasks emissions from configs that use `contactLabel` end up with an undefined `owner` property. 
Changing the `tasks_by_contact` view to emit for "unassigned" tasks ensures that ownerless tasks are displayed in the tasks list. 
medic/cht-core#6274
The software is provided under AGPL-3.0. Contributions to …
> Display tasks without owner in tasks list

- Gruntfile.js
- api/src/auth.js
- api/src/controllers/login.js
- api/src/services/users.js
- api/tests/mocha/controllers/login.spec.js
- api/tests/mocha/services/users.spec.js
- tests/conf.js
Catches 404s from getting `user-settings` docs and creates `user` and `user-settings` docs when logging in. 
medic/cht-core#6249
> Allow CouchDb Admins to login in the app. 

- Gruntfile.js
- package.json
doing this inside grunt doesn't work because of how our application is
architected. Specifically, places that look for UNIT_TEST_ENV only do so
once on initialisation, and grunt doesn't restart the VM between
actions.
Instead, if we run this from npm it just executes this like bash would,
with fresh vms between each run (which is way better regardless of this
issue)
#6317
> Creating a npm-level everything action

- webapp/src/js/actions/actionTypes.js
- webapp/src/js/actions/tasks.js
- webapp/src/js/controllers/tasks-content.js
- webapp/src/js/controllers/tasks.js
- webapp/src/js/reducers/tasks.js
- webapp/src/js/selectors/index.js
- webapp/tests/karma/unit/controllers/tasks-content.js
Fixes race condition when loading a task by saving the `refreshTasks` promise in the state and setting the selected task after tasks are refreshed.
medic/cht-core#6323
> Fixes race condition when loading a task

- webapp/src/js/services/enketo.js
- webapp/tests/karma/unit/services/enketo.js
Avoids a race condition causing images to never be rendered.
medic/cht-core#6321
> Load images after rendering HTML 

- .travis.yml
- tests/e2e/common/common.specs.js
New IAM user and policies created for travis-ci: medic/medic-infrastructure/pull/139
Fixes medic/cht-core#4877
Tested access keys and limited s3 bucket access:
```
root@02:/app# export AWS_ACCESS_KEY_ID=[secure]
root@02:/app# export AWS_SECRET_ACCESS_KEY=[secure]
root@02:/app# export S3_PATH=s3://medic-e2e/A-TEST001
root@02:/app# vi hello.txt
root@02:/app# aws s3 cp hello.txt "$S3_PATH"/hello.txt
upload: ./hello.txt to s3://medic-e2e/A-TEST001/hello.txt
root@02:/app# aws ec2 describe-volumes --region eu-west-2
An error occurred (UnauthorizedOperation) when calling the DescribeVolumes operation: You are not authorized to perform this operation.
```
We still need to ensure travis is decrypting the keys correctly (that I've formatted them appropriately in .travis.yml). 
- Readable: Concise, …
> travis-ci AWS Access Keys

- webapp/src/js/services/enketo.js
Adds a global `window.debugFormModel()` for developers to call via the developer console when debugging Enketo forms. Exposes the rendered Enketo form model as an xml string.
#4748
* Just wanting to close on naming and approach before I write a documentation PR
* Unsure if `debugFormModel` is a good name for this. Open to other suggestions.
* Opened https://github.com/medic/medic-conf-test-harness/issues/33 to also expose this data via the medic conf test harness
- Internationalised: …
> Expose Enketo model xml via window.debugFormModel()

- webapp/src/js/actions/global.js
- webapp/src/js/controllers/inbox.js
- webapp/src/js/directives/header.js
- webapp/src/js/services/modal.js
- webapp/src/js/services/snackbar.js
- webapp/src/js/services/update-service-worker.js
- webapp/tests/karma/unit/services/modal.js
Change modals so that they are always singletons, stopping multiple
update dialogs from popping over each other.
Additionally, snackbar if dev and always log out when an important file
changes, so developers can more easily see when ddocs and the service
worker changes, hopefully making it easier to know when to refresh.
medic/cht-core#6272
> Improvements to resource refresh notifications

- admin/src/css/theme.less
- admin/src/js/controllers/upgrade.js
- admin/src/templates/display_translations.html
- admin/src/templates/forms_xml.html
- admin/src/templates/index.html
- admin/src/templates/upgrade.html
> A range of styling improvements for the admin app

- api/src/controllers/login.js
- api/src/public/login/script.js
- api/src/templates/login/index.html
- api/tests/mocha/controllers/login.spec.js
If the 302 response is cached in the service worker the user is
sent to the app. If they don't have a current session then they're
sent back to the login page.
medic/cht-core#6337
> Don't cache login redirection

- shared-libs/rules-engine/src/index.js
- shared-libs/rules-engine/src/rules-state-store.js
- shared-libs/rules-engine/test/rules-state-store.spec.js
- webapp/src/js/controllers/analytics-targets.js
- webapp/src/js/controllers/tasks.js
- webapp/src/js/services/debounce.js
- webapp/src/js/services/rules-engine.js
- webapp/tests/karma/unit/controllers/analytics-targets.spec.js
- webapp/tests/karma/unit/controllers/tasks.js
- webapp/tests/karma/unit/services/debounce.js
- webapp/tests/karma/unit/services/rules-engine.js
Tracks the following events:
- How long it takes to load tasks tab
- How long it takes to load targets tab
- How many contacts are "dirty" when tasks/targets refresh
- How long it takes for the "freshness" thread to run
- After how much time is the "freshness" thread canceled (when canceled)
medic/cht-core#6188
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in …
> Adds Telemetry to Rules Engine, TasksCtrl and TargetsCtrl.

- sentinel/src/schedule/outbound.js
- shared-libs/transitions/src/schedule/due_tasks.js
- shared-libs/transitions/test/unit/due_tasks.js
- tests/e2e/sentinel/schedules/outbound.spec.js
Adds a hard limit of 1000 documents to be processed by `due_tasks` and `outbound` in a single process. 
Refactors `due_tasks` to use promises.
Adds `outbound` e2e test. 
medic/cht-core#6125
> Limits due_tasks and outbound queries to 1000 entries

- webapp/src/css/inbox.less
- webapp/src/templates/directives/actionbar.html
Restructures the HTML of the add person and add place menus to
be consistent with the add report menu so they look the same.
Also modifies the height restriction on the stacked icons so
the padding is maintained.
medic/cht-core#6394 …
> Make add contact menu HTML consistent

- ddocs/medic/_attachments/translations/messages-en.properties
> Add missing state.duplicate translation

- shared-libs/calendar-interval/src/index.js
- shared-libs/calendar-interval/test/index.js
- shared-libs/rules-engine/src/pouchdb-provider.js
- shared-libs/rules-engine/src/provider-wireup.js
- shared-libs/rules-engine/src/rules-state-store.js
- shared-libs/rules-engine/test/integration.spec.js
- shared-libs/rules-engine/test/pouchdb-provider.spec.js
- shared-libs/rules-engine/test/provider-wireup.spec.js
- shared-libs/rules-engine/test/rules-state-store.spec.js
- webapp/src/js/controllers/analytics-targets.js
- webapp/tests/karma/unit/controllers/analytics-targets.spec.js
Adds property to rules-engine state that contains a date representing the last time the state was updated. 
Upon loading a stale state during initialization and after before every state "recalculation", checks whether the state was last updated outside the current reporting interval. If yes, stores the `target` doc based on the stale state for the previous reporting interval before proceeding with initialization or recalculating the state. 
Updates `calendar-interval` library to return an interval that would include a provided timestamp. 
Updates target interval date comparison to be inclusive.
medic/cht-core#6209
- Documented: …
> Store previous month's targets on interval turnover

- webapp/src/js/services/form2sms.js
- webapp/tests/karma/unit/services/form2sms.spec.js
Updates `forms2sms` service so it requires the `xml2sms` form property to be set and truthy in order to generate SMS. If the value is Boolean, fallback to ODK standard, otherwise treat as angular expression.
medic/cht-core#6162 …
> App forms don't default to sending SMS. 

- api/src/services/authorization.js
- api/tests/mocha/services/authorization.spec.js
- tests/e2e/api/controllers/db-doc.spec.js
Includes `_unassigned` key in db-doc subjectIds, if allowed.
medic/cht-core#6421
> Db-doc now allows unassigned docs

- shared-libs/rules-engine/src/provider-wireup.js
- shared-libs/rules-engine/src/refresh-rules-emissions.js
- shared-libs/rules-engine/src/task-states.js
- shared-libs/rules-engine/test/provider-wireup.spec.js
- shared-libs/rules-engine/test/refresh-rules-emissions.spec.js
- shared-libs/rules-engine/test/task-states.spec.js
- tests/e2e/target-aggregates.spec.js
- webapp/src/js/controllers/inbox.js
- webapp/src/js/services/db-sync.js
- webapp/src/js/services/rules-engine.js
- webapp/tests/karma/unit/services/db-sync.js
- webapp/tests/karma/unit/services/rules-engine.js
Adds incoming changes feed listener that reacts when receiving `task` documents, by marking their corresponding "subjects" as dirty. 
When recalculating, if multiple tasks exist for a single emission, a single winner is chosen, while the rest are cancelled with a "duplicate" stateReason. The winner is the most recent, but not "future", most ready task. "Future" tasks are ignored to align with previous functionality. 
Fixes error thrown when receiving subject-less report in Rules-Engine changes listener. 
De-flakes unrelated e2e test. 
medic/cht-core#6389
medic/cht-core#6417
- Documented: Configuration and user documentation on …
> Cancel "duplicate" tasks

- admin/src/js/controllers/message-queue.js
- admin/tests/unit/controllers/message-queue.js
- tests/patches/webdriver-manager-config.patch
Switches MessagesController unit tests to use promises instead of timeouts. 
medic/cht-core#5960
> Bump chromedriver to 83 and fixes unit test

- shared-libs/rules-engine/src/pouchdb-provider.js
- shared-libs/rules-engine/src/rules-emitter.js
- shared-libs/rules-engine/test/mocks.js
- shared-libs/rules-engine/test/pouchdb-provider.spec.js
- shared-libs/rules-engine/test/rules-emitter.spec.js
- shared-libs/rules-engine/test/transform-task-emission-to-doc.spec.js
- webapp/src/js/services/rules-engine.js
- webapp/tests/karma/unit/services/rules-engine.js
Makes that a report will only be allowed to generate tasks for one contact!
So, instead of broadening the scope when calculating (which would have been a deep rabbit-hole), i'm tightening it. 
> Tighten relation between report "primary" subject and tasks

- sentinel/server.js
- sentinel/src/lib/feed.js
- sentinel/tests/unit/lib/feed.js
Always restart the feed from the `sentinel-meta-data.processed_seq`.
Awalys equeue first, then stop the feed. 
Always null-check before stopping the feed. 
Switches from `async.queue.kill` to `async.queue.pause` + `async.queue.resume` because 
https://caolan.github.io/async/v3/docs.html#QueueObject
Crash on unhandled exception.
medic/cht-core#6440
- Backwards compatible: Works with existing data and configuration or includes a migration. Any …
> Stop storing last_seq and null-check before cancel.

- tests/e2e/sentinel/schedules/purging.spec.js
Which causes tests to spuriously fail on the 1st and 2nd of the month
> Removing unneeded test target

- demo-forms/multimedia-repeats.xml
- webapp/src/js/services/enketo.js
When Enketo fires the addrepeat event it inits the widgets on the
new HTML so we should replace the image loaders at the same time.
medic/cht-core#6450
> Replace images loaders on addrepeat

- tests/scalability/sync.jmx
Paths in sync.jmx were hardcoded to an old PC of mine. Updated to be relative.
> changed paths to relative paths so it works on other computers

- INSTALL.md
Add a sentence delineating  [DEVELOPMENT.md](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md) vs [INSTALL.md](https://github.com/medic/cht-core/blob/master/INSTALL.md)
medic/cht-core#6508
> Add a sentance deliniating INSTALL.md vs DEVELOPMENT.md per #6508

- admin/src/templates/edit_user.html
- tests/e2e/users/add-user.specs.js
- tests/page-objects/users/add-user-modal.po.js
The User name field should be blank when adding a new user, this PR adds the autocomplete="off" property to the input field in admin/user. 
I checked password and confirm password fields as well as login fields and all of them has the property correctly. Just this one was missing.
medic/cht-core#6404
The …
> Turn off the autocomplete on user name field.

- webapp/src/css/dropdown.less
Issue: medic/cht-core#6481
Increase the width of the component a bit and wrap the text instead of hide it when overflow.
Here is how it looks now:
In **mobile** the new size is ignored as expected taking the full width, but the wrapping is applied:
The PR also takes into account **nested bullets** with long texts:
And finally, the changes also place nicely with **scrolls** when the list is too largem and **Firefox**:
- Backwards compatible: …
> Increase width and wrap text in dropdown selects

- webapp/src/js/controllers/contacts-edit.js
- webapp/src/js/controllers/contacts-report.js
- webapp/src/js/controllers/reports-add.js
- webapp/src/js/controllers/tasks-content.js
- webapp/tests/karma/unit/controllers/tasks-content.js
The error should be cleared when, either
a) the form is rendered again, or
b) a value in the form has changed
medic/cht-core#6386
> Clear form submission error

- shared-libs/transitions/src/lib/history.js
- shared-libs/transitions/test/unit/lib/history.js
- shared-libs/transitions/test/unit/messages.js
- tests/e2e/transitions/message_duplicates.spec.js
- tests/e2e/transitions/utils.js
Adds `app_settings.sms.allowed_duplicates_limit` property to define maximum number of duplicate messages to send. Defaults to 5. Maximum allowed value is 20. 
medic/cht-core#6094
> Configurable duplicate message limit

- sentinel/src/schedule/outbound.js
- sentinel/tests/unit/schedule/outbound.js
- shared-libs/outbound/src/outbound.js
- shared-libs/outbound/test/outbound.spec.js
- shared-libs/transitions/src/transitions/mark_for_outbound.js
- tests/e2e/sentinel/transitions/mark_for_outbound.js
Adds a hash into completed_tasks so we can correctly detect when to
re-send a record.
This changes the sending semantics for outbound to be that we send an
outbound request whenever we have a configuration with a truthy
relevant_to, and where the prior send (if any) for that configuration
sent a different payload.
This is not a perfect system. If your mapping function is not idempotent
outbound may fire requests when you do not intend it to, e.g., if a user
doesn't actually edit the document meaningfully, or if sentinel or
another process writes to the document.
medic/cht-core#6419
> Outbound will send multiple requests for the same record

- api/src/services/authorization.js
- api/tests/mocha/controllers/changes.js
- api/tests/mocha/services/authorization.spec.js
- ddocs/medic/views/docs_by_replication_key/map.js
- shared-libs/view-map-utils/src/view-map-utils.js
- shared-libs/view-map-utils/test/view-map-utils.js
- tests/e2e/api/controllers/_changes.spec.js
- tests/e2e/api/controllers/all-docs.spec.js
- tests/e2e/api/controllers/bulk-docs.spec.js
- tests/e2e/api/controllers/bulk-get.spec.js
- tests/e2e/api/controllers/db-doc.spec.js
Adds a new property to `replication_depth`, called `report_depth` that reduces the depth of report replication, with the exception of reports that are submitted by the authenticated user. 
Only works in conjunction with regular replication depth, and the selected report depth is the one paired with the selected contact depth. 
Reports with `needs_signoff` work as before. 
medic/cht-core#6352
- Backwards compatible: Works with existing data and …
> Adds report replication depth

- webapp/src/js/services/enketo.js
- webapp/tests/karma/unit/services/enketo.js
Creates a timestamped log that can be analysed later, keeping the
original location for backwards compatability. Potentially we'd want to
change the original location so that it never overwrites that location.
> Add support for logging all geolocation results

- DEVELOPMENT.md
Remove serveo, add pagekite from [developer setup doc](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md) 
medic/cht-core#6551
> Remove serveo, add pagekite from developer setup doc 

- docker-compose.yml
- release-notes/docs/3.9.0.md
We updated the CHT docker image to include the new horticulturalist that contains a fix to handle upgrading projects to 3.9
@garethbowen 
Not sure if I created the correct subcategories to place this information inside. Please let me know if it should reside elsewhere.
> 3.9 CHT Docker Image Update

- Gruntfile.js
Running unit tests locally fails if the credentials you have set up from couchdb do not match what is expected. This change just explicitly sets the expected username and password.
> update couchdb credentials for running tests

- api/src/services/authorization.js
- api/tests/mocha/services/authorization.spec.js
- ddocs/medic/views/docs_by_replication_key/map.js
- tests/e2e/api/controllers/_changes.spec.js
- tests/e2e/api/controllers/all-docs.spec.js
- tests/e2e/api/controllers/bulk-get.spec.js
- tests/e2e/api/controllers/db-doc.spec.js
Changes the definition of a "sensitive" report, so it needs to:
1. be about the user's contact or the user's place
2. be submitted by someone the user can't see
3. have a field called `private` with a truthy value. 
medic/cht-core#6370
The software is provided under AGPL-3.0. Contributions to this project …
> Adds `private` sensitive property

- shared-libs/rules-engine/src/provider-wireup.js
- shared-libs/rules-engine/test/mocks.js
- shared-libs/rules-engine/test/provider-wireup.spec.js
- webapp/src/js/services/debounce.js
- webapp/src/js/services/rules-engine.js
- webapp/tests/karma/unit/services/debounce.js
- webapp/tests/karma/unit/services/rules-engine.js
Updates `rules-engine` shared lib to only allow a single `refreshRulesEmissions` call to be executed in parallel. All calls to `fetchTasksFor` and `fetchTargets` are queued and are execute sequentially. 
To support accurate Telemetry readings, calls to `fetchTargets` and `fetchTasksFor` return promisemitters, which resolve when the tasks are done and emit two events: `queued` when placed in the queue and `running` when execution started.
The webapp `RulesEngine` service listens to these events and logs a new Telemetry record, `queued`, that registers the time the request spent in a queue (from `queued` event to `running` event), along with the already existent "execution" record, that only registers execution time (from the `running` event to promise resolution). 
medic/cht-core#6562
- …
> Single emissions recalculation thread

- sentinel/src/schedule/outbound.js
- sentinel/tests/unit/schedule/outbound.js
- shared-libs/transitions/package-lock.json
- shared-libs/transitions/package.json
- shared-libs/transitions/src/db.js
- shared-libs/transitions/src/schedule/due_tasks.js
- shared-libs/transitions/test/unit/due_tasks.js
- tests/e2e/sentinel/schedules/due_tasks.spec.js
Also changes batching mechanism for `due_tasks` and `outbound` now that Sentinel tasks are run in parallel and don't block each other. 
This fixes a potential bug where the queue of 1000 entries may be saturated with "errored" docs which will be processed over and over: for example a `scheduled_task` with a missing message translation or an outbound task that always fails to be sent. 
medic/cht-core#6582
- Backwards compatible: Works with …
> Fix due_tasks to match due date the same as the messages_by_state view

- tests/e2e/api/controllers/bulk-docs.spec.js
- tests/e2e/login/purge.spec.js
- tests/page-objects/forms/generic-form.po.js
- tests/page-objects/reports/reports.po.js
- webapp/tests/karma/karma-unit.conf.js
- webapp/tests/karma/unit/directives/auth.js
Tries to fix:
- Auth directive unit tests
- Offline user purge e2e test (that didn't wait for reports to load before asserting and sometimes timed out)
- Bulk docs e2e test that was timing out waiting for sentinel to process past docs
- the add new family form e2e test that was accessing stale elements because of "referencing" them while before asserting / accessing them
- Backwards compatible: Works with existing data and configuration or …
> Attempt to de-flake some unit/e2e tests

- api/src/controllers/login.js
- api/src/routing.js
- api/src/services/cookie.js
- tests/e2e/api/routing.js
This keeps pushing the userCtx expiry date a year ahead so it's
unlikely to ever expire in normal usage conditions. If this cookie
expires then the user is redirected to the login page despite
having a valid CouchDB session and AuthSession cookie.
medic/cht-core#6583 …
> Refresh the userCtx expiry when getting session

- admin/src/js/controllers/edit-user.js
- admin/tests/unit/controllers/edit-user.js
Fixes issue where the replication warning rejection was caught by the wrong catch block and not ending up displayed to the user. 
Also converts all edit-user unit tests to use promises instead of timeouts. 
medic/cht-core#6578 …
> Fixes replication warning not being displayed when editing a user

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
The slack #cht-contributors channel has been archived in June 2020. 
Removes patch release supported software step. 
Adds patch release forum post step. 
> Updates release issue templates to exclude archived channel reference

- shared-libs/transitions/src/lib/utils.js
- shared-libs/transitions/test/unit/lib/utils.js
- tests/e2e/sentinel/transitions/registration.spec.js
Because `medic-client/reports_by_subject` emits multiple times per document, ensure we're returning a unique array when attempting to clear schedules.
medic/cht-core#6624
> Updates getReportsBySubject to return array without duplicates.

- tests/e2e/login/token-login.spec.js
- tests/page-objects/reports/reports.po.js
This PR will increase reliability in e2e tests:
1. Remove loading spinner check on page redirection, since redirection happens first.
2. Check reports IDs when angular/browser is ready.
medic/cht-core#6605 …
> 6605-fix-e2e-login

- sentinel/src/schedule/replications.js
- sentinel/tests/unit/schedule/replications.js
Ticket: https://github.com/medic/cht-core/issues/6591
> Fix regex that causes usernames with `-` chars to skip meta replication

- api/src/migrations/restrict-access-to-sentinel-db.js
- api/tests/mocha/migrations/restrict-access-to-audit-db.spec.js
- api/tests/mocha/migrations/restrict-access-to-sentinel-db.spec.js
This PR will apply access restriction to Sentinel DB where users with "sentinel" role or _admin users are allowed. 
medic/cht-core#6120
> 6120 access control sentinel

- tests/e2e/concatenate-xpath-strings.spec.js
- tests/page-objects/forms/concatenate-strings.po.js
- webapp/tests/mocha/unit/packages.spec.js
Add a test which runs against the version of `openrosa-xpath-evaluator`
medic/cht-core#6490
> add test for the version of openrosa-xpath-evaluator

- api/src/services/authorization.js
- api/tests/mocha/services/authorization.spec.js
Authorization `isSensitive` now can accept a function to determine if the user is allowed to see the submitter.
When getting allowed doc ids, sort subjects array to leverage much quicker binary search. 
Also uses binary search when searching for undone-deletions in the ids list. 
medic/cht-core#6577
The …
> Only search for submitter on "demand" and use binary search.

- webapp/src/ts/app.component.ts
- webapp/src/ts/components/filters/facility-filter/facility-filter.component.ts
- webapp/src/ts/components/filters/form-type-filter/form-type-filter.component.ts
- webapp/src/ts/components/filters/freetext-filter/freetext-filter.component.ts
- webapp/src/ts/components/header/header.component.ts
- webapp/src/ts/components/snackbar/snackbar.component.ts
- webapp/src/ts/modals/guided-setup/guided-setup.component.ts
- webapp/src/ts/modules/about/about.component.ts
- webapp/src/ts/modules/messages/messages.component.ts
- webapp/src/ts/modules/reports/reports-content.component.ts
- webapp/src/ts/modules/reports/reports.component.html
- webapp/src/ts/modules/reports/reports.component.ts
- webapp/src/ts/selectors/index.ts
- webapp/src/ts/services/changes.service.ts
- webapp/tests/karma/ts/modules/messages/messages.component.spec.ts
Updates all selectors to be created with "createSelector". 
Moves all redux subscriptions in components from constructors to ngOnInit. 
> 4750 update selectors

- scripts/remove_non_admin_users.js
The `remove_non_admin_users.js` script didn't seem to work as it was using an object from `url.parse()` as a string.  Further, it only worked with https, thus was hard to test against local dev instances.  This PR fixes both of these problems.
medic/cht-core#6663 …
> update delete non-admin users to work, compatible with http/s #6663

- webapp/src/ts/app.component.ts
- webapp/src/ts/modals/edit-user/edit-user-settings.component.ts
- webapp/src/ts/services/language.service.ts
- webapp/src/ts/services/languages.service.ts
- webapp/tests/karma/ts/modals/edit-user/edit-user-settings.component.spec.ts
- webapp/tests/karma/ts/modals/edit-user/update-password.component.spec.ts
medic/cht-core#4750
Migration of the services `SetLanguageCookie`, `SetLanguage` and `Language` from [js/services/language.js](https://github.com/medic/cht-core/blob/2c1db1618bdafc5ec14c3a27aa4a37249fcc1b4a/webapp/src/js/services/language.js).
- The changes cause that when the user goes to _"User settings" > "Edit user profile"_ and change its language setting the UI changes the current language to the one selected. Also causes that when the user logs in or refresh the page, the user language is used instead of the default one.
- There is a block commented with a TODO [here](https://github.com/medic/cht-core/blob/bdb4ec74fe0a9bac700897f7a538ce94aa7cbdb6/webapp/src/ts/services/language.service.ts#L40-L47) that uses a component `$.datepicker` that looks not migrated yet. Once migrated these …
> 4750 - Angular migration of Language* services

- Gruntfile.js
Adding the --inspect option opens a port that can be used by an editor/IDE to allow for interactive debugging.
The switch is described here: https://nodejs.org/en/docs/guides/debugging-getting-started/#enable-inspector
VS Code instructions to attach: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_attach-to-node-process-action
Jetbrains IDE instructions to attach: https://www.jetbrains.com/help/ruby/running-and-debugging-node-js.html#4c71e
> Configure node debugger for development

- DEVELOPMENT.md
This adds instructions for persisting the couch config, which otherwise
only exists in the container and therefore is ephemeral.
> Update CouchDB docker instructions.

- .github/ISSUE_TEMPLATE/z_release_major.md
@garethbowen updated for your review based on discussion in weekly product team call. The "Communication" section would be managed by the Product Management team
> Update release ticket with communication section

- webapp/src/ts/app.module.ts
- webapp/src/ts/providers/translate-message-format-compiler.provider.ts
- webapp/tests/karma/ts/providers/translate-message-formate-compiler.provider.spec.ts
We used to rely on messageformat to provide pluralization. The AngularJS translator allowed you to control how you could interpolate a translation, but ngx-translate does not. 
It does, however, allow you to overwrite the default compiler and use that as the middle man between it and messageformat. 
I found a library that passed **all** translations through messageformat (https://www.npmjs.com/package/ngx-translate-messageformat-compiler) which is bad for use, because of all the caveats. for example, messageformat encloses params in single curly braces, versus double curly braces that we use. 
So I quickly created our own compiler that does a really stupid filter (only passes translations to messageformat if they use single curly braces!) and mostly rushed it to unblock @njogz with …
> Adds translations compiler to support pluralization

- .github/ISSUE_TEMPLATE/z_release_major.md
After discussing with Michael and Marc, I have added couple of items on end-user documentation and cleaned-up an error for the blog post
> add documentation to release ticket

- tests/conf.js
Currently if you do nothing to the conf and try to run e2e tests it will fail. Protractor is trying to load directories as modules with the path expansion defined. This fixes for now. I see we have a second config that has just 2 conditionals that are for travis only. Really should work out how to get that back into 1 file. 
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking …
> protractor no longer requires directories when running e2e locally

- package.json
We're already exceeding it with a few kb in some branches.
I'm not sure what tipped us over so suddenly, I've created an issue to investigate the bundle when the migration is complete: https://github.com/medic/angular10-migration/issues/39
The software is provided under AGPL-3.0. Contributions to this project …
> Bumps main.js bundlesize from 700 to 750kb.

- CONTRIBUTING.md
Fixes some grammar (is->if), removes a duplicate section; also adds a link to the cht-docs repo.
> doc: CONTRIBUTING.md: is->if, remove dupe section (Improving our Doc...)

- README.md
Fixes a 404 error (detailed guide is available in cht-docs...). The link leads to https://docs.communityhealthtoolkit.org/design/apps/, which doesn't exist.
> fix 404 in README.md

- DEVELOPMENT.md
Fixes 2 links. They currently lead to a page that gives the message:
`We couldn't display the repository
medic/medic `
> fix 2 links in DEVELOPMENT.md (travis)

- webapp/src/ts/services/changes.service.ts
- webapp/src/ts/services/unread-records.service.ts
- webapp/src/ts/services/xml-forms.service.ts
- webapp/tests/karma/ts/services/changes.service.spec.ts
Added debounce option in change service and set 500 milliseconds for the unread count's change listener.
https://github.com/medic/angular10-migration/issues/53
> 4750 - Adding debounce to unread count service and change service

- webapp/tests/karma/ts/effects/contacts.effects.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-content.component.spec.ts
medic/cht-core#4750
New contact tests were running OK but:
1. There were unchecked errors logged in the `contacts.effects.spec.ts` tests:
```
ERROR: 'Error fetching children', Object{error: 'we have a problem'}
✔ should catch loadChildren errors
ERROR: 'Error loading reports', Object{error: 'we have a problem'}
receiveSelectedContactReports
✔ should catch loadReports errors
✔ should call the receiveSelectedContactReports action
updateSelectedContactSummary
✔ should call the right actions
ERROR: 'Error loading summary', Object{error: 'we have a problem'}
✔ should catch contactSummaryService errors
receiveSelectedContactTargetDoc
✔ should call the receiveSelectedContactTargetDoc action
ERROR: 'Error loading target doc', Object{error: 'we have a problem'}
✔ should catch …
```
> 4750 - Angular 10 - contacts specs errors

- tests/.eslintrc
Add a eslint rule that requires a space on async arrow functions. 
medic/cht-core#https://github.com/medic/angular10-migration/issues/111
> Requires async arrow functions to have space between async and ()

- webapp/src/ts/effects/contacts.effects.ts
- webapp/src/ts/modules/contacts/contacts-content.component.html
- webapp/src/ts/modules/contacts/contacts.routes.ts
- webapp/tests/karma/ts/effects/contacts.effects.spec.ts
This PR fixes the following issues:
- [Navigating back from deceased contacts](https://github.com/medic/angular10-migration/issues/101)
- [Spinners being displayed on currently viewed contact](https://github.com/medic/angular10-migration/issues/98)
- [Incorrect primary contact link when primary contact is not a child of the place](https://github.com/medic/angular10-migration/issues/99)
- Backwards compatible: Works with existing data and configuration …
> 4750 fix issues 101, 99, and 98

- webapp/src/ts/components/content-row-list-item/content-row-list-item.component.html
- webapp/src/ts/components/filters/simprints-filter/simprints-filter.component.html
- webapp/src/ts/components/filters/sort-filter/sort-filter.component.html
- webapp/src/ts/modals/feedback/feedback.component.html
- webapp/src/ts/modules/messages/messages.routes.ts
Migrated instances of `translate-attr-title` in the codebase.
Implemented messages URL redirect when 'id' is specified but not 'type'.
https://github.com/medic/angular10-migration/issues/106
https://github.com/medic/angular10-migration/issues/108 …
> 4750 translation attr-title and messages redirect

- webapp/src/ts/components/actionbar/actionbar.component.html
- webapp/tests/karma/ts/modules/contacts/contacts-content.component.spec.ts
- Removed unnecessary attribute: `attr.data-send-to`
- Fixed override selector in unit test: `should enable edit and delete in the right action bar when admin user`
- Removed default value in beforeEach to improve test readability
- Removed unnecessary test data in unit test: `should set relevant report forms based on the selected contact`
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes …
> Contact content tests improvement

- .travis.yml
Tries to fix issue where Travis builds don't run for external contributors. 
> Update travis.yml to support external contributors

- webapp/src/js/enketo/bootstrap-datepicker.ceb.js
- webapp/src/js/enketo/bootstrap-datepicker.hil.js
- webapp/src/js/enketo/bootstrap-datepicker.tl.js
- webapp/src/js/enketo/main.js
Cherry picks locales from https://github.com/medic/cht-core/pull/6865
Fixes linting, enables the languages and normalizes locale codes, as agreed upon here: https://github.com/medic/cht-core/issues/6861#issuecomment-764478365
medic/cht-core#6849 …
> Adds bootstrap datepicker locales

- webapp/src/js/moment-locales/ceb.js
- webapp/src/js/moment-locales/hil.js
- webapp/src/js/moment-locales/tl.js
- webapp/src/ts/main.ts
Migrating moment.js locales: Tagalog, Illonggo, Cebuano
Migration ticket:
https://github.com/medic/angular10-migration/issues/128
Original ticket:
https://github.com/medic/cht-core/issues/6861
> Migrating moment.js locales: Tagalog, Illonggo, Cebuano

- .github/workflows/build.yml
Fix the issue of PRs from contributors failing in CI because the first step try to login at Docker Hub without having user credentials. The changes makes CI to omit the step if there are no credentials set.
Issue: https://github.com/medic/angular10-migration/issues/131
In this [build](https://github.com/medic/cht-core/actions/runs/521120685) I have tested both scenarios pushing a commit that then I removed from the branch where the first job _"Compile the app"_ uses a different variable that does not exist to signup so the result was the expected: the step _"Login to Docker Hub"_ were skipped, while the rest of the jobs in the pipeline used the right variable name (`DOCKERHUB_USERNAME`) and the login process did happen also as expected. …
> GH actions: skip "Login to Docker Hub" if no username is provided

- tests/conf-disabled.js
- tests/e2e/sentinel/utils.js
- tests/e2e/transitions/public_form_transitions.spec.js
- tests/utils.js
Updating public_form_transitions to async/await. Added more methods to switch to disabled control flow.
https://github.com/medic/angular10-migration/issues/73
> 73 public form transitions again

- scripts/travis/couch-start
setting version 2.3.1 to fix an issue with couchdb:2 tag on docker hub. 
medic/cht-core#https://github.com/medic/cht-core/issues/6901
> setting the 2.3.1 couchdb tag

- CONTRIBUTING.md
- README.md
This makes information about translating more accessible to first-time contributors. It appeared to me that the info was a little too "buried" in the docs, especially for people who may be translators but not necessarily developers.
If you agree, then I'd suggest that some info also be added to [this page](https://docs.communityhealthtoolkit.org/contribute/) in the docs repo (https://github.com/medic/cht-docs/issues/420).
> makes information about translating more accessible to first-time contributors

- .travis.yml
@newtewt had noted this when we moved yesterday, but I forgot to make the change in the ruckus of the failing builds. Thanks @newtewt!
> Update log storage cmd for Travis org->com

- Gruntfile.js
Removing grunt command that generates jsdocs for webapp. The original package isn't compatible with new angular and:
> Because must of us jump into the code directly to get understanding and because running a command isn't the most friendly/straight forward way for getting documentation...
More info in the ticket: https://github.com/medic/angular10-migration/issues/120
> Remove jsdocs for webapp

- sentinel/src/lib/feed.js
- sentinel/tests/unit/lib/feed.js
- tests/conf-disabled.js
- tests/conf.js
- tests/e2e/api/controllers/users.js
- tests/e2e/sentinel/transitions/mark_for_outbound.js
- tests/e2e/sentinel/transitions/registration.spec.js
- tests/utils.js
Takes a different approach to enabling/disabling protractor control flow and performs switch at the lowest level, and reduce the number of lines of changes to a minimum. 
Cherry picks a commit from `master` to fix an e2e test. 
> Enables api and sentinel e2e tests 

- tests/e2e/sentinel/transitions/registration.spec.js
This test was failing because we started to run tests before actually waiting for sentinel to update its settings. (this was a problem in travis as well, but aparently travis was fast enough that this was not an issue). 
https://github.com/medic/angular10-migration/issues/143
> Fix flacky registration e2e test

- tests/e2e/create-meta-db.js
- tests/e2e/registration-by-sms.js
- tests/e2e/transitions/sms_workflows.spec.js
- tests/e2e/users/add-user.specs.js
Refactors create-users-meta-dbs to use existent functions. 
Fixes sms_workflows afterEach not waiting for execution. 
Bulk saveDocs in registration_by_sms
Redirects back to webapp after users e2e tests.
https://github.com/medic/angular10-migration/issues/148
https://github.com/medic/angular10-migration/issues/147
> Small e2e tests fixes

- tests/conf-disabled.js
- tests/conf.js
- tests/e2e/reports-subject.js
- tests/page-objects/reports/reports.po.js
Migrating and fixing e2e tests in reports subject
https://github.com/medic/angular10-migration/issues/135
> Fix e2e flacky tests in reports subject 

- package-lock.json
- package.json
- webapp/custom-webpack.config.js
- webapp/package-lock.json
- webapp/package.json
- webapp/tests/karma/ts/services/translate-from.service.spec.ts
Saves 20KB of minified bundle size. 
https://github.com/medic/angular10-migration/issues/39
> Dedupes lodash and adds webpack-bundle-analyzer

- tests/e2e/reports-subject.js
Stabilizes reports-subject.js e2e tests by updating all tests to wait for sentinel before loading reports.
Adds additional e2e test that tests that list and content reports are updated when changes come in, to make up for the fact that the other tests are no longer observing this behavior.
https://github.com/medic/angular10-migration/issues/152
> Stabilizes reports-subject.js e2e tests

- tests/page-objects/messages/messages.po.js
Reviewed what's happening before and test wise. I've updated to use the `waitUntilReadyNative()` instead of two separate functions that per the docs do the same thing. 
> attempt at send-message flakey fix by using waituntilnative

- webapp/src/ts/app.component.ts
- webapp/src/ts/components/actionbar/actionbar.component.html
- webapp/src/ts/modules/reports/reports-add.component.ts
- webapp/src/ts/reducers/messages.ts
- webapp/src/ts/services/changes.service.ts
- webapp/src/ts/services/get-subject-summaries.service.ts
- webapp/src/ts/services/hydrate-messages.service.ts
- webapp/src/ts/services/resource-icons.service.ts
Fix changes service not restarting correctly after being disconnected.
Add beforeunload listener to stop watchers and avoid unnecessary e2e test log pollution.
Minor refactor in resource icons service.
Fix get subject summaries calling with incorrect scope.
Adds more nullchecks. 
https://github.com/medic/angular10-migration/issues/163
https://github.com/medic/angular10-migration/issues/157
https://github.com/medic/angular10-migration/issues/156
> Only display actionbar buttons when they have actions attached to them

- webapp/src/ts/components/actionbar/actionbar.component.html
- webapp/src/ts/components/actionbar/actionbar.component.ts
- webapp/src/ts/components/filters/facility-filter/facility-filter.component.ts
- webapp/src/ts/modules/contacts/contacts-content.component.ts
- webapp/src/ts/modules/contacts/contacts.component.ts
- webapp/tests/karma/ts/components/filters/facility-filter.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-content.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts.component.spec.ts
- webapp/tests/karma/ts/modules/reports/report-filters.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports.component.spec.ts
Also changes:
- contacts lists for online roles that don't have a home place to show top level contacts (just like admins) instead of ALL contacts
- contacts content to enable editing of home-place for online users. 
- facility filter to display deleted label for all online users, not just admins
medic/cht-core#6611
> Enable webapp exporting for online roles

- ddocs/medic-db/medic-client/views/contacts_by_parent/map.js
- webapp/src/js/actions/contacts.js
- webapp/src/js/controllers/contacts-edit.js
- webapp/src/js/controllers/contacts.js
- webapp/src/js/controllers/send-message.js
- webapp/src/js/services/contact-view-model-generator.js
- webapp/src/js/services/contacts.js
- webapp/src/js/services/live-list.js
- webapp/src/js/services/xml-forms.js
- webapp/tests/karma/unit/controllers/contacts-edit.js
- webapp/tests/karma/unit/controllers/contacts.js
- webapp/tests/karma/unit/services/contact-view-model-generator.js
- webapp/tests/karma/unit/services/contacts.js
- webapp/tests/karma/unit/services/xml-forms.js
- webapp/tests/karma/unit/store/contacts.js
When a contact of a hardcoded type has a `contact_type` property, fixes: 
- tasks not displaying
- not being listed in parent's contact detail page, or being listed in a separate untitled section
- editing throwing errors
- icons not displaying in list or content
- actionbar new action list when contact is selected
- error when focusing the send-message select2 
- visit count not displaying when UHC is enabled and contact is a `clinic`
medic/cht-core#6993
> Use contact-type-utils to determine contact type throughout webapp (3.10)

- admin/src/js/services/import-contacts.js
- admin/tests/unit/services/import-contacts.js
- shared-libs/transitions/src/transitions/muting.js
- shared-libs/transitions/src/transitions/update_clinics.js
- shared-libs/transitions/src/transitions/update_scheduled_reports.js
- shared-libs/transitions/test/unit/transitions/muting.js
- shared-libs/transitions/test/unit/update_clinics.js
- tests/e2e/sentinel/transitions/muting.spec.js
- tests/e2e/sentinel/transitions/update_clinics.spec.js
Fixes new contacts with muted parent not getting the muted state when the contact has a hardcoded type and a contact_type. 
Fixes update_clinics refid contact link not working when the connected contact  has a hardcoded type and a contact_type. 
Uses contact-type-utils in admin import-contacts. 
medic/cht-core#6996
> Update muting, update_clinics, update_scheduled_reports and admin import contacts (3.10)

- webapp/src/ts/modules/tasks/tasks.component.ts
- webapp/src/ts/services/rules-engine.service.ts
- webapp/tests/karma/ts/modules/tasks/tasks.component.spec.ts
- webapp/tests/karma/ts/services/rules-engine.service.spec.ts
Rules-Engine now has an observable that emits when contacts have been marked as dirty. 
The tasks component subscribes to this observable and refreshes the task like for every emission. 
medic/cht-core#6839
> Fixes race condition in displaying tasks after submission

- .github/workflows/build.yml
- scripts/travis/cleanup.js
It's better to clean up based on timestamp than build number. Now
instead of keeping the last 50 builds, which was broken with GitHub
Actions anyway, we keep the last 7 days of builds.
medic/cht-core#7000
> Fix CI cleanup script

- shared-libs/rules-engine/src/target-state.js
- shared-libs/rules-engine/test/provider-wireup.spec.js
- shared-libs/rules-engine/test/target-state.spec.js
Fix a bug where the incorrect target was being shown for targets that use `passesIfGroupCount.gte`
medic/cht-core#6811
> 6811 Fix targets with property "passesIfGroupCount.gte" counting 'pass:false'

- .github/workflows/build.yml
Because we were not running e2e tests when we first drafted the build.yml, the `publish` job was run immediately after the build, for every build. instead of running after e2e tests passed successfully. 
Now, `publish` will run as part of a separate job, depending on e2e tests passing successfully. 
> Moves publish from build to own final job.

- api/src/config.js
- api/src/logger.js
- sentinel/src/lib/logger.js
- sentinel/src/schedule/reminders.js
- shared-libs/outbound/src/outbound.js
- shared-libs/tombstone-utils/src/tombstone-utils.js
- shared-libs/transitions/src/transitions/index.js
Deletes `options`, `request` and `response` properties from `request-promise-native` errors before logging. 
medic/cht-core#7023
> Clean up request errors for security.

- DEVELOPMENT.md
add nginx-local-ip as the preferred method to add an SSL cert to dev CHT instances
> add nginx-local-ip to dev install instructions

- .github/workflows/scalability.yml
- tests/scalability/run_suite.sh
- tests/scalability/start_ec2_medic.sh
Fixes a few things related to the stale state of scalability runs.  
the set-env is no longer the way to set env vars.
Removed the quiet flag for logs
updated jmeter and setting the wget output name. 
> Update set env

- webapp/src/ts/app.component.ts
- webapp/src/ts/components/filters/form-type-filter/form-type-filter.component.ts
- webapp/src/ts/modals/edit-user/edit-user-settings.component.ts
- webapp/src/ts/services/language.service.ts
- webapp/tests/karma/ts/components/filters/form-type-filter.component.spec.ts
- webapp/tests/karma/ts/modals/edit-user/edit-user-settings.component.spec.ts
This PR:
- Adds sort form filter options by title and ascending.
- Adds await for setting language before continuing loading forms. 
Ticket: https://github.com/medic/cht-core/issues/7066
> Sort of form filter and awaiting for language

- DEVELOPMENT.md
- api/README.md
- sentinel/README.md
On the login page, the username is transformed to lowercase when submitting the form. This PR updates docs that were previously recommending a username with uppercase letters.
I also lowercased the password for consistency.
> Use lowercase username for couchdb credentials in examples

- webapp/src/ts/components/header/header.component.ts
- webapp/src/ts/services/db-sync.service.ts
- webapp/tests/karma/test.ts
- webapp/tests/karma/ts/services/db-sync.service.spec.ts
The following telemetry records are added: 
| key | value | recorded | 
| --- | ------- | -------- | 
| `replication:user-initiated`  | 1 | when the user clicks "Sync now" | 
| `replication:<database>:<direction>:success` | number representing how long in took to replicate, in ms | when replication is successful | 
| `replication:<database>:<direction>:failure` | number representing how long in took to replicate, in ms | when replication is failed | 
| `replication:<database>:<direction>:failure:reason:offline:client` | 1 | replication fails because of connection error and the app detects the client is offline | 
|  `replication:<database>:<direction>:failure:reason:offline:server` | 1 | replication fails because of connection error and the app detects the client is online | 
| …
> Adds telemetry for replication requests

- admin/package-lock.json
- admin/package.json
- api/package-lock.json
- api/package.json
- package-lock.json
- package.json
- sentinel/package-lock.json
- sentinel/package.json
- shared-libs/calendar-interval/package-lock.json
- shared-libs/calendar-interval/package.json
- shared-libs/message-utils/package-lock.json
- shared-libs/message-utils/package.json
- shared-libs/rules-engine/package-lock.json
- shared-libs/rules-engine/package.json
- shared-libs/search/package-lock.json
- shared-libs/search/package.json
- shared-libs/transitions/package-lock.json
- shared-libs/transitions/package.json
- webapp/package-lock.json
- webapp/package.json
- webapp/patches/moment-hindi-use-euro-numerals.patch
This PR:
- Fixes the MomentJS patch
- Upgrades the MomentJS to 2.29.1 in CHT-Core's apps
https://github.com/medic/cht-core/issues/7084
> Upgrade moment.js to latest version

- api/src/controllers/monitoring.js
- api/src/middleware/deprecation.js
- api/src/routing.js
- api/src/services/monitoring.js
- api/tests/mocha/controllers/monitoring.spec.js
- api/tests/mocha/middleware/deprecation.spec.js
- api/tests/mocha/services/monitoring.spec.js
- ddocs/medic-db/medic-admin/views/message_queue/map.js
- ddocs/medic-db/medic-sms/views/messages_by_last_updated_state/map.js
- tests/conf.js
- tests/e2e/api/controllers/all-docs.spec.js
- tests/e2e/api/controllers/bulk-docs.spec.js
- tests/e2e/api/controllers/bulk-get.spec.js
- tests/e2e/api/controllers/contacts-by-phone.spec.js
- tests/e2e/api/controllers/db-doc.spec.js
- tests/e2e/api/controllers/hydration.spec.js
- tests/e2e/api/controllers/monitoring.spec.js
- tests/e2e/login/db-sync-filter.spec.js
- tests/e2e/sentinel/utils.js
- tests/e2e/transitions/sms_workflows.spec.js
Updates `medic-admin/message_queue` to separately index failed (`failed`) and delivered (`delivered` and `sent`) outgoing messages. 
Adds `monitoring.messaging.outgoing..state.delivered` and `monitoring.messaging.outgoing.state.failed` counters. 
Fixes `monitoring.sentinel.backlog` not using the new metadata doc. 
Adds `/api/v2/monitoring` endpoint with the following changes compared to `api/v1/monitoring`:
- Renames `monitoring.messaging.outgoing.state`. to `monitoring.messaging.outgoing.total`. 
- Adds a new section `monitoring.messaging.outgoing.seven_days` that includes the same metrics, but only covers the last 7 days. 
- Adds a new section `monitoring.messaging.outgoing.last_hundred` that groups messages by statuses (pending, final, muted) and displays counts statuses for last 100 …
> Adds failed and delivered WO messages count to monitoring API

- scripts/get_users_meta_docs.js
- webapp/src/ts/services/telemetry.service.ts
- webapp/tests/karma/ts/services/telemetry.service.spec.ts
Change telemetry frequency from monthly to **daily**.
medic/cht-core#6915
- Telemetry frequency changed from monthly to daily.
- The id of a telemetry record now looks like `telemetry-<year>-<month>-<day>-<username>-<uuid>`. Also in the `metadata` section a new field `day` is added with the day of the month the data belongs to.
- More test coverage in the telemetry spec.
- Minor improvements in the script to collect meta data from a terminal (`scripts/get_users_meta_docs.js`):
- Output errors in the standard error stream to see the errors in the console while piping results to a JSON file.
- Add Unix exec permission and header to execute the script without the `node ` prefix.
Please also review the documentation changes [here](https://github.com/medic/cht-docs/pull/493).
It also fix the …
> 6915  - Telemetry daily frequency

- Gruntfile.js
- scripts/e2e/start_webdriver.sh
- tests/e2e/api/controllers/export-data-2.js
Fixes bug in export data afterAll.
Removes `webdriver-version`  replace, which no longer applies to current version of protractor. 
medic/cht-core#7124
medic/cht-core#7118
> Hardcode chromedriver to 90

- DEVELOPMENT.md
Fixed a typo in COUCHDB_NODE_NAME example
Fix a typo in COUCHDB_NODE_NAME example IP address
> Fix a typo in COUCHDB_NODE_NAME example IP address

- tests/e2e/forms/submit-delivery-form.specs.js
- tests/page-objects/forms/add-family-form.po.js
- tests/page-objects/forms/delivery-report.po.js
- tests/page-objects/reports/reports.po.js
- webapp/src/ts/services/enketo-translation.service.ts
- webapp/src/ts/services/enketo.service.ts
- webapp/tests/karma/karma-unit.conf.js
- webapp/tests/karma/test.ts
- webapp/tests/karma/ts/services/enketo-xml/binary-field.xml
- webapp/tests/karma/ts/services/enketo-xml/db-doc-ref-in-deep-repeat.xml
- webapp/tests/karma/ts/services/enketo-xml/db-doc-ref-in-deep-repeats-extra-repeats.xml
- webapp/tests/karma/ts/services/enketo-xml/db-doc-ref-in-deep-repeats-with-local-references.xml
- webapp/tests/karma/ts/services/enketo-xml/db-doc-ref-in-repeat.xml
- webapp/tests/karma/ts/services/enketo-xml/db-doc-ref-in-repeats-with-local-references.xml
- webapp/tests/karma/ts/services/enketo-xml/db-doc-ref-outside-of-repeat.xml
- webapp/tests/karma/ts/services/enketo-xml/deep-file-fields.xml
- webapp/tests/karma/ts/services/enketo-xml/extra-docs-with-references.xml
- webapp/tests/karma/ts/services/enketo-xml/extra-docs-with-repeat.xml
- webapp/tests/karma/ts/services/enketo-xml/extra-docs.xml
- webapp/tests/karma/ts/services/enketo-xml/file-field.xml
- webapp/tests/karma/ts/services/enketo-xml/hidden-field.xml
- webapp/tests/karma/ts/services/enketo-xml/sally-lmp.xml
- webapp/tests/karma/ts/services/enketo-xml/visit-contact-summary.xml
- webapp/tests/karma/ts/services/enketo-xml/visit.xml
- webapp/tests/karma/ts/services/enketo.service.spec.ts
Updates the way the EnketoService finds `db-doc-refs` to support "closest" searches when the reference is relative or inside a repeat. 
medic/cht-core#6718
> Search for "closest" db-doc-ref in repeats

- sentinel/src/lib/scheduling.js
- sentinel/src/schedule/purging.js
- sentinel/src/schedule/reminders.js
- sentinel/tests/unit/lib/scheduling.js
- sentinel/tests/unit/schedule/index.js
- sentinel/tests/unit/schedule/purging.js
- sentinel/tests/unit/schedule/reminders.js
Fix missed jobs from schedules ahead of time less than 1 second.
medic/cht-core#6634
- The issue was fixed replacing the use of `later.setTimeout` by the native `setTimeout` and the milliseconds ahead that is calculated before hand, taking into account the difference between "now" and the schedule to not be less than 1 second.
- Add regression tests.
- Minor refactor: method `getSchedule` was repeated in the code twice.
Doing some tests I found a bit different scenario of why this happen. Contrary to what we think, timers are likely to be executed in less than 1 seconds, here is a small test that can be executed under the `sentinel` folder (because it has the `later` dependency in the `node_modules`):
```js
$ sudo date --set="2021-06-09T14:59:59.900Z" && node -e "
var later = …
```
> Fix missed jobs from schedules ahead of time less than 1 second

- webapp/src/ts/effects/contacts.effects.ts
- webapp/tests/karma/ts/effects/contacts.effects.spec.ts
Updates the ContactsEffects code for loading reports for the selectedContact to avoid recording loaded reports if the selectedContact changed while the reports were still loading (e.g. the user navigated to a different contact before the async call to load the reports completed).  
medic/cht-core#6485
> Prevent summary cards from previously selected contacts from being displayed

- api/src/auth.js
- api/src/middleware/authorization.js
- api/src/middleware/connected-user-log.js
- api/src/routing.js
- api/src/server-utils.js
- api/tests/mocha/auth.spec.js
- api/tests/mocha/middleware/authorization.spec.js
- api/tests/mocha/server-utils.spec.js
- tests/e2e/api/routing.js
- tests/page-objects/forms/default-delivery-report.po.js
- tests/utils.js
- webapp/src/ts/app.component.ts
Updates API code to:
1. Only consider 401s from CouchDB to be valid missing authentication
2. Throw other _session errors without changes
3. Malformed _session responses result in a 500 
4. Don't send 401s for missing userCtx, instead send the actual authentication error or a 500. 
5. Add a custom header to 401 responses that webapp checks for, and only when matched it would log users out. (prevents man-in-the-middle from logging users out with 401s)
medic/cht-core#7169
> Prevent users being logged out incorrectly

- admin/package-lock.json
- admin/package.json
This is a known issue between jQuery and Select2 where the search input isn't auto focusing in jQuery 3.6.0.
Reverting jQuery version to 3.5.1
https://github.com/medic/cht-core/issues/7173
> 7173 Reverting jQuery upgrade to 3.5.1

- docker-compose.yml
per #7206
This PR returns the ability to dynamically declare couchdb default password for `medic` user via the `DOCKER_COUCHDB_ADMIN_PASSWORD` environment variable.  If not declared, it will default to `password`. 
These two tests worked as expected:
* Set password to `foobar`: `DOCKER_COUCHDB_ADMIN_PASSWORD=foobar docker-compose up`
* Use default `password` as password: `docker-compose up`
Tested on `docker-compose` version `1.26.0, build d4451659`
> revert docker-compose to allow for env var for couch pass 

- webapp/src/ts/modules/contacts/contacts-edit.component.ts
- webapp/src/ts/services/enketo.service.ts
- webapp/src/ts/services/translate.service.ts
- webapp/tests/karma/ts/modules/contacts/contacts-edit.component.spec.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
Pass the contact form's title translation key to EnketoService to correctly translate the title on desktop view and keep a consistent behavior with the mobile view.  
To keep backwards compatibility, we fallback to the old code in case the translation key is not provided.
medic/cht-core#6392
> Pass contact form's title translation key to EnketoService

- tests/e2e/contacts/person-under-area.wdio-spec.js
- tests/e2e/search/search-contacts.wdio-spec.js
- tests/e2e/search/search-reports.wdio-spec.js
- tests/e2e/translations/message-format.wdio-spec.js
- tests/page-objects/admin/user.wdio.page.js
- tests/page-objects/contacts/contacts.wdio.page.js
- tests/page-objects/search/search.wdio.page.js
Test the Search Functionality
medic/cht-core#[80]
> 80-Test for Search functionality

- Gruntfile.js
- package-lock.json
- package.json
- scripts/e2e/start_webdriver.sh
This PR:
- Bumps up version to 3.11.3 
- Removes hard coded CHROMEDRIVER_VERSION
> Bump version to 3.11.3

- Gruntfile.js
- package-lock.json
- package.json
- scripts/e2e/start_webdriver.sh
This PR:
- Bumps version to 3.12.1
- Removes hard coded CHROMEDRIVER_VERSION
> Bump version to 3.12.1

- webapp/tests/karma/ts/services/contact-summary.service.spec.ts
Fixes the  contact summary unit test that started failing because it was asserting the text of an error message that originated from the browser (and so changes to the wording of the error message from the browser could cause the test to fail).  
> Fix flaking contact summary test

- TESTING.md
- tests/e2e/contacts/new-lineage-structure.wdio-spec.js
- webapp/src/ts/services/db-sync.service.ts
- webapp/tests/karma/ts/services/db-sync-retry.service.spec.ts
- webapp/tests/karma/ts/services/db-sync.service.spec.ts
Force the syncronization of the "meta" database along with the main db when user press _"Sync Now"_.
medic/cht-core#7121
> "Sync Now" also syncronize "meta" db

- admin/src/js/controllers/forms-xml.js
- admin/tests/unit/controllers/forms-xml.js
- tests/e2e/tasks/tasks-group.wdio-spec.js
Switches to returning and waiting for promises before assertions in admin unit test. 
Waits for the homeplace contact to load before switching to next test in tasks-group e2e test. 
> Fixes one flaky unit test and one flaky e2e test

- api/src/services/generate-xform.js
- api/tests/mocha/services/generate-xform.spec.js
Add clear message in the error logs when the command `xsltproc` used to process forms is not found.
medic/cht-core#6674
> Message in the error logs when xsltproc is not found

- .gitignore
- tests/e2e/contacts/new-lineage-structure.wdio-spec.js
- tests/e2e/contacts/person-under-area.wdio-spec.js
- tests/e2e/login/db-sync.wdio-spec.js
- tests/e2e/release/cht-config/generate-short-codes.wdio-spec.js
- tests/e2e/search/search-contacts.wdio-spec.js
- tests/e2e/search/search-reports.wdio-spec.js
- tests/e2e/sms/link-sms-to-patient.wdio-spec.js
- tests/e2e/tasks/task-due-dates.wdio-spec.js
- tests/e2e/tasks/tasks-group.wdio-spec.js
- tests/e2e/translations/message-format.wdio-spec.js
- tests/e2e/users/add-user.wdio-spec.js
- tests/utils.js
- tests/wdio.conf.js
Now each file doesn't need to revert db or delete users in the after. It's done in one place. 
@dianabarsan  I pulled this change out so that it could go in without working on getting the migrating done. 
> Add a common after hook. 

- demo-forms/repeat-translation.xml
- tests/e2e/contacts/person-under-area.wdio-spec.js
- tests/e2e/forms/repeat-form.wdio-spec.js
- tests/e2e/login/db-sync.wdio-spec.js
- tests/e2e/login/login-logout.wdio-spec.js
- tests/e2e/tasks/task-due-dates.wdio-spec.js
- tests/e2e/tasks/tasks-group.wdio-spec.js
- tests/page-objects/login/login.wdio.page.js
- tests/page-objects/reports/reports.wdio.page.js
- webapp/src/ts/services/enketo.service.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
Trigger a change on Enketo's form language selector, making Enketo swap in the form's inputs corresponding to the user's language.
medic/cht-core#6964
> Properly set Enketo form's language

- api/src/services/generate-xform.js
- api/tests/mocha/services/generate-xform.spec.js
Provide a clear message when the command `xsltproc` doesn't exist. This same problem was addressed in https://github.com/medic/cht-core/pull/7301 , but the workaround doesn't work in Node v8, and Node v14+, so improvements were made to also catch the errors properly in these versions.
medic/cht-core#6674
> Fix missed xsltproc error in different node versions

- .github/workflows/build.yml
The GH Action doesn't work well with jobs that have matrix strategies (https://github.com/fkirc/skip-duplicate-actions/issues/56), making some times to stuck PRs with jobs that aren't skipped nor scheduled.
So  I'm removing it for now, at least for cht-core that use matrix strategy to launch some jobs.
> Remove skip check in CI

- webapp/src/ts/modules/contacts/contacts-edit.component.ts
- webapp/src/ts/services/enketo-translation.service.ts
- webapp/tests/karma/ts/services/enketo-translation.service.spec.ts
This PR:
- Adds a trigger of Enketo beforeSave event when saving contact form, this will refresh the meta's fields (Reports already has it)
- Filters out the 1st level fields in contact form since it only process groups to be docs, this prevents incomplete data in couch's docs when saving the place. I found this behaviour while testing the meta fields. 
https://github.com/medic/cht-core/issues/6670
> 6670 - Meta's end field not refreshing when saving contact form

- tests/mobile/common/common.specs.js
- webapp/src/css/inbox.less
- webapp/src/css/mixins.less
- webapp/src/css/variables.less
- webapp/src/ts/actions/global.ts
- webapp/src/ts/app.component.html
- webapp/src/ts/app.component.ts
- webapp/src/ts/components/header/header.component.ts
- webapp/src/ts/modals/tour/tour-select.component.html
- webapp/src/ts/modals/tour/tour-select.component.ts
- webapp/src/ts/reducers/global.ts
- webapp/src/ts/selectors/index.ts
- webapp/tests/karma/ts/reducers/global.spec.ts
- webapp/tests/karma/ts/selectors/index.spec.ts
In this PR:
- Always display the tab's labels in the header bar and in the tour modal. 
- When having a small device (w: 400px) and there are more than 4 tabs in the header bar, the font size will be smaller.
- The javascript logic for minimalTabs is removed, CSS can handle the logic fine.
[medic/cht-core#7409](https://github.com/medic/cht-core/issues/7409)
View when having <= 4 tabs
View when having > 4 tabs (smaller font)
Tour, same size font no matter how many tabs since elements are stacking
> 7409 - Display the tabs' label

- DEVELOPMENT.md
- README.md
- config/default/GUIDE.md
fixed broken reference to old docs - `install.md`
medic/cht-core#7445
> fixed broken reference to old docs

- webapp/src/ts/services/enketo.service.ts
- webapp/tests/karma/ts/services/enketo-xml/db-doc-ref-broken-ref.xml
- webapp/tests/karma/ts/services/enketo-xml/db-doc-ref-same-as-repeat.xml
- webapp/tests/karma/ts/services/enketo.service.spec.ts
Treats cases where repeat elements have `db-doc` attribute, and have references to them. 
medic/cht-core#7485
> Fix xpath error when repeat is a db-doc

- webapp/src/ts/services/xml-forms.service.ts
- webapp/tests/karma/ts/services/xml-forms.service.spec.ts
This PR reorders the checks done before returning a form to take care of the bug below.
medic/cht-core#7021
> Form with truthy expression displayed despite permissions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/performance.md
- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
- scripts/release-notes/index.js
Now that the release notes were moved to https://github.com/medic/cht-docs in https://github.com/medic/cht-core/commit/61664b8544c1cc02ce32db7270d490f96cc89f7c the documention for creating the release notes on the issue templates is out of date.  
This PR just updates the release templates to include instructions for adding the release notes to https://github.com/medic/cht-docs.
Additionally, I have updated the `release-notes` script to add the proper front-matter to the new release notes pages.
> Update release issue templates regarding release documentation

- tests/e2e/login/token-login.wdio-spec.js
Removes the `after` function which only did a `revertDb` that was already done in `afterEach`.
medic/cht-core#7533
> Remove after all function that repeats work

- webapp/src/ts/modules/privacy-policy/privacy-policy.component.ts
- webapp/tests/karma/ts/modules/privacy-policies/privacy-policy.component.spec.ts
If something goes wrong accepting the privacy policy
we should catch the rejection and handle it gracefully.
medic/cht-core#7505
[description]
> Handle rejections from privacy policy accept

- api/src/controllers/users.js
- api/src/promise-utils.js
- api/src/routing.js
- api/src/server-utils.js
- api/src/services/users.js
- api/tests/mocha/services/users.spec.js
- tests/e2e/api/controllers/users.js
This PR adds a `createManyUsers` function to the `usersService` that works in a similar way as the `createUser` function.  
It can be used directly from the service `usersService.createManyUsers([])` within the API or from a standalone API route `POST /api/v2/users`
This is part of the work in progress for CSV bulk users import
[Related cht-docs PR](https://github.com/medic/cht-docs/pull/614)
medic/cht-core#7490
> Add API route to create many users

- tests/e2e/api/controllers/users.js
The `array-callback-return` eslint rule was merged to master before the `api/create-many-users` branch which breaks it. This branch fixes it.
> Fix eslint error in `tests/e2e/api/controllers/users.js`

- ddocs/medic/_attachments/translations/messages-en.properties
- webapp/src/js/enketo/constants.js
- webapp/src/js/enketo/widgets.js
- webapp/src/ts/components/snackbar/snackbar.component.ts
- webapp/src/ts/services/enketo.service.ts
- webapp/src/ts/services/update-service-worker.service.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
This PR:
- Increases the Enketo's upload file size limit to 30MB, leaving a couple of megas for other things.
- Adds a validation that sums all form's attachments and ensures it's not more than 30MB.
-  Shows error message to the user when limit is exceeded by using the snackbar.
https://github.com/medic/cht-core/issues/7529
> 7529 - Increase Enketo's upload file size limit and add validation when submitting form

- DEVELOPMENT.md
Updates documentation for the recommended NodeJS version for running the CHT in a development environment to be the required `12.x` (after the changes from https://github.com/medic/cht-core/pull/7257).
Updates were already made to the [doc site](https://github.com/medic/cht-docs/commit/70332ffa01624de14a49d52ea637306cee55a14b).  Note that technically I think we want to keep this dev environment split between the DEVELOPMENT.md (for cht-core development) and the [docs site](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/) (for app development).  There is not much duplication here and the purpose/audience of the two is different.
Also, I realize that all of this is changing soon (with `4.0.0`) but it seems appropriate to try to avoid confusion in the meantime by fixing …
> Fix node version in DEVELOPMENT.md

- DEVELOPMENT.md
Currently the recommended command from the DEVELOPMENT.md docs for running CouchDB on docker contains the `--rm` flag which causes the container to be removed as soon as it is stopped.  This conflicts with later documentation regarding the ability to start and stop the `medic-couchdb` container.  
This PR just removes the `--rm` flag and adds some doc on how the container can be removed.
[Forum post](https://forum.communityhealthtoolkit.org/t/errors-while-trying-to-run-core-locally/1767/2) for context.
> Fix docker run command for CouchDB in DEVELOPMENT.md

- tests/e2e/forms/repeat-form.wdio-spec.js
- tests/forms/repeat-translation-select.xml
- webapp/src/ts/services/enketo.service.ts
> Backport choice_filter xlsforms fix to 3.14.x

- config/default/app_settings.json
- webapp/src/ts/services/enketo-prepopulation-data.service.ts
- webapp/tests/karma/ts/services/enketo-prepopulation-data.service.spec.ts
enable the ability to get user's language in Enketo forms
medic/cht-core#7559
> make the user's language available in Enketo forms

- admin/src/js/services/db.js
- admin/src/js/services/session.js
- admin/tests/unit/services/db.js
- admin/tests/unit/services/session.js
- admin/tests/unit/services/telemetry.js
- admin/tests/utils.js
- api/src/public/login/script.js
- tests/e2e/navigation/bfcache.wdio-spec.js
- tests/page-objects/admin/user.wdio.page.js
- tests/wdio.conf.js
- webapp/src/ts/app.component.ts
- webapp/src/ts/services/session.service.ts
The bug had to do with the browser's bfcache, see [related documentation](https://web.dev/bfcache/)  
Essentially, it restored the page and its state from memory without even hitting the network. Showing a half logged in/half logged out state when coming back to the app from the login page with the browser's back button.
With this PR, when the app is restored from the bfcache, the session is validated once more to make sure the user doesn't get stuck in an impossible state.
medic/cht-core#7538
> 7538 - Validate cookie when restoring the app from the bfcache 

- package-lock.json
- package.json
Setting package version to `3.15.0-FR-bulk-user-upload`
https://github.com/medic/cht-core/issues/7611
> 7611 - Setting version to 3.15.0-FR-bulk-user-upload

- admin/src/js/controllers/upgrade-confirm.js
- admin/src/js/controllers/upgrade.js
- admin/tests/unit/controllers/upgrade.spec.js
- api/src/services/setup/upgrade.js
- api/src/services/setup/utils.js
- api/tests/mocha/services/setup/upgrade-steps.spec.js
- api/tests/mocha/services/setup/upgrade.spec.js
- api/tests/mocha/services/setup/utils.spec.js
Also set the upgrade as errored when the upgrade-service upgrade request fails. 
The alternative would have been to set an upgrade status that allows for a "complete" call retry (which is a bit more complicated). 
medic/cht-core#7601
> Upgrade endpoint payload change

- api/src/services/token-login.js
- api/src/services/users.js
- api/tests/mocha/services/token-login.spec.js
- api/tests/mocha/services/users.spec.js
I've also made a few edits to the [spreadsheet](https://docs.google.com/spreadsheets/d/13f5Tj6to8FK2uy1bC9ibfAxzuYQHCtzG7FOxpr92NpE/edit?usp=sharing) that adds a `token_login` field, validates its value (`TRUE`/`FALSE` only) and make the password generation dependent on this field.
medic/cht-core#7634
> Support login by SMS in bulk user upload

- api/package-lock.json
- api/package.json
- package-lock.json
- package.json
- webapp/src/ts/main.ts
`npm ci` hangs when installing `grunt-contrib-watch` because it's trying to fetch the remote heads and tags of the project's github repository
```
npm sill pacote Retrying git command: ls-remote -h -t git://github.com/scdf/grunt-contrib-watch.git attempt # 2
```
For an unknown reason, `git ls-remote -h -t git://github.com/scdf/grunt-contrib-watch.git` times out whereas `git ls-remote -h -t https://github.com/scdf/grunt-contrib-watch.git` works normally.
This change makes npm install `grunt-contrib-watch` and `openrosa-formlist` from github over https to avoid running into that timeout error.  
We should maybe raise an issue to @github
> Fix `npm ci` hanging

- webapp/src/css/inbox.less
- webapp/src/ts/components/navigation/navigation.component.html
This PR fix the issue 6028, clipping the the header of Task, Contact and Report tabs when the title is too long for mobile view.
1.  Use a mobile device, browser developer tools, then toggle device to mobile, or set view port width to 340px(more or less)
2.  Go to Task, Contact and/or Report tab
3.  Check if the overflow text of too long titles is replaced by ellipsis (...)
medic/cht-core#6028
> Title test too long for mobile 340px view port width - Apply ellipsis text overflow

- api/src/controllers/africas-talking.js
- api/src/controllers/credentials.js
- api/src/db.js
- api/src/migrations/restrict-access-to-vault-db.js
- api/src/routing.js
- api/src/services/rapidpro.js
- api/tests/mocha/controllers/credentials.js
- shared-libs/outbound/src/outbound.js
- shared-libs/settings/src/index.js
- shared-libs/settings/test/index.spec.js
- tests/e2e/africas-talking.js
- tests/e2e/api/routing.js
- tests/e2e/rapidpro.spec.js
- tests/utils.js
Replace the old way of storing credentials for authentication with third party services with a new method that supports clustered couchdb. Adds an API for setting the credentials and adds encryption at rest.
Also solves an issue where the plaintext password could be output in the log files.
medic/cht-core#5904
medic/medic-infrastructure#302
> Store credentials in a cluster safe way

- api/src/public/login/style.css
Switch the font family of the login page from "Helvetica Neue",Helvetica,Arial,sans-serif" to "Noto, sans-serif".
medic/cht-core#6382
> change the login font family to Noto sans serif

- webapp/src/css/inbox.less
This PR:
- Enables action's button labels in small font size (same as tab's label)
- Fixes `fa-stack` icon positioning by making it same height as the other icons in the action bar.
https://github.com/medic/cht-core/issues/7721
> 7721 - Display labels in action buttons when device is small

- api/src/services/records.js
- api/src/services/report/smsparser.js
- api/tests/mocha/services/records.spec.js
- api/tests/mocha/services/report/smsparser.spec.js
This is a further improvement to stripping invisible characters. Instead of always
removing invisible unicode characters, now they're only removed from non-string
fields so we don't modify values where the character may be desired.
medic/cht-core#7676
> Leave invisible characters in string fields

- admin/tests/unit/controllers/multiple-user.spec.js
- api/src/controllers/users.js
- api/src/services/users.js
Assign the newly created contact as primary contact of a place only if we're also creating the place
You can test this PR by:
- creating a user, its contact and its place all at once with the bulk user upload feature ([docs PR](https://github.com/medic/cht-docs/pull/727))
- making sure the newly created place has the newly created user's contact as primary contact
> Set contact as primary contact of a place with bulk user upload

- scripts/build/index.js
- tests/wdio-upgrade.conf.js
- export all container tags
- change e2e upgrade folder structure so docker doesn't report folder access errros
> Archv3 export all container tags

- webapp/src/ts/services/enketo.service.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
This PR fixes unit tests for multimedia forms.
- Adds validation to prevent navigation when using `windows.history` and `form.pages._getCurrentIndex()` returns undefined. This mainly because we want to test the feature and karma doesn't do well on navigation. Also, we can't mock `windows.history` because it's ready only. 
- Enables unit tests that were breaking karma
https://github.com/medic/cht-core/issues/7768
> 7768 - Fix unit tests for multimedia forms

- shared-libs/transitions/package-lock.json
- shared-libs/transitions/package.json
- shared-libs/transitions/src/lib/search.js
- shared-libs/transitions/src/transitions/user_replace.js
- shared-libs/transitions/test/unit/transitions/user_replace.js
- tests/e2e/default/enketo/forms/basic_form.xml
- tests/e2e/protractor/forms/user_replace.wdio-spec.js
- tests/integration/sentinel/transitions/user_replace.spec.js
- webapp/src/ts/services/db-sync.service.ts
- webapp/src/ts/services/transitions.service.ts
- webapp/src/ts/services/transitions/muting.transition.ts
- webapp/src/ts/services/transitions/transition.ts
- webapp/src/ts/services/transitions/user-replace.transition.ts
- webapp/src/ts/services/user-replace.service.ts
- webapp/tests/karma/ts/services/transitions.service.spec.ts
- webapp/tests/karma/ts/services/transitions/user-replace.transition.spec.ts
- webapp/tests/karma/ts/services/user-replace.service.spec.ts
Overview of logic flow:
- CLIENT (in `webapp`)
- `replace_user` form submitted  
- Triggers _client-side_ `user-replace.transition` to set `replaced` properties on user's _current_ contact
- `replaced.by` = `_id` of new contact
- `replaced.status` = "PENDING"
- Any additional reports submitted after the user is replaced (but before the client syncs) will be automatically re-parented by the client-side transition
- Client syncs.
- When syncing completes successfully, the `syncStatusChanged` function in the `user-replace.service` is triggered
- If the user has been replaced, and the status is set to "PENDING", then we know everything has now synced successfully (since that is what triggered `syncStatusChanged` in the first place
- Set the status on the original contact to "READY" and sync …
> Add client-side transition for offline user replace

- nginx/nginx.conf
- tests/integration/api/routing.spec.js
> Remove `server_name` from nginx config

- scripts/docker-helper/cht-docker-compose.sh
- scripts/docker-helper/docker-compose-developer-3.x-only.yml
This PR adds a compose filed called `docker-compose-developer-3.x-only.yml` and then updates the `cht-docker-compose.sh` script to know to look for that.  While this won't work for 3.x, it will unblock many developers who will still need to run 3.x instances for development for years to come.
See [docs PR  too](https://github.com/medic/cht-docs/pull/801)
> Add 3.x compose file for docker helper until we fix it or remove it

- scripts/build/cht-core.yml.template
1 line fix to allow passing in an env var to set the path for the mount point for `cht-nginx` service
medic/cht-core#7832
> Fix bringing own certs 

- api/src/server-utils.js
- api/tests/mocha/server-utils.spec.js
- tests/mobile/common/common.specs.js
- webapp/src/ts/constants.ts
Always ends errored requests. Updates client fetch to treat case where unsuccessful changes request has 200 status. 
medic/cht-core#7759
> Always end errored requests

- haproxy/entrypoint.sh
- scripts/build/cht-core.yml.template
Necessary for k8s hosted deploys. We need our healthcheck service address to be found on localhost and not docker service names.
[description]
> Configurable Healthcheck service address

- webapp/src/ts/constants.ts
- webapp/src/ts/services/auth.service.ts
- webapp/src/ts/services/session.service.ts
- webapp/tests/karma/ts/services/auth.service.spec.ts
- webapp/tests/karma/ts/services/session.service.spec.ts
- Adds explicit header to webapp session request
- don't default to permission denied when api is offline
medic/cht-core#2967
> Improve interaction between online webapp and api startup page

- shared-libs/settings/src/index.js
- shared-libs/settings/test/index.spec.js
- tests/utils.js
When secret is too short, concatenate with itself until we have desired string length. 
medic/cht-core#7840
> Allow for short CouchDb Secret

- .github/PULL_REQUEST_TEMPLATE.md
While we want to automate having the compose URLs added, we can manually add them until automation is put in place.  Further, automation will need the exact same change made before it will work, so this is a good first step to take regardless. 
medic/cht-core#7848
> Update template so PR submitters add compose URLs manually 

- api/tests/mocha/services/report/smsparser-compact-textform.spec.js
- shared-libs/message-utils/test/index.js
- shared-libs/rules-engine/package.json
- shared-libs/rules-engine/test/integration.spec.js
- shared-libs/rules-engine/test/provider-wireup.spec.js
Some of the unit test fail for me when I run them locally due to timezone issues. (The TZ of my local system is CST (UTC-6)).  It appears that all the unit test (`grunt unit`) run fine in UTC or in TZs that are > UTC (such as EAT), but they fail in TZ that are < UTC.  
The goal of this PR is to correct those issues so that the unit tests work regardless of the system TZ.
> Fix unit tests so they also run in TZs that are < UTC

- scripts/build/cht-core.yml.template
Since default `CERTIFICATE_MODE` is `OWN_CERT`, updates default `SSL_MOUNT_PATH` to match the folder where the self signed certificates are stored, and avoid generating them every time nginx container is recreated. 
When using other values for `CERTIFICATE_MODE`, this value must be changed to reflect the cert path in the container, if persistence is desired. 
medic/cht-core#7855
> Change default SSL_MOUNT_PATH to match the default CERTIFICATE_MODE

- scripts/add-local-ip-certs-to-docker-4.x.sh
this is a quick port of [the old script](https://github.com/medic/cht-core/blob/master/scripts/add-local-ip-certs-to-docker.sh) to support 4.x 
NA
> Shell script to get local IPs certs into a 4.x nginx instance

- couchdb/10-docker-default.ini
- tests/integration/.mocharc.js
- tests/integration/contacts/contact-edit.spec.js
- tests/integration/couchdb/couch_chttpd.spec.js
- tests/integration/couchdb/couch_httpd_script/Dockerfile
- tests/integration/couchdb/couch_httpd_script/docker-compose.yml
- tests/integration/couchdb/couch_httpd_script/index.js
- tests/utils.js
Also adds e2e test to check:
- that the endpoints are not available on the host network
- that the endpoints require authentication over docker network
- that the sharding is correct (2x win here). 
medic/cht-core#7864
* CHT Core: CHT_CORE_COMPOSE_URL
* CouchDB Single: COUCH_SINGLE_COMPOSE_URL
* CouchDB Cluster: COUCH_CLUSTER_COMPOSE_URL
> Expose couch-httpd port 5986 over docker network

- api/src/services/setup/upgrade-steps.js
- api/src/services/setup/utils.js
- api/tests/mocha/services/setup/upgrade-steps.spec.js
- api/tests/mocha/services/setup/utils.spec.js
medic/cht-core#7859
* CHT Core: https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7859-no-doc-error/docker-compose%2Fcht-core.yml
* CouchDB Single: https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7859-no-doc-error/docker-compose%2Fcht-couchdb.yml
* CouchDB Cluster: https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7859-no-doc-error/docker-compose%2Fcht-couchdb-clustered.yml
> Log error when no compose files were overwritten on upgrade complete

- .github/actions/update-staging-url-placeholders/index.js
With the change in #7879 , we need to update the deep links for the compose URLs from `builds` -> `builds_4`.
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:mrjones-staging-link-update/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:mrjones-staging-link-update/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:mrjones-staging-link-update/docker-compose/cht-couchdb-clustered.yml)
> Update deep staging link: builds -> builds_4

- couchdb/README.md
~~correct env var in couchdb readme as `CLUSTER_PEER_IPS` is deprecated in favor of `COUCHDB_SERVERS`~~ Saved for later - instead just fix missing opening quote.
* CHT Core: CHT_CORE_COMPOSE_URL
* CouchDB Single: COUCH_SINGLE_COMPOSE_URL
* CouchDB Cluster: COUCH_CLUSTER_COMPOSE_URL
> add missing opening quote on couch readme

- webapp/src/css/inbox.less
- webapp/src/ts/components/header/header.component.html
Partners have reported that users are accidentally logging themselves out when attempting to sync and then are unable to log back in.
So we moved sync component to top.
medic/cht-core#7900
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7900-reorder-hamburger-menu/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7900-reorder-hamburger-menu/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7900-reorder-hamburger-menu/docker-compose/cht-couchdb-clustered.yml)
> reorder hamburger menu, move sync to top

- api/package-lock.json
- api/src/services/settings.js
- api/tests/mocha/services/settings.spec.js
- shared-libs/.eslintrc
- shared-libs/transitions/src/transitions/index.js
- shared-libs/transitions/test/unit/transitions.js
- tests/integration/transitions/sentinel-api-transitions.spec.js
- fixes transition filter errors causing processing transitions to hang (forever)
- `deprecated-transitions` not gets `transitionsLib` from config
- adds unit test coverage for `deprecated-transitions`
- adds e2e test
medic/cht-core#7912
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7912-fix-deprecated-transitions-api/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7912-fix-deprecated-transitions-api/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7912-fix-deprecated-transitions-api/docker-compose/cht-couchdb-clustered.yml) …
> Fix deprecated-transitions api 

- ddocs/medic-db/medic/views/doc_summaries_by_id/map.js
- webapp/src/ts/modules/reports/reports-content.component.html
- webapp/src/ts/services/get-summaries.service.ts
- webapp/tests/mocha/unit/views/doc_summaries_by_id.spec.js
When a report has an empty value for their patient_id field, or lacks the field entirely, will not link to the patient contact in the UI, despite having a valid patient_uuid field.
Instructions for AT :
- before fix
Fill and submit a report form missing or empty patient_id field, but having valid patient_uuid field, you would notice there is no link to patient contact on the report detail ui.
- After fix
The report detail ui now have a link to the patient contact.
medic/cht-core#6994
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:6994-add-contact-link-to-report-ui/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:6994-add-contact-link-to-report-ui/docker-compose/cht …
> add contact link to report with  #6994

- api/src/controllers/privacy-policy.js
- api/tests/mocha/controllers/privacy-policy.spec.js
medic/cht-core#7841
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7841-refactor-privacy-controller/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7841-refactor-privacy-controller/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7841-refactor-privacy-controller/docker-compose/cht-couchdb-clustered.yml)
> Refactor privacy controller to use template service

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
- .github/workflows/build.yml
- admin/src/js/controllers/upgrade.js
- api/src/environment.js
- api/src/routing.js
- api/tests/mocha/routing.spec.js
- scripts/build/cht-core.yml.template
- scripts/ci/cleanup.js
- webapp/src/ts/services/enketo.service.ts
- webapp/src/ts/services/xml-forms.service.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
- webapp/tests/karma/ts/services/xml-forms.service.spec.ts
We catch all errors that happen when forms fail to load. However we don't register feedback docs when these crashes happen.
medic/cht-core#7525
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7525-register-failing-forms-feedback-doc/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7525-register-failing-forms-feedback-doc/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7525-register-failing-forms-feedback-doc/docker-compose/cht-couchdb-clustered.yml)
> add more log to XMLFormService to add precision in case form load fails

- api/src/services/settings.js
- api/tests/mocha/services/settings.spec.js
- shared-libs/.eslintrc
- shared-libs/transitions/src/transitions/index.js
- shared-libs/transitions/test/unit/transitions.js
- tests/integration/transitions/sentinel-api-transitions.spec.js
- fixes transition filter errors causing processing transitions to hang (forever)
- deprecated-transitions not gets transitionsLib from config
- adds unit test coverage for deprecated-transitions
- adds e2e test
#7912
(cherry picked from commit 8be4b33697b59098f969725b07ef9d0001119fee)
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7912-deprecated-transitions-4.0.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7912-deprecated-transitions-4.0.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7912-deprecated-transitions-4.0.x/docker-compose/cht-couchdb-clustered.yml)
The software is provided under …
> Fix deprecated-transitions endpoint blocking transitions from executing in API

- webapp/src/ts/services/feedback.service.ts
- webapp/src/ts/services/telemetry.service.ts
- webapp/tests/karma/ts/services/feedback.service.spec.ts
Add the device Id in feedback docs for debugging purposes.
Instructions for AT :
- Before fix : feedback docs do not include the device id
- After fix : feedback docs now include the device id
- How to test : Perform any action that would trigger feedback docs registration, then check if the doc contains a `deviceId` field
medic/cht-core#7127
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7127-record-device-id-in-feedback-docs/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7127-record-device-id-in-feedback-docs/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7127-record-device-id-in-feedback-docs/d …
> add device id to feedback docs #7127

- webapp/src/css/dropdown.less
- webapp/src/css/inbox.less
- webapp/src/css/private-vars.less
- webapp/src/css/sidebar-filter.less
- webapp/src/css/targets.less
- webapp/src/css/variables.less
Extracting color variables to another file, the ones that are not part of the palette.
The variables in private-vars.less are still accessible anywhere that imports variable.less, so the original idea doesn't work. However having them in 2 files might help devs to understand the right way of using them
https://github.com/medic/cht-core/issues/7862
* CHT Core: CHT_CORE_COMPOSE_URL
* CouchDB Single: COUCH_SINGLE_COMPOSE_URL
* CouchDB Cluster: COUCH_CLUSTER_COMPOSE_URL
> Extracting non-palette color vars to a new file

- api/src/services/report/smsparser.js
- api/tests/mocha/services/report/smsparser.spec.js
medic/cht-core#7933
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7933-fix-bsaggregate-error/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7933-fix-bsaggregate-error/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7933-fix-bsaggregate-error/docker-compose/cht-couchdb-clustered.yml)
> Always return form definition, even when some fields are invalid

- api/src/services/report/smsparser.js
- api/tests/mocha/services/report/smsparser.spec.js
#7933
(cherry picked from commit a0bcf5b6e83fe7b2af755d2a08a0dfb1987c0635)
> Always return some form definition 3.17.x

- api/src/services/report/smsparser.js
- api/tests/mocha/services/report/smsparser.spec.js
#7933
(cherry picked from commit a0bcf5b6e83fe7b2af755d2a08a0dfb1987c0635)
> Always return some form definition 3.16.x

- api/src/services/report/smsparser.js
- api/tests/mocha/services/report/smsparser.spec.js
#7933
(cherry picked from commit a0bcf5b6e83fe7b2af755d2a08a0dfb1987c0635)
* [Core](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7933-4.0.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7933-4.0.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:7933-4.0.x/docker-compose/cht-couchdb-clustered.yml)
> Always return some form definition 4.0.x

- .gitignore
- webapp/custom-webpack.config.js
For some reason this file was ending up in API but it's only relevant to webapp. Moved to proper location.
Also added it to gitignore because there's no need to commit it.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-analyzer-output-dir/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-analyzer-output-dir/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-analyzer-output-dir/docker-compose/cht-couchdb-clustered.yml)
> Fixes webpack analyzer output directory

- shared-libs/settings/src/index.js
- shared-libs/settings/test/index.spec.js
medic/cht-core#7926
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7926-better-decryption-message/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7926-better-decryption-message/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7926-better-decryption-message/docker-compose/cht-couchdb-clustered.yml)
> Gracefully handle decryption error

- api/src/controllers/favicon.js
- api/src/routing.js
- api/src/services/branding.js
- api/tests/mocha/services/branding.spec.js
Prevents an unhandled rejection for misconfigured branding. Also refactors the code into a service to make it able to be tested.
medic/cht-core#7976
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7976-handle-missing-branding-attachment/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7976-handle-missing-branding-attachment/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7976-handle-missing-branding-attachment/docker-compose/cht-couchdb-clustered.yml)
> Handle when branding doc is missing attachment

- scripts/set-default-contact/index.js
- scripts/set-default-contact/readme.md
Fixes  to #7987
* fixes readme to reference `index.js` vs `index.cjs`
* checks for  `place.contact` not being set
* downgrades use of User API from `/v2` to `/v1` so it works with earlier 3.x instances.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:set-default-contact-script/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:set-default-contact-script/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:set-default-contact-script/docker-compose/cht-couchdb-clustered.yml)
> Default contact script:  api v2 -> v1 change, work with sparser place objects

- tests/e2e/default/enketo/submit-form.wdio-spec.js
- tests/page-objects/default/enketo/generic-form.wdio.page.js
- tests/page-objects/default/reports/reports.wdio.page.js
- webapp/src/ts/services/enketo.service.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
Manually set the `editStatus` of an Enketo form to `false` before rendering the form. During the form initialization, the re-evaluation of some `calculate`s can cause the form to be marked as edited before receiving any input from the user.  
Resetting the `editStatus` prevents this behavior from affecting the cancel confirmation dialog behavior.  After this change, the cancel confirmation dialog should always be shown when the user has input data into the form (regardless of what calculations are done while initing the form).
Closes https://github.com/medic/cht-core/issues/7910
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7910_cancel_dialog/docker-compose/cht-core.yml)
* [CouchDB …
> 7910 Fix issue where cancel confirm dialog not shown

- admin/src/js/filters/build-version.js
- admin/src/templates/upgrade.html
- api/resources/translations/messages-en.properties
- api/src/services/deploy-info.js
- api/tests/mocha/services/deploy-info.spec.js
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/integration/api/routing.spec.js
- tests/page-objects/upgrade/upgrade.wdio.page.js
Changes `version` field to display `base_version` (like `4.2.0`) and adds a separate field that displays the full build version (which helps differentiate builds for the same branch from one another). 
medic/cht-core#8009
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8009-separate-admin-build-and-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8009-separate-admin-build-and-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8009-separate-admin-build-and-version/docker-compose/cht-couchdb-clustered.yml) …
> Separate base version from build in admin app upgrade page

- scripts/docker-helper-4.x/cht-docker-compose.sh
adds check for `docker-compose` in path and also shows actual LAN IP to Docker Helper 4.x and this should support too.
IP change means that instead of this with the `127` IP:
```
Success! "supervisor_chw_create" is set up:
https://127-0-0-1.my.local-ip.co:10446/ (CHT)
https://127-0-0-1.my.local-ip.co:10446/_utils/ (Fauxton)
```
We show the hosts actual `192` LAN IP:
```
Success! "supervisor_chw_create" is set up:
https://192-168-68-26.my.local-ip.co:10446 (CHT)
https://192-168-68-26.my.local-ip.co:10446/_utils/ (Fauxton)
```
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:add-lan-ip-to-docker-helper/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:add-lan-ip-to- …
> add LAN IP to Docker Helper 4.x

- tests/e2e/default-mobile/reports/delete.wdio-spec.js
- tests/e2e/default/login/renew-token.wdio-spec.js
- tests/e2e/default/reports/breadcrumbs.wdio-spec.js
- tests/e2e/default/reports/date-filter.wdio-spec.js
- tests/e2e/default/reports/delete.wdio-spec.js
- tests/e2e/default/reports/export.wdio-spec.js
- tests/e2e/default/reports/sidebar-filter.wdio-spec.js
This work focuses on e2e only. The code validation to prevent saving reports without `reported_date` will be done later after the teams prioritize work. 
- Fixes typos and format in e2e
- Fixes report_date property when creating reports.
https://github.com/medic/cht-core/issues/8030
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-reported-date-in-reports-e2e-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-reported-date-in-reports-e2e-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-reported-date-in-reports-e2e-tests/docker-compose/cht-couchdb-clustered.yml)
The software …
> Fix report date in reports e2e tests

- haproxy/Dockerfile
- haproxy/entrypoint.sh
Upgrades haproxy from an unmaintained version to the most recent LTS including a recent security patch.
medic/cht-core#8076
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8076-update-haproxy/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8076-update-haproxy/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8076-update-haproxy/docker-compose/cht-couchdb-clustered.yml)
> Update haproxy to latest LTS

- api/src/controllers/forms.js
- api/src/services/forms.js
- api/src/services/generate-xform.js
- api/tests/mocha/controllers/forms.spec.js
- api/tests/mocha/services/config-watcher.spec.js
- api/tests/mocha/services/forms.spec.js
- api/tests/mocha/services/generate-xform.spec.js
Leverages the fact that all forms' doc ids are prefixed with `form:` (source: https://github.com/medic/cht-conf/blob/ba6155395ee2f198fb847e3ce8e3dd2c28f3d1d8/src/lib/upload-forms.js#L73) , which makes it possible to use `_all_docs` to get a list of forms to update. 
medic/cht-core#7964
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7964-no-api-startup-query/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7964-no-api-startup-query/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7964-no-api-startup-query/docker-compose/cht-couchdb-clustered.yml) …
> Use _all_docs to get forms on API startup.

- haproxy/default_frontend.cfg
medic/cht-core#8130
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8130-haproxy-lua-lock/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8130-haproxy-lua-lock/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8130-haproxy-lua-lock/docker-compose/cht-couchdb-clustered.yml)
> fix(#8130): haproxy lua lock up

- .github/PULL_REQUEST_TEMPLATE.md
I find I sometimes have to look these up. I think having an example directly in the PR template will help adopting and correct use of semantic commit messages. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:semantic-pr-title-template/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:semantic-pr-title-template/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:semantic-pr-title-template/docker-compose/cht-couchdb-clustered.yml)
> chore: Update PR template to instruct about semantic PR titles / commit messages

- webapp/src/css/inbox.less
Fixes medic/cht-core#8177
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8177-more-options-screen-resize/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8177-more-options-screen-resize/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8177-more-options-screen-resize/docker-compose/cht-couchdb-clustered.yml)
> fix(#8177): More Options Menu visible in LHS when resizing from desktop to mobile

- webapp/src/ts/services/feedback.service.ts
#8136 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8136-feedback-log-timestamp/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8136-feedback-log-timestamp/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8136-feedback-log-timestamp/docker-compose/cht-couchdb-clustered.yml)
> feat(#8136): Add current timestamp into feedback document logs

- tests/page-objects/upgrade/upgrade.wdio.page.js
Cherry-picked from https://github.com/medic/cht-core/commit/536e72f16b79d73ac049562e47980bdb2111b6ca
medic/cht-core#8244
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:cherry-pick-8244-flexible-upgrade-beta-span/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:cherry-pick-8244-flexible-upgrade-beta-span/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:cherry-pick-8244-flexible-upgrade-beta-span/docker-compose/cht-couchdb-clustered.yml)
> chore(#8244): Fix upgrade e2e test when pushing a beta

- nginx/nginx.conf
#8214
(cherry picked from commit 2d9702c131a4ff054b4769e839aea47e7fadb190)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.x-nginx-timeout/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.x-nginx-timeout/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.x-nginx-timeout/docker-compose/cht-couchdb-clustered.yml)
> chore(#8214): Increase nginx timeout to 1h to match ALB timeout (#8283)

- tests/integration/couchdb/views/docs-by-replication-key.spec.js
Moves test to integration folder and makes it work with mocha and chai.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:chore_couch_view_test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:chore_couch_view_test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:chore_couch_view_test/docker-compose/cht-couchdb-clustered.yml)
> chore: move CouchDB's view test

- tests/e2e/default/about/about.wdio-spec.js
- tests/e2e/default/contacts/edit.wdio-spec.js
- tests/e2e/default/enketo/add-family.wdio-spec.js
- tests/page-objects/default/about/about.wdio.page.js
Also disables entire suite that had a single disabled test and was sometimes failing the `onBefore` call. 
medic/cht-core#8254
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8254-disable-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8254-disable-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8254-disable-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8254): skip should remove the primary contact from the clinic when the contact is deleted

- Gruntfile.js
- api/package-lock.json
- api/package.json
- package-lock.json
- package.json
- scripts/conflicts/package-lock.json
- scripts/conflicts/package.json
- scripts/package-lock.json
- scripts/package.json
- scripts/set-default-contact/package-lock.json
- scripts/set-default-contact/package.json
- sentinel/package-lock.json
- sentinel/package.json
- webapp/package-lock.json
- webapp/package.json
https://github.com/medic/cht-core/issues/8334
@dianabarsan I'm playing around with npm overrides which _should_ be a cleaner way of fixing things like the recent pouchdb node-fetch patch. Can you please have a look and let me know what you think? If it's an improvements I'll override a whole lot more dependencies to try and make dependabot happy.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:experiment-with-npm-overrides/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:experiment-with-npm-overrides/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:experiment-with-npm-overrides/docker-compose/cht …
> Experiment with npm overrides

- webapp/src/ts/components/fast-action-button/fast-action-button.component.html
- webapp/src/ts/components/panel-header/panel-header.component.html
- webapp/src/ts/components/panel-header/panel-header.component.ts
- webapp/src/ts/modules/reports/reports-more-menu.component.html
The tooltip's style overrides this component, so I changed the component's input name to be different from the HTML's title attribute. 
https://github.com/medic/cht-core/issues/8355
Test recording:
https://github.com/medic/cht-core/assets/66472237/0767ff81-de7e-40da-888f-9f9213c5aeaa
https://github.com/medic/cht-core/assets/66472237/54ccf1ef-7f8c-4f90-a58d-d47e3190aaa6
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8355_fix_review_title/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8355_fix_review_title/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8355_fix_review_title/docker-compose/cht- …
> fix(#8355): fix header in new modal

- tests/page-objects/default/admin/admin.wdio.page.js
My hunch is this test was failing because the click landed on a different element. 
Looking at the screenshot capture, where the click was supposed to enable the language, it appears as if the click landed on `download` instead. 
Mu guess is that the accordion was still in animation when the click was issued. Adding a timeout to delay the click. 
medic/cht-core#8357
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8357-disable-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8357-disable-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8357-disable-test/docker-compose/cht-couchdb-cluster …
> chore(#8357): Stabilize or disable languages flaky test

- scripts/build/index.js
- tests/e2e/default/telemetry/telemetry.wdio-spec.js
- webapp/src/ts/services/telemetry.service.ts
- webapp/tests/karma/ts/services/telemetry.service.spec.ts
medic/cht-core#8161
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8161-fix-telemetry-app-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8161-fix-telemetry-app-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8161-fix-telemetry-app-version/docker-compose/cht-couchdb-clustered.yml)
> fix(#8161): get telemetry app version from correct place.

- api/src/generate-service-worker.js
- api/tests/mocha/generate-service-worker.spec.js
- tests/e2e/default/service-worker/service-worker.wdio-spec.js
Adds login's images to service worker's cache.
medic/cht-core#8385
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8385_cache_login_img_service_worker/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8385_cache_login_img_service_worker/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8385_cache_login_img_service_worker/docker-compose/cht-couchdb-clustered.yml)
> fix(#8385): Adds login's images to service worker's cache

- package.json
Adds `postinstall` script. 
medic/cht-core#8367
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8367_fresh_start_helper/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8367_fresh_start_helper/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8367_fresh_start_helper/docker-compose/cht-couchdb-clustered.yml)
> fix(#8367): adds postinstall

- tests/integration/api/server.spec.js
- tests/utils/index.js
[description]
medic/cht-core#8404
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8404-ignore-logging-error/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8404-ignore-logging-error/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8404-ignore-logging-error/docker-compose/cht-couchdb-clustered.yml)
> chore(#8404): ignore error when test logging fails

- package-lock.json
- package.json
Older versions of cht-conf were [broken with Node ](https://github.com/medic/cht-conf/issues/538)17+ because Webpack 4.x [used the ](https://github.com/medic/cht-conf/pull/540/files#r1119345390)md4[ hash by default](https://github.com/medic/cht-conf/pull/540/files#r1119345390) and that has is no longer supported in Node 17.x
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-cht-conf-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-cht-conf-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-cht-conf-version/docker-compose/cht-couchdb-clustered.yml)
The software is …
> chore: Update cht-conf version from 3.15.2 to 3.18.3

- api/src/db.js
- api/src/services/generate-xform.js
- api/tests/mocha/db.spec.js
- api/tests/mocha/services/generate-xform.spec.js
- couchdb/10-docker-default.ini
- adds couchdb config `max_document_size` equal to 4GB
- raises couchdb `max_http_request_size` to 4GB
- adds a doc-by-doc retry on 413 errors to `db.saveDocs`
medic/cht-core#8457
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8457-api-forms-payload/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8457-api-forms-payload/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8457-api-forms-payload/docker-compose/cht-couchdb-clustered.yml)
> fix(#8457): increase couchdb doc size and retry saving forms

- nginx/nginx.conf
#8335
The list of ciphers in the nginx config are outdated. This PR updates them.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:nginx-cipher-fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:nginx-cipher-fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:nginx-cipher-fix/docker-compose/cht-couchdb-clustered.yml)
> Nginx change - use more modern cipher

- .browserslistrc
- package-lock.json
medic/cht-core#8159
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8159-set-browserslist/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8159-set-browserslist/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8159-set-browserslist/docker-compose/cht-couchdb-clustered.yml)
> chore(#8159): update browserslist to chrome 90

- .github/workflows/build.yml
- config/standard/test/contact-summary/nutrition/contact.json
- config/standard/test/contact-summary/nutrition/expected-output.json
medic/cht-core#8558
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.x-skip-protractor-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.x-skip-protractor-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.2.x-skip-protractor-tests/docker-compose/cht-couchdb-clustered.yml)
> chore(#8558): don't run Protractor e2e test suites

- .github/workflows/build.yml
- sentinel/src/lib/feed.js
- sentinel/tests/unit/lib/feed.js
medic/cht-core#8539
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8539-advance-seq-on-failed-tombstone/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8539-advance-seq-on-failed-tombstone/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8539-advance-seq-on-failed-tombstone/docker-compose/cht-couchdb-clustered.yml)
> fix(#8539): advance Sentinel seq on failed tombstone

- tests/utils/index.js
Currently, after integration or E2E tests, the test CHT instance does not get stopped/removed. So, running the tests locally results in an additional CHT instance that is constantly running on my local machine (that does not get torn down until the next time I run the e2e/integration tests).
This change will cause the containers to be stopped/removed by default.  However, if the `DEBUG` envar is set when running the tests, the containers will be retained.
(As a side note, I have included some documentation about the `DEBUG` flag in https://github.com/medic/cht-docs/pull/1185)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:tear_down_test_containers/docker-compose/cht-core.yml)
* [CouchDB …
> chore(tests): tear down test containers when e2e tests complete

- webapp/src/js/enketo/contact-saver.js
Note the base branch for this change is `enketo-service-refactor`. This contains a fix for https://github.com/medic/cht-conf-test-harness/issues/239 but should not be merged to main. I did not open a cht-core issue for this.
In production, we have [the typescript line](https://github.com/medic/cht-core/blame/cf4a1dde1fe2cca28f201c65f1b70bcd2dda6f6b/webapp/src/ts/services/contact-save.service.ts#L96C33-L96C43) `repeated?.child_data || [];`
In the `enketo-service-refactor` branch used by cht-conf-test-harness, we have this near enemy `repeated ? repeated.child_data : [];`
The behavior differs for defined values of `repeated` with an `undefined` value of `child_data`. This change reconciles the difference. 
* …
> fix(cht-conf-test-harness#239): update contact saver to fix error

- scripts/add-local-ip-certs-to-docker-4.x.sh
Code had been updated to pull `local-ip.medicmobile.org` certs, but comments and stdout updates to user were still using old `local-ip.co` domain
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:mrjones-plip-patch-1/docker-compose/cht-couchdb-clustered.yml)
> fix(docker-helper): update comments & stdout for local-ip.com -> local-ip.medicmobile.org

- tests/e2e/default/reports/sidebar-filter.wdio-spec.js
- webapp/src/ts/components/filters/facility-filter/facility-filter.component.html
- webapp/src/ts/components/filters/facility-filter/facility-filter.component.ts
- webapp/src/ts/components/filters/form-type-filter/form-type-filter.component.ts
- webapp/src/ts/modules/reports/reports.component.ts
- webapp/src/ts/services/place-hierarchy.service.ts
- webapp/src/ts/services/transitions/muting.transition.ts
- webapp/tests/karma/ts/components/filters/facility-filter.component.spec.ts
- webapp/tests/karma/ts/components/filters/form-type-filter.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports.component.spec.ts
- webapp/tests/karma/ts/services/place-hierarchy.service.spec.ts
- webapp/tests/karma/ts/services/transitions/muting.transition.spec.ts
- Preventing running old filter's code related to element scroll.
- Loading facilities in the filter only when the sidebar is open, and we haven't fetched the facilities yet. 
- We had to change how the default facility filter works
- Loading forms in the filter only when the sidebar is open, and we haven't subscribed to the forms yet.
https://github.com/medic/cht-core/issues/8576
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8576_slow_reports_tab/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8576_slow_reports_tab/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8576_slow_reports_tab/docker- …
> fix(#8576): slow reports tab

- tests/integration/sentinel/transitions/sentinel-transition-error-log.spec.js
[description]
- Update `app_settings.json` with an unknown or crashing transition. 
- Look at sentinel logs and verify there is a descriptive error. 
- Wait 5 minutes and verify the descriptive error is reprinted.
medic/cht-core #8235 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8235-e2e-for-sentinel-transition-error/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8235-e2e-for-sentinel-transition-error/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8235-e2e-for-sentinel-transition-error/docker-compose/cht-couchdb-clustered.yml)
The software is provided under AGPL-3.0. Contributions to …
> chore(#8235):add test to check sentinel error log

- tests/e2e/default/enketo/death-report.wdio-spec.js
- tests/e2e/default/enketo/edit-report-with-attachment.wdio-spec.js
- webapp/src/ts/modals/training-cards/training-cards.component.ts
- webapp/src/ts/modules/contacts/contacts-edit.component.ts
- webapp/src/ts/modules/contacts/contacts-report.component.ts
- webapp/src/ts/modules/reports/reports-add.component.ts
- webapp/src/ts/modules/tasks/tasks-content.component.ts
- webapp/src/ts/services/enketo.service.ts
- webapp/src/ts/services/xml-forms.service.ts
- webapp/tests/karma/ts/modals/training-cards/training-cards.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-report.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports-add.component.spec.ts
- webapp/tests/karma/ts/modules/tasks/tasks-content.component.spec.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
medic/cht-core#8589
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8589-430-backport/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8589-430-backport/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8589-430-backport/docker-compose/cht-couchdb-clustered.yml)
> fix(#8589): don't check form expression on edit for 4.3

- tests/e2e/default/enketo/death-report.wdio-spec.js
- tests/e2e/default/enketo/edit-report-with-attachment.wdio-spec.js
- webapp/src/ts/modals/training-cards/training-cards.component.ts
- webapp/src/ts/modules/contacts/contacts-edit.component.ts
- webapp/src/ts/modules/contacts/contacts-report.component.ts
- webapp/src/ts/modules/reports/reports-add.component.ts
- webapp/src/ts/modules/tasks/tasks-content.component.ts
- webapp/src/ts/services/enketo.service.ts
- webapp/src/ts/services/form.service.ts
- webapp/src/ts/services/xml-forms.service.ts
- webapp/tests/karma/ts/modals/training-cards/training-cards.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-edit.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-report.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports-add.component.spec.ts
- webapp/tests/karma/ts/modules/tasks/tasks-content.component.spec.ts
- webapp/tests/karma/ts/services/enketo-form.service.spec.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
- webapp/tests/karma/ts/services/form.service.spec.ts
medic/cht-core#8589
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8589-edit-form-with-expression/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8589-edit-form-with-expression/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8589-edit-form-with-expression/docker-compose/cht-couchdb-clustered.yml)
> fix(#8589): don't check form expression on edit

- tests/e2e/default/translations/incorrect-locale.wdio-spec.js
medic/cht-core#8535
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8535-fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8535-fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8535-fix/docker-compose/cht-couchdb-clustered.yml)
> fix(#8535): wait for service worker before waiting for the popup.

- scripts/docker-helper-4.x/cht-docker-compose.sh
This PR removes the `-it` flag to the `docker exec` calls in the docker helper script per this ticket:
> When running [some linux command], most of the time you don't need the `-it` (aka **STDIIN** via `--interactive and **STDOUT** via `--tty` for the psuedo-tty options)
This should be backwards compatible with linux/mac/wsl2 and be forwards compatible with git BASH where the error was discovered.
per medic/cht-core#8580
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8580-gitbash-docker-helper/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8580-gitbash-docker-helper/docker-compose/cht-couchdb.yml)
* [CouchDB …
> fix(#8580) fix docker exec calls to be git bash compatible

- tests/e2e/default/enketo/death-report.wdio-spec.js
- tests/e2e/default/enketo/edit-report-with-attachment.wdio-spec.js
- webapp/src/ts/modals/training-cards/training-cards.component.ts
- webapp/src/ts/modules/contacts/contacts-edit.component.ts
- webapp/src/ts/modules/contacts/contacts-report.component.ts
- webapp/src/ts/modules/reports/reports-add.component.ts
- webapp/src/ts/modules/tasks/tasks-content.component.ts
- webapp/src/ts/services/enketo.service.ts
- webapp/src/ts/services/form.service.ts
- webapp/src/ts/services/xml-forms.service.ts
- webapp/tests/karma/ts/modals/training-cards/training-cards.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-edit.component.spec.ts
- webapp/tests/karma/ts/modules/contacts/contacts-report.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports-add.component.spec.ts
- webapp/tests/karma/ts/modules/tasks/tasks-content.component.spec.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
- webapp/tests/karma/ts/services/form.service.spec.ts
#8589
(cherry picked from commit 5723cd3de99fad98450f475ced338ab22b502a2a)
medic/cht-core#8589
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.4.x-8589-cherry-pick/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.4.x-8589-cherry-pick/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.4.x-8589-cherry-pick/docker-compose/cht-couchdb-clustered.yml)
> fix(#8589): don't check form expression on report edit

- tests/scalability/launch-specification.json
- tests/scalability/prepare-ec2.sh
- tests/scalability/run_suite.sh
- tests/scalability/start-ec2-cht.sh
Old image wouldn't run `apt-get update` command. 
Adds wait for build to be on the market, as opposed to crafting some convoluted GH actions settings (tried and didn't work) to wait for a different workflow to be successful. 
medic/cht-core#8578
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8578-fix-scalability-suite/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8578-fix-scalability-suite/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8578-fix-scalability-suite/docker-compose/cht-couchdb-clustered.yml)
The software is provided under AGPL-3.0. Contributions to this project are accepted …
> fix(#8578): update scalability suite aws image

- scripts/cht-3x-node-upgrade/upgrade.sh
This PR enables partners who are running out of support CHT 3.x versions to upgrade their node versions in the container.  Node binary is written to `/srv` when upgraded, so persist across reboots.  The script existed before to help with #7957, but a partner wanted to ugprade to latest node `8.x`, so this PR expands the script to support both Node 12 and node 8, with backwards comparability to default to `12`
* deploy CHT3.x [locally](https://docs.communityhealthtoolkit.org/apps/guides/hosting/3.x/app-developer/)
* List running containers with `docker ps` - look for the `medic-os` one you just started. 
* Assuming it's called `cht3x-docker-medic-os-1`, you can get shell by calling `docker exec -it  cht3x-docker-medic-os-1 /bin/bash`
* download the script from this branch: `curl -o …
> chore(monkey-patch-node): Node 8 upgrade script

- nginx/nginx.conf
close medic/cht-core#8582
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8582-tidy-up-http2-warning/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8582-tidy-up-http2-warning/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8582-tidy-up-http2-warning/docker-compose/cht-couchdb-clustered.yml)
> fix(#8582): fixes http2 declaration warning

- webapp/src/js/enketo/medic-xpath-extensions.js
- webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js
[description]
medic/cht-core#8556
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8556-fix-xpath-extensions-tests-in-nzt/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8556-fix-xpath-extensions-tests-in-nzt/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8556-fix-xpath-extensions-tests-in-nzt/docker-compose/cht-couchdb-clustered.yml)
> fix(#8556): make xpath date extensions consistent

- tests/e2e/default/transitions/client-side-muting.wdio-spec.js
This feels brute force and if you have any better ideas I'm open to them, but essentially the test fails because it can't log in because an "update is available". This just forces a reload to the login page.
medic/cht-core#8375
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8375-retry-login/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8375-retry-login/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8375-retry-login/docker-compose/cht-couchdb-clustered.yml)
> chore(#8375): make muting test more reliable

- webapp/src/css/enketo/medic.less
- Adjusting Enketo label to content with `display: inline;`
The `display: inline-block;` or `display: block;` doesn't work for long text or fields in columns.
medic/cht-core#8669
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8669-enketo-label-fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8669-enketo-label-fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8669-enketo-label-fix/docker-compose/cht-couchdb-clustered.yml)
> fix(#8669): adjusting Enketo label to content

- tests/e2e/default/enketo/unauthorized-form.wdio-spec.js
- tests/e2e/default/sms/gateway.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/users/user.wdio.page.js
Backporting https://github.com/medic/cht-core/commit/956f81acd84166613daf11f7fc96637e961c1243
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:backporting-e2e-fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:backporting-e2e-fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:backporting-e2e-fix/docker-compose/cht-couchdb-clustered.yml)
> chore: backporting e2e fix

- webapp/src/css/private-vars.less
- webapp/src/css/targets.less
- webapp/src/css/theme.less
- webapp/src/css/variables.less
- webapp/src/ts/components/analytics-targets-progress/analytics-targets-progress.component.html
Update Target Page CSS to meet match Figma design 
#8686 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8686-update-target-ui-to-match-figma/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8686-update-target-ui-to-match-figma/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8686-update-target-ui-to-match-figma/docker-compose/cht-couchdb-clustered.yml)
> fix(#8686): update target UI to match figma

- tests/e2e/default/more-options-menu/online-user/permissions-enabled.wdio-spec.js
- tests/e2e/default/translations/incorrect-locale.wdio-spec.js
This PR contains:
- Delete `describe` inside `describe`
- Make all the tests independent
- Remove code inside the `describe` section
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:flaky-permission-enabled-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:flaky-permission-enabled-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:flaky-permission-enabled-test/docker-compose/cht-couchdb-clustered.yml)
> chore: Flaky test - permission-enabled and incorrect-locale

- haproxy/README.md
- tests/e2e/standard/wdio.conf.js
- tests/e2e/upgrade/wdio.conf.js
#8727 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8727-upgrade-for-macos/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8727-upgrade-for-macos/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8727-upgrade-for-macos/docker-compose/cht-couchdb-clustered.yml)
> chore(#8727): change docker socket path in upgrade e2e test

- api/package-lock.json
- tests/e2e/default/enketo/training-cards.wdio-spec.js
- webapp/src/ts/app.component.ts
- webapp/src/ts/modals/training-cards/training-cards.component.ts
- webapp/src/ts/services/training-cards.service.ts
- webapp/tests/karma/ts/services/training-cards.service.spec.ts
#8131
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8131-delay-training-cards-popup/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8131-delay-training-cards-popup/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8131-delay-training-cards-popup/docker-compose/cht-couchdb-clustered.yml)
> fix(#8131): display training cards after accepting privacy policies

- api/package-lock.json
- tests/e2e/default/contacts/fab-actionbar.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- webapp/src/ts/components/actionbar/actionbar.component.html
- webapp/src/ts/services/fast-action-button.service.ts
- webapp/tests/karma/ts/services/fast-action-button.service.spec.ts
Adds separate checks for `con_create_people` on contact page actionbar and FAB. 
#8730 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8730-fix-actionbar-permissions/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8730-fix-actionbar-permissions/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8730-fix-actionbar-permissions/docker-compose/cht-couchdb-clustered.yml)
> fix(#8730): fix permission checks for contact fab and actionbar

- tests/e2e/default/tasks/forms/home-visit.properties.json
- tests/e2e/default/tasks/tasks-breadcrumbs.wdio-spec.js
- tests/e2e/default/tasks/tasks.wdio-spec.js
- webapp/src/ts/services/enketo.service.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
#8745
(cherry picked from commit 34edb11f7f5b9a2f945945387e70a762098c8148)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8745-for-4.5.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8745-for-4.5.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8745-for-4.5.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#8745): don't evaluate form context when opening a task

- tests/e2e/default/tasks/forms/home-visit.properties.json
- tests/e2e/default/tasks/tasks-breadcrumbs.wdio-spec.js
- tests/e2e/default/tasks/tasks.wdio-spec.js
- webapp/src/ts/services/enketo.service.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
#8745
(cherry picked from commit 34edb11f7f5b9a2f945945387e70a762098c8148)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8745-fix-task-form-context-4.4.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8745-fix-task-form-context-4.4.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8745-fix-task-form-context-4.4.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#8745): don't evaluate form context when opening a task (#8746)

- shared-libs/user-management/src/libs/facility.js
- shared-libs/user-management/src/users.js
- shared-libs/user-management/test/unit/libs/facility.spec.js
- shared-libs/user-management/test/unit/users.spec.js
- tests/integration/api/controllers/users.spec.js
#8689
Upon quick check it was clear why this was performing so badly. This isn't a complete solution because it'll still perform badly with large numbers of users, but should be a significant improvement.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8689-low-hanging-fruit/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8689-low-hanging-fruit/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8689-low-hanging-fruit/docker-compose/cht-couchdb-clustered.yml)
> fix(#8689): only get needed facilities

- webapp/src/css/enketo/medic.less
The issue happens with the fields type `string`. This was introduced in 2016 in [this commit](https://github.com/medic/cht-core/commit/67965c28f34d191389acd5321e1cf2d7aaf2b1cf#diff-ffd309e5c33dabe1de84b768e50eada8718a478d4516e2bb033aeb52c6f09438R125)
#8585
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8585-fix-Asterisk-for-required-field-in-enketo/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8585-fix-Asterisk-for-required-field-in-enketo/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8585-fix-Asterisk-for-required-field-in-enketo/docker-compose/cht-couchdb-clustered.yml)
The software is …
> fix(#8585): fixing display of question label with summary appearance

- admin/src/js/controllers/upgrade.js
- admin/tests/unit/controllers/upgrade.spec.js
- api/src/controllers/upgrade.js
- api/tests/mocha/controllers/upgrade.spec.js
- api/tests/mocha/routing.spec.js
#8038 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8038-use-builds-url-from-env/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8038-use-builds-url-from-env/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8038-use-builds-url-from-env/docker-compose/cht-couchdb-clustered.yml)
>  fix(#8038): use builds url from env var

- webapp/src/ts/services/fast-action-button.service.ts
- webapp/tests/karma/ts/services/fast-action-button.service.spec.ts
#8118
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8118-dont-message-yourself/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8118-dont-message-yourself/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8118-dont-message-yourself/docker-compose/cht-couchdb-clustered.yml)
> fix(#8118): logged in user can message themselves

- tests/utils/index.js
#8780 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8780-remove-deprecated-rmdir/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8780-remove-deprecated-rmdir/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8780-remove-deprecated-rmdir/docker-compose/cht-couchdb-clustered.yml)
> chore(#8780): remove deprecated fs.rmdir usage

- webapp/tsconfig.base.json
Clearly this is not really necessary (I guess our linting config is already covering this?).  But, seems worth explicitly adding it here so we can check the box on https://github.com/medic/cht-core/issues/8437....
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:alwaysStrict/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:alwaysStrict/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:alwaysStrict/docker-compose/cht-couchdb-clustered.yml)
> chore(#8437): enable alwaysStrict in webapp tsconfig

- webapp/src/ts/services/indexed-db.service.ts
- webapp/src/ts/services/telemetry.service.ts
- webapp/tests/karma/ts/services/indexed-db.service.spec.ts
- webapp/tests/karma/ts/services/telemetry.service.spec.ts
- Adds service to return a list of db names when `indexedDB.databases()` isn't supported by the browser --- looks at Firefox 😒
#8777
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:indexdb-polyfill-firefox/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:indexdb-polyfill-firefox/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:indexdb-polyfill-firefox/docker-compose/cht-couchdb-clustered.yml)
> fix(#8777): IndexedDB polyfill

- shared-libs/rules-engine/src/pouchdb-provider.js
- shared-libs/rules-engine/test/pouchdb-provider.spec.js
PouchDb is notoriously slow to query views with a large number of keys. This is what happened when task recalculation was triggered. For users with large numbers of contacts, these requests became so heavy it took minutes to complete, sometimes crashing PouchDb entirely. 
This adds a short-circuit to the key loaded query, when there are more than  500 keys, and instead gets all rows and filters them. 
The limit of 500 can be changed. In my sample test with ~10000 reports, it took roughly the same time to get all rows vs query with 500 keys. 
Performance difference: 
| contacts | reports | Query style                   | duration | duration | duration | duration | AVG    | IDB Crashes |
|------------| ------ |-------------------------------|----------|----------|----------|----------|------ …
> perf(#8771): improve performance of task recalculation for many contacts

- tests/integration/api/routing.spec.js
Tiny change to get a more helpful message than [`expected null to be truthy`](https://github.com/medic/cht-core/actions/runs/7530916999/job/20498760460?pr=8756#step:17:1036) when these assertions fail
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:explanation-message-on-test-failure/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:explanation-message-on-test-failure/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:explanation-message-on-test-failure/docker-compose/cht-couchdb-clustered.yml) …
> chore: add an explanation message to 2 assertions in  `routing.spec.js`

- tests/e2e/default/targets/target-aggregates.wdio-spec.js
- tests/page-objects/default/contacts/contacts.wdio.page.js
- webapp/src/ts/modules/contacts/contacts-content.component.html
#8789 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8789-fix-target-aggregates-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8789-fix-target-aggregates-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8789-fix-target-aggregates-test/docker-compose/cht-couchdb-clustered.yml)
> fix(#8789): targets aggregates test is failing silently

- package-lock.json
- package.json
https://github.com/medic/cht-core/issues/8823
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:prep-for-4.6/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:prep-for-4.6/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:prep-for-4.6/docker-compose/cht-couchdb-clustered.yml)
> chore(#8823): update version to 4.6.0

- scripts/build/index.js
- scripts/build/versions.js
- scripts/ci/publish.js
- tests/e2e/default/telemetry/telemetry.wdio-spec.js
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/webapp.wdio-spec.js
- tests/page-objects/upgrade/upgrade.wdio.page.js
- tests/utils/index.js
#8901 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8901-branch_with/underscores|and-things/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8901-branch_with/underscores|and-things/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8901-branch_with/underscores|and-things/docker-compose/cht-couchdb-clustered.yml)
> chore(#8901): support underscores in branch names

- scripts/docker-helper-4.x/cht-docker-compose.sh
Fixes docker helper 4.x to have valid TLS on 1st run:
* refactors `get_is_container_running()` to be called `nginx_is_running()` (only nginx is ever used with it)
* adds an extra check that `nginx` returns a `301` as opposed to `000` or other failure, ensuring it is up and running
Per #8612
I narrowed down the bug to these three lines being called before `nginx` container was fully running:
```
docker exec -it $nginxContainerId bash -c "curl -s -o /etc/nginx/private/cert.pem https://local-ip.medicmobile.org/fullchain"  2>/dev/null
docker exec -it $nginxContainerId bash -c "curl -s -o /etc/nginx/private/key.pem https://local-ip.medicmobile.org/key"  2>/dev/null
docker exec -it $nginxContainerId bash -c "nginx -s reload"  2>/dev/null
```
By adding a `sleep 5` above these, I could get it to …
> chore(#8612) Fix docker helper to have valid TLS on 1st run

- .github/dependabot.yml
Attempt to enable dependabot to update dependencies automatically. This first version is a trial run. Further improvements would be to add configurations for the other package.json locations, add other registries like docker and gh actions, etc.
Configuration docs are here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-patch-2/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-patch-2/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:garethbowen-p …
> chore: enable dependabot to update dependencies

- webapp/src/ts/modules/contacts/contacts.component.ts
Refactor [formatContacts](https://github.com/medic/cht-core/blob/e16f5df6dfdf6437d9deb14a25f96f77cb84eb10/webapp/src/ts/modules/contacts/contacts.component.ts#L233) to reduce cognitive complexity.
Closes #8803 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8803-refactor-format-contacts/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8803-refactor-format-contacts/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8803-refactor-format-contacts/docker-compose/cht-couchdb-clustered.yml)
> fix(#8803): refactor formatContacts to reduce cognitive complexity

- api/src/auth.js
- api/tests/mocha/auth.spec.js
- haproxy/default_frontend.cfg
- tests/integration/haproxy/keep-alive-script/Dockerfile
- tests/integration/haproxy/keep-alive-script/cmd.sh
- tests/integration/haproxy/keep-alive-script/docker-compose.yml
- tests/integration/haproxy/keep-alive.spec.js
Node 19 adds keep-alive header to requests by default. This makes the `content-length` header very significant **and** important because it enables the server to know when one request has been fully received and another one is sent through the same connection. 
When authenticating a user, we take all headers from the original user's request and pass them to a GET /_session request, presumably so we don't have to filter out all the ways through which the user can authenticate (cookie, authorization etc). This meant that if the original request was a POST, and it had a `content-length` header, this header was also forwarded. This meant that when the connection would later be reused, the server (haproxy in this case) would truncate the previous's request `content-length` number of characters …
> fix(#8868): don't forward all headers for get requests

- api/src/auth.js
- api/tests/mocha/auth.spec.js
- tests/integration/haproxy/keep-alive-script/Dockerfile
- tests/integration/haproxy/keep-alive-script/cmd.sh
- tests/integration/haproxy/keep-alive-script/docker-compose.yml
- tests/integration/haproxy/keep-alive.spec.js
Node 19 adds keep-alive header to requests by default. This makes the content-length header very significant and important because it enables the server to know when one request has been fully received and another one is sent through the same connection. When authenticating a user, we take all headers from the original user's request and pass them to a GET /_session request, presumably so we don't have to filter out all the ways through which the user can authenticate (cookie, authorization etc). This meant that if the original request was a POST, and it had a content-length header, this header was also forwarded. This meant that when the connection would later be reused, the server (haproxy in this case) would truncate the previous's request content-length number of characters from the …
> fix(#8868): don't forward all headers for get requests (#8924)

- webapp/src/ts/modules/error/error.component.html
- webapp/src/ts/modules/error/error.component.ts
- webapp/src/ts/services/navigation.service.ts
- webapp/tests/karma/ts/modules/error/error.component.spec.ts
- webapp/tests/karma/ts/services/navigation.service.spec.ts
Adds a link to the exit error page and test coverage of new code. 
- When no navigation history (hard-reload) navigates to Home (message tab in default config)
- When 
- "access denied" and "no found" navigate to the previous page, shows `back` label to match error message context ([conversation with Nicole](https://medic.slack.com/archives/C02GME3BQE6/p1710791439222369?thread_ts=1710759172.451819&cid=C02GME3BQE6)).
- Any other error navigates to the previous page and shows `Reload application` label
Tests: 
https://github.com/medic/cht-core/assets/66472237/990b3dbc-84a3-46e9-926e-4f095748f729
<details>
<summary>Desktop view</summary>
</details>
<details>
<summary>Mobile view</summary>
</details>
#8844 
* …
> fix(#8844): adding link to exit error page

- webapp/src/css/enketo/medic.less
- Excludes `or-appearance-list-nolabel` from the style that displays options. 
<details>
<summary>Test video:</summary>
https://github.com/medic/cht-core/assets/66472237/e58ce706-37bd-4b78-917c-eac8c7e070ac
</details>
<details>
<summary>Screenshots mobile</summary>
</details>
#8939
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8939-grid-display-in-forms-broken/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8939-grid-display-in-forms-broken/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8939-grid-display-in-forms-broken/docker-compose/cht-couchdb-clustered.yml)
The software is provided …
> fix(#8939): display of Eketo's or-appearance-list-nolabel

- .browserslistrc
I have added a rationale comment for the .browserslistrc file. 
Addresses issue https://github.com/medic/cht-core/issues/8997
> doc(#8997): adds explanatory comment for .browserslistrc settings

- tests/e2e/default/contacts/contact-details.wdio-spec.js
- tests/factories/cht/reports/pregnancy.js
- tests/page-objects/default/contacts/contacts.wdio.page.js
- webapp/src/ts/modules/contacts/contacts-content.component.ts
- webapp/src/ts/services/contact-view-model-generator.service.ts
This PR fixes the unintended bug where the number of reports that would be retrieved for the contact and passed to the `contact-summary` calculation was [capped at 50](https://github.com/medic/cht-core/blob/3e126356afba2c75e68a5c70dab2eb8bf60e65c5/webapp/src/ts/services/search.service.ts#L133). So, the `contact-summary` for contacts associated with >50 reports, would not have the full context of all that contacts reports.
With this fix, for the sake of accuracy, we provide all the reports associated with that contact (limit of 500 reports).
<details>
<summary>Video showing created woman has pregnancy card when reports are less than 50</summary>
https://github.com/medic/cht-core/assets/2597305/d2d2b462-c91a-4509-952c-dd41645a2f71
</details>
<details>
<summary>Video showing pregnancy card …
> fix(#8815): fix contact-summary calculation to include all reports

- shared-libs/infodoc/src/infodoc.js
- shared-libs/infodoc/test/infodoc.js
- shared-libs/transitions/test/unit/finalize-transition.js
- tests/integration/infodocs/infodocs.spec.js
- tests/utils/index.js
Adds a new `run_date` field to infodoc transitions information. Date is saved in ISO format to be consistent with the other date fields in the doc (initial and latest replication date). 
Refactors / condenses old infodoc e2e tests to use async/await. 
#9012
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9012-infodoc-transition-date/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9012-infodoc-transition-date/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9012-infodoc-transition-date/docker-compose/cht-couchdb-clustered.yml) …
> feat(#9012): save transition run timestamp in infodoc

- package.json
- webapp/package.json
- webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js
- webapp/tests/mocha/unit/validate_doc_update.spec.js
Closes #9015
These tests should now work in any TZ! Honestly, I am not super concerned about the exact date comparison assertions since we are just deferring all the comparison logic to `moment`.  These assertions are a "nice to have" if/when we ever got to refactoring this logic, but in reality they are mostly asserting moment's functionality....
I confirmed that these tests all run in at least the following TZs:
- `Canada/Pacific`
- `Africa/Monrovia`
- `Pacific/Auckland`
- `UTC`
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9015_fix_tz_tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9015_fix_tz_tests/docker-compose/cht-couchdb.yml)
* [CouchDB …
> chore(#9015): update date diff xpath tests to work in any TZ

- tests/e2e/default/translations/incorrect-locale.wdio-spec.js
#8788 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8788-retry-before-and-after/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8788-retry-before-and-after/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8788-retry-before-and-after/docker-compose/cht-couchdb-clustered.yml)
> chore(#8788): use beforeEach so retries work

- tests/e2e/default/transitions/create-user-for-contacts.replace-user.wdio-spec.js
- tests/integration/api/controllers/monitoring.spec.js
- tests/integration/api/routing.spec.js
- tests/utils/index.js
#8338
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8338-e2e-session/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8338-e2e-session/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8338-e2e-session/docker-compose/cht-couchdb-clustered.yml)
> chore(#8338): use CouchDb session in e2e tests requests

- api/src/controllers/well-known.js
- api/src/routing.js
- api/tests/mocha/controllers/well-known.spec.js
- tests/integration/api/controllers/well-known.spec.js
- tests/integration/api/routing.spec.js
#8917
Have partners configure the `assetlinks` property in `app_settings.json` and the CHT will automatically serve it at `/.well-known/assetlinks.json` for them
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8917-serve-android-url-verification-assetlinks/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8917-serve-android-url-verification-assetlinks/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8917-serve-android-url-verification-assetlinks/docker-compose/cht-couchdb-clustered.yml)
> feat(#8917): Support Android app links verification

- shared-libs/server-checks/src/checks.js
- shared-libs/server-checks/test/checks.js
#9023 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9023-update-server-checks/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9023-update-server-checks/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9023-update-server-checks/docker-compose/cht-couchdb-clustered.yml)
> fix(#9024): assert couchdb version, ignore node version

- webapp/src/ts/services/android-api.service.ts
- webapp/tsconfig.base.json
https://github.com/medic/cht-core/issues/8437
Very minor change to set [`noImplicitThis` ](https://www.typescriptlang.org/tsconfig/#noImplicitThis) that is one more step in the direction of being able to enable `strict` mode.  
There were only two places where we were violating this rule and both of them were deliberate because we are using a shadowed `this` to be able to reference DOM elements.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8437_no_implicit_this/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8437_no_implicit_this/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8437_no_implic …
> chore(#8437): add `noImplicitThis` to webapp tsconfig

- tests/e2e/default/translations/incorrect-locale.wdio-spec.js
#8788
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8788-put-beforeeach-in-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8788-put-beforeeach-in-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8788-put-beforeeach-in-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#8788): move beforeeach to test for retry but also get debug info

- shared-libs/contacts/src/places.js
- shared-libs/contacts/test/unit/places.spec.js
- tests/integration/api/controllers/places.spec.js
Primary contacts of ancestors are no longer validated when creating a new place.
#8985
(cherry picked from commit 6bb7f6963aad9454c22d6836f5c4c7cff33398b9)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8985-4.7.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8985-4.7.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8985-4.7.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#8985): remove extra validation for parent place contact (#9027)

- shared-libs/search/src/search.js
- tests/e2e/default/contacts/infinite-scrolling.wdio-spec.js
- webapp/src/ts/modules/contacts/contacts.component.ts
- webapp/tests/karma/ts/modules/contacts/contacts.component.spec.ts
- Refactor `ngOnInit` to use `async/await` and add a unified `try/catch` block 
#9006 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9006-improve-contact-list-apdex/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9006-improve-contact-list-apdex/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9006-improve-contact-list-apdex/docker-compose/cht-couchdb-clustered.yml)
> perf(#9006): reduce contacts page_size and refactor ngOnInit

- api/src/services/setup/databases.js
- api/tests/mocha/services/setup/databases.spec.js
#9117 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9117-fix-users-ddoc-setting/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9117-fix-users-ddoc-setting/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9117-fix-users-ddoc-setting/docker-compose/cht-couchdb-clustered.yml)
> fix(#9117): use correct _users database name

- api/src/controllers/login.js
- api/tests/mocha/controllers/login.spec.js
#9122
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9122-detect-double-slash-redirection/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9122-detect-double-slash-redirection/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9122-detect-double-slash-redirection/docker-compose/cht-couchdb-clustered.yml)
> fix(#9122): detect unsafe redirection on login

- .github/ISSUE_TEMPLATE/z_release_major.md
This PR improves clarity of the release steps to make the release process smoother.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:improve-release-steps/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:improve-release-steps/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:improve-release-steps/docker-compose/cht-couchdb-clustered.yml)
> chore: add clarity to CHT release steps

- admin/tests/unit/services/update-user.spec.js
- tests/e2e/default/reports/breadcrumbs.wdio-spec.js
- tests/e2e/default/sms/messages-sender-data.wdio-spec.js
- tests/e2e/default/tasks/tasks-breadcrumbs.wdio-spec.js
- webapp/src/ts/modules/messages/messages.component.ts
- webapp/src/ts/modules/reports/reports.component.ts
- webapp/src/ts/modules/tasks/tasks.component.ts
- webapp/src/ts/services/extract-lineage.service.ts
- webapp/tests/karma/ts/modules/messages/messages.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports.component.spec.ts
- webapp/tests/karma/ts/modules/tasks/tasks.component.spec.ts
- webapp/tests/karma/ts/services/delete-docs.service.spec.ts
- webapp/tests/karma/ts/services/enketo.service.spec.ts
- webapp/tests/karma/ts/services/extract-lineage.service.spec.ts
- webapp/tests/karma/ts/services/form.service.spec.ts
- webapp/tests/karma/ts/services/send-message.service.spec.ts
- webapp/tests/karma/ts/services/transitions/create-user-for-contacts.transition.spec.ts
- webapp/tests/karma/ts/services/update-facility.service.spec.ts
- webapp/web-components/cht-form/src/app.module.ts
- webapp/web-components/cht-form/src/stubs/db.service.ts
- The scope of this work is breadcrumbs in Reports, Message and Tasks pages. 
- This PR implements the support for when a user has many facility IDs assigned. The rules are:
- If the user is online, leave breadcrumbs as they are. 
- If the user is offline but has multiple facilities, leave breadcrumbs as they are. 
- If the user is offline but only 1 facility is assigned, remove the last piece of the breadcrumb if the name is the same as the user's facility. 
- To assign more than one facility to a user:
- Go to couchdb, find the `_users` database, find the offline user `org.couchdb:<username>`
- Make `facility_id` an array and add the IDs: `"facility_id: [ "id-1", "id-2" ]`
- the facility should be at the same level in the hierarchy. 
- Go find the `medic` database, find the offline user …
> feat(#6543): add back breadcrumbs for users with many facilities

- tests/factories/cht/reports/pregnancy.js
The test `/tests/e2e/default/contacts/contact-details.wdio-spec.js` started being flaky on the CI as noted by #9155. 
The initlal lmp calculation was `const lmp = moment().subtract(3, 'months');`
My initial hypothesis and investigation suggested the `lmp` value was varying depending on the date the test is run and how many days the previous 3 months had. 
Therefore, the fix I came up with was to use a fixed date and then subtract a specific number of days so that lmp will always be 12 weeks. 
Unfortunately, the test is still flaky. 
- The original `const lmp = moment().subtract(3, 'months');`fails by giving 13 weeks instead of the expected 12 weeks
- The fix to use 👇, also fails giving 13 weeks instead of the expected 12 weeks
```
const fixedPregDate = moment('2024-06-03');
const lmp = …
```
> fix: update lmp calculation to fix flaky test

- tests/integration/couchdb/couch_chttpd.spec.js
- tests/integration/couchdb/couch_httpd_script/docker-compose.yml
- tests/integration/specs.js
#9179
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9179-fix-integration-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9179-fix-integration-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9179-fix-integration-test/docker-compose/cht-couchdb-clustered.yml)
> fix(#9179): updates docker network integration test

- .github/workflows/build.yml
- ddocs/.eslintrc
- ddocs/users-meta-db/users-meta/views/device_by_user/map.js
- ddocs/users-meta-db/users-meta/views/device_by_user/reduce.js
- package-lock.json
- package.json
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/wdio.conf.js
- tests/factories/cht/reports/pregnancy.js
- tests/integration/couchdb/couch_chttpd.spec.js
- tests/integration/couchdb/couch_httpd_script/docker-compose.yml
#9166
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9166-4.7.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9166-4.7.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9166-4.7.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#9166): backwards compatible couchdb views (4.7.x)

- .github/workflows/build.yml
- ddocs/.eslintrc
- ddocs/users-meta-db/users-meta/views/device_by_user/map.js
- ddocs/users-meta-db/users-meta/views/device_by_user/reduce.js
- package-lock.json
- package.json
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/wdio.conf.js
- tests/factories/cht/reports/pregnancy.js
- tests/integration/couchdb/couch_chttpd.spec.js
- tests/integration/couchdb/couch_httpd_script/docker-compose.yml
#9166
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9166-4.8.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9166-4.8.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9166-4.8.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#9166): backwards compatible couchdb views (4.8.x)

- haproxy/Dockerfile
- haproxy/tests/compose.yml
- haproxy/tests/with_mock.bats
- package.json
Haproxy published a new 2.6.18 image today, which breaks one of our unit tests. It might also break behavior.
Fixing the image version to `2.6.17` resolves the issue and makes sure we're having expected behavior. 
#9187 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-fix-haproxy-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-fix-haproxy-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-fix-haproxy-test/docker-compose/cht-couchdb-clustered.yml)
> fix(#9187): fix haproxy version to 2.6.17

- haproxy/Dockerfile
- haproxy/tests/compose.yml
- package.json
- tests/e2e/upgrade/upgrade.wdio-spec.js
Fixes haproxy image to 2.6.17
Skips waiting for deployment complete when upgrading from an old version. 
#9187
#9186
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-4.7.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-4.7.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-4.7.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#9187): fix haproxy version to 2.6.17 - 4.7.x

- haproxy/Dockerfile
- haproxy/tests/compose.yml
- package.json
- tests/e2e/upgrade/upgrade.wdio-spec.js
Fixes haproxy image to 2.6.17
Skips waiting for deployment complete when upgrading from an old version. 
#9187
#9186
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-4.8.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-4.8.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9187-4.8.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#9187): fix haproxy version to 2.6.17 - 4.8.x

- tests/e2e/upgrade/upgrade.wdio-spec.js
#9186 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9186-skip-deployment-complete/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9186-skip-deployment-complete/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9186-skip-deployment-complete/docker-compose/cht-couchdb-clustered.yml)
> fix(#9186): skip waiting for deployment complete

- api/src/controllers/person.js
- api/tests/mocha/controllers/person.spec.js
- shared-libs/cht-datasource/src/local/person.ts
- shared-libs/cht-datasource/test/local/person.spec.ts
- tests/integration/api/controllers/person.spec.js
Result of https://github.com/medic/cht-core/issues/9065#issuecomment-2186704076
Closes https://github.com/medic/cht-core/issues/9065
Basically this PR just adds a check to the REST api so that only online users (user with full DB access) can call the `person` endpoint. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9065_block_offline_users/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9065_block_offline_users/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9065_block_offline_users/docker-compose/cht-couchdb-clustered.yml) …
> fix(#9065): block offline users from using api/v1/person endpoint

- admin/src/js/controllers/edit-user.js
- admin/tests/unit/controllers/edit-user.spec.js
- config/default/app_settings.json
- ddocs/medic-db/medic-client/validate_doc_update.js
- ddocs/medic-db/medic/validate_doc_update.js
- webapp/src/ts/modules/contacts/contacts-more-menu.component.ts
Type casts users with existing `string` `facility_id` to `Array`  `facility_id` that can be loaded in the edit form of the Admin app. 
Closes #9203 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:facility-backward-compatibility/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:facility-backward-compatibility/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:facility-backward-compatibility/docker-compose/cht-couchdb-clustered.yml)
> fix(#9203): add facility_id backward compatibility in admin app

- .github/workflows/build.yml
- .gitignore
- package-lock.json
- shared-libs/cht-datasource/package.json
Fixes #9127
Generate [TypeDoc](https://typedoc.org/) from the commented source code and push it to [medic/cht-datasource](https://github.com/medic/cht-datasource) to live at https://docs.communityhealthtoolkit.org/cht-datasource.
So once this PR gets merged to master, CI will publish the generated docs every time a PR gets merged to master and a branch build gets published.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9127-document-cht-datasource/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9127-document-cht-datasource/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9127-document-cht-data …
> docs(#9127): document cht-datasource

- webapp/src/ts/components/sender/sender.component.html
The  problem was when `sentBy` is `true`, the `span` inside the `ng-template` with `#noLinkLabel` was being rendered yet it should render when `sentBy` is `false`. 
Closes #9156 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9156-duplicate-name/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9156-duplicate-name/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9156-duplicate-name/docker-compose/cht-couchdb-clustered.yml)
> fix(#9156): fix duplicate name in reports

- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/wdio.conf.js
- tests/e2e/upgrade/webapp.wdio-spec.js
- tests/page-objects/default/about/about.wdio.page.js
Add a scenario to the individual test `should upgrade to current branch` to verify that it is possible to update from a specific build version, `master` branch it is being used for this test.
Related to issue #9123 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-from-build-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-from-build-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-from-build-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9123): add scenario that update from build version to 'master'

- scripts/docker-helper-4.x/cht-docker-compose.sh
#9243
The `-it` options from `docker exec -it` were added out of habit from using that docker command but is not needed in this context and is actually causing issues when scripting with docker helper
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9243-fix-docker-helper-certificate/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9243-fix-docker-helper-certificate/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9243-fix-docker-helper-certificate/docker-compose/cht-couchdb-clustered.yml)
> fix(#9243): remove unneeded options when installing certificate in docker helper

- tests/e2e/upgrade/upgrade-master.wdio-spec.js
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/wdio.conf.js
- tests/page-objects/upgrade/upgrade.wdio.page.js
Fixes upgrade page hitting header instead of upgrade button when there are many releases to choose from. 
Changes how we select the "latest" release, so it's always the version that is released before the version we test. 
#9218 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9218-fix-upgrade-on-release-tag/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9218-fix-upgrade-on-release-tag/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9218-fix-upgrade-on-release-tag/docker-compose/cht-couchdb-clustered.yml)
The software is provided under AGPL-3.0. Contributions to this project are accepted …
> fix(#9218): fix upgrade e2e test for tags

- webapp/src/ts/effects/contacts.effects.ts
- webapp/tests/karma/ts/effects/contacts.effects.spec.ts
Fixes bug and updates unit tests to verify default value, `contact_type` and `type`.
#9264
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-telemetry-granularity-contact-details/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-telemetry-granularity-contact-details/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-telemetry-granularity-contact-details/docker-compose/cht-couchdb-clustered.yml)
> fix(#9264): telemetry granularity for contact details page

- webapp/src/ts/components/filters/analytics-filter/analytics-filter.component.ts
- webapp/tests/karma/ts/components/filters/analytics-filter.component.spec.ts
#9275
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-targets-dropdown/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-targets-dropdown/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-targets-dropdown/docker-compose/cht-couchdb-clustered.yml)
> fix(#9275): set targets' dropdown on navigation

- tests/e2e/upgrade/admin-user.wdio-spec.js
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/e2e/upgrade/webapp.wdio-spec.js
Closes #9233
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9233-clean-up-and-organize-upgrade-e2e-folder/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9233-clean-up-and-organize-upgrade-e2e-folder/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9233-clean-up-and-organize-upgrade-e2e-folder/docker-compose/cht-couchdb-clustered.yml)
> chore(#9233): clean up and organize e2e tests: folder /upgrade

- scripts/docker-helper-4.x/cht-docker-compose.sh
This PR:
* updates docker helper to use `docker compose` instead of `docker-compose`
* helps users by defending against `docker compose` not being installed
per #8781
Testing:
* I tested this by spinning up an ubuntu 18 VM and running `apt install docker.io docker-compose` which installed it like this:
```
$ docker version
Client:
Version:           24.0.7
[SNIP]
$ docker-compose version
docker-compose version 1.25.0, build unknown
[SNIP]
$ docker compose version
docker: 'compose' is not a docker command.
```
* then I tested this branch on that old VM to make sure it failed to run (as expected)
* I also tested this branch on Fedora 39 bluefin which had modern docker 2.x  and it succeeded (as expected)
* …
> fix(#8781):  docker helper to use docker compose v2x

- api/Dockerfile
- scripts/build/index.js
- sentinel/Dockerfile
1. The problem is that the `cp -r` doesn't preserve symbolic links. So I changed to this `await exec('cp', ['-a', '${workingDir}/node_modules', service]);`
2. Then, the docker files still need the node-modules and the shared-libs folders to find the dependencies during run time. I'm copying those folders into the working directory of the container. 
#9106
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fixes-e2e-for-local-run/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fixes-e2e-for-local-run/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fixes-e2e-for-local-run/docker-compose/cht-couchdb- …
> chore(#9106): fix dependencies for e2e tests that runs in local environment

- shared-libs/validation/test/validations.js
#9315
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9315-fix-badly-mocked-unit-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9315-fix-badly-mocked-unit-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9315-fix-badly-mocked-unit-test/docker-compose/cht-couchdb-clustered.yml)
> chore(#9315): fix test to use promises not callbacks

- api/src/generate-service-worker.js
- api/src/services/config-watcher.js
- api/src/services/deploy-info.js
- api/tests/mocha/generate-service-worker.spec.js
- api/tests/mocha/services/config-watcher.spec.js
- api/tests/mocha/services/deploy-info.spec.js
- tests/e2e/default/service-worker/service-worker.wdio-spec.js
- webapp/src/ts/services/feedback.service.ts
- webapp/src/ts/services/version.service.ts
- webapp/tests/karma/ts/services/feedback.service.spec.ts
- webapp/tests/karma/ts/services/version.service.spec.ts
Uses service worker deploy-info to get version in feedback service. 
#9294 
#8645
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9294-feedback-doc-on-couch-crash/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9294-feedback-doc-on-couch-crash/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9294-feedback-doc-on-couch-crash/docker-compose/cht-couchdb-clustered.yml)
> fix(#9294): adds deploy-info to service worker

- .github/workflows/build.yml
#9097
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9097-load-docker-images-for-external-contributors/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9097-load-docker-images-for-external-contributors/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9097-load-docker-images-for-external-contributors/docker-compose/cht-couchdb-clustered.yml)
> chore(#9097): load docker images for external contributors

- tests/e2e/default/reports/sidebar-filter.wdio-spec.js
- tests/page-objects/default/reports/reports.wdio.page.js
[We removed the old search and filters](https://github.com/medic/cht-core/pull/9326). These features are well covered with unit tests, but we need automation tests for form, facility, and status filters. This PR adds basic test cases for those three filters.  
- There are already automation for [Reports' search](https://github.com/medic/cht-core/blob/master/tests/e2e/default/reports/search-reports.wdio-spec.js) and [Contacts' search](https://github.com/medic/cht-core/blob/master/tests/e2e/default/contacts/search-contacts.wdio-spec.js)
- There is already automation [for the date filter](https://github.com/medic/cht-core/blob/master/tests/e2e/default/reports/sidebar-filter.wdio-spec.js)
#8181
https://github.com/medic/care-teams/issues/148
* …
> feat(#8181): add automation tests for report's filter

- api/src/controllers/person.js
- api/tests/mocha/controllers/person.spec.js
- shared-libs/cht-datasource/src/remote/person.ts
- shared-libs/cht-datasource/test/remote/person.spec.ts
- tests/integration/api/controllers/person.spec.js
Closes #9389 
https://github.com/medic/cht-docs/pull/1509
Simple change to update the `personType` query parameter name on the `api/v1/person` endpoint to just be `type`.  
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9389_fix_person_type_param/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9389_fix_person_type_param/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9389_fix_person_type_param/docker-compose/cht-couchdb-clustered.yml)
> fix(#9389): update api/v1/person query param from personType to type

- package-lock.json
- package.json
- tests/e2e/default/transitions/client-side-muting.wdio-spec.js
- webapp/package-lock.json
- webapp/package.json
#9395 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9395-move-dependency/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9395-move-dependency/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9395-move-dependency/docker-compose/cht-couchdb-clustered.yml)
> fix(#9395): move moment-locales-webpack-plugin dependency to webapp

- webapp/src/css/inbox.less
Removing the line-height seems to fix it 
https://github.com/user-attachments/assets/2585d0a1-a73d-403f-b287-fb3f87ff4b76
Closes #9291 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9291-align-icon/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9291-align-icon/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9291-align-icon/docker-compose/cht-couchdb-clustered.yml)
> fix(#9291): align fab icon in mobile view

- webapp/src/css/badge.less
- webapp/src/css/icon.less
- webapp/src/css/inbox.less
- webapp/src/css/material.less
- webapp/src/css/old-nav.less
- webapp/src/css/private-vars.less
- webapp/src/css/variables.less
<details>
<summary>selected icon and label have color #FFFFFF</summary>
</details>
<details>
<summary>Unselected icon and label have color #A7A9AC </summary>
</details>
<details>
<summary>Snackbar is above FAB and adjusts when Tab navigation is not present</summary>
https://github.com/user-attachments/assets/3207e6d7-3ad9-4b76-af6a-66d3c890a901
</details>
<details>
<summary>Removed the white outline for the notification dot </summary>
</details>
<details>
<summary>Made the highlight pill consistent size </summary>
</details>
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:move-nav-feedback/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:move-nav-feedback/docker …
> chore(#9327): adjust new nav styles after manual testing

- shared-libs/user-management/src/users.js
- shared-libs/user-management/test/unit/users.spec.js
- tests/integration/api/controllers/users.spec.js
#9433 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9433-fix-users-contact-update/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9433-fix-users-contact-update/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9433-fix-users-contact-update/docker-compose/cht-couchdb-clustered.yml)
> fix(#9433): use existent facility when updating user

- sentinel/src/schedule/outbound.js
- sentinel/tests/unit/schedule/outbound.spec.js
This fixes a bug where outbound tasks that are not yet due are removed because of the cron setting.
closes #8947 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8947-outbound-push-cron-config-bug/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8947-outbound-push-cron-config-bug/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8947-outbound-push-cron-config-bug/docker-compose/cht-couchdb-clustered.yml)
> fix(#8947): filter out valid outbound tasks with empty configs because they are not due

- haproxy/tests/Makefile
- haproxy/tests/compose.yml
- haproxy/tests/with_mock.bats
Haproxy port in unit test was conflicting with existing CouchDB container (https://github.com/medic/cht-core/blob/master/.github/workflows/build.yml#L62)
I honestly don't know how this worked before. 
#9446
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9446-haporxy-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9446-haporxy-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9446-haporxy-test/docker-compose/cht-couchdb-clustered.yml)
> fix(#9446): change haproxy port in unit test

- webapp/src/css/material.less
This PR closes https://github.com/medic/care-teams/issues/182
We still have the ripple-effect when clicking the menu-icon to open the Sidebar but importantly, when you close the Sidebar menu the shadow is not there. 
<details>
<summary>Video </summary>
https://github.com/user-attachments/assets/d899a776-34cf-480f-bc58-29befef77b16
</details>
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:182-hamburger-icon/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:182-hamburger-icon/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:182-hamburger-icon/docker-compose/cht-couchdb-clustered.yml)
The software …
> chore(#9327): remove shadow after clicking hamburger menu

- webapp/src/css/old-nav.less
This fixes feedback from Michael
- Adjusts the positioning of the unread notification 
- Adjusts the tab's width 
- Adjusts padding on pages without list - old nav
Testing
<details> <summary>The unread notification </summary>
</details> 
<details> <summary> The tab's width </summary>
https://github.com/user-attachments/assets/c16db214-e063-4c02-b804-f589e3bf6b1e
</details>
#9327
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9327-tab-nav-feedback/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9327-tab-nav-feedback/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9327-tab-nav-feedback/docker-co …
> fix(#9327): adjustments in old tab navigation

- webapp/src/css/content-list.less
- webapp/src/css/inbox.less
- webapp/src/css/material.less
- webapp/src/css/modal.less
- webapp/src/css/old-nav.less
- webapp/src/css/theme.less
- The filter's border colored was removed.
- Desktop - Aligned top bar title with the first element of the list icon/checkbox/text
- Mobile - Aligned top bar title with the secont element of the list icon/text
- Fixed letter spacing to mat components
- Fixed padding of about, user, privacy policy and testing pages
- Old nav - removes margin bottom of about, user, privacy policy and testing pages
Testing:
<details><summary> Old nav </summary>
https://github.com/user-attachments/assets/ff1560eb-5a84-4df7-8398-2531b95ef59b
https://github.com/user-attachments/assets/ebed931e-bece-4c2f-84f8-54bcc0334894
</details>
<details><summary> New nav  </summary>
https://github.com/user-attachments/assets/f858d60d-8d92-4dcb-9a72-664ae139a9a5
</details>
#9327
* …
> fix(#9327): spacing in new nav and old nav

- scripts/add-local-ip-certs-to-docker-4.x.sh
- scripts/docker-helper-4.x/cht-docker-compose.sh
In the forums folks have [had issues](https://forum.communityhealthtoolkit.org/t/using-sudo-with-docker-helper-installing-tls-certs/3979/9?u=mrjones) getting TLS certs downloaded in docker helper.  This PR:
* updates [add cert script](https://github.com/medic/cht-core/blob/master/scripts/add-local-ip-certs-to-docker-4.x.sh) and [docker helper](https://github.com/medic/cht-core/blob/master/scripts/docker-helper-4.x/cht-docker-compose.sh) to move the `curl` calls to be on `localhost` instead of inside `nginx` container.
* be extra defensive about `curl` calls to output user facing errors in case of DNS or `404` errors
* add an explicit check for valid TLS after we install the cert
* unchanged: we re-install the cert every time clean
* updates docs URLs to not be redirects
* test on a new …
> chore: docker helper 4x move curl TLS certs outside nginx container

- tests/e2e/upgrade/upgrade.wdio-spec.js
CHT recently released the new nav; this PR updates the unit tests to run the upgrade from `latest` CHT version (with new nav) instead of old nav. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:upgrade-tests-after-new-nav-release/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:upgrade-tests-after-new-nav-release/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:upgrade-tests-after-new-nav-release/docker-compose/cht-couchdb-clustered.yml)
> chore: update upgrade e2e

- scripts/deploy/src/install.js
- scripts/deploy/troubleshooting/get-volume-binding
This needs to be merged after [this](https://github.com/medic/helm-charts/pull/24) PR gets merged that releases the newest helm-charts.
You use this troubleshooting script to get the pv, pvc information and the subPath you need to set for your pre-existing data.
Example output:
```
./troubleshooting/get-volume-binding example-namespace cht-couchdb
{
"mountPath": "/opt/couchdb/data",
"name": "couchdb-claim0",
"subPath": "data",
"volumeType": "PVC",
"claimName": "couchdb-claim0",
"hostPath": null,
"pvName": "couchdb-pv-example-namespace",
"pvSize": "100Gi",
"storageClass": null,
"pvAccessModes": [
"ReadWriteOnce"
]
}
```
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:cht-deploy-troubleshooting-and-helm-chart-update/docker-co …
> fix(#9468): use latest helm-charts and troubleshooting for volumes

- webapp/src/css/sidebar-filter.less
#9490
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-display-wide-screens/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-display-wide-screens/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-display-wide-screens/docker-compose/cht-couchdb-clustered.yml)
> fix(#9490): sidebar filter container for wide screens

- webapp/src/css/modal.less
- webapp/src/ts/services/modal.service.ts
Training cards feature is using Enketo; adding scroll to the the form body to make Enketo buttons always visible 
#9292
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:long-content-training-cards/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:long-content-training-cards/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:long-content-training-cards/docker-compose/cht-couchdb-clustered.yml)
> fix(#9292): add scroll to training cards content

- webapp/src/css/modal.less
When doing the work in #9292, the training form's title was removed. We are putting it back because it's optional. 
[When the form's properties is defined with an empty title](https://docs.communityhealthtoolkit.org/building/guides/training/training-cards/#step-3-configure-the-training-form), the training doesn't display any title:
```js
{
"title": "", <----
"context": {
"start_date": "2023-07-13",
"duration": 60,
"user_roles": [ "nurse" ]
}
}
```
Testing:
When it's not defined, it displays the form id:
```js
{
"context": {
"start_date": "2023-07-13",
"duration": 60,
"user_roles": [ "nurse" ]
}
}
```
Testing:
Otherwise, the specified title:
```js
{
"title": "Some training", <----
"context": {
"start_date": "2023-07-13",
"duration": 60,
"user_roles": [ "nurse" ]
}
}
```
Testing:
Code …
> fix(#9292): add back training cards form's title

- package-lock.json
- package.json
#9519
Bump CHT version to 4.13.0
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9519-update-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9519-update-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9519-update-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9519): update CHT version to 4.13.0

- tests/e2e/default/enketo/training-cards.wdio-spec.js
- webapp/src/ts/app.component.ts
- webapp/src/ts/services/training-cards.service.ts
- webapp/tests/karma/ts/services/training-cards.service.spec.ts
Saves the last viewed date in the local storage, and if the date is before today, then displays the training cards
<details><summary>Test video: Desktop and mobile views</summary> 
https://github.com/user-attachments/assets/916b3a78-3fe1-4443-b64b-92e7c2a9a075
</details>
https://github.com/medic/cht-core/issues/9488
[PR CHT Docs](https://github.com/medic/cht-docs/pull/1612)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:training-cards-once-a-day/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:training-cards-once-a-day/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:training-cards-once-a-day/do …
> feat(#9488): show training cards once a day

- shared-libs/rules-engine/src/rules-state-store.js
- shared-libs/rules-engine/src/target-state.js
- shared-libs/rules-engine/test/rules-state-store.spec.js
- shared-libs/rules-engine/test/target-state.spec.js
- tests/e2e/default/targets/target-accuracy.wdio-spec.js
#9552 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-missing-aggregate/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-missing-aggregate/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-missing-aggregate/docker-compose/cht-couchdb-clustered.yml)
> fix(#9552): handle rules-engine stale state after upgrade

- shared-libs/rules-engine/src/rules-state-store.js
- shared-libs/rules-engine/src/target-state.js
- shared-libs/rules-engine/test/rules-state-store.spec.js
- shared-libs/rules-engine/test/target-state.spec.js
- tests/e2e/default/targets/target-accuracy.wdio-spec.js
#9552
(cherry picked from commit dc47c51e4660269c8daa3fd6e3ad08a4d37a7e8b)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-for-4.13.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-for-4.13.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-for-4.13.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#9552): handle rules-engine stale state after upgrade  for 4.13.x

- webapp/src/ts/components/sidebar-menu/sidebar-menu.component.html
This PR ensures when you click the links on the sidebar even if it the same module 
<details>
<summary>Desktop</summary>
https://github.com/user-attachments/assets/4ca64262-a14b-40ca-ba74-dc9b85b82af1
</details>
<details>
<summary>Mobile</summary>
https://github.com/user-attachments/assets/2746f446-da7b-4c31-a914-9f4571ee73a0
</details>
Closes #9514 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9514-close-sidebar/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9514-close-sidebar/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9514-close-sidebar/docker-compose/cht-couchdb-clustered.yml)
The …
> chore(#9514): close sidebar on clicking same module in sidebar

- shared-libs/rules-engine/src/rules-state-store.js
- shared-libs/rules-engine/src/target-state.js
- shared-libs/rules-engine/test/provider-wireup.spec.js
- shared-libs/rules-engine/test/rules-state-store.spec.js
- shared-libs/rules-engine/test/target-state.spec.js
#9552
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-interval-turnover/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-interval-turnover/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9552-interval-turnover/docker-compose/cht-couchdb-clustered.yml)
> fix(#9552): migrate stale target state for interval turnover

- package-lock.json
- package.json
Bump CHT version to 4.14.0
#9571
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9571-update-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9571-update-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9571-update-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9571): update CHT version to 4.14.0

- api/src/services/rapidpro.js
- api/tests/mocha/services/rapidpro.spec.js
- tests/e2e/default/sms/rapidpro.wdio-spec.js
- when api/v2/broadcast responds with 400, set the status as failed, so API doesn't retry sending the same message. This fixes incorrect phone number messages trying to be sent over and over. 
- when api/v2/broadcast responds with 200, but without a status update, set the state to queued to fix message duplication (https://forum.communityhealthtoolkit.org/t/duplication-of-messages-in-textit-rapidpro/4047/19).  
#9467
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9467-update-rapidpro/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9467-update-rapidpro/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic: …
> fix(#9467): better handling of RapidPro error codes

- shared-libs/validation/src/validator_functions.js
- shared-libs/validation/test/validations.js
- shared-libs/validation/test/validator_functions.js
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9604-fix-integer-validation/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9604-fix-integer-validation/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9604-fix-integer-validation/docker-compose/cht-couchdb-clustered.yml)
> fix(#9604): fix integer validation in sms rules

- shared-libs/validation/src/validator_functions.js
- shared-libs/validation/test/validations.js
- shared-libs/validation/test/validator_functions.js
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9604-fix-integer-validation-4.14.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9604-fix-integer-validation-4.14.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9604-fix-integer-validation-4.14.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#9604): fix integer validation in sms rules (backport)

- api/server.js
- tests/integration/api/server.spec.js
#9618
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9618-api-should-start-wiht-broken-forms/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9618-api-should-start-wiht-broken-forms/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9618-api-should-start-wiht-broken-forms/docker-compose/cht-couchdb-clustered.yml)
> fix(#9618): don't crash api on startup if form is broken

- api/src/services/setup/view-indexer.js
- api/tests/mocha/services/setup/view-indexer.spec.js
Removes view indexer request timeout param. This didn't end up terminating the request at haproxy level 
#9286
#9617
#8573
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9286-dont-timeout/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9286-dont-timeout/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9286-dont-timeout/docker-compose/cht-couchdb-clustered.yml)
> fix(#9286): don't pass request timeout prop

- .github/actions/deploy-conf/action.yml
Fixes #9644 
Adds the commands needed for converting and uploading training forms via the cht-conf gh-action
> chore(#9644): update cht-conf gh-action

- tests/integration/cht-form/default/person-edit.wdio-spec.js
- tests/integration/cht-form/wdio.conf.js
- webapp/src/ts/modules/messages/messages.component.ts
- webapp/src/ts/modules/reports/reports.component.ts
- webapp/src/ts/modules/tasks/tasks.component.ts
- webapp/src/ts/services/extract-lineage.service.ts
- webapp/src/ts/services/user-contact.service.ts
- webapp/tests/karma/ts/modules/messages/messages.component.spec.ts
- webapp/tests/karma/ts/modules/reports/reports.component.spec.ts
- webapp/tests/karma/ts/modules/tasks/tasks.component.spec.ts
- webapp/tests/karma/ts/services/extract-lineage.service.spec.ts
- webapp/tests/karma/ts/services/user-contact.service.spec.ts
Closes https://github.com/medic/cht-core/issues/9561
More details on source of the problem are in the issue, but TLDR is that a dependency on the `changes.service` leaked into cht-form. The `changes.service` tries to listen to the db for changes and prints an error if it cannot, before re-trying to listen again.  In cht-form, there is no db to listen to and the result is that when cht-form runs, the `changes.service` code just contantly spams error messages to the logs.  
My fix here is to update the service dependency tree to move some code out of the `extract-lineage.service` (which the `enketo.service` needs) and put it in the `user-contact.service`.  This essentially removes the dependency on the `changes.service` (and a number of other things not needed by `enketo.service`).   I …
> chore(#9561): refactor services to fix cht-from error

- tests/e2e/default/admin/admin-access.wdio-spec.js
- tests/e2e/default/contacts/contact-details.wdio-spec.js
- tests/e2e/default/contacts/muting-contact-using-form.wdio-spec.js
- tests/e2e/default/contacts/person-under-area.wdio-spec.js
- tests/e2e/default/db/initial-replication.wdio-spec.js
- tests/e2e/default/db/ongoing-replication.wdio-spec.js
- tests/e2e/default/enketo/extension-lib-form.wdio-spec.js
- tests/e2e/default/enketo/undo-death-report.wdio-spec.js
- tests/e2e/default/login/login-logout.wdio-spec.js
- tests/e2e/default/more-options-menu/offline-user/all-permissions.wdio-spec.js
- tests/e2e/default/more-options-menu/offline-user/edit-permission-disabled.wdio-spec.js
- tests/e2e/default/privacy-policy/privacy-policy.wdio-spec.js
- tests/e2e/default/purge/purge.wdio-spec.js
- tests/e2e/default/service-worker/service-worker.wdio-spec.js
- tests/e2e/default/targets/target-accuracy.wdio-spec.js
- tests/e2e/default/targets/target-aggregates.wdio-spec.js
- tests/e2e/default/tasks/tasks.wdio-spec.js
- tests/e2e/default/training-materials/training-materials.wdio-spec.js
- tests/e2e/default/transitions/create-user-for-contacts.create-user.wdio-spec.js
- tests/e2e/default/transitions/create-user-for-contacts.replace-user.wdio-spec.js
- tests/e2e/default/translations/enabled-languages.wdio-spec.js
- tests/e2e/default/translations/incorrect-locale.wdio-spec.js
- tests/e2e/upgrade/upgrade.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/common/modal.wdio.page.js
- tests/utils/index.js
When we sync, and an update comes, the update modal can appear _before_ we see the sync status update to successful, and it will close the sidebar menu when it shows up.
This made e2e sync function retry and spend time on unnecessary waits. 
Adds reloadSession common page function. 
#9660
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-e2e-sync/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-e2e-sync/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-e2e-sync/docker-compose/cht-couchdb-clustered.yml) …
> chore(#9660): update e2e sync function

- .github/PULL_REQUEST_TEMPLATE.md
To remind contributors to test in old and new design. 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:updating-check-list/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:updating-check-list/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:updating-check-list/docker-compose/cht-couchdb-clustered.yml)
> chore: updating list of manual checks

- couchdb/10-docker-default.ini
- couchdb/Dockerfile
- sentinel/src/lib/purging.js
- tests/integration/api/routing.spec.js
It appears that `changes_doc_ids_optimization_threshold` is still working and will provide us the same performance we had before. 
#9642
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9642-purging-without-changes-2/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9642-purging-without-changes-2/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9642-purging-without-changes-2/docker-compose/cht-couchdb-clustered.yml)
> perf(#9642): set `changes_doc_ids_optimization_threshold` a high value

- api/src/errors.js
- api/src/public-error.js
- api/src/services/privacy-policy.js
- api/src/services/records.js
- api/tests/mocha/services/privacy-policy.spec.js
When privacy policies doc is malformed, treat it as a 404 instead of some custom error. 
#9527 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9527-fix-privacy-policy-error/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9527-fix-privacy-policy-error/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9527-fix-privacy-policy-error/docker-compose/cht-couchdb-clustered.yml)
> fix(#9527): don't log error when privacy policy doc is malformed

- api/resources/translations/messages-ar.properties
The error was due to a missing translation in the [Arabic translations file - row `1240`](https://github.com/medic/cht-core/issues/9683#issuecomment-2522716453).
Closes #9715 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9715-fix-arabic/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9715-fix-arabic/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9715-fix-arabic/docker-compose/cht-couchdb-clustered.yml)
> fix(#9715): update broken translation

- admin/src/js/services/session.js
- admin/tests/unit/services/session.spec.js
I tried a bunch of events (beforeunload, popstate, etc), but none prevented the navigation in Angular v1. 
Cleaning the history was what worked the best in Chrome and Firefox. It's not perfect, but significant improvement.
<details><summary>Test video: Back button navigation in Chrome and Firefox</summary>
https://github.com/user-attachments/assets/40260b45-5238-4f58-a90f-e2b31ac8c2bc
</details>
#9213
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-back-button-on-logout/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix-back-button-on-logout/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic: …
> fix(#9213): fixes back button navigation after logout

- shared-libs/rules-engine/src/provider-wireup.js
- shared-libs/rules-engine/test/integration.spec.js
- shared-libs/rules-engine/test/provider-wireup.spec.js
I'm proposing this change based on a) the evidence from #9714 which demonstrates that interval turnover is likely causing incorrect values in target docs, and b) [this comment](https://github.com/medic/cht-core/pull/9486#discussion_r1802337684) from #9486 which suggests interval turnover is no longer needed.  The linked comment also suggests this is maybe not the correct approach, so I'm open to all suggestions.
Removing interval turnover reopens the hole documented via #6209 but it should be significantly smaller after #9486.
#9714 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9714-no-interval-turnover/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9714-no …
> feat(#9714): remove rules-engine's interval turnover

- shared-libs/outbound/src/outbound.js
- shared-libs/outbound/test/outbound.spec.js
> fix(#9747): throw error if outbound config is undefined

- .github/dependabot.yml
Closes https://github.com/medic/cht-core/issues/9796
Following the [dependabot config docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#ignore--) to ignore the various dependencies that we cannot bump because they are associated with ongoing open issues.
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:ignore-dependabot/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:ignore-dependabot/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:ignore-dependabot/docker-compose/cht-couchdb-clustered.yml) …
> chore(#9796): ignore blocked dependencies in dependabot

- .github/dependabot.yml
Following up on https://github.com/medic/cht-core/pull/9797, here are more dependencies that are formally blocked from upgrading (associated with existing logged issues).  
My rational for which dependencies to ignore is based on dependencies that are known to be _hard blocked_. These are ones where we know an upgrade is going to require significant changes to a core platform (and this is documented on an existing issue).  I have not included dependencies like [uuid](https://github.com/medic/cht-core/issues/9769) or [sinon](https://github.com/medic/cht-core/issues/9768) in the ignore list since it is not clear if these upgrades are hard blocked (instead they may just require minor changes). …
> chore(#9796): ignore additional blocked dependencies in dependabot

- admin/package-lock.json
- admin/package.json
- package-lock.json
- package.json
- webapp/package-lock.json
- webapp/package.json
Bumps bikram-sambat and bikram-sambat-bootstrap versions to 1.8.0
#9842
> chore(#9842): bump bikram-sambat and bikram-sambat-bootstrap versions to 1.8.0

- package-lock.json
- package.json
#9837
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:418x-update-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:418x-update-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:418x-update-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#9837): update version to 4.18.0

- .github/workflows/build.yml
Add command `sudo apt update` to CI jobs requiring ubuntu packages installed.
Sample of failing job: https://github.com/medic/cht-core/actions/runs/13988657188/job/39168226452
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix_failing_ci/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix_failing_ci/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fix_failing_ci/docker-compose/cht-couchdb-clustered.yml)
> fix: add apt update to CI jobs that require installation of ubuntu packages

- shared-libs/user-management/src/sso-login.js
- shared-libs/user-management/src/users.js
- shared-libs/user-management/test/unit/sso-login.spec.js
- shared-libs/user-management/test/unit/users.spec.js
- tests/integration/api/controllers/users.spec.js
Updates `libs/user-management` to allow for creating or updating of SSO couch users.
Closes #9760
> feat(#9760): add support for sso user create/update

- webapp/tests/karma/ts/modules/messages/messages-content.component.spec.ts
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9905-fix-message-component-tests/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9905-fix-message-component-tests/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9905-fix-message-component-tests/docker-compose/cht-couchdb-clustered.yml)
> fix(#9905): mock auth service

- webapp/tests/karma/karma-unit.base.conf.js
#9905
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fail-webapp-tests-based-on-coverage/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fail-webapp-tests-based-on-coverage/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:fail-webapp-tests-based-on-coverage/docker-compose/cht-couchdb-clustered.yml)
> chore(#9905): fail webapp tests based on coverage

- scripts/release-notes/index.js
Closes #9903 
This PR updates the release notes generation script to automatically include the current date when generating a new release page. The format and placement of the date follow the backdating pattern used in [cht-docs#1843](https://github.com/medic/cht-docs/issues/1843).
> feat(#9903): auto-include current date in release notes

- api/src/services/setup/upgrade-steps.js
- api/tests/mocha/services/setup/upgrade-steps.spec.js
- shared-libs/couch-request/src/couch-request.js
- shared-libs/couch-request/test/couch-request.js
- shared-libs/environment/src/index.js
- shared-libs/environment/test/index.spec.js
- tests/e2e/default/sms/rapidpro.wdio-spec.js
Fixes #9951 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9951-fix-circular-call/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9951-fix-circular-call/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9951-fix-circular-call/docker-compose/cht-couchdb-clustered.yml)
> fix(#9951): avoid circular call and clear deploy info cache when finalizing upgrade

- .github/ISSUE_TEMPLATE/z_release_major.md
- .github/ISSUE_TEMPLATE/z_release_patch.md
- scripts/release-notes/index.js
Adds post-release step of announcing community members individually. 
Replaces text from patch release template with text from minor release template for consistency. 
Minor edits to release notes script to have headers consistent with hextra docs theme. 
closes #9964
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:release-template-edits/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:release-template-edits/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:release-template-edits/docker-compose/cht-couchdb-clustered.yml) …
> chore(#9964): update release templates

- api/src/controllers/login.js
- api/src/services/settings.js
- api/src/services/sso-login.js
- api/tests/mocha/controllers/login.spec.js
- api/tests/mocha/services/sso-login.spec.js
- ddocs/users-db/users/views/users_by_field/map.js
- shared-libs/user-management/src/index.js
- shared-libs/user-management/src/roles.js
- shared-libs/user-management/src/sso-login.js
- shared-libs/user-management/src/token-login.js
- shared-libs/user-management/src/users.js
- shared-libs/user-management/test/unit/sso-login.spec.js
- shared-libs/user-management/test/unit/token-login.spec.js
- shared-libs/user-management/test/unit/users.spec.js
- tests/integration/api/controllers/login.spec.js
- tests/integration/api/controllers/users.spec.js
- tests/utils/mock-oidc-provider.js
- webapp/src/ts/modules/configuration-user/configuration-user.component.ts
- webapp/src/ts/services/user-settings.service.ts
- webapp/tests/karma/karma-unit.base.conf.js
- webapp/tests/karma/ts/modules/configuration-user/configuration-user.component.spec.ts
- webapp/tests/karma/ts/services/update-password.service.spec.ts
Closes #9963
Closes #9836
Closes #9938
Updates OIDC user configuration.  Instead of a boolean `oidc` field on the `_users` doc, there is now a string `oidc_username` field on the `_users` doc and a boolean `oidc_login` field on the `user-settings` doc.  This follows the pattern from token login where the auth-sensitive information is stored on the `_users` doc, while non-sensitive info is kept on the `user-settings` doc to allow the offline user UI logic to handle special cases for OIDC users.
Specifically, when a user had `oidc_login: true` in their user settings doc, they will not see the option in the app to update their password.
> feat(#9890): add mapping from OIDC to CHT user

- scripts/docker-helper-4.x/cht-docker-compose.sh
This PR renames the docker compose file for couchdb in docker helper to be  `cht-couchdb.yml` .  
Shout out to @sugat009 and @dianabarsan for making this an easy PR to throw together!
closes #9968
1. ensure new instance created in this branch's docker helper starts up correct
2. ensure new instance created in this branch's docker helper can be upgraded to new version and the couchdb image version gets upgraded too
3. note that instances created from `master` right now will need to be upgraded by renaming the compose file. for example, if have a project called `test1` then you would call: `mv ~/.medic/cht-docker/test1-dir/compose/couchdb.yml  ~/.medic/cht-docker/test1-dir/compose/cht-couchdb.yml`
Test that renaming a couch file from `master` works on this branch per above
If Build CI …
> fix(#9968): docker helper couchdb upgrade fix

- .github/workflows/build.yml
When doing development that requires new translation strings we need to provide _values_ for the translation keys for each of the required languages or else the `translations` job will fail in CI.  However, early in the development process we may not know all the needed translation strings (or how they will eventually be used/displayed). Finalizing the UX often comes towards the end of development. That is the point where our [translation process](https://docs.communityhealthtoolkit.org/community/contributing/translations/#adding-new-keys) indicates we should reach out on the forum to ask for help translating the strings.  
I think it is useful to have the `translations` job continue to fail until values are actually provided for the required languages, but I would also like the CI run to …
> chore: update GH action config to not require translations for publish

- .github/workflows/build.yml
This pull request introduces caching for the Chrome 90 installer in the GitHub Actions workflow to optimize build times. The key changes include adding a cache step, modifying the Chrome installation logic to leverage the cache, and separating the chromedriver installation.
Closes #9971 
> feat(#9971): add caching for Chrome 90 installer to optimize build process

- tests/e2e/default/telemetry/telemetry.wdio-spec.js
This small PR resolves the `faker` deprecation warings which you can find in the [CI logs](https://github.com/medic/cht-core/actions/runs/15336080315/job/43153950799#step:16:363):
```python
[@faker-js/faker]: faker.internet.userName() is deprecated since v9.1.0 and will be removed in v10.0.0. Please use faker.internet.username() instead.
```
> fix: resolve deprecated userName faker usage

- tests/e2e/default/tasks/tasks.wdio-spec.js
closes #9998 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9998-flaky-tasks-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9998-flaky-tasks-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:9998-flaky-tasks-test/docker-compose/cht-couchdb-clustered.yml)
> test(#9998): fix flaky tasks test

- shared-libs/cht-datasource/src/libs/core.ts
- shared-libs/cht-datasource/src/qualifier.ts
- shared-libs/cht-datasource/test/qualifier.spec.ts
Commit 1 adds the `ReportQualifier` based on the description in #9835.
An additional error is included in cases where the `data` is not a valid `object`.
Commit 2 tweaks `hasField` and `hasFields` to perform an optional
truthy check on values, which is utilized to detect empty strings 
in `isContactQualifier` and `isReportQualifier` to return `false`
for such field values.
> feat(#9835): add `ReportQualifier` functions and update `hasField`

- .github/workflows/build.yml
- .github/workflows/cleanup.yml
- .github/workflows/conventional-commits.yml
- .github/workflows/scalability.yml
Unbuntu 24-04 comes with docker compose 2.36.0: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
closes #10013 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:ubuntu-latest/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:ubuntu-latest/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:ubuntu-latest/docker-compose/cht-couchdb-clustered.yml)
> chore(#10013): use ubuntu-latest for ci workers

- tests/e2e/default/tasks/config/tasks-contact-config.js
- tests/e2e/default/tasks/tasks.wdio-spec.js
- webapp/src/ts/modules/tasks/tasks-content.component.html
- webapp/src/ts/modules/tasks/tasks-content.component.ts
- webapp/tests/karma/ts/modules/tasks/tasks-content.component.spec.ts
Allow editing of a contact via the linked task entry. The CHT already allows creating a new contact based on type through a task; this builds on that functionality.
Closes https://github.com/medic/cht-core/issues/9974
> feat(#9974): support opening contact edit form from task

- tests/e2e/default/tasks/tasks.wdio-spec.js
- tests/page-objects/default/common/common.wdio.page.js
- tests/page-objects/default/tasks/tasks.wdio.page.js
closes #10050 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10050-fix-flaky-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10050-fix-flaky-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10050-fix-flaky-test/docker-compose/cht-couchdb-clustered.yml)
> fix(#10050): update tasks e2e test for stability

- config/default/tasks.js
- webapp/src/ts/reducers/tasks.ts
- webapp/src/ts/services/format-date.service.ts
- webapp/tests/karma/ts/reducers/tasks.spec.ts
Closes https://github.com/medic/cht-core/issues/9957
**Is your feature request related to a problem? Please describe.**
Currently tasks are sorted only by due date. The update takes into account both a priority score and due date.
**Describe the solution you'd like**
Implemented a refined sorting algorithm that (Sort by priority and then due date within the same priority):
- Primarily sorts tasks by priority (higher numbers first)
- For tasks with equal priority, sorts by due date (earlier dates first)
- Handles invalid values consistently:
- Tasks with invalid priorities move to end
- Within same priority, invalid dates move to end
- Maintains original order when both priority and date are invalid
**Describe alternatives you've considered**
****Alternative Solution 1****
Similar to the …
> feat(#9957): dynamic sorting of tasks by priority and due date

- api/src/controllers/person.js
- api/src/routing.js
- shared-libs/cht-datasource/src/index.ts
- shared-libs/cht-datasource/src/libs/parameter-validators.ts
- shared-libs/cht-datasource/src/person.ts
- shared-libs/cht-datasource/src/qualifier.ts
- shared-libs/cht-datasource/src/remote/person.ts
- shared-libs/cht-datasource/test/index.spec.ts
- shared-libs/cht-datasource/test/person.spec.ts
- shared-libs/cht-datasource/test/qualifier.spec.ts
- shared-libs/cht-datasource/test/remote/person.spec.ts
Deals with the following step:
> Expose a unified interface for the interaction from the relevant top-level [concept module](https://docs.communityhealthtoolkit.org/cht-datasource/src).
> feat(#10036): add API support for `createPerson`

- .github/workflows/build.yml
- api/src/services/africas-talking.js
- api/tests/mocha/services/africas-talking.spec.js
- tests/e2e/default/sms/africas-talking.wdio-spec.js
- tests/utils/index.js
No longer attempt to double parse body.
Adds CI only e2e test that interacts with Africa's Talking Sandbox server.
#10068
(cherry picked from commit fb52de8606201fdbc853e3c108f878e8640b4f7f)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10068-for-4.21/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10068-for-4.21/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10068-for-4.21/docker-compose/cht-couchdb-clustered.yml)
> fix(#10068): fix africa's talking request body parsing (#10073)

- .github/workflows/stale-prs.yml
closes #10084
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10084-handle-stale-prs/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10084-handle-stale-prs/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10084-handle-stale-prs/docker-compose/cht-couchdb-clustered.yml)
> chore(#10084): automate stale PR handling with scheduled GitHub Action

- .github/dependabot.yml
https://github.com/medic/cht-core/issues/10114
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-depdendabot-excludes/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-depdendabot-excludes/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:update-depdendabot-excludes/docker-compose/cht-couchdb-clustered.yml)
> chore(#10114): add uuid to dependabot ignore list due to ES2022 issue

- api/tests/mocha/controllers/report.spec.js
- shared-libs/cht-datasource/src/input.ts
- shared-libs/cht-datasource/src/local/person.ts
- shared-libs/cht-datasource/src/local/place.ts
- shared-libs/cht-datasource/src/local/report.ts
- shared-libs/cht-datasource/test/input.spec.ts
- shared-libs/cht-datasource/test/local/person.spec.ts
- shared-libs/cht-datasource/test/local/place.spec.ts
- shared-libs/cht-datasource/test/local/report.spec.ts
- shared-libs/cht-datasource/test/remote/report.spec.ts
- tests/integration/api/controllers/person.spec.js
- tests/integration/api/controllers/place.spec.js
- tests/integration/api/controllers/report.spec.js
- tests/integration/shared-libs/cht-datasource/person.spec.js
- tests/integration/shared-libs/cht-datasource/place.spec.js
- tests/integration/shared-libs/cht-datasource/report.spec.js
WIP PR to store `parent` and `contact` fields with a dehydrated lineage.
We would need to fetch the parent and check its type and ensure it is one of the preconfigured/ allowedparents for the currently created place/person's contact_type
This parent if valid(meaning has a `contact_type` from one of the allowed `parents`  in the contact type object for the given input) will later be used to store `parent` field with de-hydrated lineage in a person/place doc.
Previously, we just stored the `string` containing the parent `id` instead of the de-hydrated lineage.
TODO: Store `contact` with lineage in a place, which shouldn't be as tricky given that there is no validation we'd have to do based on settings.
The software is provided under AGPL-3.0. Contributions to this project are accepted under …
> feat(#10038): store parent/contact with lineage instead of string

- couchdb/10-docker-default.ini
Removes server_options overriding sndbuff: https://github.com/apache/couchdb/issues/1810
Removes socket_options as they are identical with CouchDb defaults: https://github.com/apache/couchdb/blob/main/src/chttpd/src/chttpd.erl#L97
closes #10125
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10125-no-sever-options/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10125-no-sever-options/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10125-no-sever-options/docker-compose/cht-couchdb-clustered.yml) …
> chore(#10125): remove server and socket options from couch config

- shared-libs/cht-datasource/src/local/libs/core.ts
- shared-libs/cht-datasource/test/libs/core.spec.ts
- shared-libs/cht-datasource/test/report.spec.ts
We autoconvert the update payload's `reported_date`
to a unix epoch before doing the validation checks
with the original document.
Fixes: https://github.com/medic/cht-core/pull/10083#issuecomment-3227044948.
> fix(#9835): fix missing `reported_date` bug

- package-lock.json
- package.json
Bump CHT version in package.json file to 4.22.0
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10245-bump-version/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10245-bump-version/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10245-bump-version/docker-compose/cht-couchdb-clustered.yml)
> chore(#10245): bump CHT version to 4.22.0

- webapp/package-lock.json
- webapp/package.json
Fixes #10319 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10319_fix_esbuild/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10319_fix_esbuild/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10319_fix_esbuild/docker-compose/cht-couchdb-clustered.yml)
> fix(#10319): explicitely specify esbuild and update to 0.25.10

- package-lock.json
- package.json
- shared-libs/couch-request/src/couch-request.js
- shared-libs/couch-request/test/couch-request.js
#10296
(cherry picked from commit 5f8066a72a2ef64342476def4f854f820cff8ecd)
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10296-for-4.x/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10296-for-4.x/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10296-for-4.x/docker-compose/cht-couchdb-clustered.yml)
> fix(#10296): adds custom undici agent as dispatcher for fetch reques

- webapp/src/ts/services/telemetry.service.ts
- webapp/tests/karma/ts/services/telemetry.service.spec.ts
- The temporary [deleteDeprecatedTelemetryDB function](https://github.com/medic/cht-core/blob/601d992394983f589ae627f3fe11a4b080bc5b42/webapp/src/ts/services/telemetry.service.ts#L344) was deleted and it's calls.
- All unit tests that fails because of this change were fix.
Closes [#8657](https://github.com/medic/cht-core/issues/8657)
> feat(#8657): remove logic for cleaning up old telemetry db

- .github/dependabot.yml
Both [ngx-bootstrap](https://www.npmjs.com/package/ngx-bootstrap) and [ngx-cookie-service](https://www.npmjs.com/package/ngx-cookie-service) target their major versions to the compatible major version of Angular. 
The goal is to avoid PRs like: https://github.com/medic/cht-core/pull/10287 where it is trying to upgrade `ngx-bootstrap` to `20.x` when we have not updated Angular yet.
> chore: add ngx dependencies to angular dependabot group

- shared-libs/cht-datasource/src/local/libs/doc.ts
- shared-libs/cht-datasource/test/local/libs/doc.spec.ts
Changes how logging is done in `cht-datasource`'s `src/local/libs/doc.ts` when checking for existence of a `ddoc`.
Addresses #10309 
* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10309-refine-log-message/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10309-refine-log-message/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:10309-refine-log-message/docker-compose/cht-couchdb-clustered.yml)
> chore(#10309): refine logging when checking for existence of ddoc in cht-datasource
