medic/cht-core

packages/kujua-sms/kujua-sms/rewrites.js
packages/kujua-sms/kujua-sms/updates.js
packages/kujua-sms/kujua-sms/views.js
packages/kujua-utils/kujua-utils.js

Add lower level couchdb support to update a document's message tasks.   Also add a higher level API to medic-api that will accept a message's UUID and new state value as an argument.  This requires a view to index all messages so a document lookup can be done based on a message uuid.  Opening PR for potential discussion.

Messages API

---

static/js/services/delete-doc.js

Fix for #945 
Before deleting a contact, we GET its catchment area.  If the
catchment area has already been deleted, this GET will fail.  This
commit ignores the failure if it is because the catchment area is
deleted.

Fix for #945 cannot delete a contact whose catchment area has been deleted

---

static/js/controllers/contacts-content.js
static/js/controllers/contacts.js
static/js/controllers/edit-contact.js
static/js/controllers/inbox.js

This changes the behaviours of the `ContactUdpated` listeners in various
controllers to simplify their handling of deleted contacts.  In short,
the listeners update `$scope.items` directly, where appropriate, in
place of triggering database queries.
This should fix #919 and #923.
@garethbowen please review!

Fix #923 and #919 - bugs when deleting contacts

---

packages/kujua-sms/kujua-sms/views.js

Fix for #963
`getName` was renamed to `getPosition` in
25324a399c19ad9027f666716578a9db89448b7b.  This commit updates
`kujua-sms/views.js` to correctly reference `getPosition` instead of `getName`.
Also adds null-safe dereference for `facility.parent` which is passed to
`getPosition`.

Fix for #963 - view can't find `getName` method

---

static/js/controllers/edit-contact.js
static/js/controllers/inbox.js
static/js/services/http-wrapper.js
static/js/services/message-contacts.js
tests/karma/unit/services/http-wrapper.js

An alternative approach to (https://github.com/medic/medic-webapp/pull/955) for fixing #925.
This adds a new parameter for HTTP requests made through the
`HttpWrapper` service - `updateTarget`.  Current options for
`updateTarget` are `filter`, `left` and `right`, referring to different
sections of the UI which an HTTP request might update on successful
completion.
When the user navigates to different states, the `stateChangeStart`
listener selectively cancels pending HTTP requests depending on the old
and new states.
There are three tests which are broken by this commit.  They check that
the callback functions are working by testing that the error callbacks
are executed for cancelled requests.  This commit changed the behaviour
of the rest canceller from calling `resolve()` on request …

Fix for #925: tag HTTP requests with their update target

---

static/js/controllers/help.js
static/js/services/debug.js
static/js/services/index.js
templates/partials/help.html

Issue: https://github.com/medic/medic-webapp/issues/1647
Couple things that are a bit strange:
Since we're using the ipCookie service the $logProvider.debugEnabled() gets called kind of late, so you will see $log.debug() output until then.  I don't think we have many $log.debug() calls currently so there's not much effect atm.
The pouchDB service doesn't seem to have a `debug` property on it.

initial attempt at debug mode controller

---

packages/libphonenumber/libphonenumber/utils.js
packages/libphonenumber/tests/libphonenumber.js
static/js/enketo/widgets/phone-widget.js
tests/karma/unit/services/send-message.js

https://github.com/medic/medic-webapp/issues/1762
See the tests for what is valid or invalid. 
This follows what libphonenumber does : allow any dots, dashes, spaces, but not other punctuation, and not letters.
Please advise on whether this would break existing instances, if users already saved invalid phone numbers for instance.

#1762 - no letters in phone numbers

---

static/js/controllers/contacts.js
static/js/controllers/tasks.js
templates/partials/tasks_list.html
tests/karma/unit/controllers/tasks.js
tests/karma/utils.js

On some pages (notably the tasks page) the loading indicator doesn't
work properly. This is due to offloading work in $timeout calls, which
gives Angular a chance to do work between those calls. To fix this I
moved the loading state change to occur after the work done in $timeout
calls.

Clean up loading indicators

---

bower.json

bootstrap-tour has a bug in its latest tag with tours that contain orphan
steps. This has been fixed but only in master; there is not yet a release.
I've forked the repo and created a v0.10.3 tag that contains v0.10.2 plus
this one fix which we can use until they release a real version.

Temporary fix tour bug. Issue: #933

---

lib/fulltext.js
lib/views.js

Should prevent couch errors like this:
```
08:24:05 couch.1  | [info] [<0.940.0>] OS Process #Port<0.3612> Log :: function raised exception (new TypeError("doc.errors is undefined", "undefined", 3)) with doc._id abc-123
```

Make `doc.errors` dereferencing safe in couch views

---

static/js/services/db.js
static/js/services/import-contacts.js

This fixes a repeated spurious "Update available" message on page load/reload. The version detection relies on an ETag header but does not correctly discard the `W/` prefix for weak ETags, leading
to a presumed version mismatch.
This doesn't appear to be covered by unit tests, and probably should be split out to an ETag parser module one way or another so it can be unit tested without lots of screaming and gnashing of teeth.

Support weakly-validated ETag headers

---

static/js/services/db-sync.js

Previously this used a boolean which is then converted to a string.

Use strings to define replication direction

---

lib/app.js
lib/validate_doc_update.js
tests/nodeunit/unit/validate_doc_update.js

Issue #2047  
Ok here's the updated testable validate_doc_update.js for user-settings docs. Remember this could potentially affect any doc change.
Couple changes worth looking at below. 
I did this for easier testing so I could pass in an empty object `{}` and it would return properly.  I can't imagine it having a negative affect, worth a second pair of eyes or maybe some tests.
```
-    if (userCtx.name === null) {
+    if (typeof userCtx.name === 'undefined' || userCtx.name === null) {
```
I added a few tests against `validate_doc_update.allowed` just to kick the tires a bit.  I wasn't sure how much coverage we wanted on this issue. I could continue writing coverage against other parts of the  module if we want.  I just focused on the validateUserSettings function.  Please have a look …

validation for user-settings docs

---

static/js/services/enketo-prepopulation-data.js
static/js/services/enketo-translation.js
tests/karma/unit/services/enketo-prepopulation-data.js
tests/karma/unit/services/enketo-translation.js

Allows the first layer of binding to be a bit looser (at the callers
description); all layers of binding after that are strict 1:1 mappings between
the data and the XML.
Issue: #2164

Make binding stricter

---

static/js/bootstrap.js
static/js/controllers/inbox.js
static/js/services/db-sync.js
templates/partials/about.html
tests/karma/unit/services/db-sync.js

This moves the initial replication into the bootstrap layer which means it runs once per user+device+server, not every page load. The user will now see a spinner while the initial replication is going. This means they won't be querying the database until all the data is up to date which speeds up the overall initial replication time.
One downside is because this is running before Angular has started it's not easy to capture the replication data to show on the About page. I've tried to capture the same data and output it to the console. That combined with the fact the app won't load until the replication completes hopefully gives enough info about the state of replication. I'd welcome feedback here about how to include more information.
With this patch initial startup takes about 3.5 …

Move initial replication into bootstrap. Issue: #2394

---

static/js/services/enketo-translation.js
tests/karma/unit/services/enketo-translation.js

There is no documentation on why we were filtering this out, and it does
contain useful information (GPS coords).

No longer filter meta nodes #2450

---

packages/kujua-sms/kujua-sms/updates.js
packages/kujua-sms/kujua-sms/utils.js

cf4c3ff fixed bug where default response did not respect locale value
Not sure if this is necessary for DIY/v0.4 compatibility. I know there
is a project or two that use this feature.  It allows you to support
reporters in multiple languages based on a field named `locale` set in
the form or a query parameter `locale` set on the gateway.
Issue: https://github.com/medic/medic-webapp/issues/2410

ported a patch from `diy` branch that was lost.

---

Gruntfile.js
patches/pouchdb-ignore-safari-check.patch

On some TECNO phones they omit Chrome from their userAgent, causing
PouchDB to mis-categorise them as Safari, which disables IDB support,
which causes crazy issues.

PouchDB learns about Tecnos #2797

---

static/js/controllers/contacts-edit.js
static/js/controllers/contacts-report.js
static/js/controllers/reports-add.js
static/js/controllers/tasks-content.js

Our main debouncing strategy of setting $scope.saving and having angular
disable the button on that value mostly works, but on slower phones
you're able to get more than one action in before Angular gets itself
together.
This doubly-checks to make sure save isn't called more than once.

Extra debouncing for slow devices #2909

---

static/js/services/enketo.js
static/js/services/user-contact.js
static/js/services/user.js
tests/karma/unit/services/enketo.js
tests/karma/unit/services/user-contact.js

Now when the users contact_id is configured but the referenced doc isn't found it's treated the same as if the contact_id isn't configured. This means errors are handled and user friendly messages shown.

Handle missing user contact better. Issue: #2944

---

static/js/controllers/reports-add.js
static/js/services/enketo.js
tests/karma/unit/services/enketo.js

Creating a new report or updating an existing one will save the xml
content as an attachment instead of as a property on the object. Both
types (property or attachemnt) are supported for opening documents, so
no migration is neccessary.

XML form content stored as attachment

---

static/js/services/select2-search.js

Once the user selects an entry replace the search-optimised search
result with the full document from CouchDB.

Hydrate full document on selection #3069

---

kanso.json

Not sure how this got lost, probably never forwarded ported from 0.4.x
branch.  Sentinel looks good though, I think the minor change to webapp
was left behind.
Issue: https://github.com/medic/medic-webapp/issues/3125

added outgoing deny list setting to kanso.json.

---

scripts/ci/after_success.sh

Minification is the default, but if you want you can specify to not
do it. Currently set to alpha and beta to make debugging things easier,
because debugging is more important than performance in these stages.

Don't minify alpha and beta releases

---

static/js/services/db-sync.js
tests/karma/unit/services/db-sync.js

If a client has an old medic ddoc lying around it shouldn't be
replicated back to the server as it's massive and quickly blows out
the auditing database.
medic/medic-webapp#3268

Don't replicate ddocs back to server

---

kanso.json
packages/kujua-sms/kujua-sms/utils.js
static/js/app.js
templates/partials/reports_content.html

If the schedule task name translation_key is available use it to
generate group name, otherwise fall back to concatenating the group
number to the untranslated schedule name.
medic/medic-webapp#3283

Translate task schedule group titles 

---

static/js/modules/feedback.js
tests/nodeunit/unit/feedback.js

Workers use a serialization function that can't handle some common
types such as DOM, URLs, etc. If these get logged at any point it
breaks the feedback mechanism because the feedback doc can't be saved
to pouch. Stringify these as we go.
medic/medic-webapp#3273

Stringify log arguments to be worker friendly

---

npm-shrinkwrap.json
package.json
static/js/services/db.js
tests/karma/unit/services/db.js

For some reason this breaks replication: changes are seen and accepted
by the validator, but then they don't continue to propagate.
We're going to revert for now and look into pouchdb-validation later.

Disable client-side validation #3236

---

static/css/analytics-widgets.less
templates/partials/analytics/targets.html

Allows non-English characters (eg: Hindi) to overflow where necessary.
To get the title to line up nicely we need flexbox which also means
floating is no longer necessary.
medic/medic-webapp#3297

Allow text overflow in target titles

---

Gruntfile.js

This greatly eases testing of patches to dependencies.
@garethbowen please review.  I'm in two minds about whether this should really be included by default or not - it's really helpful when it's helpful, but generally fiddling with stuff in `node_modules` is a quick way to get your working directory into an inconsistent state...so, what do you reckon?

Rebuild inbox.js in grunt dev when changes are made in node_modules

---

static/js/controllers/contacts-content.js

Show the patient name underneath the report type on the patient
profile page for consistency with everywhere else it's shown.
medic/medic-webapp#3309

Show report subject name on patient page

---

static/js/services/enketo.js

Run contact forms through the same translation function that report
forms go through so itext elements work as expected and contact forms
can be translated to the user's language.
medic/medic-webapp#3323

Translate contact forms

---

Gruntfile.js
patches/moment-hindi-use-euro-numerals.patch

Closes #3335 
An alternative to this would be to redefine our Hindi locale as e.g. `hi-u-nu-latn`, but @shreyakb is confident that no one ever uses Devanagari numbers when writing in Hindi.

Don't use Devanagari numerals with Hindi locale

---

static/js/controllers/contacts-edit.js
static/js/controllers/contacts-report.js
static/js/controllers/reports-add.js
static/js/controllers/tasks-content.js
static/js/services/contact-form.js
static/js/services/enketo.js
static/js/services/index.js
static/js/services/xml-form.js
tests/karma/unit/controllers/tasks-content.js
tests/karma/unit/services/enketo.js

Refactor the Enketo service to promote code reuse so both contact and
report forms benefit from features like translation and xml caching.
Also various other code cleanups where appropriate.
medic/medic-webapp#3325

Improve reuse rendering contact and report forms

---

static/js/modules/nootils.js

These tests fail for me with UTC code in there (my tz is UTC+1) right
now). It's probable we don't notice because a) no one runs these tests
locally and b) travis runs against UTC so we never notice.

Remove UTC usage as its not needed.

---

npm-shrinkwrap.json
package.json

The XSL stylesheet was mistakenly marked as XSL version 1.0, which caused
Firefox to reject it.
Closes #3354

Bump enketo-xslt version to fix firefox bug

---

static/js/controllers/tasks.js

Because we load the livelist and the task report in parallel it's
highly likely the list won't contain the ID on page load. So instead of
clearing if the item isn't in the livelist, only clear if we haven't
been given an ID to select. This is consistent with other tabs.
medic/medic-webapp#3090

Don't clear selected if loading specific task

---

static/js/filters/message.js
static/js/modules/format.js

Seems like the name is some legacy situation : it's not limited to clinics anyway.
Kept the old name as legacy cos filter are used in unexpected places, it's hard to track down. `contact_summary`s use it for instance.

Rename clinic filter to lineage.

---

static/css/inbox.less

Attempt to fix issue where bullet is sometimes rendered as å€¢.
#3020

Use unicode code point for bullet in CSS. #3020

---

static/js/services/outgoing-messages-configuration.js
static/js/services/properties.js
tests/karma/unit/services/import-properties.js
tests/karma/unit/services/outgoing-messages-configuration.js

In medic/medic-webapp#3127 support is added for moving message
translation out of app_settings into the standard translation files.
Here, we add support for this change in import and export functions.
Translation export no longer exports when the translation is actually in
the translation file. This stop empty lines with a key but no value
appearing in translation files.
Translation import ignores translation lines when importing into
app_settings, so as to not break on exports generated prior to this
change.
medic/medic-webapp#3350

app_setting translation import / export fixes

---

package.json
tests/karma/unit/controllers/inbox.js

NB: migration notes are here:
http://sinonjs.org/releases/v2.1.0/migrating-to-2.0/
We don't seem to hit anything that they note. I have no idea why
the code in inbox.js ever worked, I guess it was exploiting a bug.

Upgrading to the latest version of sinon

---

README.md

We no longer use Lucene for actual search, but instead just for certain
in-app analytics (if you have them enabled).
For example, see api's calculation of active pregnancies:
https://github.com/medic/medic-api/blob/master/controllers/active-pregnancies.js
Specifically, the use of the FTI server:
https://github.com/medic/medic-api/blob/master/controllers/utils.js#L130-L141
medic/medic-webapp#2497

Clarify lucene's purpose

---

static/js/controllers/contacts-edit.js

As per https://github.com/medic/medic-webapp/issues/2912#issuecomment-299800741
While this does relate to #2912, I think the change is generally more correct.  Adding it to #2912 will significantly delay and obscure it, hence separate PR.

Identify if a doc is unsaved by checking rev, not id

---

static/js/services/search-filters.js
tests/protractor/e2e/report-date-filter.js

Our custom mobile daterangepicker was broken by an update in the
daterangepicker library at some point. This modifies our custom code
to no longer hide the picker and lets the library do that automatically
via a new 'autoApply' option which selects as soon as the end date is
selected. This also applies to the desktop but it's an improvement
there as well I think.
Also removes a bunch of translations which are no longer used.
medic/medic-webapp#3467

Fixes daterangepicker on mobile 

---

Gruntfile.js
static/js/controllers/contacts-report.js
static/js/controllers/reports-add.js
static/js/controllers/tasks-content.js
static/js/modules/xpath-element-path.js
static/js/services/enketo-translation.js
static/js/services/enketo.js
tests/karma/unit/services/enketo.js

TODO before merging:
Extensions to the form Model:
* extra docs can be added by defining structures in the model with the attribute `db-doc="true"`, e.g.:
```
<data>
<root_prop_1>val A</root_prop_1>
<other_doc db-doc="true">
<type>whatever</type>
<other_prop>val B</other_prop>
</other_doc>
</data>
```
Report (as before):
```
{
_id: '...',
_rev: '...',
type: 'report',
_attachments: { xml: ... ],
fields: {
root_prop_1: 'val A',
}
}
```
Other doc:
```
{
_id: '...',
_rev: '...',
type: 'whatever',
other_prop: 'val B',
}
```
* linked docs can be referred to using the `doc-ref` attribute, with an xpath.  This can be done at any point in the model, e.g.:
```
<sickness>
<sufferer doc-ref="/sickness/new">
<new db-doc="true">
<type>person</type>
<name>Gómez</name>
<original_report …
```

Allow creation of multiple docs from a single XForm

---

static/js/controllers/contacts-edit.js
static/js/controllers/contacts-report.js
static/js/controllers/inbox.js
static/js/controllers/reports-add.js
static/js/controllers/tasks-content.js
static/js/services/enketo.js
tests/karma/unit/controllers/tasks-content.js

Enketo has an event that fires when the form content has been updated
by the user. This change leverages that so that the "may lost content"
warning dialog is only shown when the user has actually changed a
value.
This fixes a bug where the warning is shown when the form failed to
render, and also a bug where the warning is shown when the form has no
fields.
medic/medic-webapp#1601
medic/medic-webapp#3045

Adds a listener to Enketo to notify on change

---

static/js/controllers/configuration-forms.js
templates/partials/configuration_forms.html

The futon links look a bit dodgy right now, and possibly only work for couch 2.  Would be possible to make a futon link service or something, but seems like a lot of effort.  In fact, in hindsight, linking straight to the "forms" view in futon might be as helpful as this change.

Include a list of installed xforms on the forms config page

---

ddocs/medic-conflicts/_id
ddocs/medic-conflicts/views/conflicts/map.js

Add a simple conflict view to allow people to see conflicts. In a
separate ddoc to avoid large view index rebuilds on larger partners.
medic/medic-webapp#3502

Conflict view

---

Changes.md
static/js/controllers/configuration-forms.js
templates/partials/configuration_forms.html

When uploading xforms you can now upload the full meta doc which
means you can set the icon, title, hidden_fields, etc as well as
the context of the form.
This isn't backwards compatible as we should only use meta files
from now on.
medic/medic-webapp#3540

Replaces context field with meta field for xform upload

---

ddocs/medic-client/views/help_pages/map.js
static/js/controllers/about.js
templates/partials/about.html

This removes the concept of help pages which were intended to be
in-app user documentation but has never been implemented. We can
add it back if we decide to implement it one day.
medic/medic-webapp#1895

Removes the help pages implementation

---

.github/ISSUE_TEMPLATE.md

A proposal: add a proactive reminder to protect the confidentiality of patient and health worker PII; this reminder will automatically appear in every issue. This reminder would be deleted as a rule prior to the issue being filed, so as not to cause clutter.

Add boilerplate GitHub issue template PHI warning

---

templates/partials/contacts_content.html

On the contact detail page, the reports list heading was being hidden
but not the list content when the user didn't have the
"can_view_reports" permission.
medic/medic-webapp#3452

Hides the report list when user lacks permission

---

scripts/upload_xform.sh
static/css/enketo/medic.less

The upload_xform script was removing the title from the xform
definition so it wouldn't show in the UI. This broken medic-collect
integration which relies on the title being present.
This change leaves the title in the form. It is replaced during
render with the translated version from the doc. This is hidden on
mobile where the title is displayed in the title bar instead.
medic/medic-webapp#3390

Hides form title in CSS instead of removing from form

---

package-lock.json
package.json

I think this needs an update to `package-lock.json` too.  What's the correct way to do that?

Update openrosa-xpath-evaluator with better support for [] statements

---

Changes.md
package-lock.json
package.json
static/js/controllers/edit-user.js
static/js/services/index.js
static/js/services/translate.js
tests/karma/unit/controllers/edit-user.js
translations/messages-en.properties

Stops the user entering weak passwords when creating or editing
a user. Weak is defined as being at least 8 characters long and
having sufficient complexity.
medic/medic-webapp#1472

Adds password strength validation 

---

static/js/enketo/widgets/db-object-widget.js

When the selected db object is changed in a select2 widget we
attempt to bind to other fields defined by that object. This
allows form configurations that can interrogate other fields
on the object.
The bug was that when binding the code matched all the fields in
all the selects, rather than just the fields in this repeat
section.
medic/medic-webapp#3430

Reduces select2 update binding scope

---

README.md

We now link to this section (#enabling-a-secure-couchdb) in an api
error message that is thrown on api startup if you have not configured
couchdb correctly.
medic/medic-webapp#3606

Improving the readme to make security section clear #3606

---

lib/fulltext.js

Exporting reports filtered by place relies on the "clinic" field
so we need to include it in the lucene index.
Also fixes an exception that's thrown when doc.fields is null.
medic/medic-webapp#3593

Adds the clinic back into lucene index

---

Changes.md
scripts/ci/setup.sh

Update submodules to latest master before running tests.  Example build where you can see latest master is checked out: https://travis-ci.org/medic/medic-webapp/jobs/250756289#L3985
Travis also does a `git submodule update --recursive` after git clone here https://travis-ci.org/medic/medic-webapp/jobs/250756289#L487 if we could add some logic there to check the travis branch string and append `--remote` that could work too.
Related: https://github.com/medic/medic-webapp/issues/3359

Run CI on master branch against latest master of submodules

---

lib/fulltext.js

The default "text" type splits fields by non-word characters
which means "pregnancy_visit" matches "pregnancy" and forms
are returned when they shouldn't be. Using "string" foces it
to match exactly (except for case).
medic/medic-webapp#3615

Uses exact matching for form field

---

kanso.json

The node modules are packaged in CI for releases and is rarely ever used in dev.  It slows down the dev build step significantly, in my setup `grunt deploy` improves from 59s to 11s.
https://github.com/medic/medic-webapp/issues/2678

Stop kanso from building node modules (api and sentinel)

---

packages/app-settings/app-settings/updates.js
packages/kujua-sms/kujua-sms/updates.js
tests/nodeunit/unit/kujua-sms/updates.js

The couch updates endpoints were always returning 200 status even
if the operation failed. This change returns 200, 400, or 404 as
appropriate so it's more obvious when a request fails.
medic/medic-webapp#3674

Returns correct http codes

---

static/js/controllers/configuration-forms-xml.js
static/js/services/xml-forms.js
tests/karma/unit/services/xml-forms.js

This updates the XmlForms service to not return forms with
context.collect true. This means users cannot filter by a collect
form which will never have any reports submitted. Furthermore
they cannot attempt to fill in a collect form. The only place
which still shows collect forms is the forms admin page.
medic/medic-webapp#3625

Hides collect forms in the UI

---

tests/protractor/e2e/auditing.js
tests/protractor/e2e/bulk-delete.js
tests/protractor/e2e/forms/submit-delivery-form.specs.js
tests/protractor/e2e/send-message.js
tests/protractor/page-objects/forms/delivery-report.po.js
tests/protractor/page-objects/users/add-user-modal.po.js

When selecting elements for webdriver tests, if your selector selects several, the first will be used and the other dropped. This can cause a selection of the wrong element.
medic/medic-webapp#3698

3698 more than one

---

tests/protractor/e2e/submit-enketo-form.js

When selecting elements for webdriver tests, if your selector selects several, the first will be used and the other dropped. This can cause a selection of the wrong element.
medic/medic-webapp#3691

Avoid selecting multiple elements in webdriver tests

---

static/js/app.js
static/js/services/changes.js
templates/modals/version_update.html
tests/protractor/conf.js
tests/protractor/e2e/auditing.js
tests/protractor/e2e/bulk-delete.js
tests/protractor/e2e/contact-summary.js
tests/protractor/e2e/contacts/create-new-district.specs.js
tests/protractor/e2e/docs-by-replication-key-view.js
tests/protractor/e2e/forms/submit-delivery-form.specs.js
tests/protractor/e2e/registration-by-sms.js
tests/protractor/e2e/report-date-filter.js
tests/protractor/e2e/send-message.js
tests/protractor/e2e/sms-gateway.js
tests/protractor/e2e/submit-enketo-form.js
tests/protractor/helper.js
tests/protractor/page-objects/forms/delivery-report.po.js
tests/protractor/utils.js

This means we don't need to refresh as much as the changes feed updates the UI without any refresh. It also means we test more code because we're now testing the UI is updated automatically.
Also uses `done.fail` which actually fails the test and returns the error message so it's easier to debug when something goes wrong.
medic/medic-webapp#3696

Enable the changes feed for e2e tests

---

kanso.json

Specify recipients in config per countedReport, instead of using the countedReports array. It allows for batching.
medic/medic-webapp#3678

Document change of config for multi_forms_alert : recipients are specified per report.

---

static/js/controllers/contacts.js
tests/karma/unit/controllers/contacts.js

The home place was showing the primary contact's UUID instead of
name. This change makes the home place code use the same service
as the rest of the list so it renders consistently.
medic/medic-webapp#3723

Fully resolve home place

---

kanso.json

Rename multi_form_alert -> multi_report_alert. Rename config fields to use snake_case.
medic/medic-webapp#3677

Rename multi_form_alert -> multi_report_alert.

---

kanso.json

If num_reports_threshold gets too big we could get some memory problems when generating messages for the alert. 100 is really conservative.
medic/medic-webapp#3725

Document limit of 100 for num_reports_threshold in multi_report_alerts

---

static/js/services/enketo.js
tests/karma/unit/services/enketo.js

Without the reported_date the docs fail validate_doc_update.
medic/medic-webapp#3760

Set reported_date on extra docs in Enketo

---

static/js/services/get-contact-summaries.js
tests/karma/unit/services/get-contact-summaries.js

Before this change when a document had a contact or parent that
wasn't found in the database we defaulted to showing the UUID
because that's all the information we had available. This is a
common situation for restricted users who don't replicate the whole
tree.
Now the parent is hidden altogether so the only names shown are of
contacts you can view.
medic/medic-webapp#3752
medic/medic-webapp#3769

Hide contact when not found

---

static/css/theme.less

The default overflow wraps text under the icon, but using auto
causes the text to align vertically.
medic/medic-webapp#3758

Use overflow auto to get content to line up nicely

---

static/js/controllers/inbox.js
templates/inbox.html
tests/karma/unit/controllers/inbox.js

Due to a bug in worker-pouch or possibly Chrome if we query the DB
too quickly and the query throws then we get an uncaught exception
in the log. Querying info() first means the code executes only once
the database is ready.
medic/medic-webapp#3754

Delay db query to avoid uncaught exception

---

static/js/controllers/edit-user.js
static/js/services/db.js
tests/karma/unit/controllers/edit-user.js
tests/karma/unit/services/db.js
translations/messages-en.properties

The invalid characters are converted to their UTF code to reduce
the likelihood of collisions with other databases.
The create user UI has been updated to fail validation if the
username has unusual characters.
medic/medic-webapp#3778

Escape invalid characters when syncing with meta db

---

static/js/services/changes.js
tests/karma/unit/services/changes.js

To avoid losing changes while api is down (eg for an upgrade) record
the last sequence you got up to.
Additionally, record the first sequence instead of letting PouchDB
work it out itself, so that lastSeq always has a start value.
medic/medic-webapp#3783

Watching changes now understands where it left off

---

static/js/services/update-user.js
tests/karma/unit/services/delete-user.js

There are two documents for each user - the couchdb doc in the
_users database, and the settings doc in the medic database. When
deleting we delete both. If the couchdb user is not found the
service errored out making it impossible to delete the medic user
through the UI. Now the service continues if the couch user delete
404s.
medic/medic-webapp#3788

 Delete user continues if couch user not found

---

static/js/services/db-sync.js
tests/karma/unit/services/db-sync.js

By default pouchdb writes checkpoints locally and remotely when
a document is replicated. The checkpoint is so the next replication
can pick up where this one left off. For us this means lots of
checkpoints being replicated over slow connections.
This change keeps the checkpoints in the local database but removes
them on the remote database.
medic/medic-webapp#3644

Don't write remote checkpoints

---

static/js/controllers/contacts-report.js

Setting selected clears the cancel target so we need to wait for it
to finish before setting the cancel target.
medic/medic-webapp#3797

Set the cancel target after setting selected

---

static/js/services/contact-view-model-generator.js
tests/karma/unit/services/contact-view-model-generator.js

This change hydrates a places child places so the names of their
contacts are displayed in the child list.
medic/medic-webapp#3807

Hydrate child contact names

---

static/js/services/lineage-model-generator.js
tests/karma/unit/services/lineage-model-generator.js

This means wherever the lineage model generator is used we can now
access the details of the contact of a parent. For example, it's
useful to know the name and phone number of the contacts of the
parents when filling in forms.
medic/medic-webapp#3812

Hydrate the contacts of parents

---

tests/protractor/e2e/registration-by-sms.js
tests/protractor/utils.js

After looking at this for some time it's still not clear why it
would be failing. It's more important now to have reliability than
perfect coverage, so I've just removed the check.
Also fixes a warning about a selector referencing multiple elements.
medic/medic-webapp#3822

Remove the assertion that form name is resolved

---

Changes.md

We're not actually going to support this we've now decided. Instead,
just use patient_name like always
medic/medic-webapp#3838

Removing migration note

---

static/js/services/contact-view-model-generator.js
tests/karma/unit/services/contact-view-model-generator.js

array.find is not defined in Chrome 30 so use underscore instead.
medic/medic-webapp#3855

Refactor to not use array.find

---

tests/protractor/utils.js

This document stores sequence numbers, and so is only relevant on the
specific instance it was created on. Replicating it to another instance
will cause sentinel to behave incorrectly.
medic/medic-webapp#3860

Store sentinel meta-data in a _local document

---

static/js/controllers/contacts-content.js
static/js/controllers/messages-content.js
static/js/services/lineage-model-generator.js
tests/karma/unit/services/lineage-model-generator.js

The lineage model generator was returning an empty model when the
document with the given ID was not found. This caused uncaught
errors and made it less obvious to the user what was going wrong.
This change throws a 404 error which can be interpreted by the
caller and displayed to the user in some useful way.
medic/medic-webapp#3718

Throw an error when document not found

---

static/js/controllers/contacts-edit.js

This reduces the doc size by only storing the id of the related
docs rather than inlining the whole doc.
medic/medic-webapp#3785

Call extract lineage on the docs contact and parent

---

tests/protractor/e2e/registration-by-sms.js
tests/protractor/helper.js
tests/protractor/page-objects/common/common.po.js

Remove the function that checks if the element is attached - it
never worked. It did however add a 400ms wait so this might break
things that rely on a small wait.
medic/medic-webapp#3842

Remove broken function

---

static/js/controllers/contacts-content.js

Instead of showing the snackbar any time the contact isn't found,
only show it when it's not found and the user was trying to select
it. This means the snackbar won't show on background changes or a
badly configured facility_id.
medic/medic-webapp#3718

Don't show the snackbar except on user action

---

static/js/services/enketo.js

The version of the browser on the Tecno doesn't have the outerHTML
function for xml nodes. This change detects if it's missing and uses
a workaround if it is.
medic/medic-webapp#3880

Polyfill outerHTML function

---

static/js/controllers/inbox.js
templates/partials/configuration_upgrade.html

Show relative date tooltips on configuration pages

---

templates/partials/actionbar.html

The delete all button should be enabled when one or more records
are selected.
medic/medic-webapp#3808

Enable delete all button in select mode on mobile

---

static/js/services/lineage-model-generator.js
static/js/services/select2-search.js
static/js/services/user-contact.js
tests/karma/unit/services/lineage-model-generator.js
tests/karma/unit/services/user-contact.js

Moves the lineage mergine out of Select2Search and adds it behind
an optional parameter on the LineageModelGenerator so it can be
reused by UserContact which prepares data for the TargetGenerator
among others.
medic/medic-webapp#3890

Centralise merging lineage into the doc

---

package-lock.json
package.json

Bumps the dependency to the latest 1.3 release to get some bug
fixes.
medic/medic-webapp#3891

3891 bump xpath evaluator

---

package-lock.json
package.json

This will need backporting to 2.13

Update openrosa-xpath-evaluator to support dates with single-digit day and month values

---

static/css/theme.less
templates/modals/edit_user.html

The facility and contact are required only when adding a restricted
user, so this change adds an asterix when the type is set to
restricted.
Also adds a css class "required" for use on the form-group which
adds an asterix after the label which makes it easier to keep the
style consistent througout the app.
medic/medic-webapp#3561

Mark required fields when adding restricted user

---

static/js/services/contact-save.js
tests/karma/unit/services/contact-save.js

1. Siblings (in the case of a family form, the head of household)
already get their parent lineage mostly correct, because they attach the
doc as the parent, (see the if (child) block in
prepareAndAttachSiblingDocs()) which then later on (see the promiseChain
in the same function) get loaded from CouchDB with its whole hierarchy.
However, they still need to extract the lineage to clean it up
2. Repeated docs preperation was moved until *after*
prepareAndAttachSiblings was run, so that the doc they prepare against
has its parents loaded correctly (the same state the siblings rely on)
NB: this is really gross. It relies on non-obvious ordering. I've added
comments, but we should consider reworking this
medic/medic-webapp#3840

Inner docs should have correct lineages

---

static/js/app.js
static/js/bootstrapper.js
static/js/services/debug.js
static/js/services/session.js
tests/nodeunit/unit/bootstrapper.js

Previously we checked for the cookie after bootstrapping which
meant if the redirect to the login page was cancelled, for example
by pressing "esc", then the user could access the offline data
without a cookie or session. The navigation can still be cancelled
but the app won't be bootstrapped so the data cannot be easily
accessed.
This change also fixes how we remove cookies so it actually works.
medic/medic-webapp#3239

Check for userCtx cookie before bootstrapping

---

static/css/content-list.less
static/css/material.less
static/js/directives/content-row.js
static/js/services/contact-schema.js
static/js/services/live-list.js
templates/partials/actionbar.html
templates/partials/contacts_content.html
templates/partials/content_row_list_item.html
tests/karma/unit/services/contact-schema.js

Uses the static resources doc rather than the font awesome fonts
which means we have more flexibility and also makes the icons
configurable.
medic/medic-webapp#3945

Loads contact icons from resources not font awesome

---

tests/protractor/e2e/registration-by-sms.js
tests/protractor/e2e/sms-gateway.js

On clicking report tab, report page takes time to load and the ‘.loading-status ng-hide’ displays first  the spinner then  ‘No reports’ then the reports list finally loads… This has been the root cause of some test failures ( #3509 ). While waiting for related issue to be fixed, I have inserted a `wait for the list to load` line of code in relevant tests. (Screenshot was taken from a Travis job).

Make e2e stable

---

static/js/controllers/edit-user.js
templates/modals/edit_user.html
tests/karma/unit/controllers/edit-user.js
tests/protractor/e2e/users/add-user.specs.js
tests/protractor/page-objects/common/common.po.js

If type isn't set the app behaves very strangely when the user
logs in.
This change also rearranges the order of validations to the order
they appear on screen.
medic/medic-webapp#3904

Make type a required field when saving users

---

static/css/inbox.less
static/css/material.less
static/css/variables.less
static/js/filters/resource-icon.js
static/js/services/resource-icons.js
templates/partials/contacts_content.html
tests/karma/unit/services/resource-icon.js

The ResourceIcons service and resourceIcons filter now detect if
the icon is an svg and inline the xml if it is. This means we can
now apply css styles to the svg which is important, for example,
when we want to use a coloured icon for clinic in the list and the
same icon in white in the action bar.
medic/medic-webapp#3945

Update resource icons to inline svgs

---

Changes.md
kanso.json

Actual code change is here:
https://github.com/medic/medic-sentinel/commit/f9b539a7f9a8ddec245307bb216b19d6e7a31fb7
medic/medic-webapp#3818

Documentation for silence_for change

---

kanso.json
lib/views.js
static/js/controllers/guided-setup-modal.js
templates/modals/guided_setup.html

Including three (3!) views that were only used by this feature.
medic/medic-webapp#3950

Dropping usage-stats that we don't use anymore

---

static/js/services/db-sync.js
tests/karma/unit/services/db-sync.js

The PouchDB implementation has a bug causing the app to replicate
from 0 on load which would cause a significant performance issue
for us. Revert this commit when the underlying issue has been
resolved.
medic/medic-webapp#3898

Disable single sided checkpointing

---

static/js/services/add-read-status.js
static/js/services/changes.js
static/js/services/unread-records.js
tests/karma/unit/services/add-read-status.js
tests/karma/unit/services/changes.js
tests/karma/unit/services/unread-records.js

Without the listener admins don't see the updated status bubbles
until they refresh the page. This also extends the Changes service
to be able to register listeners on the meta db.
Finally it also fixes a bug where the reports list was styling
reports with deleted read docs as read rather than unread.
medic/medic-webapp#3944

Register change listener on meta db

---

static/js/controllers/messages.js
static/js/controllers/reports.js

The reports controller wasn't waiting for the async response
before setting loading to false. The messages controller wasn't
defaulting loading to true so there was a lag before the spinner
was shown.
medic/medic-webapp#3969

Don't show no more reports when there are reports

---

static/js/filters/date.js
static/js/services/format-date.js
tests/karma/unit/filters/relative-date.js
tests/karma/unit/services/format-date.js

Modifies our relative date logic so that if the date is today, show the
time (10:10 AM) instead. Dates later or earlier than today will show
relative values as normal (3 days ago).
medic/medic-webapp#3613

Show time for today instead of relative date

---

static/js/services/changes.js
tests/karma/unit/services/changes.js

Don't let !options be a possible path to an if statement that then
expects options to exist.
Correct unsubscribe so that it completely removes the callback item.
medic/medic-webapp#3985

Clarity, correct unsubscribe

---

static/css/enketo/medic.less

CSS updates to make Enketo forms more consistent with the rest of
our app. Mostly updates to font sizes, whitespace, and colours.
medic/medic-webapp#3961

Enketo form styling updates

---

.gitignore
Procfile
package.json

I use [`foreman`](https://www.npmjs.com/package/foreman) for running services in dev.  Now everything's in one repo, it makes sense to store the `Procfile` here.  I thought this might be interesting to others.
On this branch, run `npm start` to run webapp, api and sentinel concurrently.

Use foreman for managing services in dev

---

static/js/controllers/reports.js
static/js/services/place-hierarchy.js
templates/partials/filters/facility.html
templates/partials/filters/facility_items.html
tests/karma/unit/controllers/reports.js
tests/karma/unit/services/place-hierarchy.js
translations/messages-en.properties

Change the stub removal rules so that you hoist the children of a stub up a
level in cases where there is only one parent stub to a collection of children.
This means restricted users will have the parents they are unable to see hidden,
but we won't just throw away arbitrary trees of facilities because there is a
stub at some level.
Changed the UI so that if it has to display a stub facility it says [deleted]
for admins (because we know it's deleted) and [unavailable] for restricted
users, because it may be deleted, or we may just not have permissions to see it.
medic/medic-webapp#3902

Improved facility filter logic

---

Gruntfile.js
package-lock.json
package.json

[`optimize-js`](https://github.com/nolanlawson/optimize-js) adds hints to the browser's JS parser to make it treat immediately-executed functions more efficiently.  From a brief play, it looks like it might make our JS parsing a bit faster - so app start-up time should be improved.
This looks like it should be considered, although the results for Chrome 30 don't look believable.  
`templates.js` also showed significant speedup, but it's already about 10 times as fast as `inbox.js`.

Speed up javascript loading

---

static/css/inbox.less

Issue #4010 
I can't find any `.item-content label` instances which are not also `.item-content .body label`, so unless any are created programmatically (apart from the enketo ones), then this change should be safe.

Make disabled labels in enketo forms hidden again

---

sentinel/lib/validation.js
sentinel/test/unit/validations.js

The view sorting doesn't work as expected so resort to checking the
reported_date of each doc until one is found.
medic/medic-webapp#651

Remove bad assumption from uniqueWithin validation

---

.jshintrc
static/js/enketo/widgets/android-datepicker.js
static/js/enketo/widgets/countdown-widget.js

Seems weird to have a lint exception for this, especially when we're often referencing it via `window` (or `$window`).

Don't allow unqualified medicmobile_android references

---

static/css/content-list.less
static/css/dropdown.less
static/css/material.less
static/css/targets.less
static/css/theme.less
static/css/variables.less

We have two sizes of icons: 30px by 30px and 60px by 60px. All
icons are to be scaled to these sizes. This may cause scaling
issues for small or non-square icons but these should be replaced
with square svgs.
medic/medic-webapp#4063

Force icons to our dimensions

---

static/js/enketo/widgets/simprints.js

This means that user can see when they have succesfully set a value for this
field.
Issue: #3511

Make Simprints registration input field visible

---

sentinel/test/unit/transitions.js
sentinel/transitions/index.js

It's annoying that we can't tell when sentinel has finished processing.

Log when sentinel catches up to the changes feed on start up

---

Changes.md
api/config.default.json
api/migrations/add-permissions-configuration.js
templates/partials/actionbar.html

Added two new permissions to the configuration in medic-webapp: `can_view_message_action` and 
`can_view_call_action` to determine whether these actions are available to particular users.
Also wasn't 100% clear on when the `config.default.json` is used along with the add permissions migration, but figured it probably needed to be added to both.
medic/medic-webapp#3657

3657 Hide message and call actions based on configurable permissions

---

templates/partials/configuration_upgrade.html

Instead of displaying the default message saying "instance
must be deployed via Horticulturalist" before the DDOC is fetched,
show a loading throbber. Once the DDOC is downloaded, relevant content
is displayed (either the "no-horti" message or the actual UI).
medic/medic-webapp#3966

Adds loading throbber to "Configuration > Upgrade" before DDOC load

---

Changes.md
static/js/app.js
static/js/controllers/contacts-edit.js
static/js/controllers/contacts-report.js
static/js/controllers/reports-add.js
static/js/controllers/tasks-content.js
static/js/services/enketo.js
templates/partials/contacts_edit.html
templates/partials/contacts_report.html
templates/partials/reports_add.html
templates/partials/tasks_content.html
tests/karma/unit/services/enketo.js
translations/messages-en.properties

Added in a `type` property to the `Error` being thrown to determine what type of error it was (generic or because of the lack of associated contact), and thus display a different error message depending on error type.
medic/medic-webapp#1359

1359 No associated contact error message

---

static/js/controllers/configuration-translation-application.js
templates/partials/configuration_translation_application.html

Adding Translation-Keys option to the list of languages
medic/medic-webapp#3022

Adding Translation-Keys option to the list of languages

---

static/js/directives/enter.js
static/js/directives/index.js
templates/directives/modal.html
tests/karma/unit/directives/enter.js

Adding support to delete a single user by using enter in the delete modal dialog.
medic/medic-webapp#2309

Adding support to delete a user with enter

---

Gruntfile.js
api/package-lock.json
api/package.json
api/server.js
package-lock.json
package.json
shared-libs/hello-world/index.js
shared-libs/hello-world/package-lock.json
shared-libs/hello-world/package.json
static/js/controllers/about.js

Not for merging, just for discussion.
This seems like a nice way to do shared libs. I'm not sure yet if it works in Yarn, which could be an issue. This means that we get to have shared libraries that don't need to be versioned separately and go through npm publishing.
Interestingly enough, npm actually uses symlinks, so you don't even need to npm install again when a shared lib changes. `grunt dev` would only need to know that the dir has changed and then re-run itself.

Way we could do shared libs

---

static/js/services/delete-docs.js
tests/karma/unit/services/delete-docs.js

When a report is submitted by the district's primary contact,
applying LineageModelGenerator on that report results in a circular
referenced object, which throws an error when attempting to delete.
Fix is to minify the report's contact lineage prior to deletion.
medic/medic-webapp#4076

Fixes bug where circular reference prevents report deletion

---

api/config.default.json
static/js/controllers/inbox.js
static/js/controllers/index.js
static/js/controllers/logout-confirm.js
templates/modals/logout_confirm.html
templates/partials/header.html
translations/messages-en.properties

Users can now log out if in a browser or if the can_log_out_on_android
permission is set. By default no roles have that permission so
existing instances will continue to behave as they always have.
medic/medic-webapp#3450

Add permission to allow mobile users to log out

---

sentinel/test/mocha/transitions/accept_patient_reports.js
sentinel/test/mocha/transitions/registration.js
sentinel/test/unit/patient_registration.js
sentinel/transitions/accept_patient_reports.js
sentinel/transitions/registration.js

During transitions update docs to have uuids of related docs. This makes it easier
to perform certain analytics queries.
medic/medic-webapp#3959

Increase linkages between SMS reports and other docs to streamline analytics queries

---

api/server.js

Should make it more obvious what we're waiting for when api is starting.

Add more logging to api startup

---

.gitignore
api/auth.js
api/config.default.json
api/handlers/changes.js
api/migrations/add-permissions-configuration.js
api/tests/unit/auth.js
api/tests/unit/handlers/changes.js
static/js/controllers/inbox.js
static/js/controllers/messages.js
static/js/controllers/reports.js
templates/partials/actionbar.html
tests/karma/unit/controllers/inbox.js
tests/karma/unit/controllers/reports.js

Following on from discussion in the issue, the changes handler has been changed to check for `admin` or `national_admin` roles instead of the `can_access_directly`. The only other use for `can_access_directly` was to show the export action icon which shouldn't be configurable, so this has been modified to check for the same roles.
medic/medic-webapp#4144

4144 Fix permission and role checking in changes handler and action bar

---

static/js/services/contact-summary.js
static/js/services/enketo.js
tests/karma/unit/services/contact-summary.js
tests/karma/unit/services/enketo.js

Adds additional validation and fallbacks for the values returned by
`app_settings.contact_summary` function to avoid runtime errors when
loading app forms.
medic/medic-webapp#4125

Fixes `contact_summary` returning undefined/non-array values form crash

---

api/handlers/changes.js
api/tests/unit/handlers/changes.js

If the list of doc IDs the user can view has changed between when
the change request was made and when the callback is invoked then
we need to make a new change request using the updated list of IDs.
medic/medic-webapp#4166

Check for updated permissions on change

---

sentinel/test/mocha/transitions/death_reporting.js
sentinel/transitions/death_reporting.js

Enhances death reporting by allowing reporting death confirmations
using the UUID of the patient in cases where they don't have a
shortcode, for example, smartphone deployments.
medic/medic-webapp#3956

Death reporting by UUID

---

static/js/services/contact-view-model-generator.js
tests/karma/unit/services/contact-view-model-generator.js

Places with deceased children will now show the reports for those
children on the contact detail page in the list of reports.
medic/medic-webapp#3956

Include reports from deceased children in place profile

---

static/js/controllers/inbox.js
static/js/filters/date.js
static/js/services/index.js
static/js/services/recurring-process-manager.js
static/js/services/relative-date.js
tests/karma/unit/controllers/inbox.js
tests/karma/unit/filters/relative-date.js
tests/karma/unit/services/recurring-process-manager.js
tests/karma/unit/services/relative-date.js
tests/mocha/unit/filters/date.spec.js

Adds a service which handles recurring processes and adds some
additional markup to relative dates, so the displayed text can be
regenerated at desired intervals.
medic/medic-webapp#2753

Update relative dates throughout the app.

---

Gruntfile.js
api/controllers/export-data-2.js
api/package-lock.json
api/package.json
api/server.js
api/tests/mocha/.jshintrc
api/tests/mocha/controllers/export-data-2.js
ddocs/medic-client/views/reports_by_form/reduce.js
scripts/mp-2584-unclearing-schedules/find_registrations.js
shared-libs/search/src/generate-search-requests.js
shared-libs/search/src/search.js
shared-libs/search/test/generate-search-requests.js
static/js/services/download-url.js
static/js/services/search.js
tests/karma/unit/services/download-url.js
tests/protractor/e2e/api/controllers/export-data-2.js
tests/protractor/e2e/api/controllers/messages.js
tests/protractor/e2e/api/controllers/users.js
tests/protractor/e2e/api/handlers/changes.js
tests/protractor/utils.js

Adds a new version of exporting, currently just for reports.
Features include only supporting a single CSV, streaming the output for server performance, and using the same query logic as the front end.
medic/medic-webapp#3594

Report exporting 2.0

---

sentinel/test/unit/update_clinics.js
sentinel/transitions/index.js
sentinel/transitions/registration.js
sentinel/transitions/update_clinics.js

Valid SMS forms would not generate a PNC schedule because of missing
doc properties at transition time.
To fix, Sentinel transitions are now in a specific order, so
`update_clinics` is executed before `registration`.
Also, `update_clinics` hydrates the contact property.
medic/medic-webapp#4201

Fixes bug where PNC schedule was not being added for valid SMS forms

---

sentinel/lib/lineage.js
sentinel/test/unit/lineage.js
static/js/services/contact-save.js
static/js/services/enketo.js
tests/karma/unit/services/contact-save.js
tests/karma/unit/services/enketo.js

When saving with bulkDocs it's possible that the docs will be
replicated to the server one at a time. This causes sentinel
hydration to not find the parent doc which then is set to null
and the doc is later persisted.
This change handles this situation gracefully by
- changing sentinel hydration to leave the stub if no doc found
so data is not lost, and
- changing the contact save service to save the parent doc before
any children docs so they are replicated first.
This also modifies the enketo service to use bulkDocs instead of
multiple individual puts.
medic/medic-webapp#4200

Gracefully handle partial doc replication

---

sentinel/lib/lineage.js
sentinel/test/unit/lineage.js

When processing changes, fetchHydratedDoc is called before any
transition. In the case of SMS reports, for example, buildHydratedDoc will
receive an empty array as lineage parameter, which will cause it to
throw a TypeError. This stops all of the transitions from executing.
The fix is to return original document if lineage array is empty.

Sentinel buildHydratedDoc SMS transition bugfix

---

static/js/enketo/widgets/phone-widget.js

The phone widget adds an input for interacting with in the UI but
keeps the form input for the formatted phone value. The UI input
has to have the `data-relevant` attribute removed otherwise
Enketo tries to process it.
medic/medic-webapp#4230

Remove the relevant attribute from UI fields

---

static/js/controllers/configuration-upgrade.js
templates/partials/configuration_upgrade.html

After clicking the upgrade button, the loading throbber and the upgrade
message stay visible until the upgrade is complete and the app is
redeployed by Horticulturalist.
Adds a little markup in the template so the upgrade error is more
obvious.
medic/medic-webapp#3967

Makes Horticulturalist UI upgrade throbber visible until deployment

---

sentinel/test/functional/transitions.js
sentinel/transitions/index.js

Transitions are now guaranteed to run in the order listed in the
available transitions array.
medic/medic-webapp#3565

Enforce transition order

---

api/handlers/changes.js
static/js/services/changes.js

Issue: #4236
Looks like it works locally.  Should be backported to `2.14.x`.

Always set return_docs:false in PouchDB.changes() calls

---

static/js/bootstrapper.js
tests/nodeunit/unit/bootstrapper.js

We should do this as a first step.  Should be backported to `2.14.x`.
Issue: #4196

Close bootstrapper database when we've finished with it

---

sentinel/transitions/index.js

As a consequence of changing `transitions` from Object
pairs to Array, every time sentinel config were reloaded,
all available transitions were pushed into the array.
Hence, after multiple reloads, the transitions array had
as many duplicates, all of which were applied to changes.
The fix is to empty the transitions array on load.

Empties transitions array on load

---

api/handlers/changes.js

With longpoll replication we don't make multiple requests to couch
so there's only one response. In this case we can shortcircuit
response merging and sorting and just copy the response.
This gives us a small performance improvement for a common use case.

Don't merge changes responses if there's only one

---

static/js/controllers/contacts-edit.js
static/js/controllers/reports-add.js

When editing a report or a contact we need to hydrate the parents
and contacts so information like the contact's name is bound to the
form model and can be shown.
medic/medic-webapp#4258

Hydrate docs when editing

---

api/controllers/export-data.js
shared-libs/search/src/generate-search-requests.js
static/js/controllers/reports.js

Remove cruft from the URL that we don't need to perform the search.
Flush headers ASAP to reduce the time it takes for the download to initiate on the client side.
medic/medic-webapp#3594

Shorter export urls and reduce export latency

---

static/js/controllers/contacts.js
tests/karma/unit/controllers/contacts.js

Adds a switch that modifies skip/limit in Contacts Search queries, depending
on whether or not current user's HomePlace is pushed at the start of the LiveList.
medic/medic-webapp#4085

Adds a switch that modifies skip/limit in Contacts Search queries if needed

---

package-lock.json
package.json
tests/protractor/utils.js

Add `pouchdb-mapreduce` for testing db contents in e2e tests.

Add pouchdb-mapreduce plugin for e2e tests.

---

static/js/controllers/contacts-content.js
static/js/services/contact-change-filter.js
static/js/services/debounce.js
static/js/services/index.js
tests/karma/unit/controllers/contacts-content.js
tests/karma/unit/services/contact-change-filter.js
tests/karma/unit/services/debounce.js

ContactsContent page is now updated when a relevant change is received
through the Change listener.
The following are considered relevant changes: selected contact,
any ancestor, any direct child (new, current or removed), any
report with a subject matching either selected contact or a child.
medic/medic-webapp#3530

Adds Change feed filtering in ContactsContent to keep info up to date

---

static/js/controllers/reports.js
templates/partials/actionbar.html

We can't (easily?) tell when a download has actually returned to the
user, so disable the button for 2 seconds and hope that 2s is enough
time.
medic/medic-webapp#3594

Disable download button temporarily

---

static/js/services/get-subject-summaries.js
tests/karma/unit/services/get-subject-summaries.js

When an XML form uses patient_id as uuid field and lacks an actual
patient_uuid field, the code returned a false Unknown Subject.
This change adds a double check for "reference" type values, both
as an actual reference and as an UUID to avoid this from happening.
medic/medic-webapp#4053

Updates GetSubjectSummaries to double check patient_id fields

---

api/services/export-data.js
packages/kujua-sms/kujua-sms/lists.js
sentinel/transitions/resolve_pending.js
shared-libs/task-utils/src/task-utils.js
shared-libs/task-utils/test/set-task-state.js
tests/nodeunit/unit/kujua-sms/lists.js

Reverts setting task timestamp everytime the task state is updated to 
only when the task receives 'sent' status. 
medic/medic-webapp#4281

Reverts setting task timestamp every time task state is updated

---

ddocs/medic-client/views/doc_summaries_by_id/map.js
static/js/services/contact-change-filter.js
tests/karma/unit/services/contact-change-filter.js
tests/mocha/unit/views/doc_summaries_by_id.spec.js

Replaces usage of `patient_uuid` fields with `patient_id` when trying to determine or compare with report subject. 
medic/medic-webapp#4053
medic/medic-webapp#3530

Replaces usage of patient_uuid with patient_id

---

sentinel/test/mocha/transitions/accept_patient_reports.js
sentinel/transitions/accept_patient_reports.js

The registration transition shouldn't add the registration_id field.
medic/medic-webapp#3959

Don't add registration_id to registration forms

---

api/controllers/export-data.js
shared-libs/lineage/src/lineage.js

Individual fixes that have come out of testing lineage:
- Fixing bad revert of a refactor to the v1 export library
- Fixing v2 export libraries addition of quick head flushing to only effect v2, and for v2 errors to understand that headers have been flushed
- Fixing lineage so it handles data_records that don't have contacts (ie JSON forms)
medic/medic-webapp3826

3826 lineage refactoring fixes

---

.travis.yml

Make the travis build log quicker to load and easier to understand at a glance.
This also changes previous behaviour so that uploads to s3 of test reports only happen for _failed_ build jobs, rather than all.
An example of a successful and failed build can be seen at https://travis-ci.org/medic/medic-webapp/builds/356822011.
Log files are suffixed with `.txt` so that they are served with a suitable `content-type` header by s3 for direct reading in the browser.
This PR also removes an apparently uninteresting call to `docker ps -a`.
Closes #4316
Closes #4317

travis: push webdriver and docker logs to s3

---

static/js/controllers/contacts.js
static/js/services/contact-summary.js
templates/partials/contacts_content.html
tests/karma/unit/controllers/contacts.js
tests/karma/unit/services/contact-summary.js
translations/messages-en.properties

When setting the selected contact fails, displays an error message, clears the right action bar and logs the error instead of displaying an incomplete/incorrect `ContactContent` / action bar. 
Adds error handling for configuration function `contact-summary`.
medic/medic-webapp#4301

Adds error handling for Contact selection

---

templates/partials/reports_content.html

The translation key was mistakenly updated from `selection.doc.content.raw` to `selection.formatted.content.raw`, this PR reverts it to its correct value.
medic/medic-webapp#4325

4325 Reverts raw report content translation key

---

sentinel/lib/validation.js
sentinel/test/unit/validations.js

The view map function lowercases the keys it outputs so we need
to lowercase to get the right results.
medic/medic-webapp#651

Lowercase view request keys

---

static/js/services/contact-change-filter.js
tests/karma/unit/services/contact-change-filter.js

Fixes error thrown in ContactChangeFilter when contact lineage is undefined.

ContactChangeFilter undefined lineage bugfix

---

tests/protractor/e2e/api/controllers/sms-gateway.spec.js

Adds two new tests for the `/api/sms` endpoint.

Add tests for bad sms gateway status updates

---

api/server-utils.js
api/tests/unit/server-utils.js

Replaces 301 with 302 so redirect isn't cached.
medic/medic-webapp#4364

Replaces 301 with 302 so redirect isn't cached.

---

sentinel/lib/messages.js
sentinel/test/unit/patient_registration.js
sentinel/transitions/accept_patient_reports.js
sentinel/transitions/registration.js
sentinel/transitions/update_notifications.js

Provide `patient` information as template context for sentinel transitions error messages, so `{{patient_name}}` is resolved. 
medic/medic-webapp#4373

Provide patient in template context for sentinel transitions error messages.

---

.travis.yml
Gruntfile.js
api/db-nano.js
api/db-pouch.js
api/message-utils.js
api/tests/integration/migrations/utils.js
api/tests/unit/controllers/records.js
api/tests/unit/controllers/sms-gateway.js
api/tests/unit/message-utils.spec.js

Previously, changes made to core libraries in unit tests could leak through into integration tests.
This also switches `api/message-utils` to use pouch instead of nano, but there appears to be no change in performance due to this switch.

Use PouchDB in message-utils; fix unit test envs on Travis

---

static/js/services/format-data-record.js
tests/karma/unit/services/format-data-record.js

Show the persisted message if possible but otherwise generate the
message. This shows the message that will be or would have been
sent for unsent states such as 'cleared'.
medic/medic-webapp#4388

Shows cleared messages

---

Gruntfile.js
shared-libs/lineage/test/lineage.js

This PR re-enables running of the lineage unit tests, but disables them all via `describe.skip()`.  This will have a marginal effect on build times, mainly due to an extra run of `npm install` within the `shared-lib/lineage` directory.
However, I think it's worthwhile as it allows for https://github.com/medic/medic-webapp/pull/4429 — running tests for _all_ shared libs, rather than having to manually add each to the list in `Gruntfile.js`.
Issue: #4425

[wip] Enable lineage unit tests

---

api/controllers/login.js
api/routing.js
api/tests/unit/controllers/login.js
static/js/controllers/inbox.js
static/js/services/session.js
tests/karma/unit/controllers/inbox.js
tests/karma/unit/services/session.js

Adds Change feed listener for changes made to current user. If changes in roles are detected, 
the user is notified with a VersionUpdate Modal. 
Adds api endpoint that simply refreshes userCtx cookie. 
medic/medic-webapp#4088

Refresh userCtx cookie when roles are changed

---

Gruntfile.js
admin/src/js/main.js
admin/src/templates/index.html
webapp/src/ddocs/medic-admin/rewrites.json

- Pass jquery in to select2 so it binds to the right instance
- Bundle the templates so they don't have to load asynchronously
medic/medic-webapp#4461

Fixes how select2 inits

---

sentinel/src/schedule/due_tasks.js
sentinel/tests/unit/due_tasks.js

Fixes a bug where the hydration api was being called with the patient shortcode instead of the uuid.
medic/medic-webapp#4453

Hydrates patient by UUID not shortcode

---

api/controllers/export-data.js

The headers were flushed immediately for v2 to support streaming,
but this broke v1 which prepares all the data and sends in a single
command.
medic/medic-webapp#4455

Defers writing headers for export v1 api

---

sentinel/src/lib/infodoc.js
sentinel/src/transitions/index.js

Removes _rev from doc when moving between dbs.
medic/medic-webapp#4465

Removes _rev from doc when moving between dbs

---

sentinel/src/schedule/due_tasks.js
sentinel/tests/unit/due_tasks.js

The old style of messages are generated up front and never updated.
For backwards compatibility these messages should be left unchanged.
medic/medic-webapp#4476

Don't overwrite already generated messages (master)

---

sentinel/schedule/due_tasks.js
sentinel/test/unit/due_tasks.js

The old style of messages are generated up front and never updated.
For backwards compatibility these messages should be left unchanged.
medic/medic-webapp#4476

Don't overwrite already generated messages (2.15.x)

---

Gruntfile.js
webapp/src/ddocs/medic/build_info/node_modules.json

yarn pack has a bug where it doesn't include the node_modules so we
should use npm pack until that bug is fixed.
medic/medic-webapp#4489

Switches to use npm pack

---

api/services/export-data.js

This allows the exports to return something useful until streaming
lands in 3.0.
medic/medic-webapp#4455

Limits the v1 exports to 1000 records

---

webapp/src/js/controllers/analytics-targets.js
webapp/src/templates/partials/analytics/targets.html

Adds a loading spinner to the targets page
medic/medic-webapp#4241

Adds a loading spinner to the targets page

---

api/src/controllers/users.js
api/src/services/types-and-roles.js
api/tests/mocha/services/types-and-roles.js
api/tests/unit/controllers/users.js

Previously if you passed an unknown type into `getRoles()` it would return `[ 'your-unkown-type', undefined ]`, which couchdb would then reject as an invalid list of roles.

Handle unrecognised roles in api's user controller

---

sentinel/src/transitions/update_notifications.js
sentinel/tests/unit/transitions/update_notifications.js

We can now use either message arrays or translation_key configuration
but prior to this change the transition was only checking for the
former.
medic/medic-webapp#4513

Fixes bug detecting configured on/off forms

---

webapp/src/js/services/format-data-record.js

We were using the webapp user's configured language for displaying
scheduled messages but we decided to change it to use the locale
that the message will be sent using so you can preview how it will
acutally work.
medic/medic-webapp#4514

Translates scheduled messages using the given locale

---

sentinel/src/db-pouch.js

Bypasses initing pouchdb when UNIT_TEST_ENV is set

Bypasses initing pouchdb when UNIT_TEST_ENV is set

---

api/db-pouch.js
api/routing.js
api/services/bulk-docs.js
api/tests/mocha/services/bulk-docs.js
shared-libs/bulk-docs-utils/src/bulk-docs-utils.js
static/js/services/delete-docs.js

We want to force deletion of documents and retry any failures a set number of times before giving up. This should force deletion in case of conflict, an alternative would be to use the `new_edits` flag but that doesn't seem to be its intended purpose...
medic/medic-webapp#4469

4469 Bulk delete retry errors

---

webapp/src/js/services/z-score.js
webapp/tests/karma/unit/services/z-score.js

Chrome reports request 404s in the console which can look alarming.
Using allDocs instead means we can handle the valid case of the
zscore doc being missing without an error being logged.
medic/medic-webapp#4548

Uses allDocs to handle 404s gracefully

---

api/migrations/remove-can-access-directly-permission.js

Removes the can_access_directly permission

---

sentinel/lib/message-utils.js
sentinel/test/mocha/lib/message-utils.js
static/js/modules/message-utils.js

This means if you ask for "clinic" it'll attempt to resolve the
clinic of the patient, not the sender. This allows for reports to be
submitted by anyone about a patient which generate scheduled tasks
for the patient's CHP.
medic/medic-webapp#4512

Makes recipient resolution patient centric

---

README.md
sentinel/README.md

I was reading through the README and associated documentation and found some broken links and typos, so I fixed those.
BTW, the README mentions [a Google Group](https://groups.google.com/forum/#!forum/medic-developers), but it seems inactive. Perhaps the link should be removed?

Documentation fixes

---

README.md

I finished setting up the app locally today and found some additional missing pieces in the README.
Yarn was updated to 1.7.0 in 0412e977204f695e3889290d6acfb6bb9f39febb.
`yarn start` will fail without dependencies installed for webapp and admin.

Fixes setup instructions in the README

---

shared-libs/message-utils/src/index.js
shared-libs/message-utils/test/index.js

This fixes two bugs;
Firstly, the "parent" and "grandparent" properties were based on having
clinic centric reports and were off by one in a patient centric world.
This meant when resolving the phone number iterating up the "parent" to
find the closest place of a certain type often started at the wrong level.
Secondly, when making the template context the current doc properties
should take precedence over the previous registrations.
medic/medic-webapp#4512

Fixes message recipient resolution

---

api/src/translations.js
api/tests/mocha/translations.spec.js

Because `angular-translate` expects all translations to be strings and `properties` package `cast` prioritises Booleans and Numbers before Strings, all translations must be converted to strings before being saved in CouchDB. 
medic/medic-webapp#4584

Converts all non-string translations to string.

---

api/package.json
api/src/routing.js
api/yarn.lock

Uses the helmet library with default settings to set/unset response
headers to protect against common attacks.
medic/medic-webapp#1140

Sets response headers to increase security

---

webapp/src/js/services/format-data-record.js

Passing null as the translation sanitization strategy disables it
which is safe in this case because the string is escaped when
rendered by angular.
medic/medic-webapp#4618

Fixes double escaping of messages

---

Gruntfile.js
admin/src/js/controllers/upgrade.js
admin/src/js/directives/release.js
admin/src/js/filters/build-version.js
admin/src/js/main.js
admin/src/js/services/version.js
admin/src/templates/release.html
admin/src/templates/upgrade.html
admin/tests/unit/services/version.js
webapp/src/ddocs/medic/_attachments/translations/messages-en.properties

Adds a warning flag to releases that may be incompatible because the base version of the release is older than your current base version.
medic/medic-webapp#4580

Flag potentially incompatible releases

---

api/README.md
api/auth.js
api/controllers/bulk-docs.js
api/controllers/export-data.js
api/handlers/changes.js
api/tests/mocha/controllers/bulk-docs.js
api/tests/mocha/controllers/export-data.js
api/tests/unit/auth.js
api/tests/unit/handlers/changes.js
static/js/bootstrapper.js
static/js/services/session.js

national_admin is no longer the only way to designate a user as
online only. This checks for the mm-online role in addition
everywhere we were checking for national_admin.
medic/medic-webapp#4525

Fixes everywhere that relied on national_admin

---

sentinel/src/db-nano.js
sentinel/src/transitions/index.js
sentinel/tests/unit/transitions.js
webapp/src/ddocs/medic/views/online_user_settings_by_id/map.js

Deletes all read docs, not just admin ones, so there is no change a
user will still have a read doc with no corresponding doc.
Removes an obsolete view which doesn't work now we have configurable
roles.
medic/medic-webapp#3960

Fixes a race condition in deleting read docs

---

api/src/services/authorization.js
api/tests/mocha/services/authorization.js
shared-libs/view-map-utils/src/view-map-utils.js
shared-libs/view-map-utils/test/view-map-utils.js
webapp/src/ddocs/medic/views/docs_by_replication_key/map.js

If the report has a field named "needs_signoff" then the submitter
is also considered a subject which means any supervisor who can see
the submitter can also see their report. This allows specific
reports to be replicated to supervisors for review.
medic/medic-webapp#4591

Allows replication of specific reports to supervisors

---

sentinel/test/mocha/transitions/death_reporting.js
sentinel/transitions/death_reporting.js

The old configuration used the reporting_date of the confirmation
as the date_of_death of the patient. This enables the transition
to be configured to use any other property in the report so users
can provide the actual date of death.
medic/medic-webapp#4636

Allows configuration of date of death field

---

ddocs/medic-client/views/doc_summaries_by_id/map.js
static/js/services/get-summaries.js
static/js/services/live-list.js
templates/partials/reports_content.html
tests/mocha/unit/views/doc_summaries_by_id.spec.js

If the patient with the patient_id isn't found but the form has a
patient_name field then show that value. Otherwise display
"unknown subject" as before.
This is useful for supervisors who don't have access to the patient
doc.
medic/medic-webapp#4591

Shows patient name if submitted

---

api/server.js

Toward #4676
Emit NODE_OPTIONS during API startup. Doing this proved useful for diagnostic purposes while troubleshooting an OOM issue in production, and it seems fairly harmless. Useful for observing things like `--max_old_space_size`. Always a string.
medic/medic-webapp#4676

Emit NODE_OPTIONS during API startup

---

api/controllers/messages.js
api/tests/unit/controllers/messages.js

Improves performance by not making db updates where nothing changed but the _rev.
medic/medic-webapp#4688

Saves docs only if the task state has updated

---

api/src/routing.js
api/src/server-utils.js
tests/e2e/api/controllers/changes.js

If proxies throw errors, don't try to send headers twice.

Fix proxy headers on errors

---

sentinel/src/transitions/registration.js
sentinel/tests/unit/patient_registration.js

Adds support for the following fields:
months_since_dob, months_since_birth, age_in_months,
years_since_dob, years_since_birth, age_in_years
medic/medic-webapp#4597

Supports new registration fields to define age in months or years

---

api/src/controllers/changes.js
api/src/services/db-config.js
api/tests/mocha/controllers/changes.js
api/tests/mocha/services/db-config.spec.js

By default, PouchDB http adapter batches changes requests with a batch size of 25. 
Because we're already creating our own batches by splitting `_doc_ids`, forcing PouchDB not to batch brings a slight performance improvement and also fixes missed changes bug due to CouchDB not calculating sequences reliably. 
Updates `feeds` to use new `req.id` property. 
Adds `statusCode` check in `db-config` service to reject responses with `404` and `412` statuses.
Adds `changes_doc_ids_optimization_threshold` value validation. 
medic/medic-webapp#4185

Configures PouchDB not to batch changes requests

---

api/src/migrations/convert-bad-dob-format.js
api/src/migrations/remove-empty-parents.js
sentinel/package.json
sentinel/server.js
sentinel/yarn.lock

When installing or upgrading, there may be changes (migrations) that API
has to run before sentinel has a valid environment to work with.
To avoid spamming errors, sentinel now blocks until API has booted.

Block from booting until API is ready

---

api/src/controllers/db-doc.js
api/src/middleware/authorization.js
api/src/routing.js
api/tests/mocha/controllers/db-doc.spec.js
api/tests/mocha/middleware/authorization.spec.js
tests/e2e/api/controllers/db-doc.spec.js
tests/e2e/api/routing.js

* Adds support for db-doc attachments with names containing slashes
* Adds `ddoc` specific `GET` route which forwards main `ddoc` requests (_rewrites are authorized by another route). Db-doc controller forwards all other `ddoc` requests without authorizing them.  
* Catch `auth.getUserSettings` errors in `authorization` middleware
* Adds e2e tests which prove interactions with ddocs
* Adds e2e tests to check for access to main ddoc rewrites
medic/medic-webapp#2734

Fixes bug where dbdoc-att route would not match slashed att names

---

sentinel/src/lib/schedules.js
sentinel/tests/unit/schedules.js
tests/e2e/registration-by-sms.js

Instead of sending the `config` module, send the actual configs. 
medic/medic-webapp#4735

Fixes call to config in sentinel schedules.

---

tests/page-objects/contacts/contacts.po.js
webapp/src/js/controllers/contacts-edit.js
webapp/src/js/router.js
webapp/src/templates/partials/actionbar.html
webapp/tests/karma/unit/controllers/contacts-edit.js

Adds a new route parameter to `contacts.addChild` to identify actions that originated in the contacts list.
If such a form is canceled, the user is redirected to contacts list instead of parent contact.
medic/medic-webapp#4444

Adds specific routing for canceling contacts-edit forms

---

ddocs/medic/_attachments/translations/messages-en.properties
demo-forms/mrdt-demo.xml
webapp/src/css/enketo/medic.less
webapp/src/js/enketo/widgets.js
webapp/src/js/enketo/widgets/mrdt.js
webapp/src/js/services/add-attachment.js
webapp/src/js/services/android-api.js
webapp/src/js/services/enketo-translation.js
webapp/src/js/services/enketo.js
webapp/src/js/services/index.js
webapp/src/js/services/mrdt.js
webapp/src/js/services/report-view-model-generator.js

This adds a new widget for MRDT verification which launches a third party app which
returns a photo of the MRDT result which gets attached to the report and displayed in
the report view.
Attaching binary content to the report is done generically so other widgets can use the
same pattern.
medic/medic-webapp#4743
medic/medic-webapp#4745
medic/medic-webapp#4742

Adds the MRDT enketo widget and android integration

---

api/src/controllers/db-doc.js
api/src/services/bulk-get.js
api/tests/mocha/controllers/db-doc.spec.js
api/tests/mocha/services/bulk-get.spec.js
tests/e2e/api/controllers/bulk-get.spec.js
tests/e2e/api/controllers/db-doc.spec.js

When replicating an existent `doc`, PouchDB attachment requests would not include `rev` param. When the `doc` had been deleted (or the latest `rev` would not be allowed), they would receive a `403`,  which would abort the replication process. 
As a fix, offline attachment `rev`-less denied requests will now respond with a `404`, which will cause PouchDB to retry retrieving the attachment including the `rev` param.
Omits `latest` param for offline `_bulk_get` requests.
medic/medic-webapp#2734

Offline user rev-less invalid attachment requests return a 404

---

shared-libs/phone-number/src/phone-number.js
shared-libs/phone-number/test/libphonenumber.spec.js

Adding support for phone validation partial and none.
medic/medic-webapp#4127

Adding phone validation types

---

api/src/services/authorization.js
api/src/services/bulk-get.js
api/src/services/db-doc.js
api/tests/mocha/services/bulk-get.spec.js
api/tests/mocha/services/db-doc.spec.js
shared-libs/tombstone-utils/src/tombstone-utils.js
shared-libs/tombstone-utils/test/tombstone-utils.js
tests/e2e/api/controllers/bulk-get.spec.js
tests/e2e/api/controllers/db-doc.spec.js
webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/reports.js
webapp/src/js/services/live-list.js
webapp/tests/karma/unit/controllers/contacts.js
webapp/tests/karma/unit/controllers/reports.js
webapp/tests/karma/unit/services/live-list.js

Process CouchDB delete-stubs correctly in LiveList and TombstoneUtils  …
When a doc is deleted via a DELETE call (or from Fauxton UI), CouchDB
only saves a stubbed version of the doc (containing just _id, _rev and
_deleted: true flag).
When such a change was received by webapp's listeners, it was not
filtered as relevant, since the attached doc didn't have the required
properties, so the LiveList was not updated. This modifies the webapp
changes listeners to filter delete stubs of docs that exist in the
LiveList.
Updates tombstone-utils shared library so it will try to save the
previous revision of delete-stubs as the tombstone, so offline users
will replicate the DELETEs.
Additionally, support restricted offline users, namely:
Offline users db-doc `GET` and `_bulk_get` requests always …

 Process CouchDB delete-stubs correctly in LiveList and TombstoneUtils

---

static/js/controllers/contacts.js
static/js/services/live-list.js
static/js/services/search.js
tests/karma/unit/controllers/contacts.js
tests/karma/unit/services/search.js

Adds support for truly refreshing the `LiveList`.
This is achieved by providing a list of currently loaded doc_ids to webapp's `Search` service. 
After querying `Search` shared lib as usual, the results are merged with the provided `doc_ids` prior to calling `GetDataRecords` and other operations, ensuring that all existent items from the `LiveList` are updated.
This mechanism is only triggered for Contacts when sorting is by `last_visited_date` and change with a visit report about an existent item is received.
medic/medic-webapp#4782

LiveList full refresh

---

api/src/controllers/db-doc.js
api/src/services/db-doc.js
api/tests/mocha/controllers/db-doc.spec.js
api/tests/mocha/services/db-doc.spec.js
tests/e2e/api/controllers/_changes.spec.js
tests/e2e/api/controllers/db-doc.spec.js
tests/e2e/forms/submit-photo-upload-form.spec.js

PouchDB uses db-doc GET requests with `open_revs` param as a fallback if`_bulk_get` endpoint is not available when replicating. 
medic/medic-webapp#4778

Adds support for db-doc GET requests with open revs for offline users

---

api/src/controllers/db-doc.js
api/src/routing.js
api/tests/mocha/controllers/db-doc.spec.js
tests/e2e/api/controllers/db-doc.spec.js
tests/e2e/api/routing.js

Offline users can now GET `medic-admin` ddoc and have access to the admin app. 
medic/medic-webapp#4786

Allow offline users access to the admin app

---

webapp/src/js/services/enketo.js
webapp/tests/karma/unit/services/enketo.js
webapp/tests/karma/unit/services/report-view-model-generator.js

Replaces form root element node name with form internal ID when generating attachment names for forms with file uploads. 
medic/medic-webapp#4755

Report attachment names relative to form id

---

api/src/controllers/users.js
api/src/services/users.js
tests/e2e/api/controllers/users.js

#4097
> Log who changed which user, and what fields they changed, but not the actual changes (ie don't log the password, just that it was changed).
This logs out all fields in the request body, which is not necessarily the exact field which is updated on the user object (eg. place in request body maps to user.facility_id). If this is required, I'd need to do some refactoring within the user service. 
Sample Console Output
`REQ 3ea280b0-d469-403a-9273-13edb0b8f758 ::1 - POST /api/v1/users/kenn HTTP/1.1`
`REQ 3ea280b0-d469-403a-9273-13edb0b8f758 - Update user 'kenn'. Setting field(s) 'fullname,known,foo'. Requested by 'admin'.`

4097 - Log each valid `POST /api/v1/users/{username}` with field names

---

webapp/src/js/services/report-view-model-generator.js
webapp/tests/karma/unit/services/report-view-model-generator.js

A submitted report may have fields hidden that should be shown. Only the specific field that is marked with tag="hidden" should be hidden.
medic/medic-webapp#4625
I set up a repro of the example XForm in #4625. This is a screenshot of the final result after this change (prior to the change, name2 was hidden in the report). ![screenshot from 2018-09-12 23-30-16](https://user-images.githubusercontent.com/9014751/45471698-bd550880-b6e6-11e8-810d-e1a83f38df6e.png)
Instead of writing a new unit, I altered an existing test to capture the scenario (failed prior to code change). Happy to add a dedicated test if it is called for.
I'm unsure if the base branch for this should be `master` or some specific version. Also unsure if this should be in the changelog or if this is done via tooling.

4625 - Reports pages should not hide fields which are not explicitly hidden

---

webapp/src/js/controllers/inbox.js
webapp/src/js/services/location.js
webapp/src/templates/partials/header.html

Use an absolute instead of relative url to link to configuration
#4829

4829 - Use an absolute instead of relative url to link to configuration

---

api/package.json
api/src/services/export-data-2.js
api/src/services/export/message-mapper.js
api/tests/mocha/services/export/message-mapper.js
api/yarn.lock

Fixes bug where exporting reports with scheduled_tasks, with not yet generated messages, would cause errors in API. As a fix, all scheduled messages are generated prior to exporting. 
medic/medic-webapp#4816

Fix exporting messages from reports with scheduled_tasks

---

webapp/src/js/services/search.js
webapp/tests/karma/unit/services/search.js

Any change to report filters are ignored while reports are being fetched. The function `debounce()` in `services/search.js` is effectively bouncing everything until the first query finishes. `_currentQuery.filters` is a reference to the underlying filters object (in this case `$scope.filters` from `controllers/reports.js`). Fix is to cache a copy of the objects instead of a reference.
medic/medic-webapp#4331
Good demo of the underlying issue is to comment out [this](https://github.com/medic/medic-webapp/blob/master/webapp/src/js/services/search.js#L142) line and the filters will never update.

4331 - Reports incorrectly filtered if filter changes before search returns

---

Gruntfile.js
admin/src/templates/index.html
admin/tests/karma-unit.conf.js
api/tests/mocha/ddoc-extraction.js
ddocs/medic-admin/rewrites.json
tests/e2e/api/routing.js
webapp/src/js/services/location.js

Font awesome icons not loading in the administration console. Relative paths to FontAwesome rely on a trailing `/` at the end of the url.  `/medic/_design/medic-admin/_rewrite/`
medic/medic-webapp#4837
This relative pathing seems a tad brittle.

4837 - Font awesome icons not loading in the administration console

---

.travis.yml
Gruntfile.js
admin/src/templates/index.html
admin/tests/karma-unit.conf.js
api/tests/mocha/ddoc-extraction.js
ddocs/medic-admin/rewrites.json
tests/e2e/api/routing.js
tests/e2e/common/common.specs.js
webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/reports.js
webapp/src/js/services/search.js
webapp/tests/karma/unit/controllers/contacts.js
webapp/tests/karma/unit/services/search.js

This applies to search on both the People tab and on the Reports tab. We also reset the location so that the user can select the same item that was previously selected.
medic/medic-webapp#4825

After searching, the RHS should clear of anything

---

tests/e2e/forms/submit-z-score-form.spec.js
tests/page-objects/forms/z-score.po.js
webapp/src/js/enketo/medic-xpath-extensions.js

Because of https://github.com/medic/openrosa-xpath-evaluator/commit/722622554d0849e3f97d3e19647f083ead823a98 , z-score calculate function now receives object parameters (`{ t: <type>, v: <value> }`). 
medic/medic-webapp#4848

Fixes z-score calculation errors

---

Gruntfile.js

Grunt watch doesn't deploy inbox.html changes
medic/medic-webapp#4865

Issue 4865: grunt watch doesn't deploy inbox.html changes

---

sentinel/src/db-pouch.js
sentinel/src/lib/feed.js
sentinel/src/lib/infodoc.js
sentinel/tests/unit/lib/infodoc.js

Moves existing -info doc from medic to medic-sentinel db after medic changes/updates.
medic/medic-webapp#3423

3423 remove infodoc

---

Gruntfile.js
webapp/patches/enketo-inputs-always-relevant.patch

Issue: #4875
Here's a horrible hack which makes sure that our special `<inputs>` group is always included in enketo form output, even when `relevant` evaluates to `false`.

[master] Make sure that <inputs> are always included in saved Enketo form output

---

api/src/controllers/export-data.js
api/src/services/export-data.js

Because of `compression` package, it's necessary to call `flush` after `write` so data is actually compressed and sent to the client.
(https://github.com/expressjs/compression#server-sent-events)
medic/medic-webapp#4802

OutputToXml calls flush after write

---

api/src/config.js
api/src/controllers/changes.js
api/tests/mocha/config.js
api/tests/mocha/controllers/changes.js

Unless we're listening for the `complete` event, we have no need for the `changes()` call to collect docs.  We changed this in webapp at d4beeaf78b, but not in other parts of the app.
Note that in pouch 7.0.0, this value defaults to `false` if `live` is `true`.  This means that we could in theory remove the setting in webapp and 2 of the cases in this PR, but the consequence of forgetting to set this value if we ever change to non-live listeners is big memory overhead.

Explicitly set return_docs for pouch change() calls

---

sentinel/src/transitions/accept_patient_reports.js
sentinel/tests/unit/transitions/accept_patient_reports.js

In `accept_patient_reports` transition, switches `utils.getRegistrations` call from PouchDB back to Nano. 
medic/medic-webapp#4962

Fixes accept_patient_reports to call getRegistrations with correct db

---

webapp/src/js/services/changes.js

Make it clearer in logging that changes watcher is being started on different databases.

Log which db is being watched

---

Gruntfile.js
api/src/config.js
api/src/migrations/convert-translation-messages.js
api/src/migrations/extract-translations.js
api/src/translations.js
api/tests/integration/migrations/convert-translation-messages.js
api/tests/integration/migrations/utils.js
api/tests/integration/res/migrations/reverse-names.js
api/tests/mocha/translations.spec.js
sentinel/src/config.js
webapp/src/js/services/translation-loader.js
webapp/tests/karma/unit/services/translation-loader.js

Changed the structure of translations to enable full overwrite in order to reflect addition/deletion of translation keys.
Now, the structure of the translation doc is: `{....., "custom":{...}, "default":{...}}`
* `"custom":{...}` has the custom translations uploaded via `medic-conf`
* `"default":{...}` has the default translations
Related `medic-conf` PR: https://github.com/medic/medic-conf/pull/110
medic/medic-webapp#3128

Change translations structure

---

CONTRIBUTING.md

Remove Google Groups for contributors and added link to CHT page where they can request access to Slack

Replaced Google Groups with Slack for contributors

---

sentinel/src/lib/infodoc.js
sentinel/src/lib/muting_utils.js
sentinel/src/transitions/muting.js
sentinel/tests/unit/lib/infodoc.js
sentinel/tests/unit/lib/muting_utils.js
sentinel/tests/unit/transitions/muting.js
webapp/src/js/services/contact-muted.js
webapp/tests/karma/unit/services/contact-muted.js

For analytics purposes, a contact's `muting_history` log is saved in the sentinel info doc. Each time the muted status is changed, an entry is added in the `muting_history` log, following this format: 
```
{ 
muted: [true|false],
date: '<muting/unmuting sentinel date, in ISO8601 format>',
report_id: '<report that triggered muting/unmuting>'
}
```
For analytics purposes, the contact's `muted` property now contains a human readable date (in ISO8601 format). When unmuting, the property is removed altogether, avoiding having mixed data types for the same property. 
The `muted` field value (when existent) is exposed to ContactViewModel, instead of a Boolean `true`. 
medic/medic-webapp#4767 …

Adds muting history

---

api/src/services/export/contact-mapper.js
api/src/services/export/report-mapper.js
ddocs/medic-client/views/visits_by_date/map.js
shared-libs/search/src/generate-search-requests.js
shared-libs/search/src/search.js
shared-libs/search/test/generate-search-requests.js
shared-libs/search/test/search.js
webapp/src/js/controllers/contacts.js
webapp/src/js/services/search.js
webapp/src/js/services/session.js
webapp/tests/karma/unit/controllers/contacts.js
webapp/tests/karma/unit/services/search.js
webapp/tests/karma/unit/services/session.js

Adds a new view that indexes home_visits by date, to use with a `start_key` + `end_key` query to count montly vists.
When sorting by last visited date, Search lib now returns the whole results pool, to avoid querying for `contacts_by_visited_date` twice.
DB Admins no longer default to UHC (it was impossible to load Muso contacts list as an admin, the `contacts_by_last_visited` had over 9MB and everything timed out before it was downloaded).
medic/medic-webapp#4981

Improves performance of UHC Contacts list

---

admin/src/templates/authorization_permissions.html

Updates `authorization_permissions` admin template to use new property `enabled` (instead of `value`) for existent permissions.
medic/medic-webapp#3762

Fixes bug where no permissions were checked in admin permissions page.

---

package-lock.json
package.json

event-source was hacked and therefore removed from npm. Bumping
nodemon removes the dependency and gets us up and running again.

Bump nodemon to remove bad transitive dependency

---

admin/src/css/theme.less
admin/src/js/controllers/edit-language.js
admin/src/js/controllers/edit-translation.js
admin/src/js/controllers/translation-application.js
admin/src/js/controllers/translation-languages.js
admin/src/js/directives/modal.js
admin/src/js/services/properties.js
admin/src/templates/edit_translation.html
admin/src/templates/modal.html
admin/tests/unit/controllers/edit-translation.js
admin/tests/unit/services/export-properties.js
admin/tests/unit/services/import-properties.js
api/src/config.js
sentinel/src/config.js

Allows admin to delete translation keys from admin:
Also, refactor translation related code to take into account new structure.
medic/medic-webapp#3128

Add ability to delete custom key from admin app

---

Gruntfile.js

COUCH_URL is now required for running `grunt`. As of https://github.com/medic/medic-webapp/commit/59a76afe830f3163ca0ce0c9f5ef7fb9c8445cd9.
Current error if COUCH_URL is undefined:
```
Loading "Gruntfile.js" tasks...ERROR
>> TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
```
Proposed error when COUCH_URL is undefined:
```
Loading "Gruntfile.js" tasks...ERROR
>> Required environment variable COUCH_URL is undefined. (eg. http://your:pass@localhost:5984/medic)
```

Pretty error when grunting without COUCH_URL defined

---

webapp/src/templates/partials/contacts_content.html

Applies the muted styling to all children of muted parents.
medic/medic-webapp#4768

Show children / places / contacts as muted for muted parent.

---

sentinel/src/transitions/accept_patient_reports.js
sentinel/tests/unit/transitions/accept_patient_reports.js

We want to be able to to show that CHWs receive our SMS and then respond to them.
medic/medic-webapp#4694

Linking the visit report to the task message that triggered it

---

admin/src/css/configuration.less
admin/src/css/main.less
admin/src/js/services/message-queue.js
admin/src/templates/message_queue_tab.html
admin/tests/unit/services/message-queue.js
ddocs/medic/_attachments/translations/messages-en.properties
sentinel/src/schedule/due_tasks.js
sentinel/tests/unit/due_tasks.js
shared-libs/message-utils/src/index.js
shared-libs/message-utils/test/index.js
webapp/src/css/inbox.less
webapp/src/css/messages.less
webapp/src/js/services/format-data-record.js
webapp/src/templates/partials/reports_content.html

Updates `message-utils` shared library to not throw an error when registrations are provided without a patient, rather mark the resulted message with a translatable error. 
Updates Sentinel's `due_tasks` to not save such invalid/errored messages, also not updating task statuses either in such cases.
Updates Webapp Reports Content view and Admin Message Queue to clearly display such invalid scheduled messages - displaying the message error along with the generated content.
medic/medic-webapp#649
medic/medic-webapp#5019

Accommodate to having scheduled messages about deleted patients

---

api/src/config.js

This is related to translations
These changes will ensure that as long as the migration has not been the executed to convert the translation format, `config.load()` can still execute loading the old format.
medic/medic-webapp#5062

Fix execution of config.load when migration has not executed yet

---

sentinel/tests/unit/pregnancy_registration.js
sentinel/tests/unit/reminders.js
sentinel/tests/unit/transitions/update_scheduled_reports.js

Asynchronous mocha tests must either take a callback parameter (usually called `done`) and execute that once the async code has completed, or return a promise. This fixes a bunch of places where this wasn't happening so the assertions were never actually running.

Ensures async tests run assertions

---

webapp/src/js/controllers/contacts.js
webapp/src/js/services/live-list.js
webapp/tests/karma/unit/controllers/contacts.js
webapp/tests/karma/unit/services/live-list.js

#4445
Performance optimizations for the Live-List class as-used in the contacts tab. 
Contact controller currently calls `livelist.update` once per list item and then `livelist.refresh` after all items are added. 
This change updates the interface `livelist.set` to avoid the incremental dom changes from `livelist.update` and then the full re-paint from `livelist.refresh`. The proposed change inserts the items each item into the model once, sorts the full list once, and then draws everything once. To avoid unnecessary scanning, update `livelist.dom` to a hashmap. `livelist.set()` accepts an optional flag `reuseExistingDom` which can avoid expensive calls to `listItemFor` when the contents of the DOM are being reused and not updated (eg. pagination). 
On my SM-G361H. Times are a measure of …

#4445 - Reduce time to render contacts list through live-list

---

scripts/travis/couch-start
tests/e2e/api/routing.js

This test fails when running tests against Couch 2.3, since this endpoint has been finally implemented. 
Offline users are still blocked from accessing `_purge`. 

Remove _purge e2e test for online users.

---

shared-libs/message-utils/package-lock.json
shared-libs/message-utils/package.json
shared-libs/message-utils/src/index.js

This PR is needed to publish the shared-libs/message-utils change that is required by https://github.com/medic/medic-webapp/pull/5081
Travis fails because it uses the published package
medic/medic-webapp#4598

Mark message that is empty or fails translation as errored

---

webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/messages-content.js
webapp/src/js/controllers/reports.js
webapp/src/js/services/live-list.js
webapp/src/js/services/search-filters.js
webapp/tests/karma/unit/controllers/contacts.js
webapp/tests/karma/unit/controllers/reports.js
webapp/tests/karma/unit/services/live-list.js

Changes Reports and Cotnacts LiveList to use child controller $scope instead of Inbox $scope, so the child scopes created by LiveList get destroyed when tabs are changed.
Clears jQuery event listeners in MessagesContentCtrl.
Removes Reports Filters DateTimePicker html when switching tabs. 
medic/medic-webapp#5050

Fixes Messages, Reports and LiveList memory leaks

---

webapp/src/templates/partials/header.html

This change updates the webapp dropdown menu to use the same translation
key as and admin app uses so the naming will be consistent.
medic/medic-webapp#4960

Uses consistent naming for the App Settings console

---

api/package-lock.json
api/package.json
sentinel/package-lock.json
sentinel/package.json
webapp/package-lock.json
webapp/package.json

Reference latest version of translation-utils which has the fix about the replace call which fails when the value is not a string.
medic/medic-webapp#5062

Fix translations

---

.travis.yml

This makes it clearer which repo a slack notification is generated for.

Add "[webapp]" to slack notification

---

webapp/src/js/services/contact-view-model-generator.js
webapp/tests/karma/unit/services/contact-view-model-generator.js

This is a very minor performance tweak to avoid an unnecessary PouchDB.get() for a place's primary contact when the document is already in the place's children. In my limited exposure to project data, the primary contact is often a child of the place.
Looks like the in-memory lookup is ~0-1ms and PouchDB lookup ranges from 10-45ms. Not impressive... but I'm here cause it's on my list, and it doesn't add much compexity. Very open to just closing this as won't fix due to insufficient gains.
"The data fetched in right-panel step R6 was already fetched in step R4. Can we consolidate?" from #4445 

Contact RHS - Avoid primary contact lookup when redundant

---

admin/package-lock.json
admin/package.json
api/package-lock.json
api/package.json
ddocs/medic/_attachments/translations/messages-en.properties
sentinel/package-lock.json
sentinel/package.json
sentinel/tests/integration/schedules.js
sentinel/tests/unit/due_tasks.js
shared-libs/message-utils/src/index.js
webapp/package-lock.json
webapp/package.json
webapp/tests/karma/unit/services/format-data-record.js

Mark the message as errored when translation fails. Marking the message as errored will prevent it from being sent.
medic/medic-webapp#4598

4598 failed message translation no sent

---

api/src/ddoc-extraction.js
api/tests/mocha/ddoc-extraction.js

When doing a non-Horticulturalist deploy, `medic` ddoc lacks the `deploy_info` property which horti adds. 
As a result, ddoc extraction would update `medic-client` every time it ran (because `undefined` properties don't get saved in CouchDB). 
Fix: only copy `deploy_info` if either old or new value exist. 
This would not occur in production deployments which are handled by Horticulturalist. 
medic/medic-webapp#5109

Don't write deploy_info if undefined

---

shared-libs/server-checks/package-lock.json
shared-libs/server-checks/package.json
shared-libs/server-checks/src/checks.js
shared-libs/server-checks/test/checks.js

ServerChecks shared lib now exports a function that returns the CouchDB version.
medic/medic-webapp#5076

Exports function that returns CouchDB version

---

admin/src/js/controllers/edit-translation.js
admin/src/templates/edit_translation.html

Hide the translation delete button when the user edits a generic translation. Only custom translations can be deleted.
medic/medic-webapp#3128

Hide delete button when the editing generic trans

---

api/src/migrations/fix-user-db-security.js

I get errors pretty frequently when running this migration locally, to
do with CouchDB not being able to find shards. It seems to be that it's
smashing the user DB too much. This rewrite makes the writing part
syncronous.

 Increase migration stability 

---

webapp/src/js/services/target-generator.js
webapp/tests/karma/unit/services/target-generator.js

The problem is when you're admin you don't have a userContact so it's trying to stringify null which throws so we should wrap that in an if block.
For extra performance, skipping the TargetGenerator.init altogether if the RulesEngine is disabled because it's never going to get any targets emitted.
medic/medic-webapp#5071

Fix loading of Targets tab as admin

---

api/src/migrations/drop-audit-doc-index.js
api/src/migrations/namespace-form-fields.js

These were added erroneously by prettier.
Split off from https://github.com/medic/medic-webapp/pull/5124

Removes the linebreaks in status output

---

demo-forms/muting-forms/mute_clinic.properties.json
demo-forms/muting-forms/mute_clinic.xml
demo-forms/muting-forms/mute_district_hospital.properties.json
demo-forms/muting-forms/mute_district_hospital.xml
demo-forms/muting-forms/mute_health_center.properties.json
demo-forms/muting-forms/mute_health_center.xml
demo-forms/muting-forms/mute_person.properties.json
demo-forms/muting-forms/mute_person.xml
demo-forms/muting-forms/unmute_clinic.properties.json
demo-forms/muting-forms/unmute_clinic.xml
demo-forms/muting-forms/unmute_district_hospital.properties.json
demo-forms/muting-forms/unmute_district_hospital.xml
demo-forms/muting-forms/unmute_health_center.properties.json
demo-forms/muting-forms/unmute_health_center.xml
demo-forms/muting-forms/unmute_person.properties.json
demo-forms/muting-forms/unmute_person.xml

Sample forms that can be used for muting and un-muting at different levels of hierarchy. Very basic form.

Add demo forms for muting and un-muting the different levels of hierarchy

---

api/src/services/authorization.js
api/tests/mocha/services/authorization.spec.js
tests/e2e/api/controllers/_changes.spec.js

When constructing the list of  `doc_ids` to request changes, check if an `_id` is present before adding it's tombstone. 
medic/medic-webapp#5186

Only replicate deletes if doc is still deleted

---

admin/src/css/configuration.less
admin/src/templates/message_queue_tab.html

On smaller screens the outgoing messages table rows no longer wrap
so it's still readable.
medic/medic-webapp#5221
@dianabarsan Code review please!
@amandacilek Design review please! I've added screenshots to the original issue.

Changes outgoing messages so rows do not wrap

---

Gruntfile.js
webapp/src/js/controllers/about.js
webapp/src/js/controllers/bulk-delete-confirm.js
webapp/src/js/controllers/guided-setup-modal.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/reloading-modal.js
webapp/src/js/controllers/tasks.js
webapp/src/js/services/android-api.js
webapp/src/js/services/debug.js
webapp/src/js/services/enketo.js
webapp/src/js/services/search-filters.js
webapp/src/js/services/snackbar.js
webapp/src/js/services/tour.js
webapp/src/js/services/update-user.js
webapp/tests/karma/unit/services/enketo.js

Angular suggests using:
* `$window` instead of `window`,
* `$timeout()` instead of `setTimeout()`, and
* `$timeout.cancel()` instead of `clearTimeout()`
This corrects those uses, and adds regex checks for these to grunt.

Use less globals in angular

---

api/src/controllers/changes.js
api/tests/mocha/controllers/changes.js

Removes forwarding `seq_interval` request param from PouchDB replication requests. 
medic/medic-webapp#5235

Don't forward seq_interval in upstream Changes requests

---

shared-libs/registration-utils/package-lock.json
shared-libs/registration-utils/package.json
shared-libs/registration-utils/src/index.js
shared-libs/registration-utils/test/index.spec.js

Adds getPatientId and getSubjectIds methods to @medic/registration-utils shared library.
To be used along with https://github.com/medic/medic-webapp/pull/5194
medic/medic-webapp#4885

Shared getPatientId and getSubjectIds implementations.

---

Gruntfile.js
webapp/package.json
webapp/patches/pouchdb-browser.patch
webapp/src/js/app.js
webapp/tests/karma/unit/services/db.js
webapp/yarn.lock

Reverts change that upgrades PouchDB version from 6.4.3 to 7.0.0 in Webapp (API and Sentinel left unchanged). 
medic/medic-webapp#5257

Downgrade PouchDB to 6.4.3

---

Gruntfile.js
ddocs/medic/rewrites.json
webapp/src/js/controllers/inbox.js

When users upgrade from 2.x their old appcache needs to be
updated with new files. This change ensures the appcache is
available at the old location as well as the new location.
This is not a long term solution but will do until we
migrate to using service worker caching instead.
medic/medic-webapp#5247

Serves new appcache from old location

---

api/src/server-utils.js
api/tests/mocha/server-utils.spec.js
tests/e2e/api/controllers/users.js

#5234 
Just pushing the buttons described by this issue. Please double check the expected behavior of this change via the unit tests. Confirm you expect these scenarios to result in error code `500` or aspects of the code make be think they should be `502`/`100` respectively?

5234 - Guard against bad HTTP codes in error reporting

---

webapp/src/js/bootstrapper/index.js
webapp/tests/mocha/unit/bootstrapper.spec.js

Navigate to webapp 3.4 (master)
Login as restricted user.
Go offline during initial replication.
Click "Try again"
Observed error: `Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-6i0jYw/zxQO6q9fIxqI++wftTrPWB3yxt4tQqy6By6k=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.`
This change should be merged into 3.4.
#5270

CSP is blocking inline script on bootstrap retry button

---

api/src/routing.js
api/tests/mocha/routing.spec.js

Tweaking this fix. Tested e2e with a horti deployment via admin page upgrade page. Deployment didn't actually complete, but was able to kick off without error.
#5277

5277 - CSP connect-src still blocking upgrades via admin upgrade page

---

tests/base.conf.js

Run e2e tests. 
Browse to tests/results/report.html to view report
Expected: Report
Obsereved: Empty report
#5228

5228 - Jasmine e2e test report is always empty

---

admin/package-lock.json
admin/package.json
api/package-lock.json
api/package.json
sentinel/package-lock.json
sentinel/package.json
sentinel/src/lib/muting_utils.js
sentinel/src/lib/utils.js
sentinel/src/transitions/accept_patient_reports.js
sentinel/src/transitions/muting.js
sentinel/src/transitions/registration.js
sentinel/tests/unit/lib/muting_utils.js
sentinel/tests/unit/lib/utils.js
sentinel/tests/unit/transitions/accept_patient_reports.js
sentinel/tests/unit/transitions/muting.js
sentinel/tests/unit/transitions/registration.js
webapp/package-lock.json
webapp/package.json
webapp/src/js/bootstrapper/purger.js
webapp/src/js/services/contact-view-model-generator.js
webapp/src/js/services/rules-engine.js

When clearing schedules, either by `registration` transition or `accept_patient_reports` transition, switches from matching `patient_id` only (via `utils.getRegistrations`) to matching `_id`, `patient_id` and `place_id` (via `utils.getReportsBySubject`).
This allows clearing schedules for patients that were created while offline. 
medic/medic-webapp#4885

Clear offline schedules

---

api/src/migrations/convert-translation-messages.js
api/tests/integration/migrations/convert-translation-messages.js

It is already done by the translation merging process. In fact, it may cause invalid values to be mapped to generic.
medic/medic-webapp#5271

Don’t set generic values

---

README.md

We should never really reference it, and they're going to take it away soon.
Much better to go through the official node api instead.

Remove reference to 5986

---

Gruntfile.js

Running e2e tests locally today was very slow and I had more transient failures than normal, particularly in the `_changes.spec.js` suite. Looking at the failures, my `medic-test-user-admin-meta` database was very large, I deleted it and tests reliability and speed improved. Sorry, I didn't take any measurements but the difference was quite obvious.
#5228

Delete medic-test-user-admin-meta during reset-test-databases command

---

api/src/controllers/changes.js
api/src/db.js
api/tests/mocha/controllers/changes.js
tests/e2e/api/controllers/_changes.spec.js

PouchDB (as of 7.0.0) has four mechanisms for handling `last_seq` while replicating:
1. In the [Changes handler](https://github.com/pouchdb/pouchdb/blob/1da0eb6fbe33ea1aeb55e2b16f479a992ebcb5be/packages/node_modules/pouchdb-adapter-http/src/index.js#L1026) it uses `result.last_seq` to batch changes; this affected us in API prior to batching and Couch 2.3
2. In the Replication Handler ([here](https://github.com/pouchdb/pouchdb/blob/1da0eb6fbe33ea1aeb55e2b16f479a992ebcb5be/packages/node_modules/pouchdb-replication/src/replicate.js#L308) and [here](https://github.com/pouchdb/pouchdb/blob/1da0eb6fbe33ea1aeb55e2b16f479a992ebcb5be/packages/node_modules/pouchdb-replication/src/replicate.js#L133)) it uses the `seq` of the last change in a batch OR `result.last_seq` when writing local and remote …

Updates seq of live changes in batched changes feeds

---

webapp/src/js/bootstrapper/purger.js

The hash function was incorrectly generating every hash as '0'.
As 0 is falsy in JS, that constituted no hash at all, and so it would always think 
something had changed.
medic/medic#5048

Fixing purge's hash function

---

api/src/db.js
api/src/services/user-db.js
api/tests/integration/migrations/utils.js
api/tests/mocha/services/user-db.spec.js
webapp/src/js/services/db.js

I think this was broken in c9f192ce1eb6e21505dd9a1c69ed648a9b06fa80, but I'm not sure.
Two parts didn't work:
- db.info() doesn't throw when the DB doesn't exist, it just returns the error
- We were treating PouchDB instantiation as a promise

Create user's meta dbs correctly

---

api/src/controllers/login.js
api/tests/mocha/controllers/login.spec.js

This means the locale cookie is available for the bootstrap
stage before the angular app has loaded.
medic/medic#5326

Writes locale cookie on login response

---

Gruntfile.js
api/src/resource-extraction.js

API service fails to start when run via `npm start`.
```Error: ENOENT: no such file or directory, mkdir '/Users/wtekeu/projects/codes/medic-webapp/src/extracted-resources'```

Api service fails to start via npm start

---

tests/e2e/login/purge.spec.js
webapp/src/js/bootstrapper/index.js

This test originally failed because of issues with Chrome 71. Re-enabling it now that Chrome 72 is stable (used in travis), it appears it's now broken because I removed the userCtx parameter during a rebase by mistake.
#5267

5267 - Re-enable purging spec together with service worker

---

ddocs/medic/views/reports_by_form_year_month_clinic_id_reported_date/map.js
sentinel/src/transitions/update_scheduled_reports.js
sentinel/tests/unit/transitions/update_scheduled_reports.js

- Changes `filter` function to check if the transition has already run
- Fixes `reports_by_form_year_month_clinic_id_reported_date` to not test for legacy `doc.year`
- Switches logic from deleting current doc and updating old duplicate to deleting old duplicate
- Refactors to use promises instead of callbacks
medic/medic#5347

Fixes update_scheduled_reports

---

sentinel/src/transitions/death_reporting.js
sentinel/tests/unit/transitions/death_reporting.js

Allows submiters without a phone number to successfully register a death.
medic/medic#5359

Fixes death_reporting filter.

---

sentinel/src/lib/schedules.js
sentinel/tests/unit/schedules.js

This requires a config change. You need to add `"start_mid_group": false` to the definition of the schedule. For instace:
```
{
"name": "ANC Reminders LMP",
"translation_key": "schedule.anc_lmp",
"summary": "",
"description": "",
"start_from": "lmp_date",
"start_mid_group": false,
"messages": [
```
medic/medic#3093

Prevents schedule from starting mid-group

---

webapp/src/js/actions/index.js
webapp/src/js/controllers/contacts-edit.js
webapp/src/js/controllers/contacts-report.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/reports-add.js
webapp/src/js/controllers/tasks-content.js
webapp/src/js/directives/navigation.js
webapp/src/js/reducers/index.js
webapp/src/js/router.js
webapp/src/templates/directives/navigation.html
webapp/src/templates/partials/contacts_edit.html
webapp/src/templates/partials/contacts_report.html
webapp/src/templates/partials/reports_add.html
webapp/src/templates/partials/tasks_content.html
webapp/tests/karma/unit/controllers/tasks-content.js

Continuing on from [this PR](https://github.com/medic/medic/pull/5323), moving scope properties to the redux store
medic/medic#4750

4750 Moves enketoStatus to redux store

---

shared-libs/message-utils/package-lock.json
shared-libs/message-utils/package.json
shared-libs/message-utils/src/index.js
shared-libs/message-utils/test/index.js

If provided with a valid phone number recipient, message-utils should use that as a `to` field instead of defaulting to the sender (`from`). 
Certain transitions (like `accept_patient_reports`) support including an explicit phone number as message recipient, while `multi_report_alerts` always passes explicit phone numbers when generating messages. 
medic/medic#5369

Adds support for sending messages to specific phone numbers.

---

sentinel/src/transitions/index.js
sentinel/tests/unit/transitions.js

Running in parallel with a large number of users can fail and
even crash CouchDB. This is slower but much safer.
medic/medic#5420

Runs deletions of read docs serially not in parallel

---

admin/src/css/configuration.less
admin/src/css/theme.less
admin/src/js/controllers/edit-translation.js
admin/src/templates/edit_translation.html
admin/src/templates/translation_application.html
admin/tests/unit/controllers/edit-translation.js
webapp/src/css/common.less
webapp/src/css/theme.less

Also makes the translation key required when adding a translation.
Also changes the translation list to show the key with styling when the translation is missing for that key.
medic/medic#5405
medic/medic#5120
medic/medic#5121

Fix a bug where edit translation failed silently

---

sentinel/src/transitions/registration.js
sentinel/tests/unit/patient_registration.js
sentinel/tests/unit/pregnancy_registration.js

Registration transition used to calculate `last_menstrual_period`, `expected_birth_date` and `date_of_birth` relative to current date at processing time instead of the registration's `reported_date`, resulting in incorrect dates in case Sentinel gets behind or is misconfigured. 
medic/medic#5410

Updates registration LMP, EBD and DOB calculations to be relative to reported_date

---

webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/reports.js

Fixes bug where, after switching selectMode, reports were still selected
medic/medic#5417

Fix report selection clearing

---

sentinel/src/transitions/accept_patient_reports.js
sentinel/tests/unit/transitions/accept_patient_reports.js

- reverse sequence between silencing registration and adding report uuid: we don't want to link a report to a reminder that has already been cleared. When tasks are cleared, the field `cleared_by` is added which is enough for the analytics team.
- fix linking logic to prevent conflicts: now if the the second put results in a conflict, we update the `_rev` and re-put.
- fix potential bug with finding the messages to clear: changed when the filter component is applied.  Indeed, if we consider 2 tasks belonging to the same group. The most recent one is `sent` and the oldest want is `scheduled`. The old implementation will clear the second one even though is not in the `silence_for` window but just because the first one is.
- fix tests
medic/medic#4694 …

Fix linking logic to prevent conflicts

---

Gruntfile.js
tests/e2e/sentinel/transitions/accept_patient_reports.spec.js
tests/e2e/sentinel/transitions/conditional_alerts.spec.js
tests/e2e/sentinel/transitions/death_reporting.spec.js
tests/e2e/sentinel/transitions/default_responses.spec.js
tests/e2e/sentinel/transitions/generate_patient_id_on_people.spec.js
tests/e2e/sentinel/transitions/multi_report_alerts.spec.js
tests/e2e/sentinel/transitions/muting.spec.js
tests/e2e/sentinel/transitions/registration.spec.js
tests/e2e/sentinel/transitions/resolve_pending.spec.js
tests/e2e/sentinel/transitions/update_clinics.spec.js
tests/e2e/sentinel/transitions/update_notifications.spec.js
tests/e2e/sentinel/transitions/update_scheduled_reports.spec.js
tests/e2e/sentinel/transitions/update_sent_by.spec.js
tests/e2e/sentinel/utils.js
tests/utils.js

Adds e2e tests for every Sentinel transition - except for `update_sent_forms` which is only used by the broken `reminders`.
medic/medic#4857

Adds Sentinel e2e tests

---

scripts/travis/cleanup.js

Instead of trying to delete the artefact from _this_ build, this PR deletes the 50 oldest builds up to 50 build numbers before this build. This has the added benefit of cleaning up any missed artefacts to keep the db under control.
medic/medic#5297

Cleans up only old build artefacts

---

tests/e2e/api/controllers/export-data-2.js

I'm reasonably sure this is what is causing test failures to look like they're coming from `afterEach`. It's wrong either way.
medic/medic#5293

Failing test was passing

---

.gitignore
Gruntfile.js
api/src/routing.js

- adds uglifying for login/script.js and service-worker.js
- adds cssmin for login/styles.css
- fixes a bug where uglifying was happening too early on webapp code so files weren't being minified at all
- reformats the Gruntfile for consistency
#5489

Uglifies more files for fast loading

---

api/src/config.default.json
config/standard/app_settings.json
webapp/src/js/app.js
webapp/src/templates/directives/actionbar.html

- all default roles have this permission
- hides `edit` button in Reports actionbar
- redirects to `error/403` on route transition
- improves route permissions transitions handling
medic/medic#5537

Adds `can_update_reports` permission.

---

.travis.yml

Apparently errors in the `after_success` section don't fail the build. This causes the subsequent jobs to fail with a misleading error ("failed to start API"). Moving it into the `script` section causes the `compile` job to fail so it fails earlier and in a way that's easier to debug.
medic/medic#5196

Moves the publish step into CI script

---

grunt/service-worker.tmpl
webapp/src/js/app.js

Broken experience after merging #5448. I can no longer log in as an offline user. Due to
```Uncaught (in promise) DOMException: Failed to execute 'respondWith' on 'FetchEvent': The fetch event has already been responded to```

Cannot log in as offline user: Failed to execute 'respondWith' on 'FetchEvent'

---

api/src/controllers/login.js
api/src/services/cookie.js
api/tests/mocha/controllers/login.spec.js
webapp/src/js/bootstrapper/index.js
webapp/src/js/services/session.js

1) Create cookie login=force during offline logout (client side)
2) Prevent users from accessing the app when cookie login=force exist (client side)
3) When the user comes back online, delete cookie and force login (server side)
medic/medic#5183

Force login for offline users who logout

---

package-lock.json
webapp/tests/karma/unit/services/delete-docs.js

Error message is:
```json
Converting circular structure to JSON
--> starting at object with constructor 'Object'
|     property 'parent' -> object with constructor 'Object'
--- property 'contact' closes the circle
```

Fix error message comparison

---

release-notes/docs/3.4.0.md

It would be useful to document significant live-site issues which are likely to impact users who deploy that build. In this case, I'm imagining partners trying to self-host this build; or somebody deploying the latest stable build. Not sure how helpful this would actually be, but it's a starting point.

Add a v3.4.0 "Known Issues" in release notes

---

Gruntfile.js
grunt/service-worker.js

Although #3986 isn't officially schedule in 3.5, this is a requirement which we missed from #5183 (scheduled in 3.5). https://github.com/medic/medic/issues/5183#issuecomment-454589247
From @garethbowen:
> Related: #3986 . We should make sure this is fixed at the same time.
I forgot about this when reviewing @wtekeu's fix for 5183 (logging out while offline). But since that one is all wrapped up and reviewed, I'm spinning off another PR for this.  Unsure if we'd want to bring #3986 into the release for easier AT tracking.
This won't work on developer machines in master if they are using a database which is not `medic`, but I merged it with #5448 and it does work without modification when combined with that change. …

3986 - Make login page available offline

---

api/src/resource-extraction.js
api/src/routing.js
api/tests/mocha/resource-extraction.spec.js

Deploying latest master is crashing inside the docker container due to the permissions of the folder where resources are extracted. This change redirects production resource extraction to `/tmp` when `NODE_ENV=production`.
#5519  …

Extract resources to /tmp when NODE_ENV=production

---

webapp/src/js/enketo/widgets/notewidget.js

Fix bug in notewidget plugin related to html() call  when applying live link html
medic/medic#5536

Fix bug with call html()

---

README.md

Added steps that detail creating, downloading, and registering your ngrok account to your computer. 
Then starting the webapp and running ngrok to expose the port you're running on. So you can access your local environment on another device. This is a work around for service workers requiring a https site. 

Adding instructions on using ngrok to access your local dev environment. 

---

api/src/config.default.json
webapp/src/js/controllers/contacts.js
webapp/src/js/services/index.js
webapp/src/js/services/target-generator.js
webapp/src/js/services/uhc-settings.js
webapp/tests/karma/unit/services/target-generator.js
webapp/tests/karma/unit/services/uhc-settings.js

Moves app settings `uhc.visit_count.month_start_date` to `uhc.month_start_date` (old location still checked for backwards compatibility). 
Uses app settings `uhc.month_start_date` calendaristic interval to determine target instance relevance, falls back to calendaristic month if not set. 
medic/medic#5544

Calculate targets based of UHC month_start_date.

---

ddocs/medic-client/views/contacts_by_last_visited/map.js
ddocs/medic-client/views/visits_by_date/map.js

If the report has a field visited_date, it will be used to determine the visit date. If it does not exist, reported_date will be used.
medic/medic#5579

Added new field visited_date to 2 views

---

api/src/public/appcache-upgrade.html
api/src/routing.js
ddocs/medic/_attachments/appcache-upgrade.html
ddocs/medic/rewrites.json
grunt/service-worker.js
tests/e2e/service-worker.js

Another regression from #5361. The android app navigates the user to `/medic/_design/medic/_rewrite/` and does not use the root url. To support offline mode, we need to ensure that a redirect from that rewrite page to root is cached.
I see a few options here: 
1. Existing service workers - The `appcache-upgrade.html` could register the existing service-worker and redirect once registration completes. During an upgrade this would load all of the app's resources during an empty page and is not ideal.
1. Appcache - Given that we have the appropriate manifest already in place (required for the upgrade process), I think this is the easiest and is the fix I pursued here.
1. New service worker - Could also do this. But it's a new file, a new build step, and a bit of a registration process. If …

Cache the path accessed from _rewrite

---

api/src/middleware/authorization.js
api/src/routing.js
api/tests/mocha/middleware/authorization.spec.js
tests/base.conf.js
tests/e2e/api/controllers/_changes.spec.js
tests/e2e/api/controllers/all-docs.spec.js
tests/e2e/api/controllers/bulk-docs.spec.js
tests/e2e/api/controllers/bulk-get.spec.js
tests/e2e/api/controllers/db-doc.spec.js
tests/e2e/api/routing.js
tests/e2e/sentinel/transitions/registration.spec.js
tests/utils.js

When db name is not `medic`, instead of proxying straight to CouchDB, changes url to match the DB name and forwards to next route.
Fixes `/admin` prefixed routes from proxying straight to CouchDB.
Updates offline users e2e tests to test with `medic-test` and `medic` dbs urls. 
Adds deprecated API V0 routing e2e testing. 
medic/medic#5692
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking …

Fixes offline user API restrictions

---

api/README.md
api/src/controllers/record-utils.js
api/src/controllers/records.js
api/src/controllers/sms-gateway.js
api/src/services/records.js
api/src/services/report/smsparser.js
api/src/services/report/textforms-parser.js
api/src/services/report/validate.js
api/tests/form-definitions.js
api/tests/mocha/controllers/record-utils-parser.spec.js
api/tests/mocha/controllers/record-utils-validate.spec.js
api/tests/mocha/controllers/sms-gateway.spec.js
api/tests/mocha/services/record-parser.spec.js
api/tests/mocha/services/record-public-forms.spec.js
api/tests/mocha/services/record-timestamp.spec.js
api/tests/mocha/services/record-validate.spec.js
api/tests/mocha/services/record.spec.js
api/tests/mocha/services/records.spec.js
api/tests/mocha/services/report/smsparser.spec.js
ddocs/medic/_attachments/translations/messages-en.properties
tests/e2e/api/controllers/records.spec.js
webapp/src/js/controllers/contacts.js

Removed the requirement to provide a phone number (if you're from an
external facility you may not have a representitive phone number).
Added a 'complex' data type which lets JSON-backed JSON forms pass
complex JSON data in.
Added validation for JSON forms that come in as actual JSON, to give
type fields a point.
Removed features that are undocumented and (as far as I can tell from
actively supported projects) no longer used:
- Mapping SMS data into JSON paths
- is_numeric_years|months|days, which were in various levels of support
and reference in the codebase
- "autoreply" and "messages_task", which were referenced in test data
but had not associated features
- arbitrary eval-based (with magic scoping) validation that wasn't used
anywhere
General code cleanup to remove code that didn't …

Making JSON-inputed JSON forms more flexible

---

Gruntfile.js
tests/e2e/api/controllers/records.spec.js
webapp/patches/messageformat-default-plurals.patch

Opting for the most basic `make-plural` function: 
https://github.com/eemeli/make-plural/blob/master/packages/plurals/umd/plurals.js#L1
medic/medic#5705

Patch messageformat to provide "default" plurals fn instead of errors

---

webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/reports.js
webapp/tests/karma/unit/controllers/contacts.js

Limiting to the number of items in the livelist means if a new item
is added to the bottom of the list it won't be returned in the
search results.
medic/medic#5718

Make 50 the minimum contact search limit

---

webapp/src/js/controllers/analytics-reporting-detail.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/reports.js
webapp/src/templates/directives/filters/facility.html
webapp/src/templates/partials/filters/facility_items.html
webapp/tests/karma/unit/controllers/inbox.js
webapp/tests/karma/unit/controllers/reports.js

With this commit, the report tab will load without the facilities tree filter being built. When the user clicks on the tab, an initial load of the facilities tree takes place. Subsequent load happen as the user is scrolling through the list of facilities hierarchy and reaching the bottom of the list.
medic/medic#4423
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in …

Alleviate performance issue related to report tab

---

api/src/services/authorization.js
api/tests/mocha/services/authorization.spec.js
ddocs/medic/views/docs_by_replication_key/map.js
tests/e2e/api/controllers/_changes.spec.js
tests/e2e/docs-by-replication-key-view.js

Updates `docs_by_replication_key` to emit every id in submitter lineage for reports marked with `needs_signoff`. 
Updates API authorization service to return unique allowed doc ids (due to reports now emitting multiple keys)
medic/medic#5485 …

Replicate needs_signoff reports to the whole contact lineage

---

Gruntfile.js
webapp/package.json

Post https://github.com/medic/medic/issues/5694 , our `api` and `sentinel` bundled doubled in size because of lots of duplicated dependencies ( `npm pack` straight up copies the symlinked folders ). 
Running `npm dedupe` reduces our bundle sizes to what they were before.
| Version                                                                                                   | api    | sentinel | compiled.json |
|-----------------------------------------------------------------------------------------------------------|--------|----------|---------------|
| [3.5.x](https://staging.dev.medicmobile.org/_couch/_utils/document.html?builds/medic:medic:3.5.x)         | 3.7 MB | 2.9 MB   | 20.1 MB       |
| [master](https://staging.dev.medicmobile.org/_couch/_utils/document.html?builds/medic:me …

Runs npm dedupe before packaging api and sentinel

---

Gruntfile.js
package-lock.json
package.json

Puts redux in production mode for travis builds.
medic/medic#5767
The diff of running envify before minification:
```
<   if (process.env.NODE_ENV !== 'production') {
---
>   if ("production" !== 'production') {
178670c178670
<     if (process.env.NODE_ENV !== 'production') {
---
>     if ("production" !== 'production') {
178684c178684
<   if (process.env.NODE_ENV !== 'production') {
---
>   if ("production" !== 'production') {
178705c178705
<     if (process.env.NODE_ENV !== 'production') {
---
>     if ("production" !== 'production') {
178907c178907
< if (process.env.NODE_ENV !== 'production' && typeof isCrushed.name === 'string' && isCrushed.name !== 'isCrushed') {
---
> if ("production" !== 'production' && typeof isCrushed.name === 'string' && isCrushed.name !== 'isCrushed') {
```
I …

Use loose-envify to stub out environment checks

---

webapp/src/js/directives/auth.js
webapp/tests/karma/unit/directives/auth.js

Previously if auth.online failed but auth.any passed the element
would be shown. Now both need to pass for the element to be shown.
#5464

Fixes bug with two conflicting auth attributes 

---

shared-libs/transitions/src/lib/infodoc.js
shared-libs/transitions/test/integration/transitions.js
shared-libs/transitions/test/unit/lib/infodoc.js

This is not totally correct but is a less destabilising solution than a
more correct one.
For new documents the date will be off by however long it takes for
sentinel to catch up (which could be <1s).
For old documents that don't already have info docs the date will be
hilariously off.
A more correct solution would be to keep this code as is, and to create
infodocs in API when documents get PUT/POST/bulk_docs'ed
medic/medic#5760

Set initial_creation_date of infodocs to when they are first created

---

tests/e2e/service-worker.js

Wipe cache after unregistering service worker
medic/medic#5783

Wipe cache after unregistering service worker

---

webapp/src/js/controllers/tasks-content.js
webapp/src/js/services/enketo.js
webapp/src/js/services/rules-engine.js
webapp/src/js/services/select2-search.js
webapp/tests/karma/unit/controllers/tasks-content.js
webapp/tests/karma/unit/services/enketo.js
webapp/tests/karma/unit/services/rules-engine.js

Because of replication depth, the `contact_id` for a task's action may not be present on the device. This change makes it so enketo does a "best effort" to inject contact data when none is present, instead of throwing when building a ContactSummary.
Reports associated with contacts which are not on the device are not grouped under the same contact even when the associated contact id is the same. This updates RulesEngine to group reports by contact id in such cases.
#5789 
- …

Allow mRDT Supervisor Tasks to resolve based on multiple needs_signoff reports

---

Gruntfile.js
README.md

Reworks the ordering to be a bit clearer.
Removes the creation of the _users DB since you should be doing that as
part of CouchDB setup (along side _replicator etc) that you either do
manually or allow their wizard to do for you.
Fixes the use of credentials for CouchDB 2.3.0: CouchDB is no longer in
admin party, and so you create DBs or alter config with some kind of
credential.

Rework initial security setup for CouchDB 2.3.x

---

Gruntfile.js
package-lock.json
package.json
tests/base.conf.js
tests/e2e/login/login.specs.js

The version of `webdriver-manager` that is used in the old `protractor` didn't support downloading `ChromeDriver` versions that were not `semver` valid. 
The latest versions of `ChromeDriver` are `w3c` enabled by default, so an additional param needs to be added to the setup to support certain browser actions. 
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in …

Bumps protractor to support Chrome 76

---

README.md

Fix the markdown link for CHT in the Readme
medic/medic#NA
Simple typo update. Bug found through https://explore.ovio.org

Fix markdown link in Readme

---

CONTRIBUTING.md

* Replace Medic language with CHT language
* Add table of contents
* Replace references to Slack channel with Forum
* Add first time contributor section
* Clarify language, add links, and add request for `address #[issue number]` syntax under contributing code
* Add section on contributing to documentation

Update contributions page

---

webapp/src/js/services/enketo-translation.js
webapp/tests/karma/unit/services/enketo-translation.js

Recurse when generating list of hidden fields

---

webapp/src/js/controllers/inbox.js
webapp/src/js/services/session.js
webapp/tests/karma/unit/controllers/inbox.js
webapp/tests/karma/unit/services/session.js

Attempting to initialise everything all at once is inflating our
time to first paint. By delaying less important things until the
db is warmed and the UI is rendered the user can begin interacting
with the app sooner.
#5859
The software is provided under AGPL-3.0. Contributions to this project are accepted …

Delay secondary startup tasks

---

api/src/services/report/smsparser.js
api/tests/mocha/services/report/smsparser.spec.js

The data submitted through immunization forms was being translated
in the saved doc. This fix removes the translation of the values.
medic/medic#5762

Remove translation of fields values

---

webapp/src/js/enketo/OpenrosaXpathEvaluatorBinding.js
webapp/src/js/enketo/medic-xpath-extensions.js
webapp/tests/mocha/unit/enketo/medic-xpath-extensions.spec.js

Adds custom now and today implementations to medic-xpath-extensions
medic/medic#5768

Adds custom now and today implementations to medic-xpath-extensions

---

webapp/src/js/services/place-hierarchy.js
webapp/tests/karma/unit/services/place-hierarchy.js

The PlaceHierarchy service is no longer invoked with changes
callbacks so it errors when called. Updated service to not
expect callbacks.
medic/medic#5894

Fix bad merge resulting in inconsistent params

---

api/src/services/authorization.js
api/src/services/bulk-docs.js
api/tests/mocha/services/bulk-docs.js
shared-libs/tombstone-utils/src/tombstone-utils.js

Instead of loading all allowed doc ids in order to determine if a user can edit existent docs, use `_all_docs` requests to get current revs of uploaded docs and determine whether the user can edit them by running view map queries over them. 
Running locally, using the seed data (from gamma.dev): performance difference:
Instance | Uploading 100 docs to the server | Uploading 1 doc to the server 
-- | -- | --
master | 1112ms | 1088 ms |
this PR | 230ms | 87ms | 
medic/medic#5797
- …

Don't query docs_by_replication_key for offline _bulk_docs requests

---

webapp/src/js/services/tasks-for-contact.js
webapp/tests/karma/unit/services/tasks-for-contact.js

`model.children.contacts` is the result of a query, so it has an `id` or a `.doc._id`
#5899

Task list in places view doesn't include the tasks of children

---

webapp/src/js/services/enketo.js
webapp/tests/karma/unit/services/enketo.js

Triggering before save to update possible 'end' timestamp in form:
https://github.com/enketo/enketo-core/blob/a59c3322311b8966afc0f926392f7b1e193ebbce/src/js/preload.js#L50-L58
medic/medic#5768

5768 incorrect xlsform metadata

---

webapp/src/js/controllers/contacts-edit.js
webapp/src/js/services/enketo.js

Clears the enketo error whenever loading the form or making changes to the form radio buttons
medic/medic#5813

Clears the enketo error whenever loading the form or making changes to the form radio buttons

---

Gruntfile.js
webapp/patches/enketo-handle-no-active-pages.patch

Patches enketo so it logs a useful warning rather than throwing
a cryptic Error.
medic/medic#5484

Show useful error when no relevant fields

---

Gruntfile.js
README.md
shared-libs/server-checks/src/checks.js
tests/constants.js
tests/utils.js
webapp/tests/mocha/unit/testingtests/protractor/utils.spec.js

Uses docker and tmpfs mounting to provide a completely fresh CouchDB instance to
locally run e2e tests.
Travis is not affected.
This stops e2e results from polluting your CouchDB, including your `_users`
database.
CouchDB is left running under 4984 so you can inspect the DB if you wish. It
will get cleaned out on computer restart or on the next e2e call.
Additionally e2e tests will probably run faster locally as they are now
effectively running CouchDB out of a RAM drive.
It requires Docker to be installed in such a way that `docker` is available on
the command line.

Run e2e's CouchDB fresh each time via Docker

---

api/src/services/generate-xform.js
api/tests/mocha/services/generate-xform.spec.js
tests/e2e/sentinel/schedules/reminders.spec.js

Under load the 'exit' event fires before the child process has
finished writing to stdout. The 'close' event isn't fired until the
streams are closed.
medic/medic#5961

Listen for close on xsltproc child process

---

webapp/src/js/services/lineage-model-generator.js
webapp/tests/karma/unit/services/lineage-model-generator.js

Fixes LineageModelGenerator for offline users by not attempting to merge `undefined` (not replicated) parents.
medic/medic#5959

Fixes LineageModelGenerator for offline users

---

api/src/controllers/users.js
api/src/services/purged-docs.js
api/tests/mocha/controllers/users.spec.js
api/tests/mocha/services/purged-docs.js

Always check if the purge DB exists before querying it and delete the reference when it was deleted. 
Optionally also catch 404s from the _changes requests.
Fixes `users-info` not handling errors. 
medic/medic#6012
The software is provided under AGPL-3.0. Contributions to this project are accepted under the …

Catch db deleted errors.

---

tests/conf.js

Disables default config transitions in e2e tests.
PR set to merge into `6016-anc-app-targets` which adds transitions to default config. 

Disable transitions in e2e tests.

---

webapp/src/css/inbox.less

The refresh button was being pushed off the screen. This shrinks
the filters slightly so it fits nicely.
Also removes some code which was making the icons unnecessarily
small.
medic/medic#5951

Reduce filter width on small screens

---

webapp/src/js/app.js
webapp/src/js/services/index.js
webapp/src/js/services/translation-message-format-interpolation.js

Uncaught errors create feedback docs so can be a performance
issue when created in large numbers. This code catches and warns
about syntax errors which are probably a configuration issue.
#5863

Catch and downgrade interpolation syntax errors 

---

webapp/src/css/inbox.less

Limits size of resource icons in card to 30x30
medic/medic#5963

Limits size of resource icons in card

---

api/README.md
api/src/controllers/settings.js
api/src/services/settings.js
api/tests/mocha/services/settings.spec.js

Adds option to overwrite settings to api update settings endpoint
medic/medic#5940

Adds option to overwrite settings to api update settings endpoint

---

config/default/GUIDE.md

Splitting one large paragraph into two smaller ones to aid in skimming.
Fixes todo links that should never have been merged.

Guide fixes

---

webapp/src/js/controllers/tasks-content.js

Adds `selectedTask(null)` calls every time the user navigates away from the task-content controller:
a) after filling the task form
b) when cancelling filling the form: in mobile view, when pressing "X" header button and in desktop view when pressing "cancel"
medic/cht-core#6065
The software is provided …

Unset selected task explicitly

---

webapp/src/js/controllers/contacts-deceased.js

Reuse existing translation key to stop error

---

shared-libs/transitions/src/lib/utils.js
shared-libs/transitions/src/schedule/due_tasks.js
shared-libs/transitions/src/transitions/generate_patient_id_on_people.js
shared-libs/transitions/src/transitions/registration.js
shared-libs/transitions/src/transitions/utils.js
shared-libs/transitions/test/integration/schedules.js
shared-libs/transitions/test/unit/birth_registration.js
shared-libs/transitions/test/unit/due_tasks.js
shared-libs/transitions/test/unit/generate_patient_id_on_people.js
shared-libs/transitions/test/unit/lib/utils.js
shared-libs/transitions/test/unit/patient_registration.js
shared-libs/transitions/test/unit/pregnancy_registration.js
shared-libs/transitions/test/unit/transitions/registration.js
shared-libs/transitions/test/unit/utils.js

Refactors `registration` transition to use promises and not export every function. 
Refactors some utility function to use promises. 
medic/cht-core#6061

Refactors registration

---

webapp/src/js/filters/date.js

Instead of showing "Died 00:00", show "Died today".
medic/cht-core#6053

Fix rendering of people who died today

---

webapp/src/js/services/db-sync.js

Sets the timeout and heartbeat to keep the connection from the
browser alive for 10 minutes. This makes it more likely the client
will get a response if they are a long way behind the db current
seq.
medic/cht-core#6023
The software is provided under AGPL-3.0. Contributions to this project are accepted …

Set timeout on replication from server request

---

shared-libs/lineage/src/hydration.js
shared-libs/lineage/test/integration.js

Instead of performing a contact hydration for every doc-to-be-hydrated, perform the operation once, before hydrating anything else. This ensures that we never go too deep even if the docs-to-be-hydrated share some lineage.
medic/cht-core#6122 …

Only hydrate contacts once

---

api/src/controllers/changes.js
api/tests/mocha/controllers/changes.js
webapp/src/js/bootstrapper/index.js
webapp/src/js/bootstrapper/purger.js
webapp/tests/mocha/unit/bootstrapper.spec.js
webapp/tests/mocha/unit/purger.spec.js

API was throwing uncaught promise rejections which caused the
client to hang indefinitely waiting for a response during
bootstrapping.
In addition the client wasn't correctly detecting errors during
`fetch`.
medic/cht-core#6084 …

Handle errors during app bootstrap

---

admin/src/js/controllers/sms-settings.js
shared-libs/phone-number/package.json
shared-libs/phone-number/src/phone-number.js
shared-libs/phone-number/test/libphonenumber.spec.js
webapp/src/js/controllers/guided-setup-modal.js

Allows almost any values but still fails for any phone that contains a-z chars.
medic/cht-core#5864

Forces no validation

---

admin/src/js/controllers/sms-settings.js

We can't assume that the settings.outgoing_phone_replace is set.
medic/cht-core#6117

Fixes basic SMS settings page

---

tests/page-objects/contacts/contacts.po.js
webapp/src/js/controllers/reports-content.js
webapp/src/js/directives/navigation.js

These changes fix the navigation when
1) when the user is reviewing a report detail then navigate back to the list and then attempts to view again the detail of the same report (pre-fix the user will be stuck on the list)
2) when the user deletes a contact or a report, she will be redirected to the list (pre-fix the user will be stuck on the detail screen with an empty screen)
medic/cht-core#6118
- Backwards compatible: Works with existing …

Fix navigation (back + after contact/report deletion) 

---

ddocs/medic-client/views/contacts_by_last_visited/map.js
ddocs/medic/views/reports_by_form_and_parent/map.js

CouchDBs built-in _stats reduce function errors out if given anything
other than a number. Adds type checking with a fallback to 0.
medic/cht-core#6170

Check types of values passed to _stats reduce

---

docker-compose.yml

This image includes the xsltproc dependency plus other fixes.
This is based off of the documentation here: https://github.com/medic/medic-docs/blob/master/installation/public-docker-image-setup.md#use-docker-compose.
Should we just have one place where we keep the updated compose file? cc @Hareet

reference the 3.7 medic-os docker image

---

tests/patches/webdriver-manager-config.patch

E2E tests are failing due to the release of Chrome78 without a corresponding release of WebDriver. Patch maxDriverVersion

Patch webdriver-manager maxChromedriver to 78

---

api/src/server-utils.js
api/tests/mocha/server-utils.spec.js
webapp/src/js/app.js
webapp/src/js/services/db-sync.js
webapp/tests/karma/unit/services/db-sync.js

- Test and fail the replication to the server if the body size is
likely to be too large.
- Catch the error and retry with a smaller batch size.
- Give up when the batch size is set to 1.
medic/cht-core#6143 …

Retry replication with reducing batch size

---

api/src/controllers/changes.js
api/src/services/messaging.js
api/tests/mocha/services/messaging.spec.js

When we removed config.default.json we broke the upgrade path for
projects without explicit settings for sms. This restores the defaults
in code.
medic/cht-core#6163

Add defaults to restore backwards compatibility

---

api/src/services/authorization.js
api/tests/mocha/services/authorization.spec.js
ddocs/medic/views/docs_by_replication_key/map.js
shared-libs/rules-engine/src/index.js
shared-libs/rules-engine/src/pouchdb-provider.js
shared-libs/rules-engine/src/provider-wireup.js
shared-libs/rules-engine/src/refresh-rules-emissions.js
shared-libs/rules-engine/src/rules-emitter.js
shared-libs/rules-engine/src/rules-state-store.js
shared-libs/rules-engine/src/transform-task-emission-to-doc.js
shared-libs/rules-engine/test/integration.spec.js
shared-libs/rules-engine/test/mocks.js
shared-libs/rules-engine/test/pouchdb-provider.spec.js
shared-libs/rules-engine/test/provider-wireup.spec.js
shared-libs/rules-engine/test/rules-emitter.spec.js
shared-libs/rules-engine/test/rules-state-store.spec.js
tests/e2e/api/controllers/all-docs.spec.js
tests/e2e/api/controllers/bulk-docs.spec.js
tests/e2e/api/controllers/bulk-get.spec.js
tests/e2e/api/controllers/db-doc.spec.js
tests/e2e/docs-by-replication-key-view.js
webapp/src/js/services/rules-engine.js
webapp/tests/karma/unit/services/rules-engine.js

Adds a new "default" replication subject, in the form of the user's couchdb user id (org.couchdb.user:<username>). Documents that must be replicated by a specific user only should emit this value in medic/docs_by_replication_key.
Updates task documents to use this value as their user property, making uploaded tasks only available to them, and not to their supervisors or anyone who shares their lineage. Task document ids also change to use the user's doc id instead of the contact's doc id.
Updates target to also use this value as their user property (for consistency), adds the owner property that saves the contact's uuid and updates medic/docs_by_replication_key so targets emit owner - in order to make targets available for supervisors. The target doc id is updated to include the user's …

Adds per-user replicated docs, tasks are per-user replicated docs (#6191)

---

shared-libs/transitions/src/transitions/registration.js

Reverts change that makes use of `getSubjectId` to get the report's subject.  
The function used for validation `getContactUuid` only accepts shortcodes, while `getSubjectId` might return a uuid, thus marking correct reports with `registration_not_found` when one was missing `patient_id`.
medic/cht-core#6205
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in …

Registration only validates "subject" by patient_id

---

DEVELOPMENT.md

Make it clearer to use https with ngrok, to avoid endless loops: medic/cht-core#6221

Updated for https with ngrok

---

sentinel/src/schedule/outbound.js
sentinel/tests/unit/schedule/outbound.js

Adds support for using outbound push with RapidPro, or any third party tool that does authentication via credentials in HTTP headers.
Documentation and tests have yet to be included.
medic/cht-core#6207 …

6207 rapidpro outbound push

---

webapp/src/js/services/enketo.js

When switching to server-side form generation, we switched from setting the user's language directly in the xml, pre-conversion, to relying on Enketo's `lang` module.
This module contains a bug where dynamic elements would be generated using the default language instead of the one set with the module: https://github.com/enketo/enketo-core/issues/596 . 
Additionally, non-localized forms would have translation values under the `default` translation tag. 
When setting the user's language, we inadvertently stopped supporting non-localized forms that had translation labels. 
This PR attempts to detect whether the form is localized or not.
Non-localized forms are unaltered. Localized forms' html gets updated to set the user's language as active before passing them to Enketo. …

Show correct language labels for dynamic elements and non-localized forms
