medic/cht-core

lib/fulltext.js

Add the clinic name to full-text index used for searching data_records.
Fix for issue #921

Fix for #921 Full-text search: Places not indexed in Reports tab

---

lib/validate_doc_update.js
packages/kujua-sms/kujua-sms/updates.js
packages/kujua-sms/kujua-sms/views.js
packages/kujua-sms/tests/kujua-sms/smsparser.js
packages/kujua-sms/views/lib/javarosa_parser.js
packages/kujua-utils/kujua-utils.js

Issue: medic/medic-webapp/issues/817

support for medic-api messages endpoint.

---

static/js/controllers/edit-contact.js
static/js/services/db-view.js

Just a little PR to improve naming consistency which @garethbowen and I discussed a couple of days ago.

Rename `params` in DbView & EditContactCtrl to match HttpWrapper

---

lib/show-includes/configuration.js
static/js/services/download-url.js

trying to resolve case sensitivity issues.

exports bugfix

---

Changes.md
Gruntfile.js
kanso.json
lib/show-includes/configuration.js
lib/shows.js
package.json
packages/kujua-sms/kujua-sms/rewrites.js
packages/kujua-sms/kujua-sms/views.js
packages/kujua-sms/tests/kujua-sms/smsparser.js
packages/kujua-sms/tests/kujua-sms/smsparser_compact_textform.js
packages/kujua-sms/views/lib/mp_parser.js
packages/kujua-sms/views/lib/smsparser.js
packages/kujua-sms/views/lib/textforms_parser.js

v0.4.8 release

---

kanso.json
packages/kujua-sms/views/lib/app_settings.js

Issue: https://github.com/medic/medic-webapp/issues/750

added outgoing_deny_list to settinsg schema in kanso.json.

---

Changes.md
kanso.json
package.json
packages/kujua-sms/kujua-sms/rewrites.js

Issue: https://github.com/medic/medic-webapp/issues/1273

1273 records export bug/regression

---

bower.json
static/css/admin.less
static/css/inbox.less
static/js/controllers/configuration-settings-basic.js
static/js/controllers/inbox.js
static/js/enketo/widgets/db-object-widget.js
static/js/enketo/widgets/medic-place-widget.js
static/js/modules/guided-setup.js
static/js/modules/send-message.js
templates/modals/edit_report.html
templates/modals/edit_user.html
templates/modals/guided_setup.html
templates/modals/send_message.html
templates/modals/update_facility.html
templates/partials/configuration_settings_advanced.html
templates/partials/configuration_settings_basic.html

@madric please review!
Known/suspected issues:
* facility selecter does not reset to blank when creating a new user in Config section
* sending message to multiple recipients may or may not work as expected (seems a bit weird to me, but i haven't checked the old behaviour)
* enketo db-selecters are a little bit hacky right now (inline changing of `<input>` to `<select>`)
* CSS may not look like it used to (poss missing bootstrap sylings)

1395 select 2

---

static/js/controllers/inbox.js
templates/partials/help.html

Issue #1664 
This is dependent on an update in medic-android as well but shouldn't
break anything as-is.

added android app version to help page. 

---

static/js/controllers/help.js
templates/partials/help.html

Issue #1723 
Might help a little in debugging.

added database info to help page. 

---

static/js/controllers/inbox.js
tests/karma/unit/controllers/inbox.js

Redirect to 'contacts' state after contact is deleted (second try)

---

Gruntfile.js

Minimise HTML in build process before writing templates.js

---

.jshintrc
static/js/app.js
static/js/services/db.js

Segregate local PouchDB by username

---

package.json
static/js/controllers/inbox.js
static/js/enketo/widgets/phone-widget.js
static/js/services/db.js
static/js/services/import-contacts.js
static/js/services/traffic-stats.js
tests/karma/unit/controllers/inbox.js
tests/karma/unit/services/traffic-stats.js

Merge a couple of important changesets in to `testing` to unblock acceptance testing on `lg.dev`.

Periodic merge: develop to testing

---

static/js/services/live-list.js
templates/partials/reports_list_item.html

Also update report list items so their date resolution is to the nearest day,
removing relative times like "just now", "5 minutes ago" etc.
Issue: #1947

Refresh LiveList list elements every midnight

---

static/js/controllers/contacts-edit.js

Issue: #1948
I have no idea what broke this, but this fixes it.

Make contact editing work

---

static/css/inbox.less
static/js/controllers/contacts-content.js
static/js/controllers/inbox.js
static/js/services/db-sync.js
static/js/services/live-list.js
static/js/services/target-generator.js
static/js/services/task-generator.js
templates/inbox.html
templates/partials/about.html
tests/karma/unit/services/db-sync.js
tests/karma/unit/services/target-generator.js
tests/karma/unit/services/task-generator.js

#2033, rebased against `develop`.  @SCdF we should double check & merge this in the morning.

Initial sync status and warm couch

---

.travis.yml
scripts/ci/travis_after_all.py

Temporarily disable broken builds; fix crash in `travis_after_all.py`.

Merge from develop to testing

---

static/js/controllers/contacts-content.js

Display contact history most-recent-first

---

static/js/controllers/contacts.js
static/js/controllers/reports-add.js
static/js/controllers/reports.js

2153 move out of scope

---

static/js/services/enketo-translation.js
tests/karma/unit/services/enketo-translation.js

Ordered data binding

---

lib/views.js
static/js/enketo/widgets/db-object-widget.js

Adds in:
- Ajax filter (instead of loading the whole shebang)
- Fixes that came after, so that initial selections etc are honoured.

Cherry-pick the db-object-widget fixes into testing

---

static/js/controllers/edit-user.js
static/js/controllers/inbox.js
static/js/controllers/index.js
static/js/controllers/user-language-modal.js
static/js/services/language.js
templates/inbox.html
templates/modals/user_language.html
tests/karma/unit/controllers/user-language-modal.js

2155 modals 2

---

.jshintrc
Gruntfile.js
tests/.jshintrc

Moves stuff that should just be global for tests just to testing
Issue: #2274

Makes jshint more accurate

---

Changes.md
kanso.json
package.json
packages/kujua-reporting/kujua-reporting/shows.js
packages/kujua-reporting/tests/kujua-reporting/reporting.js

Issue: https://github.com/medic/medic-projects/issues/442
Added tests but coverage is lacking on `renderFacility` and would take some time to mock properly.  Thinking time better spent on 2.x code base.

time unit in weeks bug

---

kanso.json

Add documentation to app_settings. #2473

---

tests/integration/migrations/extract-person-contacts.js

Issue: #2586
Please review and merge https://github.com/medic/medic-api/pull/92 before merging this PR.

Do not break extract-person-migration if parent does not exist

---

static/js/controllers/messages-content.js
static/js/modules/send-message.js
static/js/services/select2-search.js
tests/protractor/e2e/send-message.js

Clicking add recipients works as expected.

Support add recipients #2659

---

static/js/controllers/contacts.js

Search is either a raw text search of contacts you can access, or its
all contacts that are the type one "below" your facility. E.g., for a
CHW that would be all families, for a branch manager that would be all
CHW areas, etc.

Either search or scope to type

---

static/js/controllers/contacts-content.js
templates/partials/contacts_content.html
tests/karma/unit/controllers/contacts-content.js

2343 rhs card

---

ddocs/medic-client/views/doc_summaries_by_id/map.js
static/js/services/live-list.js
templates/partials/contacts_list_item.html
translations/messages-en.properties

Replacing the breadcrumb display of where that place sits in the
heirearchy.

Contact list shows primary contact #2340

---

static/js/services/contact-schema.js
tests/karma/unit/services/contact-schema.js

Refactor contact-schema. #2697

---

static/css/material.less
static/js/controllers/contacts-edit.js
static/js/controllers/contacts.js
templates/partials/contacts_content.html
tests/karma/unit/controllers/contacts.js

2811 mobile header

---

ddocs/medic-client/views/contacts_by_freetext/map.js
ddocs/medic-client/views/contacts_by_type_freetext/map.js
ddocs/medic-client/views/reports_by_freetext/map.js

- Skip keys that we've already used or are too small
- Tweaking specific skip keys to reduce junk

Improve freetext views #2853

---

scripts/upload_xform.sh

The -c option was left for backwards compatibility but -m is preferred. Also added a -d option for running a dry-run (no changes persisted).

Add -m option for meta file. Issue: #2838

---

static/js/enketo/widgets/db-object-widget.js

This means the changes handler fires when the initial value is set.

Register listener before select2 init. Issue: #2911

---

static/js/services/changes.js
tests/karma/unit/services/changes.js

Errors kill the changes feed, so reconnect after 5 seconds if an error
occurs.

Changes feed learns about reconnecting #2919

---

static/js/controllers/contacts-edit.js

Also removed an unused function

Set showContent when creating contact. #2957

---

.travis.yml
Gruntfile.js
packages/kanso-app-settings/build/compile.js
tests/protractor/conf.js

Use couchdb 2.0 on travis

---

ddocs/medic-client/views/reports_by_freetext/map.js
templates/partials/analytics/anc/high-risk.html
templates/partials/analytics/anc/missed-appointments.html
templates/partials/analytics/anc/missing-delivery-reports.html
templates/partials/analytics/anc/upcoming-appointments.html
templates/partials/analytics/anc/upcoming-due-dates.html

It's worse than that, freetext report searching is dead Jim!

Fix ANC Anlytics links. #2975

---

templates/partials/analytics/reporting_detail.html

Also use the clinic id not phone number so the clinic name renders in the to field.

Check for phone before rendering message icon. #2998

---

static/js/controllers/inbox.js

Remove JSON forms from Actions button. #2988

---

static/js/controllers/contacts-content.js
templates/partials/contacts_content.html

ng-init causes a race condition so best to avoid it where possible. #3028

Show task count on refresh

---

static/js/controllers/contacts-content.js
tests/karma/unit/controllers/contacts-content.js

Allow same `person` to be primary contact for multiple places. #2385

---

static/js/controllers/edit-report.js

SMS reports where the phone number has not been matched to a contact yet
can now be edited and have a CHW / facility attached to them.

JSON reports with no contact can be edited #3087

---

kanso.json
packages/kujua-sms/kujua-sms/updates.js
packages/libphonenumber/libphonenumber/utils.js
static/css/inbox.less
static/css/material.less
static/js/controllers/configuration-settings-basic.js
static/js/controllers/contacts-content.js
static/js/controllers/contacts.js
static/js/enketo/widgets/phone-widget.js
static/js/filters/index.js
static/js/filters/message.js
static/js/filters/phone.js
static/js/modules/format.js
static/js/services/contact-summary.js
static/js/services/index.js
static/js/services/send-message.js
static/js/services/xml-forms.js
templates/partials/contacts_content.html
tests/karma/unit/controllers/contacts.js
tests/karma/unit/controllers/inbox.js
tests/karma/unit/services/changes.js
tests/karma/unit/services/contact-summary.js
tests/karma/unit/services/db.js
tests/karma/unit/services/enketo-prepopulation-data.js
tests/karma/unit/services/enketo.js
tests/karma/unit/services/session.js
tests/nodeunit/unit/libphonenumber.js
tests/protractor/e2e/contact-summary.js

#2914: allow for configuring additional cards to show up on contact pane.
#3037: Allow for configuring which fields show up in contact summary.
#2913: Allow for configuring additional context for showing/hiding create report actions.
#1930: Format phone numbers nicely

Configurable contact summary information

---

static/js/controllers/contacts-content.js

Puts patient names where the html expects them to be.

Add patient names to reports #3084

---

templates/partials/contacts_content.html

Hide the people section on a person page

---

static/js/modules/nootils.js
tests/karma/unit/services/rules-engine.js
tests/nodeunit/unit/nootils.js

Set the task due date to the start of the day

---

lib/views.js

Adding view to find patient person contact via their shortcode.
Fixes #3115, #3075 and partially fixes #3082.

Patient centric view support

---

kanso.json

Add translation keys to app settings schema

---

static/js/services/rules-engine.js
tests/karma/unit/services/rules-engine.js

Check patient_id on change

---

kanso.json

Corresponds to https://github.com/medic/medic-sentinel/pull/109

Add new trigger to clear schedules

---

static/js/controllers/contacts-content.js

Don't assume children.persons is defined

---

static/js/controllers/messages-content.js
static/js/controllers/messages.js

Splice message on delete

---

static/js/controllers/inbox.js
static/js/controllers/reports.js

Don't clear list when deletion detected

---

static/js/controllers/contacts-report.js

Only clear right action bar when filing new report

---

static/css/inbox.less

Set text overflow for tour buttons

---

templates/modals/edit_report.html
templates/partials/actionbar.html

Improve UI for editing JSON report

---

static/js/controllers/reports.js

Update reports when loading the tab

---

templates/partials/analytics.html

Don't show 'no configured modules' until finished loading modules

---

static/js/controllers/reports-content.js
static/js/controllers/reports.js

Fix reports change listeners

---

static/js/services/changes.js

Handle exceptions in changes callbacks

---

static/js/services/rules-engine.js

Check for null values in facts

---

static/js/modules/nootils.js
tests/nodeunit/unit/nootils.js

Don't include deleted reports when looking for most recent

---

.travis.yml
Gruntfile.js

You uhm. You definitley want to squash this.

3187 both couches

---

static/js/services/target-generator.js
tests/karma/unit/services/target-generator.js

Remove irrelevant targets from cache

---

lib/views.js

Fix scheduled report views to use doc.fields

---

static/js/services/enketo.js
static/js/services/xslt.js
tests/karma/unit/services/enketo.js

Force xform regeneration when user has changed language

---

package.json
static/js/services/send-message.js
tests/karma/unit/services/send-message.js

Avoid pouch db uuid generator

---

static/js/controllers/contacts.js
static/js/controllers/messages.js
static/js/controllers/reports.js
static/js/services/generate-search-query.js
templates/partials/actionbar.html
tests/karma/unit/controllers/contacts.js
tests/karma/unit/controllers/messages.js
tests/karma/unit/controllers/reports.js
tests/karma/unit/services/generate-search-query.js

Add export button back to reports, contacts, and messages

---

packages/kujua-sms/views/lib/smsparser.js
tests/nodeunit/unit/kujua-sms/smsparser.js

Support Nepali numerals in incoming SMS

---

packages/kujua-utils/kujua-utils.js

Fix: update_message_task does not update scheduled_tasks in 0.4

---

static/css/enketo/medic.less
static/js/controllers/contacts-edit.js
static/js/controllers/contacts-report.js
static/js/controllers/reports-add.js
static/js/controllers/tasks-content.js
static/js/directives/enketo.js
static/js/directives/index.js
templates/directives/enketo.html
templates/partials/contacts_edit.html
templates/partials/contacts_report.html
templates/partials/reports_add.html
templates/partials/tasks_content.html
translations/messages-en.properties

Add cancel button to enketo forms

---

static/js/services/auth.js
tests/karma/unit/services/auth.js

Lack of an error message in these rejections led to some very annoying debugging.  @garethbowen giving this one to you in case there was a reason for the empty rejection in the first place.

Explain why you're rejecting me!

---

Gruntfile.js
tests/.jshintrc
tests/protractor/conf.js
tests/protractor/e2e/registration-by-sms.js

Most of the work here was to start sentinel so that e2e tests can be
written to test sentinel workflows. To prove it works it includes a
test for the registration transition.
medic/medic-webapp#3229

Add e2e test for sentinel transition

---

static/js/app.js

Added hi, id, and sw locales to match the set of locales we ship with.
medic/medic-webapp#3282

Add additional supported moment locales

---

templates/partials/contacts_content.html

Full width for contact profile fields on mobile

---

npm-shrinkwrap.json
package.json

This has triggered a lot of shrinkwrap changes.
Issue: #3311

Update jquery version for enketo compatibility

---

Gruntfile.js
package.json

Issue: #3317 
```sh
Running "xmlmin:dist" (xmlmin) task
File static/dist/xslt/openrosa2html5form.xsl created: 74.29 kB → 36.72 kB
File static/dist/xslt/openrosa2xmlmodel.xsl created: 1.83 kB → 887 B
```

Minify XSL stylesheets

---

static/js/controllers/contacts-edit.js
static/js/controllers/contacts-report.js
static/js/controllers/inbox.js
static/js/controllers/reports-add.js
static/js/controllers/tasks-content.js
templates/directives/modal.html
templates/partials/contacts_edit.html
templates/partials/contacts_report.html
templates/partials/filters/navigation.html
templates/partials/reports_add.html
templates/partials/tasks_content.html

This change disables cancel button while submitting modals or enketo
reports.
medic/medic-webapp#1650

Disable buttons while saving

---

Gruntfile.js

This takes idle CPU usage on my laptop down from ~15-20% to ~1%.
It also dropped my CPU "idle" temp from ~75ºC to ~60ºC.

Lower the check interval to 1000ms from 100ms

---

npm-shrinkwrap.json

Fix outdated npm shrinkwrap entry for enketo-core

---

.travis.yml
Gruntfile.js
tests/protractor/auth.js
tests/protractor/constants.js
tests/protractor/e2e/medic-collect.js

#3370
@garethbowen this e2e test explicitly checks to prevent a repeat of the regression reported in #3118.  There are TODOs for further useful tests, but the effort of writing them makes me question their worth.  I _may_ fill them in over the course of this weekend, but please review this PR as you find it.
---
N.B. I have no idea why I need to use `5998` as the api port (I would expect `5988`), and even weirder that https://github.com/medic/medic-webapp/pull/3386 passes with the value change to `5988`, but this PR does not.
---
I've hardcoded all the API details into this test, which seems questionable.  However, I initially thought I could get these details from `tests/protractor/auth.js`, but quickly realised that (1) this file does some weird stuff that is explicitly undesirable for …

3370 collect e2e tests

---

static/js/bootstrap.js
templates/inbox.html
tests/nodeunit/unit/bootstrap.js

Show loading progress when app is starting

---

static/js/controllers/contacts-edit.js
static/js/services/enketo.js

This creates a chicken and egg requirement where the user cannot create
their own contact.
medic/medic-webapp#3394

Don't require user contact when creating contacts

---

lib/views.js
tests/protractor/e2e/sms-gateway.js

:yay: 
medic/medic-webapp#3073

3073 message delivery statuses

---

Gruntfile.js

3409 delete fixtures medic/medic-webapp#3409

---

package.json
tests/protractor/e2e/medic-collect.js

...and bump API to make it pass.
Issue: #3390

Add e2e test for getting list of forms from api

---

static/js/enketo/jquery-shim.js

This file is no longer referenced, and serves no purpose.

Delete unused file: jquery-shim.js

---

static/js/services/contacts.js

As per https://github.com/medic/medic-webapp/blob/master/static/js/controllers/home.js#L1

Only import parts of async lib that we use

---

static/js/controllers/contacts-edit.js

$timeout allows angular to finish rendering the page before Enketo
attempts to render the form using jquery.
medic/medic-webapp#3448

Adds a timeout to resolve rendering race condition

---

static/js/controllers/edit-user.js
templates/modals/edit_user.html
tests/karma/unit/controllers/edit-user.js

3067 restricted user has place and contact

---

tests/protractor/page-objects/forms/new-pregnancy-form.po.js

Added new pregnancy form page object

Protractor tests

---

static/js/enketo/widgets/db-object-widget.js

Re-initialise enketo db object selecters when cloning for repeats

---

static/js/services/contact-view-model-generator.js
tests/karma/unit/services/contact-view-model-generator.js

Not sure quite what happened, but unit test without code change breaks, and with code change passes.
#3517

3517 display contacts for restricted

---

static/js/services/enketo.js
tests/karma/unit/services/enketo.js

Improve error message when associated contact cannot be found or accessed

---

static/css/inbox.less
templates/partials/tasks_content.html

Makes the task summary page more attractive

---

Gruntfile.js
ddocs/medic-client/views/contacts_by_freetext/map.js
ddocs/medic-client/views/contacts_by_type_freetext/map.js
ddocs/medic-client/views/reports_by_freetext/map.js
static/js/services/generate-search-requests.js
tests/nodeunit/unit/views/contacts_by_freetext.js
tests/nodeunit/unit/views/contacts_by_type_freetext.js
tests/nodeunit/unit/views/reports_by_freetext.js
tests/nodeunit/unit/views/utils.js

#3392 Allow non-ascii search

---

tests/protractor/e2e/submit-enketo-form.js

Adds a small sleep to make test deterministic

---

static/css/dropdown.less
templates/partials/actionbar.html

- Vertically center the chevron and text content of menu items
- Define the chevron as a css after for consistency
- Use chevron in the Report > Submit Report menu for consistency
medic/medic-webapp#3469

Realign report menu items

---

scripts/ci/after_success.sh

This looks helpful to me, but maybe shrinkwrap's already doing something clever.

Excelude api and sentinel's dev dependencies from binary

---

Changes.md
static/js/services/contact-summary.js
tests/karma/unit/services/contact-summary.js
tests/protractor/e2e/contact-summary.js

Replaces the eval call with the slightly safer new Function()
statement. This requires a configuration change as outlined in
the changelog.
medic/medic-webapp#3546

Refactor to use Function instead of eval

---

static/js/controllers/reports-add.js
static/js/enketo/widgets/db-object-widget.js
static/js/services/enketo-translation.js
static/js/services/enketo.js
tests/karma/unit/services/enketo-translation.js
tests/karma/unit/services/enketo.js

Using the form definition we can determine if a field is a repeat
in which case we store it in an array.
Also fixes a race condition when rendering of the db-object-widget
when in a repeat.
And tidies up a couple of TODOs.
medic/medic-webapp#3430

Fixes XML to JSON conversion for repeat fields

---

static/js/controllers/edit-user.js
tests/karma/unit/controllers/edit-user.js

Closes medic/medic-projects#2372

Don't set user's password when none is supplied

---

.travis.yml

#3590 
Apparently this wasn't working on master because CouchDB was not available?
@garethbowen was this the issue? It looks like the opposite is true-- it's now available by default and so it wasn't starting and halting the build. This change works in the builds I've done, we can look at it again if it breaks master (ie if different travis servers are different)

Travis therapy

---

README.md

Issue: https://github.com/medic/medic-webapp/issues/3431

update readme with couchdb setup step.

---

static/js/controllers/contacts.js
static/js/services/contact-summary.js

- The property is lineage, not parents.
- Push the default value down into the service.
- Catch and handle any errors properly.
medic/medic-webapp#3598

Passes correct property to ContactSummary

---

.travis.yml
Gruntfile.js
tests/karma/karma-unit.conf.js

Unit tests run in headless chrome

---

tests/protractor/e2e/auditing.js
tests/protractor/e2e/bulk-delete.js
tests/protractor/e2e/contact-summary.js
tests/protractor/e2e/docs-by-replication-key-view.js
tests/protractor/e2e/registration-by-sms.js
tests/protractor/e2e/report-date-filter.js
tests/protractor/e2e/send-message.js
tests/protractor/e2e/submit-enketo-form.js
tests/protractor/e2e/users/add-user.specs.js
tests/protractor/page-objects/forms/delivery-report.po.js
tests/protractor/utils.js

This new function is designed to be called after each test,
and resets settings (if they've changed) and deletes all docs
except for a whitelist of system docs such as ddocs.
medic/medic-webapp#3602

Adds a db reset utility function 

---

tests/protractor/e2e/send-message.js
tests/protractor/utils.js

Adding some debugging, so if there is a flaky test we might be able to work out why. See: https://github.com/medic/medic-webapp/commit/14ec60e6ab8c2dfc67221535c6879c8e2df84615

Add some flaky test debugging

---

tests/protractor/utils.js

Return your promises

---

Changes.md
kanso.json

[description]
- ~~Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.~~
- ~~Tested: Unit and/or e2e where appropriate~~
- ~~Internationalised: All user facing text~~
- ~~Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.~~

3416 multi form alerts

---

static/css/inbox.less
static/css/theme.less

Long descriptions aren't recommended but where they occur we
should handle them gracefully. This also affects Reports.
medic/medic-webapp#3525

Wraps titles in task list items

---

.gitignore
tests/protractor/auth.js
tests/protractor/conf-chrome.js
tests/protractor/e2e/auditing.js
tests/protractor/e2e/bulk-delete.js
tests/protractor/e2e/common/common.specs.js
tests/protractor/e2e/contact-summary.js
tests/protractor/e2e/contacts/create-new-district.specs.js
tests/protractor/e2e/docs-by-replication-key-view.js
tests/protractor/e2e/forms/submit-delivery-form.specs.js
tests/protractor/e2e/integration.js
tests/protractor/e2e/login/login.specs.js
tests/protractor/e2e/report-date-filter.js
tests/protractor/e2e/send-message.js
tests/protractor/e2e/sms-gateway.js
tests/protractor/e2e/submit-enketo-form.js
tests/protractor/e2e/users/add-user.specs.js
tests/protractor/helper.js
tests/protractor/page-objects/common/common.po.js
tests/protractor/page-objects/contacts/contacts.po.js
tests/protractor/page-objects/forms/delivery-report.po.js
tests/protractor/page-objects/login/login.po.js
tests/protractor/page-objects/messages/messages.po.js
tests/protractor/page-objects/users/add-user-modal.po.js
tests/protractor/page-objects/users/users.po.js
tests/protractor/utils.js

Changed test files to ES6 style

Fix es6 inconsistencies

---

packages/settings/build/utils.js

update settings package on 0.4.x

---

Changes.md
packages/settings/build/utils.js

update settings package on master

---

tests/protractor/e2e/medic-collect.js

Update medic-collect e2e tests to pay attention to form context
Issue: #3642

Filter collect forms when generating forms list

---

package-lock.json
package.json
static/js/enketo/widgets.js
static/js/enketo/widgets/bikram-sambat-datepicker.js

Issue: #3404
Include bikram sambat datepicker in Enketo forms when local set to Nepali
medic/medic-webapp#3404

Include bikram sambat datepicker in Enketo forms when local set to Nepali

---

Changes.md
packages/settings/build/utils.js

update settings package in 0.4.x

---

Changes.md
packages/settings/build/utils.js

update settings package on 2.10.x

---

Changes.md
packages/settings/build/utils.js

update settings package on 2.11.x

---

Changes.md
packages/kanso-app-settings/build/compile.js
packages/settings/build/utils.js

update settings package on 2.12.x

---

kanso.json

Don't attach modules.js

---

kanso.json

Add documentation in kanso.json for multi_form_alerts' name field. And bump sentinel.
medic/medic-webapp#3635

3635 multi form alerts analytics

---

static/js/services/contact-schema.js
static/js/services/debug.js
static/js/services/enketo-prepopulation-data.js
static/js/services/enketo-translation.js
static/js/services/enketo.js
static/js/services/file-reader.js
static/js/services/live-list.js
static/js/services/markdown.js
static/js/services/translation-loader.js

Add use strict where missing from services

---

templates/partials/actionbar.html
tests/protractor/e2e/submit-enketo-form.js
tests/protractor/helper.js

Add a sleep to get tests to pass

---

tests/protractor/conf.js

Add error when running e2e tests if COUCH_NODE_NAME env var missing

---

kanso.json

Document added fields to multi_form_alerts message template context. 

---

.travis.yml
package-lock.json
package.json
tests/protractor/conf.js
tests/protractor/page-objects/forms/delivery-report.po.js

Hopefully speeds up tests and makes them more reliable.
medic/medic-webapp#3695

Run e2e tests in headless chrome

---

static/js/controllers/send-message.js
static/js/modules/format.js
static/js/services/select2-search.js

This was broken during the linked contacts refactor.
medic/medic-webapp#3727

Show lineage in select2 results

---

scripts/ci/push_to_staging.sh

Let's see if this gets pushed to staging...

Don't push PR builds to staging

---

Changes.md
packages/kanso-gardener/build/compile.js
packages/settings/build/utils.js

Don't include _url in ddoc 

---

.travis.yml
scripts/ci/push_to_staging.sh

Also push builds to builds database on staging from CI

---

static/js/controllers/contacts-edit.js

The code doesn't use the inlined fields any more so this saves
a few more bytes of redundant information.
medic/medic-webapp#3785

Minify the contact on created places

---

kanso.json

More doc for multi_report_alerts. medic/medic-webapp#3715

---

Gruntfile.js
package-lock.json
package.json

-> https://github.com/angular-pouchdb/angular-pouchdb/commits/v5.0.1

Update angular-pouchdb for flexible Pouch versioning

---

Gruntfile.js
package-lock.json
package.json

Makes the slow increase of size of static resources more obvious
and able to be compared before merging PRs.
medic/medic-webapp#3741

3741 monitor bundle size

---

tests/protractor/e2e/contacts/add-new-person.js

The assertion is just testing that the test code works as expected
not that the app code works as expected.
medic/medic-webapp#3816

Remove unnecessary flakey assertion

---

static/js/services/select2-search.js

When selecting a contact using the db object widget we rely on the
parents and contacts being hydrated so we can bind fields to xform
fields.
medic/medic-webapp#3831

Hydrate select2 results

---

tests/protractor/e2e/common/common.specs.js
tests/protractor/e2e/contacts/add-new-person.js
tests/protractor/e2e/users/add-user.specs.js
tests/protractor/page-objects/common/common.po.js
tests/protractor/page-objects/contacts/contacts.po.js
tests/protractor/page-objects/forms/new-pregnancy-form.po.js
tests/protractor/page-objects/users/add-user-modal.po.js
tests/protractor/page-objects/users/users.po.js

Added tests for the 'add user' modal:
- creating user with valid password
- attempts to create user without required fields (user name, password, place and contact for restricted user)
- attempt to create user with short, weak and non-matching passwords

Add user modal tests

---

static/js/services/contact-summary.js

Don't compile it every time the contact summary is requested.
Invalidation is handled by the page being refreshed on configuration
change.
medic/medic-webapp#3837

Cache contact summary generator function

---

static/js/modules/format.js
static/js/services/live-list.js
templates/partials/reports_list_item.html
templates/partials/tasks_list_item.html
tests/mocha/unit/modules/lineage.spec.js

Without this script injection is possible by including HTML as the
name of a contact.
medic/medic-webapp#3873

Escape lineage filter and live list output

---

static/js/controllers/guided-setup-modal.js

Logging the element being clicked caused a circular reference
serialization error to be thrown.
medic/medic-webapp#3872

Remove console statement that errored

---

static/js/controllers/guided-setup-modal.js

Wait for the Languages service to return before setting the
selected locales.
medic/medic-webapp#3872

Fix race condition in guided setup wizard

---

static/js/controllers/configuration-forms-xml.js

Current implementation works for me in Chrome 44, but not in Chrome 60.

Make more effort to get title on xform upload

---

static/js/services/contact-save.js
tests/karma/unit/services/contact-save.js

This means xforms can have complex objects bound from the select2
and calculations can be made off any of the object's fields. When
the form is submitted we fetch the object from the database using
the field._id value rather than just assuming the field is a the
_id only.
medic/medic-webapp#3889

DB types now support objects with an _id field

---

static/css/badge.less
static/css/inbox.less
templates/partials/contacts_content.html

- More space for configuration tab
- Less space between contacts table filters so they all fit on one line
- Other tidying up
medic/medic-webapp#3597

Small changes brought up during acceptance testing

---

static/js/controllers/contacts-report.js
static/js/services/contact-view-model-generator.js
static/js/services/lineage-model-generator.js
tests/karma/unit/services/lineage-model-generator.js

This allows action reports to use the contact and parents of the
report subject.
medic/medic-webapp#3912

Hydrate the contact bound to action reports

---

.travis.yml
Changes.md
package.json
packages/kanso-gardener/build/compile.js
packages/settings/build/utils.js
scripts/ci/push_to_staging.sh
tests/protractor/conf.js

Issue: https://github.com/medic/medic-projects/issues/2473
[description]

Don't include _url in ddoc

---

static/js/services/enketo.js

Make sure that non-relevant first pages are not shown for Enketo forms

---

static/js/controllers/contacts-edit.js
static/js/services/enketo.js

Remove renderContactForm function from  Enketo service API

---

static/js/services/enketo.js

It needs to be executed for contact creation forms too.
medic/medic-webapp#3928

Use the flip-to-first-page workaround more widely

---

Changes.md
kanso.json
static/css/analytics-widgets.less
static/css/inbox.less
static/css/targets.less
static/css/theme.less
static/css/variables.less
static/js/controllers/analytics-targets.js
static/js/services/target-generator.js
templates/partials/analytics.html
templates/partials/analytics/anc.html
templates/partials/analytics/reporting.html
templates/partials/analytics/targets.html
tests/karma/unit/services/target-generator.js
translations/messages-en.properties

Update the UI for targets so they are more user friendly. In particular rework how percentages are shown so we no longer show a percentage of a percentage.
medic/medic-webapp#3629
medic/medic-webapp#2522

Update targets UI

---

demo-forms/date-input.xml
static/js/enketo/widgets/bikram-sambat-datepicker.js

This is inline with changes made to medic-collect in #3405
Issue #3404

Allow use of appearance=bikram-sambat in enketo forms

---

static/css/enketo/medic.less
static/css/inbox.less
static/css/material.less
static/css/theme.less
static/js/controllers/messages-content.js
templates/partials/contacts_content.html
templates/partials/contacts_edit.html
templates/partials/contacts_report.html
templates/partials/messages_content.html
templates/partials/reports_add.html
templates/partials/reports_content.html
templates/partials/tasks_content.html
tests/protractor/e2e/contact-summary.js
tests/protractor/e2e/contacts/add-new-health-center.js
tests/protractor/e2e/contacts/add-new-person.js
tests/protractor/e2e/sms-gateway.js

Updates the contacts tab content pane.
medic/medic-webapp#3719
medic/medic-webapp#3736

Person & place profile page UI changes

---

static/js/enketo/OpenrosaXpathEvaluatorBinding.js

Fix incorrect translator reference in Enketo setup

---

package-lock.json
package.json

Bump enketo-xslt version to support cascading selects

---

scripts/conflicts/.gitignore
scripts/conflicts/.jshintrc
scripts/conflicts/README.md
scripts/conflicts/auto-resolve.js
scripts/conflicts/diff.js
scripts/conflicts/package-lock.json
scripts/conflicts/package.json

Basis for some conflict scripts.

Conflict scripts

---

kanso.json
static/js/services/place-hierarchy.js
tests/karma/unit/services/place-hierarchy.js

Allow partners to see clinic in the place hierarchy if they wish.
medic/medic-webapp#3902

Make place hierarchy configurable

---

package-lock.json
package.json
tests/protractor/conf.js
tests/protractor/e2e/auditing.js
tests/protractor/e2e/contact-summary.js
tests/protractor/e2e/contacts/add-new-health-center.js
tests/protractor/e2e/forms/submit-delivery-form.specs.js
tests/protractor/e2e/registration-by-sms.js
tests/protractor/e2e/send-message.js
tests/protractor/e2e/sms-gateway.js
tests/protractor/e2e/submit-enketo-form.js
tests/protractor/helper.js
tests/protractor/page-objects/common/common.po.js
tests/protractor/page-objects/contacts/contacts.po.js
tests/protractor/page-objects/forms/delivery-report.po.js

- Enable most of tests
-added helper function to alter timeouts and handle exceptions on click() and getText()
-used url for some page navigations instead of click()

Enable tests

---

static/css/content-list.less
static/js/services/live-list.js
templates/partials/content_row_list_item.html

Special styling for tasks due today.
medic/medic-webapp#4000

Special styling for tasks due today. #4000

---

sentinel/lib/lineage.js
sentinel/lib/messages.js
sentinel/lib/utils.js
sentinel/package-lock.json
sentinel/package.json
sentinel/test/functional/schedules.js
sentinel/test/mocha/lib/messages.js
sentinel/test/mocha/lib/utils.js
sentinel/test/mocha/transitions/accept_patient_reports.js
sentinel/test/mocha/transitions/registration.js
sentinel/test/unit/accept_patient_reports.js
sentinel/test/unit/lineage.js
sentinel/test/unit/messages.js
sentinel/test/unit/patient_registration.js
sentinel/test/unit/registration.js
sentinel/test/unit/utils.js
sentinel/transitions/accept_patient_reports.js
sentinel/transitions/conditional_alerts.js
sentinel/transitions/default_responses.js
sentinel/transitions/registration.js

Webapp version of https://github.com/medic/medic-sentinel/pull/179

3412 patient on doc

---

tests/protractor/e2e/contact-summary.js
tests/protractor/e2e/registration-by-sms.js
tests/protractor/e2e/sms-gateway.js
tests/protractor/helper.js

-Enabled all tests.
-Used helper functions for click() and getText()
-Function to log console errors on AWS
-Error handling for most fragile tests

E2e tests stability

---

static/js/services/target-generator.js
tests/karma/unit/services/target-generator.js

Otherwise, if there is no output for that target there are no initial zero values.
medic/medic-webapp#4008

Default targets to empty #4008

---

static/js/filters/date.js
tests/mocha/unit/enketo/translator.spec.js
tests/mocha/unit/filters/date.spec.js
tests/mocha/unit/mock-angular.js

Issue #3721
Not sure of the value of these filter unit tests.  There must be a better way of doing this which hopefully doesn't involve protractor.

Add dayMonth filter

---

package-lock.json
package.json
static/css/enketo/_widgets.scss
static/js/controllers/configuration-export-contacts.js
static/js/controllers/configuration-forms-json.js
static/js/controllers/configuration-forms-xml.js
static/js/controllers/import-translation.js
static/js/controllers/reports-add.js
static/js/enketo/widgets.js
static/js/services/enketo.js
static/js/services/file-reader.js
tests/karma/unit/services/enketo.js

Issue: #3096
@garethbowen please review.
I'll be pushing the changes to `file-manager.getFileUrl()` upstream if I can. **[DONE]**
I'm not actually sure if the general approach will work because it relies on getting `$scope` via `angular.element(…).scope()`.  I'm struggling to think of alternatives, but will try harder if this one isn't viable.

Add enketo filepicker widget; 32kb file size limit

---

api/controllers/people.js
api/controllers/places.js
api/migrations/extract-person-contacts.js
api/package-lock.json
api/tests/integration/migrations/extract-person-contacts.js
api/tests/integration/migrations/utils.js
api/tests/unit/controllers/people.js
api/tests/unit/controllers/places.js
api/tests/unit/migrations/extract-person-contacts.js

Fix the extract-person-contacts migration.
This both fixes some issues that came up when we introduced lineages, as well as just generally fixing some bugs
#4031

Fix extract-person-contacts migration

---

static/css/enketo/medic.less

Show enketo timepicker inline with datepicker.
Issue: #4032

Show enketo timepicker inline with datepicker

---

static/js/services/simprints.js

Fix calls to medicmobile_android.simprints_*

---

tests/mocha/unit/enketo/translator.spec.js

Without this tests that run later break because document is mocked.

Clean up after tests

---

templates/partials/contacts_content.html

This means they line up horizontally as expected and now behaves
the same as the contact summary section.
medic/medic-webapp#4045

Apply flex to cards

---

static/js/controllers/contacts-content.js
static/js/controllers/tasks-content.js
static/js/controllers/tasks.js
templates/partials/contacts_content.html

Fix some missed translations

---

tests/karma/unit/services/simprints.js

Ref https://github.com/medic/medic-webapp/pull/4066#pullrequestreview-79627013

Add test for medicmobile_android function calls

---

api/auth.js
api/server.js
static/js/services/translate.js

Also changing the logic slightly, so if you pass Basic Auth we will
always validate it, even if you don't technically need us to (eg you
have the requisite permission for full access)
medic/medic-webapp#3910

Refactor user edit api for clarity

---

static/css/configuration.less
static/js/controllers/configuration-upgrade.js
templates/partials/configuration_upgrade.html
translations/messages-en.properties

a) Changes "Upgrade" button text to "Install"
b) Adds spacing and horizontal line between Releases and Betas sections
c) Changes color of builds/releases from red to blue
d) Pins "master" branch on top of the list (if existent).
medic/medic-webapp#4006

Adds some small UI changes to "Configuration > Upgrade" page

---

Gruntfile.js
package-lock.json
package.json

Revert to mainline of google-libphonenumber

---

api/controllers/login.js
api/public/login/script.js
api/public/login/style.css
api/templates/login/index.html

Adding helpful error message when user logs in offline
medic/medic-webapp#4150

4150 offline login

---

Gruntfile.js
api/server.js
tests/protractor/conf.js
tests/protractor/e2e/api/controllers/users.js
tests/protractor/utils.js

We disabled E2E tests but we shouldn't have disabled the API ones.
Re-enabled, and fixing a bug that I found due to running the tests.

Enabling API E2E and fixing a bug it found

---

sentinel/lib/lineage.js
sentinel/test/unit/lineage.js

Include support to hydrate patient on hydrateDocs function

4003 hydrate patient

---

ddocs/medic-client/views/doc_summaries_by_id/map.js
static/js/services/get-data-records.js
static/js/services/get-subject-summaries.js
static/js/services/index.js
static/js/services/live-list.js
tests/karma/unit/services/get-subject-summaries.js
tests/mocha/unit/views/doc_summaries_by_id.spec.js
translations/messages-en.properties

In Reports page, LHS/list view, instead of displaying submitter
name/phone, display subject's name:
a) In case the report is about a person, display person name
b) In case the report is about a place, display place name
c) In case of a) or b), but the person/place is not found, display
"Unknown Subject"
d) In case neither a) nor b), display submitter name, as before
medic/medic-webapp#4053

Changes heading in Reports list from submitter to subject

---

static/js/services/db-sync.js

Work around PouchDB timeout bug

---

static/js/controllers/inbox.js

This gives more feedback on what stage of the app startup the user
is at.
medic/medic-webapp#4130

Add a startup message for loading rules

---

Gruntfile.js
tests/protractor/conf.js
tests/protractor/e2e/api/controllers/export-data-2.js

* Set timezone to UTC when running node services 
* Use UTC dates in e2e assertions 
Issue: #4250

Run servers in UTC timezone, and expect them to be run there

---

static/css/inbox.less

Lock action contain csv icon size correctly

---

tests/protractor/e2e/api/controllers/users.js
tests/protractor/e2e/api/server.js
tests/protractor/utils.js

Also include a helpful error message if no details are returned from the server.

Throw errors with proper stacktraces in protractor utils

---

static/css/theme.less

Updates stacked star icon font-size from rem to px.
medic/medic-webapp#4274

Updates stacked star icon font-size from rem to px.

---

tests/protractor/e2e/api/controllers/sms-gateway.spec.js

Issue: #3738
There are some more tests that I have written for the endpoint, but they're currently failing.  I'd like to get this reviewed and merged before focussing on tests which require changes to the endpoint itself.

Add tests for SMS gateway api endpoint

---

static/js/controllers/contacts.js
tests/karma/unit/controllers/contacts.js

Adds handling of deletes for Contacts LiveList, while preserving initial list count. 
medic/medic-webapp#4080
medic/medic-webapp#4079

Adds handling of deletes for Contacts LiveList

---

templates/partials/contacts_content.html

Only show primary contact star on primary contacts

---

static/js/enketo/widgets/db-object-widget.js
static/js/services/enketo.js

As opposed to the DOM.
Writing to the DOM does not always work, as it relies on Enketo having
created DOM fields for the elements we want to write to.
medic/medic-webapp#4248

Write directly to the Enketo data model

---

tests/karma/unit/services/recurring-process-manager.js
tests/protractor/base.conf.js
tests/protractor/e2e/registration-by-sms.js

Updates registration-by-sms e2e test spec to support Subject in LHS, also some translation changes.
Updates unreliable timeout test to use Angular's $interval instead.

Updates registration-by-sms spec and timeout unit test

---

.travis.yml
Gruntfile.js
api/server.js
sentinel/server.js

Drop CouchDB 1.x support from CI

---

api/README.md
api/package-lock.json
api/package.json
shared-libs/search/README.md

I completely forgot these docs! Clearly that checklist below needs to be more prominent!
Once we're happy with the wording I will forward port to 2.15.

Add export and search docs

---

static/js/enketo/widgets/db-object-widget.js

Support repeats with correct indexing

---

templates/directives/sender.html
tests/protractor/e2e/registration-by-sms.js
tests/protractor/e2e/reports-subject.js
translations/messages-en.properties

Show sender phone number instead of Unknown sender in Reports Content.

---

tests/protractor/e2e/bulk-delete.js
tests/protractor/e2e/common/common.specs.js
tests/protractor/e2e/send-message.js

Disable flakey e2e tests

---

api/message-utils.js

Add more description of messageUtils.updateMessageTaskStates()

---

static/js/controllers/reports.js

Select report - SetRightActionBar even when contact is not found

---

api/controllers/sms-gateway.js
api/db-pouch.js
lib/views.js
tests/protractor/e2e/api/controllers/sms-gateway.spec.js

This is a backport of #4110 for `2.15.x`.

Refuse duplicate webapp-terminating sms messages in the sms gateway endpoint

---

Gruntfile.js

Rename grunt envs for clarity

---

api/message-utils.js

This looks like it's important to do; let's see if it passes tests.

Don't forget to handle errors in callback

---

sentinel/lib/lineage.js
sentinel/test/functional/schedules.js
sentinel/test/unit/lineage.js

Fixes what looks like a typo where the wrong array is hydrated.
medic/medic-webapp#4410

Hydrates patient contacts not just parent contacts

---

api/db-pouch.js
api/lib/user-db.js
api/migrations/fix-user-db-security.js

The user dbs currently have no members in the _security doc which
leaves the db open for anyone to read. This changes that so users
can only see their own meta db. It also adds a migration to fix
existing meta dbs.
medic/medic-webapp#4412

Fixes open security on user dbs

---

sentinel/lib/message-utils.js
static/js/modules/message-utils.js
static/js/services/format-data-record.js

This means we can use more complicated information to calculate
the message recipient.
medic/medic-webapp#4410

 Builds context for evaluating recipient

---

sentinel/lib/message-utils.js
sentinel/schedule/due_tasks.js
sentinel/test/unit/due_tasks.js
static/js/modules/message-utils.js
static/js/services/format-data-record.js

- Uses the shared lineage library to actually hydrate the patient doc in the UI
- Hydrate patient when generating messages
- Changes template extraction to not overwrite doc.contact
medic/medic-webapp#4410

Improve contact hydration

---

Gruntfile.js

Fail the exec:sharedLibUnit task if any tests fail

---

Gruntfile.js

Derive shared-lib tests to run from filesystem

---

shared-libs/message-utils/package-lock.json
shared-libs/message-utils/src/index.js
shared-libs/message-utils/test/index.js

Handles the way standard sets null parents
medic/medic-webapp#4410

Handles the way standard sets null parents

---

api/manual-migrations/extract-data-record-content.js
api/manual-migrations/index.js
api/manual-migrations/minify-contacts.js
api/manual-migrations/remove-read-status.js

These migrations can be executed to improve performance and/or reduce
db size. The changes are backwards comptible so they're optional and
can be executed while the app is running.
medic/medic-webapp#4362

Adds a framework for executing background migrations

---

sentinel/src/transitions/registration.js

While this may sometimes indicate an invalid config it may also
indicate an edge case of a valid config and it's therefore overly
alarming.
medic/medic-webapp#4229

Removes error logging which may be misleading

---

demo-forms/z-score.xml
webapp/src/js/enketo/OpenrosaXpathEvaluatorBinding.js
webapp/src/js/enketo/medic-xpath-extensions.js
webapp/src/js/enketo/widgets/z-score.js
webapp/src/js/services/enketo.js
webapp/src/js/services/z-score.js
webapp/tests/karma/unit/controllers/inbox.js
webapp/tests/karma/unit/services/enketo.js
webapp/tests/karma/unit/services/z-score.js

This makes using z-score much more flexible than the widget
implementation.
medic/medic-webapp#4457

Adds an z-score xpath calculation

---

Changes.md
static/js/enketo/OpenrosaXpathEvaluatorBinding.js
static/js/enketo/medic-xpath-extensions.js
static/js/enketo/widgets/z-score.js
static/js/services/enketo.js
static/js/services/z-score.js
tests/karma/unit/controllers/inbox.js
tests/karma/unit/services/enketo.js
tests/karma/unit/services/z-score.js

Adds a z-score xpath calculation
This makes using z-score much more flexible than the widget
implementation.
medic/medic-webapp#4457

Adds a z-score xpath calculation

---

.github/ISSUE_TEMPLATE.md

I want to introduce a bug reporting template to see if we can help speed up the triage / reproduction phase of bug reporting, and help everyone write consistent, helpful and thorough bug reports.
Interesting in your thoughts on wording / process etc.

A bug template to make introducing bugs a more streamlined process

---

webapp/package.json
webapp/yarn.lock

* minor update to variable scoping
* tiny performance optimisation

Update pojo2xml to latest

---

api/server.js
api/src/db-pouch.js
api/src/ddoc-extraction.js
api/tests/integration/migrations/utils.js
api/tests/mocha/ddoc-extraction.js

Convert ddoc extraction to pouch

---

Gruntfile.js

Watches more stuff including translations and admins.
Pushes just the secondary ddocs if that's all that has changed.
Makes watchers more specific and reduces the number of triggered tasks.
medic/medic-webapp#4536

Makes grunt watch faster and more complete

---

api/package.json
tests/e2e/report-date-filter.js
tests/e2e/reports-subject.js
tests/e2e/send-message.js

Enabled message-related e2e tests and fixed flaky tests. Build passing on travis :11 times in a row for more confidence.

Enabled message tests

---

api/package.json
api/src/config.js
api/yarn.lock
sentinel/package.json
sentinel/src/config.js
sentinel/src/db-pouch.js
sentinel/src/lib/feed.js
sentinel/src/transitions/index.js
sentinel/tests/integration/transitions.js
sentinel/tests/unit/transitions.js
sentinel/yarn.lock

Removes follow library
medic/medic-webapp#4558

Removes follow library

---

README.md

Adds a vulnerability disclosure policy

Adds a vulnerability disclosure policy

---

tests/e2e/registration-by-sms.js
tests/e2e/reports-subject.js

All the e2e tests have been re-enabled with 99 % confidence level, ie there is one test that seems to be not too stable 1 time out of 13, on travis. I will monitor that.

Re-anables all tests

---

webapp/src/css/enketo/medic.less

Centers the enketo summary icons

---

.travis.yml
admin/package.json
api/package.json
package.json
sentinel/package.json
webapp/package.json

Bumps yarn version to 1.7.0

---

Gruntfile.js
README.md

Makes grunt task naming case consistent

---

api/src/controllers/changes.js
api/tests/mocha/controllers/changes.js

Adds more validation to changes controller split function.

Changes controller fix split

---

api/server.js
api/src/migrations.js
api/tests/mocha/migrations.spec.js

Convert migrations to pouch

---

api/server.js
api/src/config.js
api/src/migrations/namespace-form-fields.js
api/tests/mocha/config.js
api/tests/mocha/migrations/namespace-form-fields.spec.js

Converts api startup to promises

---

shared-libs/lineage/src/lineage.js
shared-libs/lineage/test/integration.js
webapp/src/ddocs/medic-client/views/messages_by_contact_date/map.js
webapp/src/ddocs/medic-client/views/messages_by_contact_date/reduce.js
webapp/src/js/services/hydrate-messages.js
webapp/src/js/services/index.js
webapp/src/js/services/lineage-model-generator.js
webapp/src/js/services/message-contacts.js
webapp/tests/karma/unit/services/hydrate-messages.js
webapp/tests/karma/unit/services/message-contacts.js

Messages view refactor.
medic/medic-webapp#4284

Messages view refactor

---

sentinel/src/lib/objectpath.js

Removes an unused utility

---

static/js/services/simprints.js

The simprints api check can throw exceptions, we should guard against that

Guard against simprints api throwing errors

---

api/controllers/export-data.js
api/services/export-data-2.js

Add a recursion guard to fix an edge case that can take the server down.
medic/medic-webapp#4596

Recursion guard

---

static/css/theme.less
templates/partials/reports_content.html

Replaces full date with relative date, moves it under sender and aligns is to the left. 
Full date is displayed as a tooltip on hover/click.
medic/medic-webapp#4576

Reports detail header update

---

static/css/dropdown.less
static/css/inbox.less
templates/partials/filters/sort.html

- Replaces multidropdown style with single dropdown style (ie: no
checkboxes).
- Replaces float with absolute positioning so it works on mobile.
- Fixes dropdown menu position on mobile.
- Removes arbitary padding on sort button.
medic/medic-webapp#4524

Fixes sort dropdown icons and layout

---

api/src/routing.js

In our api, we currently log http requests only. This update logs responses too.
medic/medic-webapp#4622

Adding response log

---

api/src/migrations.js
api/src/migrations/add-contact-icons-to-resources-doc.js
api/src/migrations/add-national_admin-role.js
api/src/migrations/add-resources-doc.js
api/src/migrations/add-uuid-to-scheduled-tasks.js
api/src/migrations/associate-records-with-people.js
api/src/migrations/clean-up-corrupted-users.js
api/src/migrations/convert-bad-dob-format.js
api/src/migrations/create-patient-contacts.js
api/src/migrations/drop-audit-doc-index.js
api/src/migrations/drop-couchmark-db.js
api/src/migrations/emit-complete.js
api/src/migrations/extract-person-contacts.js
api/src/migrations/extract-read-status.js
api/src/migrations/extract-settings.js
api/src/migrations/extract-translations.js
api/src/migrations/extract-user-settings-roles.js
api/src/migrations/extract-user-settings.js
api/src/migrations/fix-user-db-security.js
api/src/migrations/namespace-form-fields.js
api/src/migrations/remove-can-access-directly-permission.js
api/src/migrations/remove-empty-parents.js
api/src/migrations/remove-obsolete-ddocs.js
api/src/migrations/restrict-access-to-audit-db.js
api/src/migrations/separate-audit-db.js
api/tests/mocha/migrations.spec.js

Converts migrations from callbacks to promises

---

static/css/dropdown.less

Adding bottom padding to the filter menu.
medic/medic-webapp#4577

Adding bottom padding to filter menu

---

webapp/package.json
webapp/yarn.lock

Introduces new functions:
* max()
* min()
* selected-at()
* join()

Bump openrosa-xpath-evaluator

---

api/src/public/robots.txt

Adds a robots.txt file to disallow crawling

---

webapp/src/js/services/get-subject-summaries.js
webapp/src/js/services/lineage-model-generator.js
webapp/tests/karma/unit/services/get-subject-summaries.js

Batches the requests for summary subjects

---

shared-libs/lineage/package.json
shared-libs/lineage/src/lineage.js
shared-libs/lineage/test/integration.js
shared-libs/lineage/test/setup.js
shared-libs/lineage/test/unit.js
shared-libs/lineage/yarn.lock

Guard could be implemented with a depth counter, or an initial check for duplicate IDs in the lineage hierarchy.
medic/medic-webapp#4604

4604 Guard against infinite recursion in lineage shared library

---

ddocs/medic-client/views/reports_by_subject/map.js

Fetching patient reports by id or uuid.
medic/medic-webapp#4446

Fetching patient reports by id or uuid

---

webapp/src/js/services/session.js

Navigating to login after logout.
medic/medic-webapp#4673

Navigating to login after logout

---

static/js/controllers/contacts-content.js
templates/partials/contacts_content.html

Allows use of translation keys in task priority labels

---

api/package.json
api/src/controllers/changes.js
api/src/routing.js
api/src/services/bulk-docs.js
api/tests/mocha/controllers/changes.js
api/tests/mocha/services/bulk-docs.js
api/yarn.lock

_changes heartbeats weren't being successfully sent through, so all requests were closed by PouchDB when their ajax timeout expired. 
medic/medic-webapp#4643

Api _changes response compression 

---

api/src/controllers/changes.js
api/src/routing.js
api/tests/mocha/controllers/changes.js
tests/e2e/api/controllers/changes.js
tests/utils.js

- adds e2e test to check if _changes requests heartbeats are correctly sent
- adds fix for proxied POST requests to _changes
- removes nginx specific headers
medic/medic-webapp#4424

Changes heartbeats testing

---

tests/scalability/README.md
tests/scalability/config.json
tests/scalability/initial-replication.js
tests/scalability/package-lock.json
tests/scalability/package.json
tests/scalability/sync.jmx

Adds a scalability testing script

---

api/src/audit-proxy.js
api/src/auth.js
api/src/controllers/create-user-db.js
api/src/controllers/login.js
api/src/routing.js
api/tests/mocha/audit-proxy.spec.js
api/tests/mocha/auth.spec.js
api/tests/mocha/controllers/create-user-db.spec.js
api/tests/mocha/controllers/login.spec.js

Refactor auth to promise

---

ddocs/medic-client/views/messages_by_contact_date/map.js
ddocs/medic-sms/views/tasks_messages/map.js

Adding defensive code to prevent view errors.
medic/medic-webapp#4612

4612 view errors

---

admin/src/templates/index.html
webapp/src/templates/partials/header.html

Opens the admin app in a new tab

---

api/src/controllers/people.js
api/src/controllers/places.js
api/src/controllers/users.js
api/src/migrations/extract-person-contacts.js
api/src/routing.js
api/tests/mocha/controllers/people.spec.js
api/tests/mocha/controllers/places.spec.js
api/tests/mocha/controllers/users.spec.js
api/tests/mocha/migrations/extract-person-contacts.spec.js

Refactors people and place apis to use pouch

---

webapp/src/js/services/session.js

Ignoring logout exception; user can be already logged out.
medic/medic-webapp#4673

Ignoring logout exception; user can be already logged out.

---

admin/src/js/controllers/export-feedback.js

Limits pouch db message length.
medic/medic-webapp#4481

Limit log length

---

api/server.js

Doing server checks before import deps
medic/medic-webapp#4683

Doing server checks before import deps

---

tests/e2e/send-message.js
webapp/src/js/services/send-message.js
webapp/tests/karma/unit/services/send-message.js

all-contacts message is sent to the primary contacts for each of the areas that are below the facility in the hierarchy.
medic/medic-webapp#4708

4708 sms facility

---

api/src/controllers/changes.js
api/tests/mocha/controllers/changes.js
tests/e2e/api/controllers/changes.js

Don't restart requests when CouchDB returns an error.

---

static/js/services/enketo.js
tests/protractor/e2e/forms/submit-photo-upload-form.spec.js
tests/protractor/page-objects/forms/photo-upload.po.js

Fix submitting forms with file uploads

---

api/src/controllers/users.js
api/tests/mocha/controllers/users.spec.js

Updates api to support removal of place & contact for online users.
medic/medic-webapp#4712

4712 remove place

---

.prettierrc.json
api/src/controllers/forms.js
api/src/db-nano.js
api/src/routing.js
api/tests/mocha/controllers/forms.spec.js
tests/e2e/medic-collect.js

Refactors forms controller

---

.gitignore
scripts/release_testing_script/config.js
scripts/release_testing_script/create_release_project.js
scripts/release_testing_script/issues.js
scripts/release_testing_script/package.json
scripts/release_testing_script/projects.js

Initial pass at creating script to pull issues from github and create a project from them.

Release testing

---

webapp/src/js/app.js

Updates security check for can_view_x instead of can_access_x
medic/medic-webapp#4711

Using can_view_ permissions

---

webapp/package.json
webapp/yarn.lock

Locks enketo-core version to fix issue with jr:choicename when wrapped inside other functions.
https://github.com/enketo/enketo-core/blob/4.41.7/CHANGELOG.md
medic/medic-webapp#4808

4808 upgrading enketo

---

tests/e2e/bulk-delete.js
tests/e2e/contact-summary.js
tests/e2e/contacts/add-new-health-center.js
tests/e2e/forms/submit-delivery-form.specs.js
tests/e2e/forms/submit-photo-upload-form.spec.js
tests/e2e/integration.js
tests/e2e/login/login.specs.js
tests/e2e/registration-by-sms.js
tests/e2e/report-date-filter.js
tests/e2e/reports-subject.js
tests/e2e/send-message.js
tests/e2e/sms-gateway.js
tests/e2e/submit-enketo-form.js
tests/helper.js
tests/page-objects/common/common.po.js
tests/page-objects/contacts/contacts.po.js
tests/page-objects/forms/delivery-report.po.js
tests/page-objects/login/login.po.js
tests/page-objects/messages/messages.po.js
tests/page-objects/reports/reports.po.js

Changes:
Moved functions to related page objects according to testing area; 
replaced hardcoded explicit waits with helper calls;
removed redundant (duplicated) waits for element.
Test logic is not changed.
Successfully tested on master codebase.

Tests update

---

webapp/src/js/enketo/bootstrap-datepicker.bm.js
webapp/src/js/enketo/main.js

Date picker widget is not translated for language Bamanankan (bm)
medic/medic-webapp#4832

4832 - Bamanankan translation for datepicker

---

webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/messages.js
webapp/src/js/controllers/reports.js
webapp/src/templates/partials/actionbar.html

Disable 'Select' and 'Export' buttons when there are no reports
medic/medic-webapp#3705

Disable/Enable 'Select' and 'Export' buttons in Reports tab

---

webapp/src/css/inbox.less

The field title should never flow beyond the white bounding box of the RHS. We wrap field titles if they do not fit the space.
medic/medic-webapp#4788

On report details on the RHS, wrap field titles

---

webapp/src/css/material.less
webapp/src/templates/partials/contacts_content.html

Task_3899 To show future birthdates in red

---

webapp/src/js/controllers/edit-message-group.js
webapp/src/js/services/edit-group.js
webapp/src/js/services/format-data-record.js
webapp/src/templates/modals/edit_message_group.html

Fix issues related to editing a scheduled message  …
1) only non-translatable messages can be edited
2) the due date is always edicatable
3) adding a new message will trigger an initialization of the datepicker (which happens once the UI is updated)
4) also fixed additional issues related to initialization of datepicker
medic/medic-webapp#4787

4787 edit scheduled message

---

webapp/package.json

This is not a functional change, but updates the package to the latest release
which has the correct git URL listed in its package.json
Issue: #4727

Bump pojo2ml version

---

admin/src/js/controllers/edit-user.js
admin/src/templates/edit_user.html
admin/tests/unit/controllers/edit-user.js

If during user creation associated contact is chosen, 'Place' field has to become required
medic/medic-webapp#4772

4772 user creation

---

api/src/controllers/export-data.js
api/tests/mocha/controllers/export-data.js

Audit Logs export functionality not working
Navigate to /medic/_design/medic-admin/_rewrite/#/export/audit-logs
medic/medic-webapp#4802

Audit Logs export functionality not working

---

admin/src/js/services/message-queue.js
admin/tests/unit/services/message-queue.js

Catch the case where no rows are returned.
There's one test failing but it's the one with known flakiness...
medic/medic-webapp#4899

Handles finding no outgoing messages

---

webapp/src/js/services/search.js
webapp/tests/karma/unit/services/search.js

Counts multiple reports on same day as single visit

---

.travis.yml
Gruntfile.js

The `API_URL` environment variable doesn't seem to be used.  This PR removes references to it.

Remove references to API_URL

---

tests/e2e/send-message.js
webapp/src/js/services/send-message.js

Fixes messages to -all contacts.
medic/medic-webapp#4708

Fixes sms message to all contacts

---

tests/e2e/send-message.js
webapp/src/js/services/send-message.js

Hydrates all primary contacts for the all-contacts message.
medic/medic-webapp#4708

4708 all-contacts message

---

webapp/src/js/controllers/contacts-edit.js
webapp/src/js/controllers/contacts-report.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/navigation-confirm.js
webapp/src/js/controllers/reports-add.js
webapp/src/js/controllers/tasks-content.js

Warning dialogue when users navigate away from form
medic/medic-webapp#4013

Warning dialogue when users navigate away from form

---

.travis.yml

Use Slack integration rather than webhooks, and provide a custom notification to make it less verbose.
Before vs after:

Use a custom template to improve notifications

---

tests/e2e/forms/family-survey-form.specs.js

Comment out test for now

---

webapp/src/js/services/count-messages.js
webapp/tests/karma/unit/services/count-messages.js

Just highlighting the count text and disabling the button when characters limit is crossed.
medic/medic-webapp#670

670 limit outgoing message size

---

Gruntfile.js

Bump autoprefixer browser support 
medic/medic-webapp#4955

Updated Feature: CSS AutoPrefix for Chrome

---

tests/e2e/forms/family-survey-form.specs.js
tests/page-objects/forms/family-survey-form.po.js
tests/page-objects/forms/generic-form.po.js
webapp/src/js/controllers/inbox.js

Family Survey Submit form
medic/medic-webapp#4942

Failing test fix

---

Changes.md
sentinel/src/transitions/registration.js

Return to the callback #4975

---

package.json

Bump version number for 3.4.0 release

---

package.json

Allows calling `npm test` to run the test suite.

[master] Add npm test script

---

api/package-lock.json
api/package.json
api/server.js
api/src/auth.js
api/src/controllers/login.js
api/src/db-nano.js
api/src/db-pouch.js
api/src/environment.js
api/src/migrations/add-national_admin-role.js
api/src/migrations/add-uuid-to-scheduled-tasks.js
api/src/migrations/convert-bad-dob-format.js
api/src/migrations/extract-user-settings-roles.js
api/src/migrations/remove-empty-parents.js
api/src/migrations/restrict-access-to-audit-db.js
api/src/migrations/separate-audit-db.js
api/src/routing.js
api/src/server-utils.js
api/tests/mocha/auth.spec.js
api/tests/mocha/controllers/login.spec.js
api/tests/mocha/migrations/extract-translations.spec.js
api/tests/mocha/migrations/separate-audit-db.spec.js
api/tests/mocha/server-utils.spec.js
tests/e2e/api/routing.js

One more step towards dropping nano...

Move db settings to pouch module

---

webapp/src/js/services/db.js
webapp/tests/karma/unit/services/db.js

This moves the cleanup function outside of the startup sequence
and also solves warning from PouchDB when trying to cleanup before
the db is initialised.
medic/medic-webapp#3925

Delays view cleanup

---

webapp/src/js/services/db.js

Instead of just accepting `options` this documents what keys are
available and what their default options are. Two calls were passing
unused options so I removed these at the same time.

Uses destructuring to document options

---

webapp/src/js/enketo/widgets/countdown-widget.js

Shows countdown timer when relevant expression evaluates to true. 
medic/medic-webapp#4279

Countdown timer relevant bug

---

webapp/src/js/services/db.js
webapp/tests/karma/unit/services/db.js

Clears the timeout to stop unit test leak

---

sentinel/src/transitions/update_notifications.js
sentinel/tests/unit/transitions/update_notifications.js

Save muting triggering report ID in update_notifications as well.

---

api/src/routing.js

Redirects GET requests instead of POST requests

---

ddocs/medic/views/docs_by_replication_key/map.js
tests/e2e/api/controllers/_changes.spec.js
webapp/src/js/services/branding-images.js

Includes branding doc in replication map

---

tests/e2e/reports-subject.js

Disables report-subject test

---

release-notes/3.1.0.md

Add release notes for 3.1.0

---

Gruntfile.js
README.md
api/README.md
sentinel/README.md

#4979 - Update build scripts and documentation to avoid weak CouchDB passwords

---

release-notes/2.18.1.md

Add release notes for 2.18.1

---

ddocs/medic/_attachments/translations/messages-en.properties
webapp/src/js/services/count-messages.js

Add message "too many messages!" when the limit is crossed and make sure that the RHS message box behavior is consistent with that of LHS one
medic/medic-webapp#670

Add message and fix RHS message box

---

webapp/src/js/controllers/contacts-edit.js
webapp/src/js/controllers/contacts-report.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/reports-add.js
webapp/src/js/controllers/tasks-content.js

Warning dialogue added for New edited forms
medic/medic-webapp#4013

4013 warning dialogue

---

api/package-lock.json
api/package.json
api/src/config.js
sentinel/package-lock.json
sentinel/package.json
sentinel/src/config.js
shared-libs/translation-utils/.jshintrc
shared-libs/translation-utils/package-lock.json
shared-libs/translation-utils/package.json
shared-libs/translation-utils/src/translation-utils.js
shared-libs/translation-utils/test/.jshintrc
shared-libs/translation-utils/test/translation-utils.js
webapp/package-lock.json
webapp/package.json
webapp/src/js/services/translation-loader.js

Supports nested keys in translations.
medic/medic-webapp#4599

Adds translation-utils to support nested keys

---

api/src/routing.js

Fixing favicon caching

---

scripts/project-snapshot/index.js

Now we use project columns not issue labels. Drops support
for outputting types which wasn't used much.

Updates project snapshot script for new workflow

---

api/src/controllers/login.js
api/tests/mocha/controllers/login.spec.js

Promisify the login controller

---

admin/src/js/controllers/main.js
admin/src/templates/index.html
admin/src/templates/navigation.html

Prevents admin navigation from rendering for invalid users.
medic/medic-webapp#4710

4710 admin permission

---

webapp/src/js/controllers/contacts.js
webapp/src/js/services/contact-view-model-generator.js
webapp/src/templates/partials/contacts_content.html
webapp/tests/karma/unit/controllers/contacts.js
webapp/tests/karma/unit/services/contact-view-model-generator.js

Load visual elements of contact-content pane incrementally

---

webapp/src/js/services/contact-view-model-generator.js
webapp/src/templates/partials/contacts_content.html
webapp/tests/karma/unit/services/contact-view-model-generator.js

This is the RHS component of #5084

#5084 - Remove "Primary Contact" from RHS

---

shared-libs/translation-utils/package-lock.json
shared-libs/translation-utils/package.json
shared-libs/translation-utils/src/translation-utils.js
shared-libs/translation-utils/test/translation-utils.js

The value may be a number which will cause the call to replace to fail.
medic/medic-webapp#5062

Fix loading of translations

---

tests/e2e/contacts/add-new-person.js

[e2e] Wait until children have loaded

---

sentinel/src/lib/muting_utils.js
sentinel/src/lib/utils.js
sentinel/src/schedule/due_tasks.js
sentinel/src/transitions/accept_patient_reports.js
sentinel/src/transitions/conditional_alerts.js
sentinel/src/transitions/death_reporting.js
sentinel/src/transitions/registration.js
sentinel/tests/integration/schedules.js
sentinel/tests/unit/birth_registration.js
sentinel/tests/unit/conditional_alerts.js
sentinel/tests/unit/due_tasks.js
sentinel/tests/unit/lib/muting_utils.js
sentinel/tests/unit/lib/utils.js
sentinel/tests/unit/patient_registration.js
sentinel/tests/unit/pregnancy_registration.js
sentinel/tests/unit/transitions/accept_patient_reports.js
sentinel/tests/unit/transitions/death_reporting.js
sentinel/tests/unit/transitions/registration.js
sentinel/tests/unit/utils.js

Also
- fixes some whitespace
- converts to ES6
- converts callbacks to promises
- stops passing `db` around
- fixes lots of tests that weren't waiting for async code to run

Converts sentinel/lib/utils to use PouchDB

---

Gruntfile.js

Otherwise, every time you run this task locally you get code changes
in git status.

Retains newline present at the end of package.json

---

webapp/src/js/controllers/inbox.js

New branch for warning dialogue with increased coverage
medic/medic-webapp#4013

4013 new warning dialogue

---

package-lock.json
webapp/package-lock.json
webapp/package.json
webapp/src/js/controllers/reports-add.js
webapp/src/js/services/enketo.js
webapp/src/js/services/form2sms.js
webapp/src/js/services/get-report-content.js
webapp/src/js/services/index.js
webapp/src/js/services/submit-form-by-sms.js
webapp/tests/.jshintrc
webapp/tests/karma/unit/services/enketo.js
webapp/tests/karma/unit/services/form2sms.spec.js

Issue: #4812
Supersedes https://github.com/medic/medic-webapp/pull/5096

Support XForms that compile into SMS messages

---

api/src/migrations/add-branding-doc.js

Branding migration now passes promises back correctly, meaning the
migration controller correctly waits until it's done before running more
migrations.
The migration also doesn't conflict if the branding document already
exists, which may occur if you're re-running migrations for some reason.

Makes branding migration synchronous and re-runnable

---

webapp/src/js/controllers/contacts-report.js
webapp/src/js/controllers/reports-add.js
webapp/src/js/controllers/tasks-content.js
webapp/tests/karma/unit/controllers/tasks-content.js

Records:
- Render time, from the controller being initiated to paint
- User time, between render time and them hitting save
- Save time, from them hitting save to us completing a save

Add some basic enketo telemetry

---

release-notes/3.2.0.md

Updates release notes to reference muting overview

---

webapp/src/css/inbox.less
webapp/src/templates/partials/about.html

Styling AboutUs page - Partners section

---

api/src/routing.js
api/tests/mocha/routing.spec.js
package-lock.json
package.json

5082 - CSP to allow connections to build server

---

api/src/controllers/create-user-db.js
api/src/db-batch.js
api/src/db-pouch.js
api/src/migrations/extract-read-status.js
api/src/migrations/fix-user-db-security.js
api/src/services/user-db.js
api/tests/mocha/controllers/create-user-db.spec.js
api/tests/mocha/lib/db-batch.spec.js
api/tests/mocha/services/user-db.spec.js

Replaces nano with pouchdb from user-db, db-batch, create-user-db

---

webapp/src/js/services/resource-icons.js
webapp/tests/karma/unit/services/resource-icon.js

Download resources doc (and attachment) if cache is not set
medic/medic-webapp#5229

Download resources doc (and attachment) if cache is not set

---

release-notes/3.2.1.md

Updates 3.2.1 release notes

---

admin/src/css/theme.less
admin/src/js/controllers/main.js
admin/src/templates/index.html

Improving UI/UX for admin LHS navigation

---

release-notes/2.17.0.md

Fixed error in release note index

---

api/server.js
api/src/controllers/login.js
api/src/routing.js

Replace domain with uncaught exception handler

---

admin/src/js/controllers/export-contacts.js
admin/src/js/controllers/import-translation.js
admin/src/js/controllers/upgrade.js
webapp/src/js/controllers/send-message.js

Leverage updated Translate service in webapp and admin
medic/medic-webapp#4483

Leverage updated Translate service in webapp and admin

---

tests/e2e/login/purge.spec.js
webapp/src/js/bootstrapper/index.js
webapp/src/js/bootstrapper/purger.js

Passes the userCtx to the configured purge function

---

admin/src/js/controllers/upgrade.js
admin/src/templates/upgrade.html

5277 - Admin upgrade page "Reload application" button is broken by CSP

---

admin/src/js/services/message-queue.js

Default to key

---

admin/src/js/controllers/settings-basic.js
admin/src/templates/settings_basic.html

Country code and Gateway phone number fields shouldn't be required
medic/medic-webapp#5249

Country code and Gateway phone number fields shouldn't be required

---

README.md

Removed the Help section and updated the Contributing sections so that they would have up to date information. I'm open to other changes or alternate text!

Updated contributing section

---

admin/src/css/theme.less
admin/src/js/controllers/main.js
admin/src/templates/index.html

- Centers the content again so it's aligned with the header.
- The targets-edit route now sets the Targets nav element as
selected.
medic/medic-webapp#4960

Centers content and highlights targets

---

tests/e2e/forms/add-family-form.specs.js
tests/page-objects/forms/generic-form.po.js

This test is still really flakey

---

.browserslistrc
api/.eslintrc
package-lock.json
package.json
webapp/.eslintrc

Linting the browser compatibility code
medic/medic-webapp#5280

Linting the browser compatibility code

---

webapp/src/js/bootstrapper/index.js
webapp/src/js/bootstrapper/translator.js

Also switches English to en-us instead of en-nz.
Also some refactoring to reduce code duplication.
medic/medic#5224

Adds translations for purge states and Hindi

---

package-lock.json
package.json

Bump app version to 3.5.0

---

api/src/controllers/login.js
api/tests/mocha/controllers/login.spec.js

This means the locale cookie is available for the bootstrap
stage before the angular app has loaded.
#5326

Writes locale cookie on login response

---

.github/PULL_REQUEST_TEMPLATE.md

Remove obsolete PR documentation instructions

---

tests/base.conf.js

Writes browser console to tests/logs

---

api/src/controllers/login.js
api/src/services/cookie.js
api/tests/mocha/controllers/login.spec.js
api/tests/mocha/services/cookie.js

Translates the login page to the users locale

---

.eslintrc
admin/tests/unit/controllers/edit-translation.js
admin/tests/unit/services/message-queue.js
admin/tests/unit/services/update-user.js
api/src/migrations/separate-audit-db.js
api/src/services/authorization.js
api/tests/integration/migrations/utils.js
api/tests/mocha/controllers/login.spec.js
api/tests/mocha/controllers/utils.spec.js
api/tests/mocha/services/bulk-docs.js
sentinel/tests/unit/lib/infodoc.js
sentinel/tests/unit/lib/utils.js
sentinel/tests/unit/reminders.js
sentinel/tests/unit/validations.js
tests/e2e/api/controllers/_changes.spec.js
tests/e2e/api/server.js
webapp/src/js/controllers/inbox.js
webapp/src/js/enketo/widgets/android-datepicker.js
webapp/src/js/enketo/widgets/bikram-sambat-datepicker.js
webapp/src/js/enketo/widgets/countdown-widget.js
webapp/src/js/enketo/widgets/mrdt.js
webapp/src/js/enketo/widgets/notewidget.js
webapp/src/js/enketo/widgets/simprints.js
webapp/src/js/enketo/widgets/unselectable-radios.js
webapp/tests/karma/unit/controllers/edit-user.js
webapp/tests/karma/unit/controllers/inbox.js
webapp/tests/karma/unit/directives/show-muted-modal.js
webapp/tests/karma/unit/services/contact-view-model-generator.js
webapp/tests/karma/unit/services/tasks-for-contact.js

Turns on the eslint no-unused-variables check

---

tests/base.conf.js

fix eslint

---

api/package-lock.json

3768 - Update openrosa dependencies to avoid prototype pollution in api

---

api/src/controllers/people.js
api/src/controllers/places.js
api/tests/mocha/controllers/people.spec.js
api/tests/mocha/controllers/places.spec.js

Replaces references to PouchDB error.statusCode

---

api/src/controllers/export-data.js
api/tests/mocha/controllers/export-data.js
api/tests/mocha/services/export-data.js

node domain

---

README.md

Included Docker instructions, and updated language for building apps.

Included Docker instructions

---

sentinel/src/transitions/accept_patient_reports.js
sentinel/tests/unit/transitions/accept_patient_reports.js

Revisit logic to link report to scheduled task (based on feedback from @michaelkohn )
Also, build more complete tests
medic/medic#4694

Revisit logic to link report to scheduled task

---

sentinel/src/transitions/conditional_alerts.js
sentinel/tests/unit/conditional_alerts.js

Fixes sorting of view results in conditional_alerts. 
medic/medic#5357

Fixes conditional_alerts sorting

---

webapp/src/js/bootstrapper/translator.js
webapp/tests/mocha/unit/translator.spec.js

Adds missing Swahili bootstrap translation

---

admin/src/js/controllers/targets-edit.js
admin/src/templates/targets.html
admin/src/templates/targets_edit.html

Target details - Missing _name_ array from some of the _targets_ payload
medic/medic#5330

Target details 

---

scripts/data_deletion/delete_training_data_utils.js

Fixes view reference

---

config/standard/app_settings.json

This adds auto responses for Fractional IPV ( FIPV1 & FIPV2), DPT Booster (DPT4 & DPT5) and Hepatitis B (HB) SMS forms.
#5353

Configure autoresponses for standard immunization SMS forms

---

sentinel/src/transitions/accept_patient_reports.js
sentinel/tests/unit/transitions/accept_patient_reports.js

accept_patient_reports should only clear tasks that are in a clearable state.

---

webapp/src/css/enketo/medic.less

Fixes the checkmark in checked checkboxes

---

admin/package-lock.json
admin/package.json
api/package-lock.json
api/package.json
sentinel/package-lock.json
sentinel/package.json
webapp/package-lock.json
webapp/package.json

Bump message-utils dependency.

---

webapp/src/js/controllers/inbox.js

Fixes bug where sync status would not be updated in the UI.

---

webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/reports.js

Fixes bug where all reports are highlighted
Fixes bug where, after switching selectMode, reports were still selected
medic/medic#5417

Fix report highlighting and selection clearing

---

sentinel/src/lib/feed.js
sentinel/tests/unit/lib/feed.js

Adds unit tests for lib/feed

---

Gruntfile.js

Removes jq dependency and reformats Gruntfile

---

release-notes/3.3.0.md

Update 3.3.0 release notes

---

webapp/src/js/controllers/tasks-content.js

Fixes confirmation popup showing after task submission.

---

tests/e2e/reports-subject.js
webapp/src/js/controllers/inbox.js

Don't clear state if you're gonna show a popup

---

webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/home.js
webapp/src/js/controllers/inbox.js
webapp/src/js/controllers/reports.js
webapp/src/js/controllers/tasks-content.js

Fixes transition bug when when editing forms and navigating to other tabs.
Changes Popup behavior when pressing "YES" so it directs you to the desired URL instead of always treating it as the "cancelCallback".
Does not display popup when editing a form and executing a search (contacts & reports).
Fixes popup displayed after task submission.
medic/medic#5409

Fixes navigation warning popup.

---

CONTRIBUTING.md

Making the contributing doc link to the workflow documentation which I've updated to
not include any details only relevant to Medic teammates. It also links to the style guide.

Updates contributing link to more generic workflow doc

---

README.md

Reformatted dependencies

---

webapp/src/js/services/android-api.js
webapp/src/js/services/tour.js
webapp/tests/karma/unit/services/android-api.js

Wrap state.go call in code that ensures the route isn't undefined/null and log the error.
medic/medic#5298

Wrap state.go call in code that ensures the route isn't undefined/null

---

tests/scalability/README.md
tests/scalability/previous_results/3.3.0.jtl
tests/scalability/sync.jmx

Added some parameterization to the load testing values to make it more scriptable. Also documenting how to run via CLI, storing past results, merging results, and comparing. 

Jmeter cli

---

grunt/service-worker.js

Fixes a typo in the service worker config

---

api/src/routing.js
demo-forms/countdown-timer.xml

Opens a hole in CSP for media files

---

api/src/controllers/login.js

Handles unsuccessful login gracefully

---

api/src/controllers/login.js
api/tests/mocha/controllers/login.spec.js

Avoids writing locale cookie when language not defined

---

webapp/src/js/enketo/widgets/countdown-widget.js

Fix to allow the relevant attribute to show/hide countdown widget. 
medic/medic#4279

Fixes relevant attribute on countdown widget

---

scripts/poe/README.md
scripts/poe/cli.js
scripts/poe/lib/inquirer.js
scripts/poe/lib/slack.js
scripts/poe/lib/validate.js
scripts/poe/tests/poe-import.js

Linting and updating import/export tags
medic/medic#5504

Linting and updating import/export tags

---

api/src/routing.js

Update CSP to allow images sourced from blobs

---

tests/scalability/config.json
tests/scalability/previous_results/3.4.0.jtl
tests/scalability/sync.jmx

Adding the details for 3.4.0 test results run. Updated sync.jmx to have a merge row for 3.4.0. Updated config.json to match seed data

3.4.0 results add

---

release-notes/2.13.1.md
release-notes/2.13.2.md
release-notes/2.13.3.md
release-notes/2.13.4.md
release-notes/2.13.5.md
release-notes/2.13.6.md
release-notes/2.13.7.md

Nothing special, just copying from the Changes.md in the `2.13.x` branch which had been orphaned.

Adds release notes for 2.13 patch releases

---

config/standard/app_settings.json

Remove unused permissions

---

README.md

Remove manual webdriver start

---

tests/page-objects/forms/add-family-form.po.js

I don't know if this will fix it but it's a start.
medic/medic#4908

Waits for element to be clickable

---

release-notes/0.4.15-and-earlier.md

Combined with PR in medic-docs. It's confusing having `release-notes` in two different repos...

Merge 0.1 release notes from medic-docs

---

release-notes/docs/3.4.0.md

Adds a link to the branding feature overview

---

webapp/src/js/controllers/feedback.js

Closes the feedback modal after success

---

webapp/src/js/controllers/inbox.js
webapp/src/js/services/resource-icons.js
webapp/src/templates/inbox.html
webapp/tests/karma/unit/services/logo-image.js

[description]
medic/medic#5531

Tooltip showing as `logo`

---

.travis.yml
Gruntfile.js
scripts/.eslintrc
scripts/conflicts/auto-resolve.js
scripts/data_deletion/delete_training_data.js
scripts/data_deletion/delete_training_data_for_group.js
scripts/data_deletion/delete_training_data_utils.js
scripts/find-big-docs.js
scripts/load_messages.js
scripts/mp-2584-unclearing-schedules/unclear.js
scripts/poe/.eslintrc
scripts/poe/cli.js
scripts/poe/jest-lint.config.js
scripts/poe/jest-test.config.js
scripts/release_testing_script/config.js
scripts/release_testing_script/create_release_project.js
scripts/release_testing_script/issues.js
scripts/release_testing_script/projects.js
scripts/remove_non_admin_users.js
scripts/sms-report.js
scripts/travis/publish.js
scripts/zscore-table-to-json.js

Also turns on eslint to detect this in future.
medic/medic#5198

Fixes the build by importing environment variables

---

Gruntfile.js
admin/src/js/controllers/export-contacts.js
admin/src/js/controllers/export-feedback.js
admin/src/js/controllers/export-messages.js
admin/src/js/controllers/export-reports.js
api/README.md
api/src/controllers/export-data.js
api/src/services/export/date-format.js
api/src/services/export/feedback-mapper.js
api/src/services/export/message-mapper.js
api/src/services/export/report-mapper.js
api/tests/mocha/controllers/export-data.js
api/tests/mocha/services/export-data.js
api/tests/mocha/services/export/message-mapper.js
webapp/src/js/controllers/contacts.js
webapp/src/js/controllers/messages.js
webapp/src/js/controllers/reports.js
webapp/src/js/services/export.js

Human readable dates in exports

---

admin/src/js/controllers/targets-edit.js
admin/src/templates/targets_edit.html
admin/tests/unit/controllers/targets-edit.js
ddocs/medic/_attachments/translations/messages-en.properties

5439 target uniqueness

---

webapp/src/js/services/telemetry.js
webapp/tests/karma/unit/services/telemetry.js

Adds app and form versions to telemetry aggregates

---

webapp/src/js/services/exception-handler.js
webapp/src/js/services/feedback.js

1. Reduces what error logging results in firing Feedback messages
2. Slightly optimise how our short log history is stored
medic/medic#5530

Feedback bug fix / optimisation

---

webapp/src/css/common.less
webapp/src/css/inbox.less
webapp/src/css/theme.less

 Moves styles into common sheet to fix admin app styling

---

webapp/tests/karma/unit/services/delete-docs.js

Forgot to update second instance of wrong error message being used
medic/medic#[number]

Fix stringify error message (test)

---

api/src/routing.js

Enables gzip compression for ttf files

---

webapp/src/templates/partials/header.html

It's still available on desktop and tablet modes.
medic/medic-android#57

Hides the app settings hamburger button on mobile

---

admin/src/css/theme.less
admin/src/js/controllers/main.js
admin/src/templates/header.html

Enabled _navbar-toggle_ on admin app to display hidden menu items on mobile devices
medic/medic#5599

Navbar collapse on small screens

---

.travis.yml

For https://github.com/medic/medic/issues/5637

Added zapier webhook for notifications

---

webapp/src/js/services/exception-handler.js

JavaScript errors and crash stacks not logged to the console

---

webapp/src/templates/partials/contacts_content.html

Remove people card from a person's profile

---

webapp/src/js/controllers/reports-content.js
webapp/src/js/services/format-data-record.js
webapp/src/js/services/report-view-model-generator.js
webapp/src/templates/partials/reports_content.html
webapp/tests/karma/unit/services/format-data-record.js
webapp/tests/karma/unit/services/report-view-model-generator.js

Optimizes a particularly hot part of the linking code which is
executed twice per report field.
medic/medic#5455

Improves performance of linking to patients

---

.travis.yml

For https://github.com/medic/medic/issues/5637

Use Zapier only for notifications

---

api/src/controllers/login.js
api/tests/mocha/controllers/login.spec.js

Add back the patch to stop setting null language cookie

---

webapp/src/css/inbox.less
webapp/src/js/controllers/inbox.js
webapp/src/js/services/db-sync.js
webapp/src/templates/partials/header.html
webapp/tests/karma/unit/services/db-sync.js

When the user is offline but we know that all docs have been replicated to the server show "unknown" replication state.
Also refactors the replication events.
medic/medic#5501

Adds unknown replication status

---

Procfile
README.md
api/README.md
shared-libs/server-checks/src/checks.js

Update documentation to recommend the use of COUCH_NODE_NAME=couchdb@127.0.0.1
medic/medic#5609

Recommended COUCH_NODE_NAME should be couchdb@127.0.0.1

---

README.md

medic/medic#5630
https://github.com/medic/medic-conf/issues/182

Update to new args syntax in medic-conf v2.0.2 and correct port

---

README.md
api/package-lock.json
api/package.json
api/src/controllers/record-utils.js
api/tests/mocha/controllers/record-utils-parser.spec.js
api/tests/mocha/controllers/record-utils-public-forms.spec.js
api/tests/mocha/controllers/record-utils.spec.js
sentinel/package-lock.json
sentinel/package.json
shared-libs/transitions/package-lock.json
shared-libs/transitions/package.json
shared-libs/transitions/src/lib/utils.js
shared-libs/transitions/src/transitions/registration.js
shared-libs/transitions/src/transitions/update_clinics.js
shared-libs/transitions/test/integration/transitions.js
shared-libs/transitions/test/unit/lib/utils.js
shared-libs/transitions/test/unit/update_clinics.js
tests/e2e/sentinel/transitions/update_clinics.spec.js
tests/e2e/transitions/sentinel_api_transitions.spec.js

Adds a few steps on using medic-conf to apply the standard config so people can see how the app works with that config.

Adding steps on applying standard config via medic-conf

---

webapp/src/css/content-list.less

Updates muted contacts styling.
medic/medic#5595

Fixes UHC visits muted contacts colors.

---

admin/src/js/services/import-contacts.js
admin/src/templates/export_contacts.html
admin/tests/unit/services/import-contacts.js

Requests contact info with root URL

---

shared-libs/transitions/src/lib/schedules.js
shared-libs/transitions/src/lib/utils.js
shared-libs/transitions/test/unit/utils.js

Remove some unneeded code and use a library we already import anyway.

Drop getVal and use object-path instead

---

api/package-lock.json
api/package.json
sentinel/package-lock.json
sentinel/package.json
shared-libs/transitions/package-lock.json
shared-libs/transitions/package.json

Bumps dependency after re-publishing a new version of @medic/transitions from master branch.  

Bump medic/transitions dependency

---

package-lock.json
package.json

Set the version number in package.json and package-lock.json

Set the version number in package.json and package-lock.json

---

webapp/src/templates/partials/contacts_content.html

Fix merge with redux refactor

---

api/src/controllers/login.js
api/tests/mocha/controllers/login.spec.js

Post login credentials to /medic/login instead of environment.db
#5743

Cannot login when dbname is not `medic`

---

ddocs/medic/_attachments/translations/messages-en.properties

Adds missing translation to default

---

webapp/src/js/directives/actionbar.js
webapp/src/js/directives/date-filter.js
webapp/src/js/directives/facility-filter.js
webapp/src/js/directives/form-type-filter.js
webapp/src/js/directives/freetext-filter.js
webapp/src/js/directives/messages-list.js
webapp/src/js/directives/navigation.js
webapp/src/js/directives/reports-list.js
webapp/src/js/directives/reset-filter.js
webapp/src/js/directives/status-filter.js
webapp/src/templates/directives/filters/date.html
webapp/src/templates/directives/filters/facility.html
webapp/src/templates/directives/filters/form_type.html
webapp/src/templates/directives/filters/freetext.html
webapp/src/templates/directives/filters/navigation.html
webapp/src/templates/directives/filters/reset.html
webapp/src/templates/directives/filters/status.html
webapp/src/templates/directives/messages_list.html
webapp/src/templates/directives/reports_list.html

Turns out `controllerAs` has to be unique.
This PR updates all directives' controllers to use a unique name. 
Leaving main controllers as `$ctrl`, assuming only one is active at every point in time.
medic/medic#5741
The software is provided under AGPL-3.0. Contributions to this project are accepted under …

Fix directive controllers to differentiate scope

---

scripts/travis/cleanup.js

Fix a couple of bugs with the build cleanup script

---

webapp/src/js/enketo/widgets/countdown-widget.js

Check if the widget is still being shown before playing the beep.
medic/medic#5654

Don't beep if form is closed

---

admin/src/js/controllers/upgrade.js

Updates scope's deployDoc when deleted 

---

api/src/routing.js
demo-forms/multimedia.xml
webapp/src/js/services/enketo.js
webapp/tests/karma/unit/services/enketo.js

Adds "blob" to CSP "mediaSrc" so video and audio blobs are allowed.
Replaces the media `src` before parsing to eliminate irrelevant CSP error.
medic/medic#5753

Fixes loading media from Enketo forms

---

admin/src/js/controllers/main.js
webapp/src/js/controllers/inbox.js
webapp/src/js/services/db-sync.js
webapp/src/js/services/db.js
webapp/src/js/services/settings.js
webapp/tests/karma/unit/services/db.js

Override Pouchdb fetch method to identify 401 responses and redirect to login page
medic/medic#3919

Override Pouchdb fetch method to identify 401 responses

---

demo-forms/mrdt-demo.xml
webapp/src/css/enketo/medic.less
webapp/src/js/enketo/widgets/mrdt.js
webapp/src/js/services/android-api.js
webapp/src/js/services/mrdt.js

Makes change to webapp in order to process new incoming field timeTaken from rdt app 
https://github.com/medic/medic/issues/5695

Makes change to webapp in order to process new incoming field from rdt app

---

release-notes/docs/3.5.0.md

Grammar and layout improvements

---

webapp/src/js/services/enketo-translation.js

Improve clarity of reporting for ambiguous path matches during Enketo data binding

---

webapp/src/templates/partials/contacts_content.html

Fix merge with redux again

---

api/src/server-utils.js
api/tests/mocha/server-utils.spec.js

Objects cause a runtime exception to be thrown.
medic/medic#5809

Ensure we only write strings to the response

---

admin/src/css/configuration.less
webapp/src/css/button.less
webapp/src/css/content-list.less
webapp/src/css/dropdown.less
webapp/src/css/enketo/medic.less
webapp/src/css/inbox.less
webapp/src/css/material.less
webapp/src/css/panel.less
webapp/src/css/targets.less
webapp/src/css/theme.less
webapp/src/css/variables.less

Also fixes a css typo.
medic/medic#5711

Remove unused css

---

README.md

- Put them in order so they can be followed sequentially
- Added grunt cli as a requirement
- Added environment variables where required
- Formatting to make copy+paste easier

Update dev environment setup instructions

---

tests/.eslintrc
tests/e2e/registration-by-sms.js

Execute moment in utc mode to be consistent with server:
https://github.com/medic/medic/blob/master/scripts/e2e-servers.js#L35
medic/medic#5344

Execute moment in utc mode to be consistent with server

---

Gruntfile.js
api/src/controllers/forms.js
api/src/controllers/sms-gateway.js
api/src/db-batch.js
api/src/manual-migrations/index.js
api/src/migrations/extract-person-contacts.js
api/src/migrations/namespace-form-fields.js
api/src/services/authorization.js
api/src/services/export/report-mapper.js
api/src/services/heartbeat-filter.js
api/src/services/records.js
api/src/services/report/javarosa-parser.js
api/src/services/report/mp-parser.js
api/src/services/report/smsparser.js
api/src/services/report/textforms-parser.js
api/src/services/user-db.js

Fixes the JSDoc formatting for API

---

README.md

Fixed a spacing issue and aligned capitalization of the Table of Contents with other headings

Fix link and TOC capitalization

---

webapp/src/js/directives/auth.js

It's better to show when allowed rather than hide when blocked.
medic/medic#5829

Hide elements while determining auth

---

webapp/src/css/theme.less
webapp/src/js/filters/date.js
webapp/tests/mocha/unit/filters/date.spec.js

Add styling for weeksPregnant filter

---

api/src/controllers/login.js
api/tests/mocha/controllers/login.spec.js

Offline users should not go to /admin even if they have the right
permissions.
medic/medic#5785

Redirect offline users to webapp

---

api/src/controllers/africas-talking.js
api/src/services/africas-talking.js
api/tests/mocha/controllers/africas-talking.spec.js
api/tests/mocha/services/africas-talking.spec.js
config/standard/app_settings.json
package-lock.json
package.json
tests/base.conf.js
tests/e2e/africas-talking.js
tests/e2e/login/login.specs.js
tests/utils.js

The old method didn't work with our production stack.
medic/medic#5844

Fix Africa's Talking security checking

---

api/src/routing.js

Trust proxy to get the client IP

---

webapp/src/js/controllers/contacts-edit.js
webapp/src/js/controllers/reports-add.js
webapp/src/js/selectors/index.js
webapp/tests/karma/unit/controllers/contacts-edit.js

These tabs were both setting loadingContent to false too early.
medic/medic#5805

Fixes contact and report tab loading content

---

Gruntfile.js
sentinel/src/transitions.js
shared-libs/lineage/src/lineage.js
shared-libs/memdown/src/memdown-medic.js
shared-libs/message-utils/src/index.js
shared-libs/phone-number/src/phone-number.js
shared-libs/task-utils/src/task-utils.js
shared-libs/transitions/src/lib/history.js
shared-libs/transitions/src/lib/validation.js
shared-libs/transitions/src/transitions/multi_report_alerts.js
webapp/src/js/services/add-attachment.js
webapp/src/js/services/add-read-status.js
webapp/src/js/services/analytics-modules.js

Fixed incorrect doc statements
Dynamically find shared-libs
Correct readme linkage
Fix some indenation issues
medic/medic#5548

Added more JSDoc improvements

---

webapp/src/css/enketo/medic.less

Improve Enketo summary styling

---

shared-libs/settings/src/index.js
shared-libs/settings/test/index.js

Handle empty credentials gracefully

---

webapp/src/css/enketo/medic.less

Cannot add more than one household member
medic/medic#5729

Unhidding add button on enketo repeats 

---

webapp/src/js/controllers/messages-content.js

Fixed scrolling to unread messages
